export const initialJokes = [
    { id: '1', setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '2', setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '3', setup: "Why do programmers prefer dark mode?", punchline: "Because light attracts bugs!", category: "Programming Jokes", status: "published" as const },
    { id: '4', setup: "What do you call a fake noodle?", punchline: "An impasta!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '5', setup: "Why did the bicycle fall over?", punchline: "It was two tired!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '6', setup: "How do you organize a space party?", punchline: "You planet!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '7', setup: "Why did the math book look sad?", punchline: "Because it had too many problems.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '8', setup: "What do you call a belt made out of watches?", punchline: "A waist of time!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '9', setup: "How does a penguin build its house?", punchline: "Igloos it together!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '10', setup: "Why did the stadium get so hot after the game?", punchline: "All of the fans left!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '11', setup: "What do you call a mushroom who is the life of the party?", punchline: "A fungi!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '12', setup: "Why did the cookie go to the doctor?", punchline: "Because he was feeling crumbly.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '13', setup: "A guy is sitting in a bar when he hears a voice say: 'Nice tie!'", punchline: "It was the peanuts—they were complementary.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '14', setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '15', setup: "What do you call a grizzly bear with no teeth?", punchline: "A gummy bear!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '16', setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '17', setup: "What's the best thing about Switzerland?", punchline: "I don't know, but the flag is a big plus.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '18', setup: "I'm afraid for the calendar.", punchline: "Its days are numbered.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '19', setup: "What do you call a fish with no eyes?", punchline: "A fsh!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '20', setup: "Why did the gym close down?", punchline: "It just didn't work out!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '21', setup: "What do you call a can opener that doesn't work?", punchline: "A can't opener!", category: "Classic Dad Jokes", status: "published" as const },
];

export const initialRiddles = [
    { id: 1, question: 'What has keys but no locks?', options: ['A piano', 'A keyboard', 'A map', 'A car'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'published' as const },
    { id: 2, question: 'What has a head and a tail but no body?', options: ['A coin', 'A snake', 'A rope', 'A bookmark'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'published' as const },
    { id: 3, question: 'What gets wetter the more it dries?', options: ['A towel', 'A sponge', 'Water', 'Rain'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'draft' as const },
    { id: 4, question: 'I speak without a mouth and hear without ears. What am I?', options: ['An echo', 'A ghost', 'A phone', 'Radio'], correctOption: 'A', difficulty: 'medium' as const, chapter: 'Nature Riddles', status: 'published' as const },
    { id: 5, question: 'The more you take, the more you leave behind. What am I?', options: ['Footsteps', 'Memories', 'Time', 'Money'], correctOption: 'A', difficulty: 'medium' as const, chapter: 'Abstract Riddles', status: 'published' as const },
    { id: 6, question: 'What has cities but no houses, forests but no trees?', options: ['A map', 'A globe', 'A book', 'A painting'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'draft' as const },
];

export const initialImageRiddles = [
    {
        id: '1',
        title: 'What is hidden in this painting?',
        imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop',
        answer: 'A face looking to the left',
        hint: 'Look at the center and tilt your head',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Optical Illusions', emoji: '👁️' },
        altText: 'Abstract optical illusion painting',
    },
    {
        id: '2',
        title: 'Spot the anomaly in this landscape',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
        answer: 'The reflection is upside down',
        hint: 'Check the water carefully',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Mountain landscape reflection',
    },
    {
        id: '3',
        title: 'How many animals can you find?',
        imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&h=400&fit=crop',
        answer: 'Five: two birds, a deer, a rabbit, and a fox',
        hint: 'Look carefully at the trees and bushes',
        difficulty: 'easy' as const,
        status: 'draft' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Forest scene with hidden animals',
    },
    {
        id: '4',
        title: 'Count the triangles',
        imageUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600&h=400&fit=crop',
        answer: '16 triangles total',
        hint: 'Count both small and large triangles',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Pattern Recognition', emoji: '🔲' },
        altText: 'Geometric triangle puzzle',
    },
    {
        id: '5',
        title: 'What time does the sundial show?',
        imageUrl: 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&h=400&fit=crop',
        answer: 'About 2:30 PM',
        hint: 'Look at the shadow and the Roman numerals',
        difficulty: 'expert' as const,
        status: 'published' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Perspective Puzzles', emoji: '📐' },
        altText: 'Ancient sundial casting a shadow',
    },
];

export const initialImageRiddleCategories = [
    { id: '1', name: 'Optical Illusions', emoji: '👁️', description: 'Mind-bending visual tricks' },
    { id: '2', name: 'Hidden Objects', emoji: '🔍', description: 'Find what is concealed' },
    { id: '3', name: 'Pattern Recognition', emoji: '🔲', description: 'Identify patterns and sequences' },
    { id: '4', name: 'Perspective Puzzles', emoji: '📐', description: 'Challenge your spatial reasoning' },
];


