// Offline fallback data for the image-riddles catalog — rendered while the
// API is unreachable (see useImageRiddleCatalog).
// Rewritten 2026-09-15 for the 10 launch categories (owner-approved; seeded by
// apps/backend/scripts/dev/reset-image-riddle-content.js). The 25 riddles are
// remapped: illusion-type content (former Pattern/Perspective/Color sets)
// lives under Optical Illusions, the former Hidden Objects animals under
// Animal Camouflage. Images are real Wikimedia Commons files (URLs and
// licenses verified — see plan/16-liked-categories.md §6); each riddle keeps a
// "source" link action so the attribution surface survives offline play.
// Keep in sync with the seed SQL when editing either file.

interface FallbackActionOption {
  id: string;
  label: string;
  type: 'button' | 'link' | 'toggle' | 'dropdown' | 'custom';
  [key: string]: unknown;
}

const sourceAction = (filePage: string): FallbackActionOption => ({
  id: 'source',
  isEnabled: true,
  isVisible: true,
  label: 'Source',
  type: 'link',
  style: 'ghost',
  size: 'sm',
  ariaLabel: 'View original image source',
  position: 'below_question',
  order: 90,
  href: `https://commons.wikimedia.org/wiki/${filePage}`,
  openInNewTab: true,
});

export const initialImageRiddles = [
  // ===== Optical Illusions =====
  {
    id: '81000000-e29b-41d4-a716-446655440101',
    title: 'Are the horizontal lines in this wall crooked?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Caf%C3%A9_wall.svg/1280px-Caf%C3%A9_wall.svg.png',
    answer: 'No, they are perfectly parallel',
    alternativeAnswers: ['they are parallel', 'parallel', 'no', 'they are straight'],
    hint: 'The mortar lines are alternately staggered - check with a ruler or the edge of your screen',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Cafe wall illusion: staggered brick rows with gray mortar lines',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Caf%C3%A9_wall.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440102',
    title: 'Which of the two fins is longer?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/M%C3%BCller-Lyer_illusion.svg/1280px-M%C3%BCller-Lyer_illusion.svg.png',
    answer: 'They are the same length',
    alternativeAnswers: ['same', 'equal', 'neither', 'same length'],
    hint: 'The arrowheads fool you - cover the fins with your fingers and compare the shafts',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Muller-Lyer illusion: two equal lines with inward and outward arrowheads',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:M%C3%BCller-Lyer_illusion.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440103',
    title: 'Do you see gray dots at the intersections?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Hermann_grid_illusion.svg/1280px-Hermann_grid_illusion.svg.png',
    answer: 'No, they are white intersections',
    alternativeAnswers: ['no', 'white', 'there are no dots', 'no dots'],
    hint: 'Look straight at one intersection - the dots only appear in your peripheral vision',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Hermann grid illusion: black squares with ghostly gray dots at the intersections',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Hermann_grid_illusion.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440104',
    title: 'What do you see in the center of this figure?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Face_or_vase_7741.svg/1280px-Face_or_vase_7741.svg.png',
    answer: 'Both a vase and two faces',
    alternativeAnswers: ['a vase', 'two faces', 'faces', 'vase', 'a cup', 'cup'],
    hint: 'Let your eyes relax and the figure flips between a cup and a pair of faces',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Rubin vase figure-ground illusion in purple and gray',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Face_or_vase_7741.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440105',
    title: 'Is this a duck or a rabbit?',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Duck-Rabbit_illusion.jpg',
    answer: 'Both - it flips between duck and rabbit',
    alternativeAnswers: ['both', 'duck', 'rabbit', 'either'],
    hint: 'The two prongs are ears to one eye and a beak to the other - keep looking and it flips',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Classic duck-rabbit ambiguous figure from an 1892 magazine',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Duck-Rabbit_illusion.jpg')],
  },

  // ===== Animal Camouflage =====
  {
    id: '81000000-e29b-41d4-a716-446655440201',
    title: 'Something is pretending to be a leaf in this photo. What is it?',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/12/LeafInsect.jpg',
    answer: 'A leaf insect',
    alternativeAnswers: ['insect', 'leaf bug', 'walking leaf', 'bug'],
    hint: 'One leaf has legs - check the vein pattern for a body outline',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Animal Camouflage', emoji: '🐾' },
    altText: 'A leaf insect camouflaged among leaves',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:LeafInsect.jpg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440202',
    title: 'An insect is hiding on this branch. What is it?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Walking_Stick_%2857423%29.jpg/1280px-Walking_Stick_%2857423%29.jpg',
    answer: 'A stick insect',
    alternativeAnswers: ['insect', 'walking stick', 'phasmid', 'stick bug'],
    hint: 'Not every twig has a joint - follow the branch until part of it grows legs',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Animal Camouflage', emoji: '🐾' },
    altText: 'A stick insect camouflaged on a branch',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Walking_Stick_(57423).jpg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440203',
    title: 'A predator is pressed flat against this tree trunk. What animal is it?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Mossy_leaf-tailed_gecko_%28Uroplatus_sikorae%29_Montagne_d%E2%80%99Ambre.jpg/1280px-Mossy_leaf-tailed_gecko_%28Uroplatus_sikorae%29_Montagne_d%E2%80%99Ambre.jpg',
    answer: 'A gecko',
    alternativeAnswers: ['lizard', 'leaf-tailed gecko', 'reptile'],
    hint: 'Search for the pale eyes - the rest of the body looks like bark and lichen',
    difficulty: 'hard' as const,
    status: 'published' as const,
    timerSeconds: 120,
    showTimer: true,
    isActive: true,
    category: { name: 'Animal Camouflage', emoji: '🐾' },
    altText: 'A mossy leaf-tailed gecko camouflaged on a tree trunk',
    useDefaultActions: true,
    actionOptions: [
      sourceAction('File:Mossy_leaf-tailed_gecko_(Uroplatus_sikorae)_Montagne_d%27Ambre.jpg'),
    ],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440204',
    title: 'A well-camouflaged bird stands among this tall grass. Which bird is it?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/American_bittern_%28Botaurus_lentiginosus%29_hiding_in_tall_grass.jpg/1280px-American_bittern_%28Botaurus_lentiginosus%29_hiding_in_tall_grass.jpg',
    answer: 'An American bittern',
    alternativeAnswers: ['bittern', 'heron', 'a bittern', 'bird'],
    hint: 'It points its bill skyward so it looks like a reed - find the eye and the striped neck',
    difficulty: 'hard' as const,
    status: 'published' as const,
    timerSeconds: 120,
    showTimer: true,
    isActive: true,
    category: { name: 'Animal Camouflage', emoji: '🐾' },
    altText: 'An American bittern hiding in tall grass, pointing its bill upward',
    useDefaultActions: true,
    actionOptions: [
      sourceAction('File:American_bittern_(Botaurus_lentiginosus)_hiding_in_tall_grass.jpg'),
    ],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440205',
    title: 'A leaf-shaped insect is resting on this leaf. What is it?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/9/97/Fork-tailed_bush_katydid_%2842143s%29.jpg',
    answer: 'A katydid',
    alternativeAnswers: ['a katydid', 'katydid', 'bush cricket', 'insect', 'grasshopper'],
    hint: 'Bush crickets have long antennae - follow the thin line back from its head',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Animal Camouflage', emoji: '🐾' },
    altText: 'A fork-tailed bush katydid resting on a leaf',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Fork-tailed_bush_katydid_(42143s).jpg')],
  },

  // ===== Optical Illusions — geometry illusions =====
  {
    id: '81000000-e29b-41d4-a716-446655440301',
    title: 'Is this a real spiral?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Fraser_spiral_illusion.svg/1280px-Fraser_spiral_illusion.svg.png',
    answer: 'No, they are concentric circles',
    alternativeAnswers: ['circles', 'concentric circles', 'no', 'not a spiral'],
    hint: 'Trace one strand with your fingertip - you will come back to where you started',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Fraser spiral illusion: twisted cord segments that read as a spiral',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Fraser_spiral_illusion.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440302',
    title: 'Are the long lines in this figure parallel?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Zollner_illusion.svg/1280px-Zollner_illusion.svg.png',
    answer: 'Yes, they are parallel',
    alternativeAnswers: ['yes', 'parallel', 'they are parallel'],
    hint: 'The alternating cross-hatches tip your perception - cover the small strokes and recheck',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText:
      'Zollner illusion: parallel long lines with alternating cross-hatches that appear to converge',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Zollner_illusion.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440303',
    title: 'What shape do the pac-man corners create?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Kanizsa_triangle.svg/1280px-Kanizsa_triangle.svg.png',
    answer: 'A triangle',
    alternativeAnswers: ['kanizsa triangle', 'triangle', 'an illusory triangle'],
    hint: 'Your brain draws the edges itself - there is no outline, only three pac-men and an angle',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Kanizsa triangle: three pac-man disks with an illusory bright triangle',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Kanizsa_triangle.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440304',
    title: 'Which center circle is bigger?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Ebbinghaus_Illusion.svg/1280px-Ebbinghaus_Illusion.svg.png',
    answer: 'They are identical in size',
    alternativeAnswers: ['same', 'equal', 'neither', 'same size'],
    hint: 'Surrounded by big rings one looks small, by small rings one looks big - measure to be sure',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Ebbinghaus illusion: two equal central circles with different surrounding rings',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Ebbinghaus_Illusion.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440305',
    title: 'Do the vertical lines of this figure bend?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Hering_illusion.svg/1280px-Hering_illusion.svg.png',
    answer: 'No, they are straight and parallel',
    alternativeAnswers: ['no', 'straight', 'they are straight', 'they are parallel'],
    hint: 'The radial spokes warp the judgment - lay a ruler along one of the verticals',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Hering illusion: straight vertical lines bowed by a radial background',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Hering_illusion.svg')],
  },

  // ===== Optical Illusions — impossible objects =====
  {
    id: '81000000-e29b-41d4-a716-446655440401',
    title: 'Can you climb these stairs?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Impossible_staircase.svg/1280px-Impossible_staircase.svg.png',
    answer: 'No, they loop forever',
    alternativeAnswers: ['impossible object', 'they loop forever', 'no', 'penrose stairs'],
    hint: 'Follow any flight of steps all the way around - you end up back at the start, always climbing',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Penrose impossible staircase drawn in isometric projection',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Impossible_staircase.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440402',
    title: 'Is the lower-left corner of this cube pointing toward you or away?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Necker_cube.svg/1280px-Necker_cube.svg.png',
    answer: 'It flips between both views',
    alternativeAnswers: ['both', 'neither', 'it flips', 'ambiguous'],
    hint: 'Stare at the corner and it jumps - the wireframe has no depth cue to settle the question',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Necker cube wireframe with ambiguous depth',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Necker_cube.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440403',
    title: 'These portraits are upside down. What is wrong with the right-hand face?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Thatcher_effect.jpg/1280px-Thatcher_effect.jpg',
    answer: 'Her eyes and mouth are upside down',
    alternativeAnswers: [
      'eyes and mouth upside down',
      'the features are inverted',
      'her eyes and mouth are inverted',
    ],
    hint: 'Rotate your phone 180 degrees - the distortion hides until the face is upright',
    difficulty: 'hard' as const,
    status: 'published' as const,
    timerSeconds: 120,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Thatcher effect: two upside-down portraits, one with inverted eyes and mouth',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Thatcher_effect.jpg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440404',
    title: 'Do you see a young woman or an old lady?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/My_Wife_and_My_Mother-in-Law.jpg/1280px-My_Wife_and_My_Mother-in-Law.jpg',
    answer: 'Both - they share one drawing',
    alternativeAnswers: ['both', 'young woman', 'old woman', 'old lady', 'wife and mother-in-law'],
    hint: 'The young face turns away while the old lady looks down - the chin and ear swap roles',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'My Wife and My Mother-in-Law ambiguous figure by W. E. Hill',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:My_Wife_and_My_Mother-in-Law.jpg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440405',
    title: 'Which way is this staircase going - up or down?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Penrosetreppe_links.svg/1280px-Penrosetreppe_links.svg.png',
    answer: 'It depends on your viewpoint',
    alternativeAnswers: ['both', 'up', 'down', 'it depends', 'depends on your viewpoint'],
    hint: 'Cover the bottom half and the top flights reverse direction',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Penrose staircase variant (Penrosetreppe)',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Penrosetreppe_links.svg')],
  },

  // ===== Optical Illusions — color perception =====
  {
    id: '81000000-e29b-41d4-a716-446655440501',
    title: 'Are squares A and B the same color?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Checker_shadow_illusion.svg/1280px-Checker_shadow_illusion.svg.png',
    answer: 'Yes, A and B are identical in color',
    alternativeAnswers: ['yes', 'same color', 'they are the same', 'identical'],
    hint: 'B only looks lighter because the cylinder casts a shadow - connect them with your finger to compare',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Checker-shadow illusion: squares A and B are identical gray',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Checker_shadow_illusion.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440502',
    title: 'What number is hidden in this dotted circle?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ishihara_9.svg/1280px-Ishihara_9.svg.png',
    answer: '74',
    alternativeAnswers: ['the number is 74', 'seventy four'],
    hint: 'Trace the orange-toned dots - red-green color vision turns them into a path',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Ishihara color-test plate showing the number 74',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Ishihara_9.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440503',
    title: 'What number does this color-test plate show?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Ishihara-Test.svg/1280px-Ishihara-Test.svg.png',
    answer: '5',
    alternativeAnswers: ['the number is 5', 'five'],
    hint: 'The reddish path cuts vertically through the green dots',
    difficulty: 'easy' as const,
    status: 'published' as const,
    timerSeconds: 60,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Ishihara-style color-test plate with the number 5',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Ishihara-Test.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440504',
    title: 'Are the two inner gray squares the same shade?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Simultaneous_Contrast.svg/1280px-Simultaneous_Contrast.svg.png',
    answer: 'Yes, both are the same gray',
    alternativeAnswers: ['yes', 'same', 'identical', 'they are the same'],
    hint: 'On dark it looks lighter, on light it looks darker - cover the backgrounds and compare',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Simultaneous contrast: two identical gray squares on different backgrounds',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Simultaneous_Contrast.svg')],
  },
  {
    id: '81000000-e29b-41d4-a716-446655440505',
    title: 'Are the two red bars on these stripes the same color?',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Bezold_Effect.svg/1280px-Bezold_Effect.svg.png',
    answer: 'Yes, they are identical',
    alternativeAnswers: ['yes', 'same', 'identical', 'they are the same'],
    hint: 'White stripes brighten one red, black stripes darken the other - the Bezold effect at work',
    difficulty: 'medium' as const,
    status: 'published' as const,
    timerSeconds: 90,
    showTimer: true,
    isActive: true,
    category: { name: 'Optical Illusions', emoji: '👁️' },
    altText: 'Bezold effect: identical red bars look different on black versus white stripes',
    useDefaultActions: true,
    actionOptions: [sourceAction('File:Bezold_Effect.svg')],
  },
];

export const initialImageRiddleCategories = [
  {
    id: '7f3c9a1e-4b2d-4e8f-9a6c-1d5e8b2f7a41',
    name: 'Hidden Objects',
    emoji: '🔍',
    description: 'Find items tucked away in busy scenes',
  },
  {
    id: '8a4d0b2f-5c3e-4f9a-8b7d-2e6f9c3a8b52',
    name: 'Optical Illusions',
    emoji: '👁️',
    description: 'Images that trick your eyes and brain',
  },
  {
    id: '9b5e1c3a-6d4f-4a0b-9c8e-3f7a0d4b9c63',
    name: 'Spot the Difference',
    emoji: '🔄',
    description: 'Two images, a handful of sneaky changes',
  },
  {
    id: '0c6f2d4b-7e5a-4b1c-8d9f-4a8b1e5c0d74',
    name: 'Rebus Puzzles',
    emoji: '💬',
    description: 'Picture combinations that spell out words and phrases',
  },
  {
    id: '1d7a3e5c-8f6b-4c2d-9e0a-5b9c2f6d1e85',
    name: 'Emoji Riddles',
    emoji: '😄',
    description: 'Guess the movie, song, or phrase from emojis',
  },
  {
    id: '2e8b4f6d-9a7c-4d3e-8f1b-6c0d3a7e2f96',
    name: 'Close-up Challenges',
    emoji: '🔬',
    description: 'Everyday objects seen way too close',
  },
  {
    id: '3f9c5a7e-0b8d-4e4f-9a2c-7d1e4b8f3a07',
    name: 'Animal Camouflage',
    emoji: '🐾',
    description: 'Spot the creature hiding in plain sight',
  },
  {
    id: '4a0d6b8f-1c9e-4f5a-8b3d-8e2f5c9a4b18',
    name: 'Counting Challenges',
    emoji: '🔢',
    description: 'Count what you see — most people get it wrong',
  },
  {
    id: '5b1e7c9a-2d0f-4a6b-9c4e-9f3a6d0b5c29',
    name: 'Landmarks & Places',
    emoji: '🌍',
    description: 'Name the city or monument from a photo',
  },
  {
    id: '6c2f8d0b-3e1a-4b7c-8d5f-0a4b7e1c6d30',
    name: 'Logos & Brands',
    emoji: '🏷️',
    description: 'Recognize the brand from a cropped logo',
  },
];
