export const initialJokes = [
    { id: '1', setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '2', setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '3', setup: "Why do programmers prefer dark mode?", punchline: "Because light attracts bugs!", category: "Programming Jokes", status: "published" as const },
    { id: '4', setup: "What do you call a fake noodle?", punchline: "An impasta!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '5', setup: "Why did the bicycle fall over?", punchline: "It was two tired!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '6', setup: "How do you organize a space party?", punchline: "You planet!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '7', setup: "Why did the math book look sad?", punchline: "Because it had too many problems.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '8', setup: "What do you call a belt made out of watches?", punchline: "A waist of time!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '9', setup: "How does a penguin build its house?", punchline: "Igloos it together!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '10', setup: "Why did the stadium get so hot after the game?", punchline: "All of the fans left!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '11', setup: "What do you call a mushroom who is the life of the party?", punchline: "A fungi!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '12', setup: "Why did the cookie go to the doctor?", punchline: "Because he was feeling crumbly.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '13', setup: "A guy is sitting in a bar when he hears a voice say: 'Nice tie!'", punchline: "It was the peanuts—they were complementary.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '14', setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '15', setup: "What do you call a grizzly bear with no teeth?", punchline: "A gummy bear!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '16', setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '17', setup: "What's the best thing about Switzerland?", punchline: "I don't know, but the flag is a big plus.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '18', setup: "I'm afraid for the calendar.", punchline: "Its days are numbered.", category: "Classic Dad Jokes", status: "published" as const },
    { id: '19', setup: "What do you call a fish with no eyes?", punchline: "A fsh!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '20', setup: "Why did the gym close down?", punchline: "It just didn't work out!", category: "Classic Dad Jokes", status: "published" as const },
    { id: '21', setup: "What do you call a can opener that doesn't work?", punchline: "A can't opener!", category: "Classic Dad Jokes", status: "published" as const },
];

export const initialRiddles = [
    { id: 1, question: 'What has keys but no locks?', options: ['A piano', 'A keyboard', 'A map', 'A car'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'published' as const },
    { id: 2, question: 'What has a head and a tail but no body?', options: ['A coin', 'A snake', 'A rope', 'A bookmark'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'published' as const },
    { id: 3, question: 'What gets wetter the more it dries?', options: ['A towel', 'A sponge', 'Water', 'Rain'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'draft' as const },
    { id: 4, question: 'I speak without a mouth and hear without ears. What am I?', options: ['An echo', 'A ghost', 'A phone', 'Radio'], correctOption: 'A', difficulty: 'medium' as const, chapter: 'Nature Riddles', status: 'published' as const },
    { id: 5, question: 'The more you take, the more you leave behind. What am I?', options: ['Footsteps', 'Memories', 'Time', 'Money'], correctOption: 'A', difficulty: 'medium' as const, chapter: 'Abstract Riddles', status: 'published' as const },
    { id: 6, question: 'What has cities but no houses, forests but no trees?', options: ['A map', 'A globe', 'A book', 'A painting'], correctOption: 'A', difficulty: 'easy' as const, chapter: 'Object Riddles', status: 'draft' as const },
];

export const initialImageRiddles = [
    {
        id: '1',
        title: 'What is hidden in this painting?',
        imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop',
        answer: 'A face looking to the left',
        hint: 'Look at the center and tilt your head',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Optical Illusions', emoji: '👁️' },
        altText: 'Abstract optical illusion painting',
    },
    {
        id: '2',
        title: 'Spot the anomaly in this landscape',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
        answer: 'The reflection is upside down',
        hint: 'Check the water carefully',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Mountain landscape reflection',
    },
    {
        id: '3',
        title: 'How many animals can you find?',
        imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&h=400&fit=crop',
        answer: 'Five: two birds, a deer, a rabbit, and a fox',
        hint: 'Look carefully at the trees and bushes',
        difficulty: 'easy' as const,
        status: 'draft' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Forest scene with hidden animals',
    },
    {
        id: '4',
        title: 'Count the triangles',
        imageUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600&h=400&fit=crop',
        answer: '16 triangles total',
        hint: 'Count both small and large triangles',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Pattern Recognition', emoji: '🔲' },
        altText: 'Geometric triangle puzzle',
    },
    {
        id: '5',
        title: 'What time does the sundial show?',
        imageUrl: 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&h=400&fit=crop',
        answer: 'About 2:30 PM',
        hint: 'Look at the shadow and the Roman numerals',
        difficulty: 'expert' as const,
        status: 'published' as const,
        timerSeconds: null,
        showTimer: true,
        isActive: true,
        category: { name: 'Perspective Puzzles', emoji: '📐' },
        altText: 'Ancient sundial casting a shadow',
    },
    {
        id: '6',
        title: 'Which line segment is longer?',
        imageUrl: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=600&h=400&fit=crop',
        answer: 'They are both the same length',
        hint: 'Measure them or ignore the arrowheads',
        difficulty: 'easy' as const,
        status: 'published' as const,
        timerSeconds: 60,
        showTimer: true,
        isActive: true,
        category: { name: 'Optical Illusions', emoji: '👁️' },
        altText: 'Mueller-Lyer illusion lines',
    },
    {
        id: '7',
        title: 'Are the horizontal lines parallel or slanted?',
        imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&h=400&fit=crop',
        answer: 'They are perfectly parallel',
        hint: 'Try looking at the image from a side angle',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Optical Illusions', emoji: '👁️' },
        altText: 'Cafe Wall illusion checkering',
    },
    {
        id: '8',
        title: 'How many black dots can you see at once?',
        imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&h=400&fit=crop',
        answer: 'Zero (the dots are all white)',
        hint: 'The black dots are an artifact of your peripheral vision',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 45,
        showTimer: true,
        isActive: true,
        category: { name: 'Optical Illusions', emoji: '👁️' },
        altText: 'Scintillating grid illusion',
    },
    {
        id: '9',
        title: 'Find the hidden heart in this pattern',
        imageUrl: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=600&h=400&fit=crop',
        answer: 'In the middle-right section',
        hint: 'Look for a small red heart-shaped outline',
        difficulty: 'easy' as const,
        status: 'published' as const,
        timerSeconds: 120,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Colorful repeating pattern with hidden heart',
    },
    {
        id: '10',
        title: 'Where is the cat hiding in the logs?',
        imageUrl: 'https://images.unsplash.com/photo-1516211697506-8360bd7700a?w=600&h=400&fit=crop',
        answer: 'Upper right corner, camouflaged against the bark',
        hint: 'Look for ears and whiskers blending with the wood',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Stack of chopped wood with a hidden cat',
    },
    {
        id: '11',
        title: 'Find the panda among these characters',
        imageUrl: 'https://images.unsplash.com/photo-1472457897821-70d3819a0e24?w=600&h=400&fit=crop',
        answer: 'Located in the middle-left area',
        hint: 'Pandas have rounded ears and black eye patches',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: 60,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Crowded scene of toys with a hidden panda',
    },
    {
        id: '12',
        title: 'Spot the hidden number in the forest',
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop',
        answer: 'The number 7 is formed by the branches on the left',
        hint: 'Trace the shape of the negative space between trees',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 120,
        showTimer: true,
        isActive: true,
        category: { name: 'Hidden Objects', emoji: '🔍' },
        altText: 'Sunlight filtering through a dense green forest',
    },
    {
        id: '13',
        title: 'What comes next in this shape sequence?',
        imageUrl: 'https://images.unsplash.com/photo-1543269602-fa3958784fc5?w=600&h=400&fit=crop',
        answer: 'The blue square is the next logical step',
        hint: 'Observe the alternating colors and increasing sides',
        difficulty: 'easy' as const,
        status: 'published' as const,
        timerSeconds: 60,
        showTimer: true,
        isActive: true,
        category: { name: 'Pattern Recognition', emoji: '🔲' },
        altText: 'Abstract sequence of geometric shapes',
    },
    {
        id: '14',
        title: 'Which piece completes the pattern?',
        imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&h=400&fit=crop',
        answer: 'Piece C fits perfectly with the surrounding textures',
        hint: 'Match the colors and edge shapes of the gap',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Pattern Recognition', emoji: '🔲' },
        altText: 'Jigsaw puzzle with one missing piece',
    },
    {
        id: '15',
        title: 'Find the logic error in this grid',
        imageUrl: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=600&h=400&fit=crop',
        answer: 'The bottom right quadrant is rotated 90 degrees',
        hint: 'Compare the orientation of elements across the grid',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 120,
        showTimer: true,
        isActive: true,
        category: { name: 'Pattern Recognition', emoji: '🔲' },
        altText: 'Complex repetitive geometric grid pattern',
    },
    {
        id: '16',
        title: 'Are these stairs going up or down?',
        imageUrl: 'https://images.unsplash.com/photo-1515549832467-8c441ff74ccc?w=600&h=400&fit=crop',
        answer: 'Both (it is a perspectival paradox)',
        hint: 'Focus on one corner and then blink/shift focus',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Perspective Puzzles', emoji: '📐' },
        altText: 'Modern architectural concrete staircase',
    },
    {
        id: '17',
        title: 'How many legs does this elephant have?',
        imageUrl: 'https://images.unsplash.com/photo-1581022295087-35e593704911?w=600&h=400&fit=crop',
        answer: 'Four (the drawing creates a visual ambiguity)',
        hint: 'Follow the legs from the body down to the feet',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 120,
        showTimer: true,
        isActive: true,
        category: { name: 'Perspective Puzzles', emoji: '📐' },
        altText: 'Pen and ink drawing of an impossible elephant',
    },
    {
        id: '18',
        title: 'Find the entry point to this structure',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop',
        answer: 'There is none (the building is a logical impossibility)',
        hint: 'Trace the walls from the base to the roof',
        difficulty: 'expert' as const,
        status: 'published' as const,
        timerSeconds: 150,
        showTimer: true,
        isActive: true,
        category: { name: 'Perspective Puzzles', emoji: '📐' },
        altText: 'Abstract glass and steel skyscraper with impossible angles',
    },
    {
        id: '19',
        title: 'Are squares A and B the same color?',
        imageUrl: 'https://images.unsplash.com/photo-1525193612562-0ec53b0e5d7c?w=600&h=400&fit=crop',
        answer: 'Yes, they are the exact same shade of gray',
        hint: 'The shadow of the cylinder fools your brain',
        difficulty: 'medium' as const,
        status: 'published' as const,
        timerSeconds: 90,
        showTimer: true,
        isActive: true,
        category: { name: 'Color Observation', emoji: '🎨' },
        altText: 'Checker-shadow illusion on a game board',
    },
    {
        id: '20',
        title: 'How many unique shades of green are shown?',
        imageUrl: 'https://images.unsplash.com/photo-1557683311-eac922347aa1?w=600&h=400&fit=crop',
        answer: 'There are 12 distinct tiles of green',
        hint: 'Count only the clearly bordered blocks of color',
        difficulty: 'hard' as const,
        status: 'published' as const,
        timerSeconds: 120,
        showTimer: true,
        isActive: true,
        category: { name: 'Color Observation', emoji: '🎨' },
        altText: 'Grid of various green color swatches',
    },
];

export const initialImageRiddleCategories = [
    { id: '1', name: 'Optical Illusions', emoji: '👁️', description: 'Mind-bending visual tricks' },
    { id: '2', name: 'Hidden Objects', emoji: '🔍', description: 'Find what is concealed' },
    { id: '3', name: 'Pattern Recognition', emoji: '🔲', description: 'Identify patterns and sequences' },
    { id: '4', name: 'Perspective Puzzles', emoji: '📐', description: 'Challenge your spatial reasoning' },
    { id: '5', name: 'Color Observation', emoji: '🎨', description: 'Test your perception of color and light' },
];


