FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/frontend/package*.json ./apps/frontend/
RUN npm ci && npm cache clean --force
COPY apps/frontend ./apps/frontend
COPY tsconfig.json ./
WORKDIR /app/apps/frontend
EXPOSE 3010
CMD ["npm", "run", "dev"]
