import type { MetadataRoute } from 'next';

import { APP_URL } from '@/lib/seo';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        // Crawlers (incl. Facebook/Twitter) must be able to fetch the social
        // share images, which are generated by /api/og - without this explicit
        // allow the blanket /api disallow left every share preview imageless.
        allow: ['/', '/api/og'],
        disallow: ['/admin', '/api'],
      },
    ],
    sitemap: `${APP_URL}/sitemap.xml`,
  };
}
