'use strict';

const { distractors } = require('../lib');

const HABITATS = [
  'Savanna',
  'Rainforest',
  'Desert',
  'Arctic tundra',
  'Antarctic ice',
  'Forest',
  'Grassland',
  'Mountains',
  'Wetlands',
  'Ocean',
  'Rivers and lakes',
  'Coastal areas',
];
const DIETS = ['Herbivore', 'Carnivore', 'Omnivore'];

// [name, habitat, diet] — habitat/diet null = question skipped
const MAMMALS = [
  ['African elephant', 'Savanna', 'Herbivore'],
  ['Asian elephant', 'Rainforest', 'Herbivore'],
  ['giraffe', 'Savanna', 'Herbivore'],
  ['zebra', 'Savanna', 'Herbivore'],
  ['lion', 'Savanna', 'Carnivore'],
  ['leopard', 'Savanna', 'Carnivore'],
  ['cheetah', 'Savanna', 'Carnivore'],
  ['hippopotamus', 'Rivers and lakes', 'Herbivore'],
  ['rhinoceros', 'Savanna', 'Herbivore'],
  ['warthog', 'Savanna', 'Omnivore'],
  ['meerkat', 'Desert', 'Omnivore'],
  ['baboon', 'Savanna', 'Omnivore'],
  ['spotted hyena', 'Savanna', 'Carnivore'],
  ['aardvark', 'Savanna', 'Carnivore'],
  ['wildebeest', 'Savanna', 'Herbivore'],
  ['impala', 'Savanna', 'Herbivore'],
  ['gazelle', 'Grassland', 'Herbivore'],
  ['okapi', 'Rainforest', 'Herbivore'],
  ['gorilla', 'Rainforest', 'Herbivore'],
  ['chimpanzee', 'Rainforest', 'Omnivore'],
  ['orangutan', 'Rainforest', 'Herbivore'],
  ['bonobo', 'Rainforest', 'Herbivore'],
  ['howler monkey', 'Rainforest', 'Herbivore'],
  ['spider monkey', 'Rainforest', 'Omnivore'],
  ['squirrel monkey', 'Rainforest', 'Omnivore'],
  ['tarsier', 'Rainforest', 'Carnivore'],
  ['sloth', 'Rainforest', 'Herbivore'],
  ['capybara', 'Wetlands', 'Herbivore'],
  ['giant anteater', 'Grassland', 'Carnivore'],
  ['armadillo', 'Grassland', 'Omnivore'],
  ['tapir', 'Rainforest', 'Herbivore'],
  ['jaguar', 'Rainforest', 'Carnivore'],
  ['cougar', 'Mountains', 'Carnivore'],
  ['llama', 'Mountains', 'Herbivore'],
  ['alpaca', 'Mountains', 'Herbivore'],
  ['vicuna', 'Mountains', 'Herbivore'],
  ['tiger', 'Rainforest', 'Carnivore'],
  ['snow leopard', 'Mountains', 'Carnivore'],
  ['giant panda', 'Rainforest', 'Herbivore'],
  ['red panda', 'Rainforest', 'Herbivore'],
  ['Bactrian camel', 'Desert', 'Herbivore'],
  ['koala', 'Forest', 'Herbivore'],
  ['kangaroo', 'Grassland', 'Herbivore'],
  ['wallaby', 'Grassland', 'Herbivore'],
  ['wombat', 'Forest', 'Herbivore'],
  ['platypus', 'Rivers and lakes', 'Carnivore'],
  ['echidna', 'Grassland', 'Carnivore'],
  ['Tasmanian devil', 'Forest', 'Carnivore'],
  ['brown bear', 'Forest', 'Omnivore'],
  ['black bear', 'Forest', 'Omnivore'],
  ['polar bear', 'Arctic tundra', 'Carnivore'],
  ['raccoon', 'Forest', 'Omnivore'],
  ['red fox', 'Forest', 'Omnivore'],
  ['gray wolf', 'Forest', 'Carnivore'],
  ['coyote', 'Grassland', 'Omnivore'],
  ['lynx', 'Forest', 'Carnivore'],
  ['otter', 'Rivers and lakes', 'Carnivore'],
  ['badger', 'Forest', 'Omnivore'],
  ['beaver', 'Rivers and lakes', 'Herbivore'],
  ['moose', 'Forest', 'Herbivore'],
  ['white-tailed deer', 'Forest', 'Herbivore'],
  ['caribou', 'Arctic tundra', 'Herbivore'],
  ['bison', 'Grassland', 'Herbivore'],
  ['musk ox', 'Arctic tundra', 'Herbivore'],
  ['bighorn sheep', 'Mountains', 'Herbivore'],
  ['mountain goat', 'Mountains', 'Herbivore'],
  ['camel', 'Desert', 'Herbivore'],
  ['donkey', 'Grassland', 'Herbivore'],
  ['horse', 'Grassland', 'Herbivore'],
  ['pig', 'Forest', 'Omnivore'],
  ['goat', 'Mountains', 'Herbivore'],
  ['sheep', 'Grassland', 'Herbivore'],
  ['rabbit', 'Grassland', 'Herbivore'],
  ['hare', 'Grassland', 'Herbivore'],
  ['hedgehog', 'Forest', 'Omnivore'],
  ['mole', 'Forest', 'Carnivore'],
  ['bat', 'Forest', 'Omnivore'],
  ['vampire bat', 'Rainforest', 'Carnivore'],
  ['dolphin', 'Ocean', 'Carnivore'],
  ['orca', 'Ocean', 'Carnivore'],
  ['blue whale', 'Ocean', 'Carnivore'],
  ['humpback whale', 'Ocean', 'Carnivore'],
  ['sperm whale', 'Ocean', 'Carnivore'],
  ['narwhal', 'Arctic tundra', 'Carnivore'],
  ['beluga whale', 'Arctic tundra', 'Carnivore'],
  ['manatee', 'Rivers and lakes', 'Herbivore'],
  ['dugong', 'Coastal areas', 'Herbivore'],
  ['seal', 'Coastal areas', 'Carnivore'],
  ['walrus', 'Arctic tundra', 'Carnivore'],
  ['sea lion', 'Coastal areas', 'Carnivore'],
  ['porcupine', 'Forest', 'Herbivore'],
  ['chipmunk', 'Forest', 'Omnivore'],
  ['squirrel', 'Forest', 'Herbivore'],
  ['prairie dog', 'Grassland', 'Herbivore'],
  ['lemming', 'Arctic tundra', 'Herbivore'],
  ['weasel', 'Forest', 'Carnivore'],
  ['wolverine', 'Arctic tundra', 'Carnivore'],
  ['skunk', 'Forest', 'Omnivore'],
  ['opossum', 'Forest', 'Omnivore'],
  ['pangolin', 'Rainforest', 'Carnivore'],
  ['ibex', 'Mountains', 'Herbivore'],
  ['oryx', 'Desert', 'Herbivore'],
  ['ferret', 'Grassland', 'Carnivore'],
  ['hamster', 'Desert', 'Omnivore'],
  ['gerbil', 'Desert', 'Herbivore'],
  ['guinea pig', 'Grassland', 'Herbivore'],
  ['marmot', 'Mountains', 'Herbivore'],
  ['groundhog', 'Forest', 'Herbivore'],
];

// [name, habitat, diet]
const BIRDS = [
  ['bald eagle', 'Forest', 'Carnivore'],
  ['golden eagle', 'Mountains', 'Carnivore'],
  ['peregrine falcon', 'Coastal areas', 'Carnivore'],
  ['barn owl', 'Grassland', 'Carnivore'],
  ['snowy owl', 'Arctic tundra', 'Carnivore'],
  ['emperor penguin', 'Antarctic ice', 'Carnivore'],
  ['puffin', 'Coastal areas', 'Carnivore'],
  ['pelican', 'Coastal areas', 'Carnivore'],
  ['flamingo', 'Wetlands', 'Omnivore'],
  ['swan', 'Rivers and lakes', 'Herbivore'],
  ['goose', 'Wetlands', 'Herbivore'],
  ['mallard duck', 'Rivers and lakes', 'Omnivore'],
  ['peacock', 'Forest', 'Omnivore'],
  ['pheasant', 'Grassland', 'Omnivore'],
  ['turkey', 'Forest', 'Omnivore'],
  ['chicken', 'Grassland', 'Omnivore'],
  ['ostrich', 'Savanna', 'Omnivore'],
  ['emu', 'Grassland', 'Omnivore'],
  ['cassowary', 'Rainforest', 'Omnivore'],
  ['kiwi', 'Forest', 'Omnivore'],
  ['rhea', 'Grassland', 'Omnivore'],
  ['albatross', 'Ocean', 'Carnivore'],
  ['seagull', 'Coastal areas', 'Omnivore'],
  ['crow', 'Forest', 'Omnivore'],
  ['raven', 'Forest', 'Omnivore'],
  ['magpie', 'Forest', 'Omnivore'],
  ['sparrow', 'Forest', 'Omnivore'],
  ['robin', 'Forest', 'Omnivore'],
  ['cardinal', 'Forest', 'Herbivore'],
  ['blue jay', 'Forest', 'Omnivore'],
  ['hummingbird', 'Rainforest', 'Herbivore'],
  ['woodpecker', 'Forest', 'Carnivore'],
  ['kingfisher', 'Rivers and lakes', 'Carnivore'],
  ['toucan', 'Rainforest', 'Omnivore'],
  ['macaw', 'Rainforest', 'Herbivore'],
  ['parrot', 'Rainforest', 'Herbivore'],
  ['cockatoo', 'Forest', 'Herbivore'],
  ['canary', 'Forest', 'Herbivore'],
  ['pigeon', 'Forest', 'Omnivore'],
  ['dove', 'Forest', 'Herbivore'],
  ['stork', 'Wetlands', 'Carnivore'],
  ['heron', 'Wetlands', 'Carnivore'],
  ['crane', 'Wetlands', 'Omnivore'],
  ['vulture', 'Savanna', 'Carnivore'],
  ['condor', 'Mountains', 'Carnivore'],
  ['roadrunner', 'Desert', 'Omnivore'],
  ['hornbill', 'Rainforest', 'Omnivore'],
  ['penguin', 'Coastal areas', 'Carnivore'],
  ['sandpiper', 'Coastal areas', 'Carnivore'],
  ['oystercatcher', 'Coastal areas', 'Carnivore'],
  ['avocet', 'Wetlands', 'Carnivore'],
  ['tern', 'Coastal areas', 'Carnivore'],
  ['loon', 'Rivers and lakes', 'Carnivore'],
  ['grebe', 'Rivers and lakes', 'Carnivore'],
  ['moorhen', 'Wetlands', 'Omnivore'],
];

// [name, habitat, diet, class]
const REPTILES = [
  ['king cobra', 'Rainforest', 'Carnivore', 'Reptile'],
  ['python', 'Rainforest', 'Carnivore', 'Reptile'],
  ['boa constrictor', 'Rainforest', 'Carnivore', 'Reptile'],
  ['rattlesnake', 'Desert', 'Carnivore', 'Reptile'],
  ['grass snake', 'Wetlands', 'Carnivore', 'Reptile'],
  ['Komodo dragon', 'Grassland', 'Carnivore', 'Reptile'],
  ['chameleon', 'Rainforest', 'Carnivore', 'Reptile'],
  ['iguana', 'Rainforest', 'Herbivore', 'Reptile'],
  ['gecko', 'Desert', 'Carnivore', 'Reptile'],
  ['bearded dragon', 'Desert', 'Omnivore', 'Reptile'],
  ['monitor lizard', 'Grassland', 'Carnivore', 'Reptile'],
  ['frilled lizard', 'Rainforest', 'Carnivore', 'Reptile'],
  ['thorny devil', 'Desert', 'Carnivore', 'Reptile'],
  ['crocodile', 'Rivers and lakes', 'Carnivore', 'Reptile'],
  ['alligator', 'Wetlands', 'Carnivore', 'Reptile'],
  ['caiman', 'Rainforest', 'Carnivore', 'Reptile'],
  ['gharial', 'Rivers and lakes', 'Carnivore', 'Reptile'],
  ['sea turtle', 'Ocean', 'Omnivore', 'Reptile'],
  ['box turtle', 'Forest', 'Omnivore', 'Reptile'],
  ['tortoise', 'Desert', 'Herbivore', 'Reptile'],
  ['Galapagos tortoise', 'Grassland', 'Herbivore', 'Reptile'],
  ['snapping turtle', 'Rivers and lakes', 'Carnivore', 'Reptile'],
  ['tree frog', 'Rainforest', 'Carnivore', 'Amphibian'],
  ['poison dart frog', 'Rainforest', 'Carnivore', 'Amphibian'],
  ['bullfrog', 'Wetlands', 'Carnivore', 'Amphibian'],
  ['toad', 'Forest', 'Carnivore', 'Amphibian'],
  ['salamander', 'Forest', 'Carnivore', 'Amphibian'],
  ['newt', 'Wetlands', 'Carnivore', 'Amphibian'],
  ['axolotl', 'Rivers and lakes', 'Carnivore', 'Amphibian'],
  ['caecilian', 'Rainforest', 'Carnivore', 'Amphibian'],
  ['horned viper', 'Desert', 'Carnivore', 'Reptile'],
  ['gaboon viper', 'Rainforest', 'Carnivore', 'Reptile'],
  ['tuatara', 'Forest', 'Carnivore', 'Reptile'],
  ['skink', 'Forest', 'Omnivore', 'Reptile'],
  ['anole', 'Rainforest', 'Carnivore', 'Reptile'],
  ['basilisk lizard', 'Rainforest', 'Omnivore', 'Reptile'],
];

// [name, diet, class] — habitat question skipped (all ocean/coastal)
const SEA = [
  ['great white shark', 'Carnivore', 'Fish'],
  ['hammerhead shark', 'Carnivore', 'Fish'],
  ['whale shark', 'Carnivore', 'Fish'],
  ['tiger shark', 'Carnivore', 'Fish'],
  ['bull shark', 'Carnivore', 'Fish'],
  ['clownfish', 'Omnivore', 'Fish'],
  ['angelfish', 'Omnivore', 'Fish'],
  ['piranha', 'Carnivore', 'Fish'],
  ['salmon', 'Carnivore', 'Fish'],
  ['trout', 'Carnivore', 'Fish'],
  ['tuna', 'Carnivore', 'Fish'],
  ['swordfish', 'Carnivore', 'Fish'],
  ['blue marlin', 'Carnivore', 'Fish'],
  ['seahorse', 'Carnivore', 'Fish'],
  ['moray eel', 'Carnivore', 'Fish'],
  ['electric eel', 'Carnivore', 'Fish'],
  ['pufferfish', 'Carnivore', 'Fish'],
  ['lionfish', 'Carnivore', 'Fish'],
  ['flying fish', 'Omnivore', 'Fish'],
  ['anglerfish', 'Carnivore', 'Fish'],
  ['barracuda', 'Carnivore', 'Fish'],
  ['grouper', 'Carnivore', 'Fish'],
  ['cod', 'Carnivore', 'Fish'],
  ['herring', 'Omnivore', 'Fish'],
  ['sardine', 'Omnivore', 'Fish'],
  ['anchovy', 'Omnivore', 'Fish'],
  ['halibut', 'Carnivore', 'Fish'],
  ['flounder', 'Carnivore', 'Fish'],
  ['manta ray', 'Carnivore', 'Fish'],
  ['stingray', 'Carnivore', 'Fish'],
  ['octopus', 'Carnivore', 'Mollusk'],
  ['squid', 'Carnivore', 'Mollusk'],
  ['cuttlefish', 'Carnivore', 'Mollusk'],
  ['nautilus', 'Carnivore', 'Mollusk'],
  ['starfish', 'Carnivore', 'Echinoderm'],
  ['sea urchin', 'Herbivore', 'Echinoderm'],
  ['sea cucumber', 'Omnivore', 'Echinoderm'],
  ['crab', 'Omnivore', 'Crustacean'],
  ['lobster', 'Carnivore', 'Crustacean'],
  ['shrimp', 'Omnivore', 'Crustacean'],
  ['barnacle', 'Omnivore', 'Crustacean'],
  ['oyster', 'Herbivore', 'Mollusk'],
  ['mussel', 'Herbivore', 'Mollusk'],
  ['conch', 'Herbivore', 'Mollusk'],
  ['jellyfish', 'Carnivore', 'Cnidarian'],
  ['sea anemone', 'Carnivore', 'Cnidarian'],
  ['coral', 'Carnivore', 'Cnidarian'],
];

// [name, habitat, diet, class]
const INSECTS = [
  ['honeybee', 'Forest', 'Herbivore', 'Insect'],
  ['bumblebee', 'Grassland', 'Herbivore', 'Insect'],
  ['wasp', 'Forest', 'Carnivore', 'Insect'],
  ['hornet', 'Forest', 'Carnivore', 'Insect'],
  ['ant', 'Forest', 'Omnivore', 'Insect'],
  ['termite', 'Grassland', 'Herbivore', 'Insect'],
  ['butterfly', 'Grassland', 'Herbivore', 'Insect'],
  ['monarch butterfly', 'Grassland', 'Herbivore', 'Insect'],
  ['moth', 'Forest', 'Herbivore', 'Insect'],
  ['dragonfly', 'Wetlands', 'Carnivore', 'Insect'],
  ['damselfly', 'Wetlands', 'Carnivore', 'Insect'],
  ['ladybug', 'Grassland', 'Carnivore', 'Insect'],
  ['dung beetle', 'Grassland', 'Herbivore', 'Insect'],
  ['stag beetle', 'Forest', 'Herbivore', 'Insect'],
  ['firefly', 'Forest', 'Carnivore', 'Insect'],
  ['grasshopper', 'Grassland', 'Herbivore', 'Insect'],
  ['cricket', 'Grassland', 'Omnivore', 'Insect'],
  ['praying mantis', 'Grassland', 'Carnivore', 'Insect'],
  ['cockroach', 'Forest', 'Omnivore', 'Insect'],
  ['cicada', 'Forest', 'Herbivore', 'Insect'],
  ['aphid', 'Grassland', 'Herbivore', 'Insect'],
  ['mosquito', 'Wetlands', 'Carnivore', 'Insect'],
  ['housefly', 'Grassland', 'Omnivore', 'Insect'],
  ['flea', 'Grassland', 'Carnivore', 'Insect'],
  ['stick insect', 'Rainforest', 'Herbivore', 'Insect'],
  ['spider', 'Forest', 'Carnivore', 'Arachnid'],
  ['tarantula', 'Desert', 'Carnivore', 'Arachnid'],
  ['black widow spider', 'Desert', 'Carnivore', 'Arachnid'],
  ['scorpion', 'Desert', 'Carnivore', 'Arachnid'],
  ['tick', 'Forest', 'Carnivore', 'Arachnid'],
  ['centipede', 'Forest', 'Carnivore', 'Myriapod'],
  ['millipede', 'Forest', 'Herbivore', 'Myriapod'],
  ['katydid', 'Rainforest', 'Herbivore', 'Insect'],
  ['earwig', 'Forest', 'Omnivore', 'Insect'],
  ['mayfly', 'Rivers and lakes', 'Herbivore', 'Insect'],
];

// [question, correct, d1, d2, d3, level, chapter]
const BABIES = [
  ['What is a baby kangaroo called?', 'a joey', 'a cub', 'a fawn', 'a pup', 'easy', 'Baby Animals'],
  ['What is a baby elephant called?', 'a calf', 'a cub', 'a foal', 'a kid', 'easy', 'Baby Animals'],
  ['What is a baby dog called?', 'a puppy', 'a kitten', 'a cub', 'a kit', 'easy', 'Baby Animals'],
  ['What is a baby cat called?', 'a kitten', 'a puppy', 'a joey', 'a lamb', 'easy', 'Baby Animals'],
  ['What is a baby cow called?', 'a calf', 'a foal', 'a piglet', 'a lamb', 'easy', 'Baby Animals'],
  ['What is a baby horse called?', 'a foal', 'a calf', 'a cub', 'a fawn', 'easy', 'Baby Animals'],
  ['What is a baby sheep called?', 'a lamb', 'a kid', 'a calf', 'a colt', 'easy', 'Baby Animals'],
  ['What is a baby goat called?', 'a kid', 'a lamb', 'a foal', 'a pup', 'easy', 'Baby Animals'],
  ['What is a baby pig called?', 'a piglet', 'a calf', 'a kit', 'a joey', 'easy', 'Baby Animals'],
  ['What is a baby deer called?', 'a fawn', 'a foal', 'a calf', 'a cub', 'easy', 'Baby Animals'],
  ['What is a baby bear called?', 'a cub', 'a pup', 'a kitten', 'a fawn', 'easy', 'Baby Animals'],
  ['What is a baby lion called?', 'a cub', 'a kitten', 'a foal', 'a kid', 'easy', 'Baby Animals'],
  ['What is a baby tiger called?', 'a cub', 'a puppy', 'a calf', 'a lamb', 'easy', 'Baby Animals'],
  ['What is a baby fox called?', 'a kit', 'a cub', 'a kid', 'a fawn', 'medium', 'Baby Animals'],
  ['What is a baby wolf called?', 'a pup', 'a kit', 'a cub', 'a calf', 'medium', 'Baby Animals'],
  ['What is a baby seal called?', 'a pup', 'a calf', 'a cub', 'a joey', 'medium', 'Baby Animals'],
  ['What is a baby whale called?', 'a calf', 'a pup', 'a cub', 'a foal', 'medium', 'Baby Animals'],
  [
    'What is a baby dolphin called?',
    'a calf',
    'a pup',
    'a chick',
    'a kit',
    'medium',
    'Baby Animals',
  ],
  ['What is a baby penguin called?', 'a chick', 'a pup', 'a cub', 'a calf', 'easy', 'Baby Animals'],
  [
    'What is a baby swan called?',
    'a cygnet',
    'a duckling',
    'a gosling',
    'a chick',
    'medium',
    'Baby Animals',
  ],
  [
    'What is a baby duck called?',
    'a duckling',
    'a chick',
    'a gosling',
    'a cygnet',
    'easy',
    'Baby Animals',
  ],
  [
    'What is a baby goose called?',
    'a gosling',
    'a duckling',
    'a cygnet',
    'a chick',
    'medium',
    'Baby Animals',
  ],
  [
    'What is a baby chicken called?',
    'a chick',
    'a duckling',
    'a poult',
    'a squab',
    'easy',
    'Baby Animals',
  ],
  [
    'What is a baby owl called?',
    'an owlet',
    'a chick',
    'a fledgling',
    'a hatchling',
    'medium',
    'Baby Animals',
  ],
  [
    'What is a baby frog called?',
    'a tadpole',
    'a fry',
    'a larva',
    'a nymph',
    'easy',
    'Baby Animals',
  ],
  ['What is a baby rabbit called?', 'a kit', 'a cub', 'a joey', 'a fawn', 'medium', 'Baby Animals'],
  ['What is a baby hare called?', 'a leveret', 'a kit', 'a cub', 'a pup', 'hard', 'Baby Animals'],
  ['What is a baby beaver called?', 'a kit', 'a pup', 'a cub', 'a calf', 'hard', 'Baby Animals'],
  ['What is a baby otter called?', 'a pup', 'a kit', 'a cub', 'a calf', 'medium', 'Baby Animals'],
  [
    'What is a baby platypus called?',
    'a puggle',
    'a joey',
    'a kit',
    'a larva',
    'expert',
    'Baby Animals',
  ],
  [
    'What is a baby echidna called?',
    'a puggle',
    'a joey',
    'a calf',
    'a hatchling',
    'expert',
    'Baby Animals',
  ],
  ['What is a baby koala called?', 'a joey', 'a cub', 'a kit', 'a calf', 'easy', 'Baby Animals'],
  ['What is a baby raccoon called?', 'a kit', 'a cub', 'a pup', 'a kid', 'medium', 'Baby Animals'],
  [
    'What is a baby giraffe called?',
    'a calf',
    'a foal',
    'a cub',
    'a fawn',
    'medium',
    'Baby Animals',
  ],
  [
    'What is a baby reindeer called?',
    'a calf',
    'a fawn',
    'a foal',
    'a cub',
    'hard',
    'Baby Animals',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const GROUPS = [
  [
    'What is a group of lions called?',
    'a pride',
    'a pack',
    'a herd',
    'a flock',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of wolves called?',
    'a pack',
    'a pride',
    'a herd',
    'a troop',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of fish called?',
    'a school',
    'a herd',
    'a flock',
    'a pack',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of birds called?',
    'a flock',
    'a school',
    'a pack',
    'a pride',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of bees called?',
    'a swarm',
    'a flock',
    'a herd',
    'a pack',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of cattle called?',
    'a herd',
    'a flock',
    'a pack',
    'a swarm',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of sheep called?',
    'a flock',
    'a herd',
    'a pack',
    'a pride',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of elephants called?',
    'a herd',
    'a pack',
    'a troop',
    'a pride',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of whales called?',
    'a pod',
    'a school',
    'a herd',
    'a flock',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of dolphins called?',
    'a pod',
    'a school',
    'a herd',
    'a pride',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of crows called?',
    'a murder',
    'a flock',
    'a parliament',
    'an unkindness',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of owls called?',
    'a parliament',
    'a murder',
    'a flock',
    'a watch',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of frogs called?',
    'an army',
    'a knot',
    'a bloat',
    'a chorus',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of toads called?',
    'a knot',
    'an army',
    'a colony',
    'a bloat',
    'expert',
    'Animal Groups',
  ],
  [
    'What is a group of geese on the ground called?',
    'a gaggle',
    'a skein',
    'a flock',
    'a wedge',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of monkeys called?',
    'a troop',
    'a pack',
    'a band',
    'a tribe',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of gorillas called?',
    'a troop',
    'a herd',
    'a pack',
    'a pride',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of kangaroos called?',
    'a mob',
    'a troop',
    'a herd',
    'a band',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of domestic cats called?',
    'a clowder',
    'a pack',
    'a pride',
    'a kindle',
    'expert',
    'Animal Groups',
  ],
  [
    'What is a group of hyenas called?',
    'a cackle',
    'a pack',
    'a clan',
    'a laugh',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of zebras called?',
    'a dazzle',
    'a herd',
    'a stripe',
    'a parade',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of giraffes called?',
    'a tower',
    'a herd',
    'a stretch',
    'a patch',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of rhinoceroses called?',
    'a crash',
    'a herd',
    'a charge',
    'a storm',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of hippopotamuses called?',
    'a bloat',
    'a herd',
    'a pod',
    'a wallow',
    'expert',
    'Animal Groups',
  ],
  [
    'What is a group of crocodiles called?',
    'a bask',
    'a float',
    'a snap',
    'a herd',
    'hard',
    'Animal Groups',
  ],
  [
    'What is a group of jellyfish called?',
    'a smack',
    'a bloom',
    'a sting',
    'a drift',
    'expert',
    'Animal Groups',
  ],
  [
    'What is a group of ravens called?',
    'an unkindness',
    'a murder',
    'a parliament',
    'a conspiracy',
    'expert',
    'Animal Groups',
  ],
  [
    'What is a group of butterflies called?',
    'a kaleidoscope',
    'a swarm',
    'a flutter',
    'a rainbow',
    'expert',
    'Animal Groups',
  ],
  [
    'What is a group of locusts called?',
    'a plague',
    'a swarm',
    'a cloud',
    'a horde',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of ants called?',
    'a colony',
    'a swarm',
    'an army',
    'a nest',
    'easy',
    'Animal Groups',
  ],
  [
    'What is a group of penguins called?',
    'a colony',
    'a waddle',
    'a huddle',
    'a rookery',
    'medium',
    'Animal Groups',
  ],
  [
    'What is a group of bats called?',
    'a colony',
    'a cloud',
    'a flight',
    'a cave',
    'medium',
    'Animal Groups',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const RECORDS = [
  [
    'Which is the fastest land animal?',
    'the cheetah',
    'the lion',
    'the horse',
    'the greyhound',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the largest animal on Earth?',
    'the blue whale',
    'the African elephant',
    'the whale shark',
    'the orca',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the tallest animal in the world?',
    'the giraffe',
    'the elephant',
    'the ostrich',
    'the camel',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the largest land animal?',
    'the African elephant',
    'the giraffe',
    'the hippopotamus',
    'the white rhinoceros',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the fastest bird in a dive?',
    'the peregrine falcon',
    'the golden eagle',
    'the swift',
    'the hawk',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the largest bird in the world?',
    'the ostrich',
    'the emu',
    'the albatross',
    'the condor',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the smallest bird in the world?',
    'the bee hummingbird',
    'the goldcrest',
    'the wren',
    'the sparrow',
    'medium',
    'Animal Records',
  ],
  [
    'Which bird can fly backward?',
    'the hummingbird',
    'the kingfisher',
    'the swallow',
    'the swift',
    'medium',
    'Animal Records',
  ],
  [
    'Which bird lays the largest egg?',
    'the ostrich',
    'the emu',
    'the albatross',
    'the eagle',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the largest fish in the ocean?',
    'the whale shark',
    'the great white shark',
    'the blue whale',
    'the giant squid',
    'medium',
    'Animal Records',
  ],
  [
    'Which is the largest primate?',
    'the gorilla',
    'the orangutan',
    'the chimpanzee',
    'the baboon',
    'easy',
    'Animal Records',
  ],
  [
    'Which mammal lives the longest?',
    'the bowhead whale',
    'the elephant',
    'the lion',
    'the horse',
    'expert',
    'Animal Records',
  ],
  [
    'Which is the slowest mammal?',
    'the sloth',
    'the koala',
    'the tortoise',
    'the manatee',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the loudest animal on Earth?',
    'the sperm whale',
    'the lion',
    'the howler monkey',
    'the blue whale',
    'expert',
    'Animal Records',
  ],
  [
    'Which is the largest big cat?',
    'the tiger',
    'the lion',
    'the jaguar',
    'the leopard',
    'easy',
    'Animal Records',
  ],
  [
    'Which is the fastest animal in the sea?',
    'the sailfish',
    'the dolphin',
    'the marlin',
    'the tuna',
    'hard',
    'Animal Records',
  ],
  [
    'Which animal has the longest gestation period?',
    'the elephant',
    'the whale',
    'the giraffe',
    'the rhinoceros',
    'hard',
    'Animal Records',
  ],
  [
    'Which bird has the largest wingspan?',
    'the wandering albatross',
    'the condor',
    'the eagle',
    'the swan',
    'medium',
    'Animal Records',
  ],
  [
    'Which is the largest rodent in the world?',
    'the capybara',
    'the beaver',
    'the porcupine',
    'the wombat',
    'medium',
    'Animal Records',
  ],
  [
    'Which snake is the longest in the world?',
    'the reticulated python',
    'the anaconda',
    'the boa constrictor',
    'the king cobra',
    'medium',
    'Animal Records',
  ],
  [
    'Which snake is the heaviest in the world?',
    'the green anaconda',
    'the reticulated python',
    'the king cobra',
    'the boa constrictor',
    'medium',
    'Animal Records',
  ],
  [
    'Which is the largest spider in the world by mass?',
    'the goliath birdeater',
    'the tarantula',
    'the huntsman spider',
    'the wolf spider',
    'hard',
    'Animal Records',
  ],
  [
    'Which animal kills the most humans each year?',
    'the mosquito',
    'the snake',
    'the crocodile',
    'the hippopotamus',
    'medium',
    'Animal Records',
  ],
  [
    'Which is the largest turtle in the world?',
    'the leatherback sea turtle',
    'the Galapagos tortoise',
    'the green sea turtle',
    'the snapping turtle',
    'hard',
    'Animal Records',
  ],
  [
    'Which is the largest lizard in the world?',
    'the Komodo dragon',
    'the monitor lizard',
    'the iguana',
    'the crocodile',
    'medium',
    'Animal Records',
  ],
  [
    'Which mammal has the most powerful bite?',
    'the hippopotamus',
    'the lion',
    'the grizzly bear',
    'the crocodile',
    'hard',
    'Animal Records',
  ],
  [
    'Which is the smallest mammal in the world?',
    'the bumblebee bat',
    'the shrew',
    'the mouse',
    'the pygmy possum',
    'hard',
    'Animal Records',
  ],
  [
    'Which animal can sleep for up to three years?',
    'the snail',
    'the bear',
    'the bat',
    'the sloth',
    'medium',
    'Animal Records',
  ],
  [
    'Which bird is famous for collecting shiny objects?',
    'the magpie',
    'the crow',
    'the raven',
    'the starling',
    'medium',
    'Animal Records',
  ],
  [
    'Which animal has the thickest fur?',
    'the sea otter',
    'the polar bear',
    'the arctic fox',
    'the chinchilla',
    'expert',
    'Animal Records',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const GENERAL = [
  [
    'Which animal is known as the King of the Jungle?',
    'the lion',
    'the tiger',
    'the gorilla',
    'the elephant',
    'easy',
    'Animal Basics',
  ],
  [
    'Which mammal is known for laying eggs?',
    'the platypus',
    'the kangaroo',
    'the bat',
    'the sloth',
    'medium',
    'Animal Basics',
  ],
  [
    'Which big cat cannot roar?',
    'the snow leopard',
    'the lion',
    'the tiger',
    'the jaguar',
    'hard',
    'Animal Basics',
  ],
  [
    'Which big cat is famous for purring?',
    'the cheetah',
    'the lion',
    'the tiger',
    'the leopard',
    'hard',
    'Animal Basics',
  ],
  ['How many legs does a spider have?', 'Eight', 'Six', 'Ten', 'Four', 'easy', 'Animal Basics'],
  ['How many legs does an insect have?', 'Six', 'Eight', 'Four', 'Ten', 'easy', 'Animal Basics'],
  [
    'How many hearts does an octopus have?',
    'Three',
    'One',
    'Two',
    'Four',
    'medium',
    'Animal Basics',
  ],
  [
    'What color is the blood of an octopus?',
    'Blue',
    'Red',
    'Green',
    'Clear',
    'medium',
    'Animal Basics',
  ],
  [
    'Which way do crabs typically walk?',
    'Sideways',
    'Forward',
    'Backward',
    'In circles',
    'easy',
    'Animal Basics',
  ],
  [
    'How does a snake mainly smell?',
    'With its tongue',
    'With its nose',
    'With its skin',
    'With its ears',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a shark skeleton made of?',
    'Cartilage',
    'Bone',
    'Shell',
    'Cartoon',
    'medium',
    'Animal Basics',
  ],
  [
    'What do scorpions do under ultraviolet light?',
    'Glow',
    'Disappear',
    'Change color to red',
    'Freeze',
    'medium',
    'Animal Basics',
  ],
  [
    'How do fireflies produce light?',
    'Bioluminescence',
    'Reflecting moonlight',
    'Static electricity',
    'Heat glow',
    'medium',
    'Animal Basics',
  ],
  [
    'Which insect can survive for weeks without its head?',
    'the cockroach',
    'the ant',
    'the beetle',
    'the fly',
    'medium',
    'Animal Basics',
  ],
  [
    'How do ants breathe?',
    'Through tiny holes called spiracles',
    'With lungs',
    'Through their skin only',
    'With gills',
    'expert',
    'Animal Basics',
  ],
  [
    'How do butterflies taste food?',
    'With their feet',
    'With their tongue',
    'With their antennae',
    'With their wings',
    'medium',
    'Animal Basics',
  ],
  [
    'How long can a dolphin rest one half of its brain at a time?',
    'About two hours',
    'Twenty-four hours',
    'Ten minutes',
    'It sleeps with both halves',
    'expert',
    'Animal Basics',
  ],
  [
    'How far can an owl rotate its head?',
    'About 270 degrees',
    '90 degrees',
    '360 degrees',
    '180 degrees',
    'medium',
    'Animal Basics',
  ],
  [
    'Why does a woodpecker have such a long tongue?',
    'It wraps around its skull',
    'It is a hollow tube',
    'It can detach',
    'It has a hook at the end',
    'expert',
    'Animal Basics',
  ],
  [
    'Why are flamingos pink?',
    'Their diet of shrimp and algae',
    'Their skin pigment',
    'Sun exposure',
    'Their blood',
    'easy',
    'Animal Basics',
  ],
  [
    'Roughly how large is a kiwi egg compared to its body?',
    'About one sixth of its weight',
    'One hundredth of its weight',
    'Half of its weight',
    'One fiftieth of its weight',
    'hard',
    'Animal Basics',
  ],
  [
    'Which mammal is venomous?',
    'the platypus',
    'the koala',
    'the wombat',
    'the wallaby',
    'hard',
    'Animal Basics',
  ],
  [
    'What do aardvarks mainly eat?',
    'Ants and termites',
    'Grass',
    'Fruit',
    'Roots',
    'easy',
    'Animal Basics',
  ],
  [
    'How many teeth does an anteater have?',
    'None',
    'Twenty',
    'Thirty-two',
    'Ten',
    'medium',
    'Animal Basics',
  ],
  [
    'What grows on sloth fur?',
    'Algae',
    'Moss roots',
    'Fungi spores',
    'Small flowers',
    'medium',
    'Animal Basics',
  ],
  [
    'Is tiger skin striped as well as its fur?',
    'Yes',
    'No',
    'Only on the back',
    'Only when young',
    'medium',
    'Animal Basics',
  ],
  [
    'Are any two zebras striped identically?',
    'No',
    'Yes',
    'Only twins',
    'Only in the same herd',
    'easy',
    'Animal Basics',
  ],
  [
    'How do frogs absorb water?',
    'Through their skin',
    'With their tongue',
    'By licking leaves',
    'They drink from ponds',
    'medium',
    'Animal Basics',
  ],
  [
    'Why do chameleons change color?',
    'To communicate and control temperature',
    'Only to hide',
    'To attract prey',
    'They change only at night',
    'medium',
    'Animal Basics',
  ],
  [
    'How do geckos climb smooth walls?',
    'Sticky toe pads with microscopic hairs',
    'Claw hooks',
    'Suction cups',
    'Glue from their feet',
    'medium',
    'Animal Basics',
  ],
  [
    'Can a crocodile stick out its tongue?',
    'No',
    'Yes',
    'Only when young',
    'Only in water',
    'medium',
    'Animal Basics',
  ],
  [
    'What feeds on a giant panda diet of?',
    'Bamboo',
    'Fish',
    'Insects',
    'Berries',
    'easy',
    'Animal Basics',
  ],
  [
    'How do dolphins locate prey in murky water?',
    'Echolocation',
    'Sharp eyesight',
    'Smell',
    'Electric senses',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a group of elephant families led by?',
    'The oldest female',
    'The strongest male',
    'The fastest hunter',
    'A rotating leader',
    'medium',
    'Animal Basics',
  ],
  [
    'What do elephants use their trunks for?',
    'Breathing, smelling, and grabbing',
    'Only for drinking',
    'Only for smelling',
    'Balance only',
    'easy',
    'Animal Basics',
  ],
  [
    'What do camels store in their humps?',
    'Fat',
    'Water',
    'Muscle',
    'Food',
    'easy',
    'Animal Basics',
  ],
  [
    'What color is a polar bear skin under its fur?',
    'Black',
    'White',
    'Pink',
    'Gray',
    'medium',
    'Animal Basics',
  ],
  [
    'What is unique about each zebra pattern?',
    'It is unique like a fingerprint',
    'All zebras share one pattern',
    'It changes with age',
    'It matches their mother exactly',
    'easy',
    'Animal Basics',
  ],
  [
    'What are male seahorses famous for?',
    'Giving birth',
    'Building nests from pearls',
    'Changing into females',
    'Guarding nothing',
    'easy',
    'Animal Basics',
  ],
  [
    'Why is the clownfish safe among sea anemones?',
    'A protective mucus layer',
    'It fights the anemone',
    'It eats the stingers',
    'It hides in the tentacle shadows',
    'medium',
    'Animal Basics',
  ],
  [
    'How strong is the shock of an electric eel?',
    'Up to about 600 volts',
    'About 12 volts',
    'About 50 volts',
    'About 5000 volts',
    'hard',
    'Animal Basics',
  ],
  [
    'What can a starfish do if it loses an arm?',
    'Regrow it',
    'Nothing',
    'Replace it with a leg',
    'Swap roles with another arm',
    'easy',
    'Animal Basics',
  ],
  ['How many arms does an octopus have?', 'Eight', 'Six', 'Ten', 'Twelve', 'easy', 'Animal Basics'],
  [
    'Which sea creature has the largest eyes?',
    'the colossal squid',
    'the blue whale',
    'the great white shark',
    'the giant clam',
    'hard',
    'Animal Basics',
  ],
  [
    'What do baleen whales use to feed?',
    'Baleen plates to filter food',
    'Sharp teeth',
    'Long tongues only',
    'Suction cups',
    'medium',
    'Animal Basics',
  ],
  [
    'Which ape is the closest living relative of humans?',
    'the chimpanzee',
    'the gorilla',
    'the orangutan',
    'the baboon',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a male horse called?',
    'a stallion',
    'a mare',
    'a colt',
    'a gelding only',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a female horse called?',
    'a mare',
    'a stallion',
    'a foal',
    'a filly only',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a male deer called?',
    'a buck',
    'a doe',
    'a fawn',
    'a stag only',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a female deer called?',
    'a doe',
    'a buck',
    'a fawn',
    'a hart',
    'medium',
    'Animal Basics',
  ],
  ['What is a male sheep called?', 'a ram', 'a ewe', 'a lamb', 'a hogget', 'easy', 'Animal Basics'],
  [
    'What is a female sheep called?',
    'a ewe',
    'a ram',
    'a lamb',
    'a mutton',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a male chicken called?',
    'a rooster',
    'a hen',
    'a pullet',
    'a capon',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a female chicken called?',
    'a hen',
    'a rooster',
    'a chick',
    'a cockerel',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a young cat under one year usually called?',
    'a kitten',
    'a cub',
    'a pup',
    'a foal',
    'easy',
    'Animal Basics',
  ],
  [
    'What do you call animals that eat only plants?',
    'Herbivores',
    'Carnivores',
    'Omnivores',
    'Insectivores',
    'easy',
    'Animal Basics',
  ],
  [
    'What do you call animals that eat only meat?',
    'Carnivores',
    'Herbivores',
    'Omnivores',
    'Frugivores',
    'easy',
    'Animal Basics',
  ],
  [
    'What do you call animals that eat plants and meat?',
    'Omnivores',
    'Herbivores',
    'Carnivores',
    'Detritivores',
    'easy',
    'Animal Basics',
  ],
  [
    'What do you call an animal that is active at night?',
    'Nocturnal',
    'Diurnal',
    'Crepuscular',
    'Migratory',
    'easy',
    'Animal Basics',
  ],
  [
    'What is animal migration?',
    'Seasonal movement between regions',
    'Shedding fur',
    'Hibernation',
    'Hunting in packs',
    'easy',
    'Animal Basics',
  ],
  [
    'What is hibernation?',
    'A deep sleep to survive winter',
    'A mating ritual',
    'A hunting style',
    'A migration path',
    'easy',
    'Animal Basics',
  ],
  [
    'What is camouflage?',
    'Blending into surroundings',
    'A mating call',
    'A hunting technique',
    'A pack structure',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a predator?',
    'An animal that hunts other animals',
    'An animal that eats plants',
    'A scavenger bird',
    'A sleeping animal',
    'easy',
    'Animal Basics',
  ],
  [
    'What is an ecosystem?',
    'A community of living things and their environment',
    'A single species',
    'A food chain only',
    'A zoo habitat',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a food chain?',
    'Who eats whom in an ecosystem',
    'A group of predators',
    'A migration route',
    'A zoo feeding plan',
    'easy',
    'Animal Basics',
  ],
  [
    'What is an apex predator?',
    'A predator at the top of its food chain',
    'A predator with no teeth',
    'A plant-eating hunter',
    'A small insect eater',
    'medium',
    'Animal Basics',
  ],
  [
    'What is poaching?',
    'Illegal hunting of protected animals',
    'Feeding wild animals',
    'Tracking animals with cameras',
    'A mating season',
    'easy',
    'Animal Basics',
  ],
  [
    'What does endangered mean for a species?',
    'At risk of extinction',
    'Living in zoos only',
    'Living in captivity',
    'Recently discovered',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a habitat?',
    'The natural home of an animal',
    'An animal diet',
    'A hunting ground only',
    'A zoo cage',
    'easy',
    'Animal Basics',
  ],
  [
    'What is conservation?',
    'Protecting nature and wildlife',
    'Hunting for sport',
    'Building zoos',
    'Collecting animals',
    'easy',
    'Animal Basics',
  ],
  [
    'Which big cat has the loudest roar?',
    'the lion',
    'the tiger',
    'the leopard',
    'the cheetah',
    'medium',
    'Animal Basics',
  ],
  [
    'Which bird is a symbol of peace?',
    'the dove',
    'the eagle',
    'the owl',
    'the swan',
    'easy',
    'Animal Basics',
  ],
  [
    'Which bird is a national symbol of the United States?',
    'the bald eagle',
    'the turkey',
    'the raven',
    'the falcon',
    'easy',
    'Animal Basics',
  ],
  [
    'Which animal is a symbol of Australia?',
    'the kangaroo',
    'the kiwi',
    'the panda',
    'the tiger',
    'easy',
    'Animal Basics',
  ],
  [
    'Which bird cannot fly?',
    'the penguin',
    'the sparrow',
    'the eagle',
    'the parrot',
    'easy',
    'Animal Basics',
  ],
  [
    'Which mammals can truly fly?',
    'Bats',
    'Squirrels',
    'Sugar gliders',
    'Flying fish',
    'easy',
    'Animal Basics',
  ],
  [
    'What do snakes use to detect heat?',
    'Heat-sensing pits',
    'Their tongues',
    'Their eyes',
    'Their scales',
    'medium',
    'Animal Basics',
  ],
  [
    'What is the study of animals called?',
    'Zoology',
    'Botany',
    'Geology',
    'Ecology',
    'easy',
    'Animal Basics',
  ],
  [
    'What is the study of birds called?',
    'Ornithology',
    'Entomology',
    'Ichthyology',
    'Herpetology',
    'medium',
    'Animal Basics',
  ],
  [
    'What is the study of insects called?',
    'Entomology',
    'Ornithology',
    'Zoology',
    'Apiology',
    'medium',
    'Animal Basics',
  ],
  [
    'What is the study of fish called?',
    'Ichthyology',
    'Herpetology',
    'Entomology',
    'Marinology',
    'medium',
    'Animal Basics',
  ],
  [
    'What is the study of reptiles and amphibians called?',
    'Herpetology',
    'Ichthyology',
    'Ornithology',
    'Zoology',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a vertebrate?',
    'An animal with a backbone',
    'An animal without bones',
    'An insect',
    'A plant eater',
    'easy',
    'Animal Basics',
  ],
  [
    'What is an invertebrate?',
    'An animal without a backbone',
    'An animal with a spine',
    'A mammal',
    'A bird only',
    'easy',
    'Animal Basics',
  ],
  [
    'Which animal group are cold-blooded reptiles in?',
    'Reptilia',
    'Aves',
    'Mammalia',
    'Amphibia',
    'medium',
    'Animal Basics',
  ],
  [
    'What is an omnivore example?',
    'the bear',
    'the cow',
    'the lion',
    'the rabbit',
    'medium',
    'Animal Basics',
  ],
  [
    'What do herbivores have for grinding plants?',
    'Flat molars',
    'Sharp canines',
    'No teeth',
    'Beaks only',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a scavenger?',
    'An animal that feeds on remains',
    'A top predator',
    'A plant eater',
    'An insect only',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a nocturnal bird of prey called?',
    'an owl',
    'an eagle',
    'a falcon',
    'a sparrow',
    'easy',
    'Animal Basics',
  ],
  [
    'What is a diurnal animal?',
    'Active during the day',
    'Active at night',
    'Active at dawn only',
    'Always sleeping',
    'medium',
    'Animal Basics',
  ],
  [
    'What does it mean when an animal is territorial?',
    'It defends its area',
    'It travels constantly',
    'It lives alone by choice',
    'It hunts in packs',
    'medium',
    'Animal Basics',
  ],
  [
    'What is a species?',
    'A group that can breed together',
    'Any animal',
    'A zoo category',
    'A color pattern',
    'medium',
    'Animal Basics',
  ],
  [
    'What is binomial naming?',
    'A two-part scientific name',
    'A zoo nickname',
    'A tracking code',
    'A breed label',
    'medium',
    'Animal Basics',
  ],
  [
    'Which animal is famous for its long trunk and large ears?',
    'the elephant',
    'the rhinoceros',
    'the hippopotamus',
    'the buffalo',
    'easy',
    'Animal Basics',
  ],
  [
    'Which insect makes honey?',
    'the honeybee',
    'the wasp',
    'the ant',
    'the beetle',
    'easy',
    'Animal Basics',
  ],
  [
    'Which animal is known as humans best friend?',
    'the dog',
    'the cat',
    'the horse',
    'the parrot',
    'easy',
    'Animal Basics',
  ],
  [
    'Which animal is said to have nine lives?',
    'the cat',
    'the dog',
    'the fox',
    'the wolf',
    'easy',
    'Animal Basics',
  ],
  [
    'Which animal builds dams in rivers?',
    'the beaver',
    'the otter',
    'the badger',
    'the mole',
    'easy',
    'Animal Basics',
  ],
  [
    'Which bird lays its eggs in other birds nests?',
    'the cuckoo',
    'the robin',
    'the sparrow',
    'the dove',
    'medium',
    'Animal Basics',
  ],
  [
    'Which crab borrows shells to live in?',
    'the hermit crab',
    'the king crab',
    'the fiddler crab',
    'the horseshoe crab',
    'medium',
    'Animal Basics',
  ],
  [
    'Which mammal hangs upside down in caves?',
    'the bat',
    'the sloth',
    'the monkey',
    'the owl',
    'easy',
    'Animal Basics',
  ],
  [
    'Which insect produces silk?',
    'the silkworm',
    'the ant',
    'the bee',
    'the wasp',
    'easy',
    'Animal Basics',
  ],
  [
    'Which bird cannot fly but swims extremely well?',
    'the penguin',
    'the parrot',
    'the eagle',
    'the owl',
    'easy',
    'Animal Basics',
  ],
  [
    'Which large flightless bird lives in Australia?',
    'the emu',
    'the penguin',
    'the ostrich',
    'the kiwi',
    'easy',
    'Animal Basics',
  ],
  [
    'Which reptile is famous for its hard protective shell?',
    'the turtle',
    'the frog',
    'the snake',
    'the lizard',
    'easy',
    'Animal Basics',
  ],
];

// [question, free-text answer, chapter]
const EXTREMES = [
  ['How many legs does a spider have?', 'Eight', 'Animal Basics'],
  ['How many legs does an insect have?', 'Six', 'Animal Basics'],
  ['How many hearts does an octopus have?', 'Three', 'Animal Basics'],
  ['How many arms does an octopus have?', 'Eight', 'Animal Basics'],
  ['What is a baby kangaroo called?', 'A joey', 'Baby Animals'],
  ['What is a baby elephant called?', 'A calf', 'Baby Animals'],
  ['What is a group of lions called?', 'A pride', 'Animal Groups'],
  ['What is a group of wolves called?', 'A pack', 'Animal Groups'],
  ['What is a group of crows called?', 'A murder', 'Animal Groups'],
  ['What is a group of owls called?', 'A parliament', 'Animal Groups'],
  ['What is the largest animal on Earth?', 'The blue whale', 'Animal Records'],
  ['What is the tallest animal in the world?', 'The giraffe', 'Animal Records'],
  ['What is the fastest land animal?', 'The cheetah', 'Animal Records'],
  ['What is the largest bird in the world?', 'The ostrich', 'Animal Records'],
  ['What is the largest fish in the sea?', 'The whale shark', 'Animal Records'],
  ['What is the largest primate?', 'The gorilla', 'Animal Records'],
  ['What color is flamingo feathers related to?', 'Diet of shrimp and algae', 'Animal Records'],
  ['What do camels store in their humps?', 'Fat', 'Animal Basics'],
  ['What is a shark skeleton made of?', 'Cartilage', 'Animal Basics'],
  ['Which mammal lays eggs?', 'The platypus', 'Animal Basics'],
];

function generate(rng) {
  const rows = [];
  const habitatPool = HABITATS;
  const dietPool = DIETS;
  const classPool = ['Mammal', 'Bird', 'Reptile', 'Amphibian', 'Fish', 'Insect', 'Arachnid'];

  function animalRows(name, habitat, diet, cls) {
    const art = /^[aeiou]/i.test(name) ? 'an' : 'a';
    rows.push({
      q: `To which animal class does the ${name} belong?`,
      correct: cls,
      ds: distractors(
        classPool.filter((c) => c !== cls),
        cls,
        3,
        rng
      ),
      level: 'easy',
      chapter: 'Animal Classes',
    });
    if (habitat) {
      rows.push({
        q: `In which natural habitat does the ${name} live?`,
        correct: habitat,
        ds: distractors(
          habitatPool.filter((h) => h !== habitat),
          habitat,
          3,
          rng
        ),
        level: 'medium',
        chapter: 'Habitats',
      });
    }
    if (diet) {
      rows.push({
        q: `Is the ${name} a herbivore, carnivore, or omnivore?`,
        correct: diet,
        ds: distractors(
          dietPool.filter((d) => d !== diet),
          diet,
          2,
          rng
        ).slice(0, 2),
        level: 'medium',
        chapter: 'Diets',
      });
    }
  }

  for (const [name, habitat, diet] of MAMMALS) animalRows(name, habitat, diet, 'Mammal');
  for (const [name, habitat, diet] of BIRDS) animalRows(name, habitat, diet, 'Bird');
  for (const [name, habitat, diet, cls] of REPTILES) animalRows(name, habitat, diet, cls);
  for (const [name, diet, cls] of SEA) animalRows(name, null, diet, cls);
  for (const [name, habitat, diet, cls] of INSECTS) animalRows(name, habitat, diet, cls);

  for (const bank of [BABIES, GROUPS, RECORDS, GENERAL]) {
    for (const f of bank)
      rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  }

  for (const [q, text, chapter] of EXTREMES) rows.push({ q, text, chapter });

  return rows;
}

module.exports = { subject: 'Animals', generate };
