'use strict';

const rows = [
  [
    'What is Amazon known for besides retail? AWS cloud computing',
    'The AWS cloud platform',
    'Prime Video content',
    'Kindle e-readers',
    'Alexa devices',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Alphabet? Googles parent holding company',
    'Googles parent company',
    'Amazons rival conglomerate',
    'A biotech firm',
    'A telecom group',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Berkshire Hathaway? Warren Buffetts conglomerate',
    'The Omaha holding company',
    'A hedge fund only',
    'An insurance-only firm',
    'A bank holding company',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Berkshire largest holding famously? Apple in recent years',
    'Apple was its largest stock stake',
    'Coca-Cola the oldest stake',
    'Bank of America large stake',
    'American Express large stake',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is GE famous for historically? Industrial conglomerate founded by Edison',
    'Edison-linked industrial conglomerate',
    'A software giant',
    'A bank',
    'A retailer',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Siemens known for? German industrial engineering',
    'Industrial engineering and electrification',
    'French luxury goods',
    'Japanese robotics',
    'Korean semiconductors',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Caterpillar known for? Construction machinery',
    'Yellow construction equipment',
    'Farm tractors different Deere',
    'Mining trucks only',
    'Cranes only',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is John Deere known for? Agricultural machinery',
    'Green farm tractors and equipment',
    'Construction excavators different',
    'Automotive parts',
    'Aerospace parts',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is 3M known for? Innovation including Post-it notes',
    'Post-it notes and Scotch tape',
    'Software clouds',
    'Autos',
    'Coffee',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Procter and Gamble known for? Consumer household brands',
    'Household consumer brand portfolio',
    'Industrial machinery',
    'Airplanes',
    'Chips fabrication',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Unilever known for? Consumer goods Anglo-Dutch merged',
    'Consumer goods across foods and home care',
    'Luxury goods',
    'Airlines',
    'Semiconductors',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Nestle known for? Food and beverage giant',
    'The Swiss food and drinks giant',
    'Swiss watches',
    'Swiss banking',
    'Swiss pharma only',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Danone known for? Yogurt and dairy',
    'Dairy and plant-based foods',
    'Coffee',
    'Chocolate',
    'Cheese only',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Starbucks known for? Coffeehouse chain',
    'The global coffee shop chain',
    'Italian espresso machines',
    'Tea only',
    'Donuts',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Dunkin known for? Coffee and donuts',
    'Coffee and donuts chain',
    'Bagels only',
    'Ice cream',
    'Sandwiches only',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Krispy Kreme known for? Original glazed donuts',
    'Hot original glazed donuts',
    'Cake donuts only',
    'Coffee only',
    'Bagels',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Ben and Jerry known for? Ice cream with social mission',
    'Flavorful socially minded ice cream',
    'Frozen yogurt chain',
    'Sorbet only',
    'Cheesecake',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Haagen-Dazs known for? Premium ice cream',
    'Superpremium ice cream brand',
    'Frozen yogurt',
    'Sherbet',
    'Chocolate bars',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Lindt known for? Swiss chocolate',
    'The Swiss chocolatier brand',
    'Belgian chocolates different',
    'American chocolate different',
    'Coffee brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Ghirardelli known for? San Francisco chocolate',
    'The San Francisco chocolate brand',
    'Seattle coffee brand',
    'New York cheesecake brand',
    'Boston baked beans brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Ferrero known for? Nutella and Rocher',
    'Nutella spread and Ferrero Rocher',
    'Hershey chocolates',
    'Cadbury chocolates',
    'Mars bars',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Hershey known for? American chocolate town',
    'The Pennsylvania chocolate maker',
    'Belgian chocolates',
    'Swiss chocolates',
    'Japanese chocolates',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Mars known for? M&Ms and Snickers family firm',
    'The family candy and pet care giant',
    'Planet research firm',
    'Coffee brand',
    'Chips brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Mondelez known for? Snacks like Oreo',
    'Oreo and Cadbury snack owner',
    'Ice cream maker',
    'Beverage maker',
    'Cereal only maker',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Kelloggs known for? Breakfast cereals',
    'Cereal brands like Corn Flakes',
    'Chocolate bars',
    'Yogurt',
    'Coffee',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is General Mills known for? Cereal and food brands',
    'Cheerios and Betty Crocker owner',
    'Cleaning products',
    'Cosmetics',
    'Electronics',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Campbells known for? Condensed soups',
    'The soup company',
    'Cereal company',
    'Candy company',
    'Coffee company',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Heinz known for? Ketchup 57 varieties',
    'The ketchup with 57 varieties slogan',
    'Mustard only',
    'Mayonnaise only',
    'Pickles only',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Chobani known for? Greek yogurt',
    'The Greek yogurt brand',
    'Sour cream brand',
    'Ice cream brand',
    'Cheese brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Danone Activia known for? Probiotic yogurt',
    'The probiotic yogurt line',
    'Ice cream line',
    'Milk line',
    'Cheese line',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Red Bull owned by? Dietrich Mateschitz and Yoovidhya families',
    'The Austrian-Thai ownership',
    'Coca-Cola ownership',
    'Pepsi ownership',
    'Nestle ownership',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Monster Beverage partnered with? Coca-Cola distribution',
    'Coca-Cola as major distributor',
    'Pepsi as distributor',
    'Nestle as distributor',
    'Unilever as distributor',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Celsius known for? Fitness energy drinks',
    'The fitness energy drink brand',
    'A sports water brand',
    'A protein shake brand',
    'A tea brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Liquid Death known for? Canned water punk branding',
    'The punk-branded canned water',
    'An energy drink',
    'A soda brand',
    'A juice brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is LaCroix known for? Sparkling water',
    'The sparkling water brand',
    'Still water brand',
    'Tonic water brand',
    'Coconut water brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Perrier known for? French sparkling mineral water',
    'The French sparkling water',
    'Italian sparkling water San Pellegrino',
    'German sparkling water',
    'Spanish sparkling water',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is San Pellegrino? Italian sparkling mineral water',
    'The Italian sparkling water',
    'French sparkling water Perrier',
    'Norwegian water brand',
    'Fiji water brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Fiji Water known for? Artesian water in square bottles',
    'The square-bottle artesian water',
    'Hawaiian water brand',
    'Alpine water brand',
    'Icelandic water brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Evian known for? French alpine spring water',
    'The French Alps spring water',
    'Italian alpine water',
    'Swiss alpine water',
    'Icelandic spring water',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Voss known for? Norwegian artesian water',
    'The Norwegian cylinder-bottle water',
    'Fiji square bottles different',
    'Evian French Alps different',
    'Perrier bubbles different',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Dr Pepper known for? 23 flavors soda',
    'The 23-flavor soda',
    'Cola flavor only',
    'Lemon-lime flavor',
    'Orange soda',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Mountain Dew known for? Citrus soda Pepsi brand',
    'The citrus soda of PepsiCo',
    'The cola of Coca-Cola',
    'A root beer brand',
    'An energy shot',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Fanta owned by? Coca-Cola Company',
    'The Coca-Cola Company',
    'PepsiCo',
    'Dr Pepper Keurig',
    'Red Bull',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Sprite owned by? Coca-Cola Company',
    'The Coca-Cola Company lemon-lime',
    'PepsiCo Sierra Mist Mist Twst lineage',
    'Dr Pepper',
    'Red Bull',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is 7UP owned by? Keurig Dr Pepper in the US',
    'Keurig Dr Pepper in the US',
    'Coca-Cola',
    'PepsiCo',
    'Red Bull',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Gatorade owned by? PepsiCo',
    'PepsiCo owns the sports drink',
    'Coca-Cola owns Powerade rival',
    'Nestle owns it',
    'Red Bull owns it',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Powerade owned by? Coca-Cola',
    'Coca-Cola owns the sports drink',
    'PepsiCo owns Gatorade rival',
    'Nestle owns it',
    'Red Bull owns it',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Vitaminwater owned by? Coca-Cola',
    'Coca-Cola owns the vitamin water',
    'PepsiCo owns it',
    'Nestle owns it',
    'Danone owns it',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Smartwater owned by? Coca-Cola',
    'Coca-Cola owns the vapor-distilled water',
    'PepsiCo owns it',
    'Nestle owns it',
    'Danone owns it',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Dasani? Coca-Colas bottled water',
    'The Coca-Cola water brand',
    'The PepsiCo water Aquafina',
    'The Nestle Pure Life water',
    'The Danone water Evian',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Aquafina? PepsiCos bottled water',
    'The PepsiCo water brand',
    'The Coca-Cola water Dasani',
    'The Nestle Pure Life',
    'The Danone water',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Pure Life owned by? Nestle waters then BlueTriton era',
    'Long a Nestle water brand now BlueTriton era',
    'Coca-Cola brand',
    'PepsiCo brand',
    'Danone brand',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is BlueTriton? The North American water brands owner',
    'The owner of many former Nestle waters',
    'A Coca-Cola water unit',
    'A PepsiCo water unit',
    'A Danone water unit',
    'expert',
    'Companies & Founders',
  ],
  [
    'What is Liquid I.V.? A hydration multiplier brand owned by Unilever',
    'The hydration powder brand',
    'A canned water brand',
    'An energy drink',
    'A sports bar',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Electrolit? A Mexican hydration drink',
    'The Mexican hydration beverage',
    'A US soda brand',
    'An energy drink brand',
    'A tea brand',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Biosteel? A Canadian sports drink',
    'The Canadian sports hydration drink',
    'A US soda brand',
    'A UK energy drink',
    'An Australian juice',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Guayaki? A yerba mate energy brand',
    'The mate-based energy brand',
    'A coffee brand',
    'A tea bag brand',
    'A kombucha brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Health-Ade? A kombucha brand',
    'The kombucha maker',
    'A kefir maker',
    'A water kefir brand',
    'A juice cleanse brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is GTs Living Foods? A kombucha pioneer brand',
    'The original Synergy kombucha maker',
    'A Health-Ade rival same category',
    'A kefir maker',
    'A water brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Oatly known for? Oat milk',
    'The Swedish oat milk brand',
    'An almond milk brand',
    'A soy milk brand',
    'A coconut milk brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Alpro known for? Plant-based milks in Europe',
    'The European plant milk brand',
    'An oat milk US brand',
    'A soy sauce brand',
    'A cheese brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Silk known for? Soy and almond milks in the US',
    'The US plant milk brand',
    'The European plant brand Alpro',
    'A dairy brand',
    'A juice brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Ripple known for? Pea protein milk',
    'The pea-protein milk brand',
    'An oat milk brand',
    'An almond milk brand',
    'A coconut yogurt',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Califia Farms known for? Plant milks and creamers',
    'The plant-based beverage brand',
    'A dairy brand',
    'A juice brand',
    'A coffee roaster',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Chobani coffee line? Coffee drinks launched by Chobani',
    'The yogurt brands coffee line',
    'A rival yogurt brands coffee',
    'A tea line',
    'A water line',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is La Colombe known for? Draft latte cans and cafes',
    'The coffee roaster with draft lattes',
    'A kombucha brand',
    'An energy drink brand',
    'A tea brand',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Stumptown known for? Portland coffee roaster',
    'The Portland cold brew roaster',
    'A Seattle roaster Starbucks city',
    'An Oakland roaster Blue Bottle is Oakland too',
    'A Boston roaster',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Blue Bottle owned by? Nestle majority stake',
    'Nestle bought a majority stake',
    'JAB holding JDE peers',
    'Keurig Dr Pepper',
    'Lavazza',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is JDE Peets? A major coffee company Jacobs Douwe Egberts',
    'The Jacobs Douwe Egberts coffee giant',
    'A Swiss chocolate giant',
    'An Italian espresso brand only',
    'A US roaster only',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Lavazza? An Italian coffee roaster',
    'The Turin coffee roaster',
    'A Milan fashion house',
    'A Roman pasta brand',
    'A Naples pizza chain',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Illy? An Italian espresso brand',
    'The Trieste espresso brand',
    'The Turin roaster Lavazza',
    'A US roaster',
    'A German roaster',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Keurig known for? Single-serve K-Cup brewers',
    'The K-Cup pod brewing system',
    'Espresso machines',
    'Cold brew towers',
    'Grinders',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Nespresso? Nestles espresso capsule system',
    'The capsule espresso system by Nestle',
    'A Keurig rival by JDE',
    'A drip machine brand',
    'A grinder brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Dolce Gusto? Nescafes capsule system',
    'The Nestle capsule coffee line',
    'A Nespresso rival same company',
    'A Keurig partner brand',
    'A Lavazza capsule system A Modo Mio',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Breville known for? Premium kitchen appliances',
    'The Australian appliance brand',
    'A German appliance brand',
    'A US appliance brand',
    'A Korean appliance brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is DeLonghi known for? Italian espresso machines',
    'The Italian coffee appliance maker',
    'A German dishwasher maker',
    'A French oven maker',
    'A US blender maker',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is KitchenAid known for? Stand mixers',
    'The iconic stand mixer brand',
    'A knife brand',
    'A cookware only brand',
    'A small toaster brand only',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Le Creuset known for? French enameled cast iron',
    'The French colorful cast iron',
    'A Japanese knife maker',
    'A German knife maker',
    'A Swiss cookware brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Lodge known for? American cast iron skillets',
    'The US cast iron skillet maker',
    'The French enameled cookware',
    'The German knives',
    'The Japanese pans',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Wusthof known for? German knives',
    'The Solingen German knives',
    'Japanese knives Shun',
    'US knives',
    'French knives Opinel',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Shun known for? Japanese Damascus knives',
    'The Japanese Damascus knife brand',
    'The German Wusthof knives',
    'The Swiss Victorinox knives',
    'The US Made In knives',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Victorinox known for? Swiss Army knives',
    'The original Swiss Army knife maker',
    'German kitchen knives',
    'French cookware',
    'US multitools Leatherman',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Leatherman known for? Multitools',
    'The Portland multitool inventor',
    'Swiss Army knives different',
    'Japanese scissors',
    'German flashlights',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Yeti known for? Premium coolers and tumblers',
    'The rugged cooler and tumbler brand',
    'A thermos brand historic',
    'A blender brand',
    'A knife brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Hydro Flask known for? Insulated water bottles',
    'The insulated bottle brand',
    'A cooler brand different',
    'A coffee maker',
    'A knife maker',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Stanley known for? The viral quencher tumbler heritage brand',
    'The classic tumbler heritage brand',
    'A thermos rival name only',
    'A yoga brand',
    'A bike brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Thermos known for? Vacuum insulated containers',
    'The vacuum flask brand name',
    'A cooler brand',
    'A bottle brand only stainless',
    'A kettle brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Weber known for? Grills',
    'The charcoal and gas grill maker',
    'A smoker only brand',
    'A fire pit brand',
    'A kitchen range brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Traeger known for? Wood pellet grills',
    'The pellet grill pioneer',
    'A charcoal grill brand',
    'A gas grill brand',
    'An electric smoker brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Big Green Egg known for? Kamado ceramic grills',
    'The ceramic kamado grill',
    'A pellet grill pioneer',
    'A gas grill maker',
    'A charcoal kettle maker',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Instant Pot known for? Electric pressure cookers',
    'The multicooker pressure brand',
    'An air fryer brand only',
    'A blender brand',
    'A toaster brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Ninja Kitchen known for? Blenders and air fryers',
    'The SharkNinja kitchen brand',
    'A pressure cooker brand original',
    'A mixer brand',
    'A kettle brand',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is SharkNinja? The appliance maker split from Shark vacuum',
    'The vacuums and appliances company',
    'A cookware maker',
    'A furniture maker',
    'An electronics giant',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Dyson known for? Bagless vacuums and air devices',
    'The cyclonic vacuum innovator',
    'A mop brand',
    'A grill brand',
    'A mixer brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Miele known for? Premium German appliances',
    'The German premium appliance maker',
    'The Swedish furniture maker',
    'The Korean electronics maker',
    'The Japanese camera maker',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Bosch known for? Appliances and auto parts',
    'The German engineering conglomerate',
    'The Swedish appliance maker',
    'The US tractor maker',
    'The Italian coffee maker',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Whirlpool known for? Home appliances',
    'The major US appliance maker',
    'The Korean appliance maker',
    'The German appliance maker',
    'The Japanese appliance maker',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is LG known for? Korean appliances and electronics',
    'The Korean appliance electronics brand',
    'The Japanese electronics brand',
    'The Chinese phone brand',
    'The US appliance brand',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Haier known for? Chinese appliances and GE Appliances owner',
    'The Chinese maker owning GE Appliances',
    'The Korean maker owning LG',
    'The Japanese maker owning Sony',
    'The US maker owning Whirlpool',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Sony known for? PlayStation and electronics',
    'The PlayStation entertainment group',
    'The Xbox company Microsoft',
    'The Switch maker Nintendo',
    'The PC maker Lenovo',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Lenovo known for? ThinkPad PCs',
    'The Chinese PC maker of ThinkPad',
    'The Japanese PC maker',
    'The Korean PC maker',
    'The US PC maker Dell',
    'easy',
    'Companies & Founders',
  ],
  [
    'What is Dell known for? Direct-sale PCs',
    'The direct-order PC pioneer',
    'The Chinese PC maker',
    'The Japanese PC maker',
    'The Korean chip maker',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is ASML known for? EUV lithography machines',
    'The chipmaking machine monopoly',
    'A chip designer',
    'A chip fabricator TSMC different',
    'A memory maker different',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is TSMC known for? Contract chip manufacturing',
    'The Taiwan chip foundry leader',
    'A US memory chip maker',
    'A Korean memory maker Samsung',
    'A Dutch equipment maker ASML',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Samsung Electronics known for? Memory chips and phones',
    'Memory chips and smartphones',
    'Only TVs',
    'Only appliances',
    'Only cars',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is SK Hynix known for? Memory chips',
    'The Korean memory chip maker',
    'The Dutch equipment maker',
    'The US GPU maker',
    'The Japanese sensor maker',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Micron known for? US memory chips',
    'The American memory chip maker',
    'The Korean memory maker',
    'The Taiwan foundry',
    'The Dutch lithography',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Qualcomm known for? Mobile chips and 5G modems',
    'The smartphone chip designer',
    'The PC CPU maker Intel',
    'The GPU maker Nvidia',
    'The memory maker Micron',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Broadcom known for? Semiconductor and software deals',
    'The chip and software acquirer',
    'A GPU gaming maker',
    'A memory maker',
    'A foundry operator',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Texas Instruments known for? Analog chips and calculators',
    'Analog chips and calculators',
    'GPUs',
    'Phones',
    'Cloud services',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is Analog Devices known for? Signal processing chips',
    'The analog signal chip maker',
    'The digital ads platform',
    'The phone maker',
    'The software giant',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is ARM the company known for? Chip architecture licensing',
    'Licensing chip designs globally',
    'Selling phones',
    'Making memory',
    'Making displays',
    'medium',
    'Companies & Founders',
  ],
  [
    'What is GlobalFoundries? A contract chip foundry',
    'The US-headquartered foundry',
    'A chip designer ARM rival',
    'A memory maker',
    'An equipment maker',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Intel Foundry? Intels contract manufacturing push',
    'Intels foundry services unit',
    'The memory division',
    'The graphics only division',
    'The software division',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is Cree now Wolfspeed known for? Silicon carbide chips',
    'The silicon carbide power chip maker',
    'A memory chip maker',
    'A phone maker',
    'A display maker',
    'expert',
    'Companies & Founders',
  ],
  [
    'What is Onsemi known for? Power and sensing chips',
    'The power semiconductor maker',
    'A memory maker',
    'A foundry',
    'A software firm',
    'expert',
    'Companies & Founders',
  ],
  [
    'What is Infineon known for? German power semiconductors',
    'The German power chip maker',
    'The Dutch lithography maker',
    'The Korean memory maker',
    'The US GPU maker',
    'hard',
    'Companies & Founders',
  ],
  [
    'What is STMicroelectronics? A French-Italian chip maker',
    'The European chip alliance company',
    'The Spanish chip maker',
    'The German auto chip maker',
    'The UK chip designer',
    'hard',
    'Companies & Founders',
  ],
];

module.exports = { rows };
