'use strict';

// Tables for Business: [entity, fact, extra-fact]
const AIRLINES = [
  ['Delta Air Lines', 'the United States', 'Atlanta hub'],
  ['American Airlines', 'the United States', 'Dallas Fort Worth hub'],
  ['United Airlines', 'the United States', 'Chicago Oare hub'],
  ['Southwest Airlines', 'the United States', 'Dallas Love Field base'],
  ['Lufthansa', 'Germany', 'Frankfurt hub'],
  ['Air France', 'France', 'Paris Charles de Gaulle hub'],
  ['KLM', 'the Netherlands', 'Amsterdam Schiphol hub'],
  ['British Airways', 'the United Kingdom', 'London Heathrow hub'],
  ['Iberia', 'Spain', 'Madrid hub'],
  ['Emirates', 'the UAE', 'Dubai hub'],
  ['Qatar Airways', 'Qatar', 'Doha hub'],
  ['Etihad', 'the UAE', 'Abu Dhabi hub'],
  ['Singapore Airlines', 'Singapore', 'Changi hub'],
  ['Cathay Pacific', 'Hong Kong', 'Hong Kong hub'],
  ['ANA', 'Japan', 'Tokyo Haneda hub'],
  ['JAL', 'Japan', 'Tokyo hub'],
  ['Qantas', 'Australia', 'Sydney hub'],
  ['Air Canada', 'Canada', 'Toronto hub'],
  ['Turkish Airlines', 'Turkey', 'Istanbul hub'],
  ['Ethiopian Airlines', 'Ethiopia', 'Addis Ababa hub'],
  ['Kenya Airways', 'Kenya', 'Nairobi hub'],
  ['LATAM', 'Chile Brazil roots', 'Santiago hub'],
  ['Avianca', 'Colombia', 'Bogota hub'],
  ['Aeromexico', 'Mexico', 'Mexico City hub'],
  ['Ryanair', 'Ireland', 'Dublin base'],
];

const HOTELS = [
  ['Marriott', 'the United States', 'Bonvoy loyalty program'],
  ['Hilton', 'the United States', 'Honors loyalty program'],
  ['Hyatt', 'the United States', 'World of Hyatt program'],
  ['InterContinental Group IHG', 'the United Kingdom', 'Holiday Inn owner'],
  ['Accor', 'France', 'Ibis and Sofitel owner'],
  ['Four Seasons', 'Canada', 'luxury hotels brand'],
  ['Ritz-Carlton', 'the United States owned by Marriott', 'luxury legacy brand'],
  ['Shangri-La', 'Hong Kong', 'Asian luxury hotels'],
  ['Mandarin Oriental', 'Hong Kong roots', 'luxury hotels'],
  ['Aman', 'the Philippines founded ultra-luxury', 'resort exclusivity'],
  ['W Hotels', 'the United States Marriott lifestyle', 'trendy design hotels'],
  ['Westin', 'the United States Marriott', 'wellness hotels'],
  ['Sheraton', 'the United States Marriott', 'classic full-service hotels'],
  ['Holiday Inn', 'the United Kingdom IHG', 'family hotels'],
  ['Best Western', 'the United States', 'independent franchise hotels'],
  ['Choice Hotels', 'the United States', 'Comfort Inn owner'],
  ['Wyndham', 'the United States', 'economy hotel franchising'],
  ['Radisson', 'the United States choice lineage mixed', 'international hotels'],
  ['Kempinski', 'Germany', 'European luxury hotels'],
  ['Rosewood', 'Hong Kong owner', 'ultra-luxury hotels'],
  ['Belmond', 'owned by LVMH', 'luxury trains and hotels'],
  ['Orient Express', 'Accor brand', 'historic luxury trains'],
  ['Club Med', 'France', 'all-inclusive resorts'],
  ['Sandals', 'Jamaica', 'couples all-inclusive resorts'],
  ['Atlantis Paradise Island', 'the Bahamas', 'iconic resort casino'],
];

const BANKS = [
  ['JPMorgan Chase', 'the United States', 'largest US bank by assets'],
  ['Bank of America', 'the United States', 'second largest US bank'],
  ['Citigroup', 'the United States', 'global banking giant'],
  ['Wells Fargo', 'the United States', 'West Coast banking giant'],
  ['Goldman Sachs', 'the United States', 'investment banking elite'],
  ['Morgan Stanley', 'the United States', 'investment banking elite'],
  ['HSBC', 'the United Kingdom', 'largest European bank'],
  ['Barclays', 'the United Kingdom', 'British universal bank'],
  ['Lloyds', 'the United Kingdom', 'British retail banking'],
  ['NatWest', 'the United Kingdom', 'British retail bank'],
  ['BNP Paribas', 'France', 'largest French bank'],
  ['Societe Generale', 'France', 'French universal bank'],
  ['Credit Agricole', 'France', 'French cooperative banking'],
  ['Deutsche Bank', 'Germany', 'largest German bank'],
  ['Commerzbank', 'Germany', 'German commercial bank'],
  ['UBS', 'Switzerland', 'Credit Suisse rescuer merger'],
  ['Credit Suisse', 'Switzerland history', 'collapsed and merged into UBS 2023'],
  ['ICBC', 'China', 'the worlds largest bank by assets'],
  ['China Construction Bank', 'China', 'top Chinese state bank'],
  ['Bank of China', 'China', 'major Chinese state bank'],
  ['Agricultural Bank of China', 'China', 'rural-focused Chinese giant'],
  ['MUFG', 'Japan', 'largest Japanese bank group'],
  ['SMBC', 'Japan', 'major Japanese banking group'],
  ['Mizuho', 'Japan', 'major Japanese bank'],
  ['Standard Chartered', 'the United Kingdom', 'Asia-Africa focused bank'],
];

// [question, correct, d1, d2, d3, level, chapter]
const DEALS_FACTS = [
  [
    'What was the AOL Time Warner merger known as? A famously failed mega-merger',
    'A disastrous 2000 media merger',
    'A streaming success story',
    'A telecom deal',
    'A rail merger',
    'medium',
    'Famous Deals',
  ],
  [
    'What was Vodafone Mannesmann? A hostile takeover in Germany',
    'The first major hostile cross-border German takeover',
    'A friendly French merger',
    'A telecom bankruptcy',
    'An insurance deal',
    'expert',
    'Famous Deals',
  ],
  [
    'What was RJR Nabisco known for? A landmark leveraged buyout',
    'The Barbarians at the Gate LBO',
    'An IPO milestone',
    'A stock split event',
    'A dot com boom story',
    'hard',
    'Famous Deals',
  ],
  [
    'Which book chronicled the RJR Nabisco buyout? Barbarians at the Gate',
    'Barbarians at the Gate',
    'Liar Poker trader memoir',
    'The Intelligent Investor classic',
    'Barbarians to Angels different',
    'hard',
    'Famous Deals',
  ],
  [
    'Who wrote Liar Poker about Salomon Brothers? Michael Lewis',
    'Michael Lewis',
    'Greg Smith different Goldman exit',
    'Roger Lowenstein LTCM book',
    'Andrew Ross Sorkin crisis book',
    'medium',
    'Famous Deals',
  ],
  [
    'Which book covered the 2008 crisis inside Treasury? Too Big to Fail by Sorkin',
    'Too Big to Fail by Andrew Ross Sorkin',
    'The Big Short by Michael Lewis',
    'House of Cards by William Cohan',
    'All the Devils Are Here different coauthors',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which book told the Big Short story of shorts? The Big Short by Michael Lewis',
    'The Big Short by Michael Lewis',
    'Too Big to Fail by Sorkin',
    'When Genius Failed LTCM story',
    'Den of Thieves 80s insider trading',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which book told the LTCM collapse? When Genius Failed by Roger Lowenstein',
    'When Genius Failed',
    'The Asylum different Leigh journal',
    'Fortunes Formula Kelly strategy',
    'The Predators Ball junk bonds',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which book exposed 1980s insider trading? Den of Thieves by James Stewart',
    'Den of Thieves',
    'Barbarians at the Gate LBO',
    'The Predators Ball same era different angle',
    'Liar Poker Salomon era',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who was Ivan Boesky? An 1980s arbitrageur convicted of insider trading',
    'The arbitrageur behind the greed speech era',
    'Michael Milken junk bond king convicted',
    'Dennis Levine banker convicted',
    'Carl Icahn raider not convicted',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who was Michael Milken? The junk bond king who served prison time',
    'The Drexel high-yield pioneer convicted',
    'Ivan Boesky arbitrageur',
    'Carl Icahn activist raider',
    'T Boone Pickens oil raider',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who was the junk bond firm Drexel Burnham Lambert? The 1980s high-yield powerhouse that collapsed',
    'The firm that collapsed after scandal',
    'Salomon Brothers Treasury desk giant',
    'Goldman Sachs IPO era firm',
    'Bear Stearns mortgage collapse firm',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which 2008 bank did JPMorgan buy for cheap? Bear Stearns then Washington Mutual',
    'Bear Stearns and Washington Mutual',
    'Lehman Brothers which failed outright',
    'Merrill Lynch bought by BofA',
    'Wachovia bought by Wells Fargo',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which 2008 bank bought Merrill Lynch? Bank of America',
    'Bank of America bought Merrill',
    'JPMorgan bought Bear',
    'Wells Fargo bought Wachovia',
    'Deutsche bought parts others',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which 2008 bank failed outright with no rescue? Lehman Brothers',
    'Lehman Brothers went bankrupt',
    'Bear Stearns rescued via JPMorgan',
    'Merrill sold to BofA',
    'AIG got a government bailout',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which insurer was bailed out in 2008? AIG',
    'AIG the insurance giant',
    'MetLife different insurer',
    'Prudential different insurer',
    'Allstate different insurer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which automakers were bailed out in 2008-09? GM and Chrysler',
    'General Motors and Chrysler',
    'Ford which did not take bailout funds',
    'Toyota foreign not eligible',
    'Tesla not yet public relevant',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which US automaker refused bailout funds in 2008? Ford',
    'Ford mortgaged everything earlier instead',
    'GM took government funds',
    'Chrysler took government funds',
    'Tesla too small then',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What was TARP? The bank bailout program of 2008',
    'The Troubled Asset Relief Program',
    'A trade pact acronym',
    'A stimulus check program',
    'A mortgage agency',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What was the Dodd-Frank Act? The 2010 financial reform law',
    'The post-crisis financial regulation',
    'A tax reform law',
    'A healthcare law different ACA',
    'A trade law',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What was Sarbanes-Oxley? The 2002 accounting reform law',
    'The post-Enron corporate reform law',
    'The banking bailout law different TARP',
    'The healthcare law different',
    'The securities act of 1933 different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which energy companys collapse created SOX momentum? Enron',
    'Enrons accounting fraud collapse',
    'WorldCom separate fraud same era',
    'Tyco separate scandal era',
    'Lehman later 2008 different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which telecom collapsed in a 2002 accounting fraud? WorldCom',
    'WorldComs capitalized expenses fraud',
    'Enron energy trading fraud different',
    'Global Crossing telecom different fraud',
    'Adelphia family fraud different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who was the Enron CEO era figure convicted? Jeffrey Skilling',
    'Jeffrey Skilling the CEO convicted',
    'Kenneth Lay chairman convicted too',
    'Andrew Fastow CFO convicted',
    'Rebecca Mark executive departed earlier',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who was the Enron CFO convicted? Andrew Fastow',
    'Andrew Fastow the structured finance CFO',
    'Jeffrey Skilling CEO convicted',
    'Kenneth Lay chairman convicted',
    'Cliff Baxter executive tragic',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who blew the whistle at Enron? Sherron Watkins',
    'Sherron Watkins the VP who warned',
    'Cynthia Cooper WorldCom whistleblower different',
    'Coleen Rowley FBI whistleblower different',
    'Anton Valukas examiner different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who was the WorldCom whistleblower? Cynthia Cooper',
    'Cynthia Cooper the internal auditor',
    'Sherron Watkins Enron different',
    'Coleen Rowley FBI different',
    'Harry Markopolos Madoff different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who flagged the Madoff scheme repeatedly? Harry Markopolos',
    'Harry Markopolos the SEC-warning quant',
    'Cynthia Cooper WorldCom auditor',
    'Sherron Watkins Enron VP',
    'Eileen Foster Countrywide whistleblower',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who ran the largest Ponzi scheme in history? Bernie Madoff',
    'Bernie Madoff convicted 2009',
    'Allen Stanford separate Ponzi',
    'R Allen same Stanford different spelling',
    'Tom Petters Minnesota Ponzi different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'How large was Madoffs fraud estimated? About 65 billion dollars',
    'Roughly 65 billion in statement losses',
    'About 8 billion Stanford scheme',
    'About 3.5 billion Petters scheme',
    'About 1 billion minor schemes',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who was the Wolf of Wall Street based on? Jordan Belfort',
    'Jordan Belfort the penny stock fraudster',
    'Bernie Madoff different fraudster',
    'Boesky 80s arb different',
    'Belfort partner Danny Porush different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who directed The Wolf of Wall Street? Martin Scorsese',
    'Martin Scorsese',
    'Adam McKay Big Short director',
    'Judd Apatow comedy producer',
    'David O Russell different films',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which movie dramatized the 2008 housing shorts? The Big Short',
    'The Big Short 2015 film',
    'Margin Call 2011 night of crisis',
    '99 Homes foreclosure drama',
    'Arbitrage thriller different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which movie dramatized one banks crisis night? Margin Call',
    'Margin Call the 2011 drama',
    'The Big Short broader story',
    'Wall Street 1987 original',
    'Equity female-led trading drama',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which 1987 film defined Wall Street greed? Wall Street with Gordon Gekko',
    'Wall Street with Michael Douglas Gekko',
    'Trading Places comedy different',
    'Wall Street sequel Money Never Sleeps later',
    'Boiler Room pump dump film',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Gordon Gekko? Michael Douglas',
    'Michael Douglas won an Oscar for it',
    'Charlie Sheen Bud Fox young broker',
    'Martin Sheen his father Carl fox',
    'Daryl Hannah Darien role',
    'easy',
    'Celebrity Facts',
  ],
  [
    'What was Gekkos famous creed? Greed is good speech',
    'The greed is healthy speech',
    'Lunch is for wimps different trader film',
    'Sell sell sell line',
    'Blue Horseshoe loves Anacott steel line',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which film had lunch is for wimps? Wall Street 1987 via lineage actually Trading Places line by Mortimer? Ambiguous',
    'The line is from Wall Street sayings lore',
    'Glengarry sales film different rant',
    'Boiler Room brokerage film different',
    'Margin Call different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which play/film shouted coffee is for closers? Glengarry Glen Ross',
    'Glengarry Glen Ross by David Mamet',
    'Wall Street different',
    'Boiler Room inspired by it',
    'Margin Call different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who wrote Glengarry Glen Ross? David Mamet',
    'David Mamet playwright',
    'Aaron Sorkin different writer',
    'Arthur Miller classic writer',
    'Neil Simon comedy writer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which printer scene is famous in Office Space? Destroying the printer gangster style',
    'The fax machine beatdown scene',
    'TPS report covers memo',
    'Stapler red Swingline obsession',
    'Cube neighbor noise complaints',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What was red Swingline stapler famous from? Office Space Milton obsession',
    'The stapler Milton wanted back',
    'The printer beaten down',
    'The TPS reports',
    'The Friday casual day',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What report did Office Space obsess over? TPS reports with covers',
    'The TPS reports covers memo',
    'The Synergy decks',
    'The Q3 projections',
    'Theexpense reports spelling',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which show featured Hooli? Silicon Valley satirized tech',
    'Silicon Valley HBO with Hooli',
    'The Social Network Facebook film',
    'Super pumped Uber saga',
    'WeCrashed WeWork saga',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which show dramatized WeWork? WeCrashed with Jared Leto',
    'WeCrashed the WeWork rise fall',
    'Super Pumped the Uber saga',
    'The Dropout Theranos saga',
    'Inventing Anna fake heiress story',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which show dramatized Theranos? The Dropout with Amanda Seyfried',
    'The Dropout Elizabeth Holmes story',
    'WeCrashed WeWork story',
    'Super Pumped Kalanick story',
    'Inventing Anna Delvey story',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Theranos? Elizabeth Holmes',
    'Elizabeth Holmes convicted of fraud',
    'Sunny Balwani president convicted too',
    'Carly Fiorina HP different',
    'Ginni Rometty IBM different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who founded WeWork? Adam Neumann',
    'Adam Neumann the we co-founder',
    'Miguel McKelvey cofounder architect',
    'Masayoshi Son SoftBank mega-backer',
    'Steve Hilton unrelated name',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which SoftBank founder backed WeWork heavily? Masayoshi Son',
    'Masayoshi Son the Vision Fund backer',
    'Jack Ma Alibaba partner friend',
    'Yuri Milner DST backer',
    'Peter Thiel Founders Fund backer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which show dramatized Uber founder era? Super Pumped',
    'Super Pumped The Battle for Uber',
    'WeCrashed WeWork show',
    'The Dropout Theranos show',
    'Halt and Catch Fire PCs era show',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Uber? Travis Kalanick and Garrett Camp',
    'Kalanick and Camp founded Uber',
    'Dara Khosrowshahi later CEO',
    'Logan Green Lyft cofounder',
    'John Zimmer Lyft cofounder',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Lyft? Logan Green and John Zimmer',
    'Green and Zimmer founded Lyft',
    'Kalanick and Camp Uber founders',
    'Bhavish Ola Indian counterparts',
    'Marc Andreessen investor unrelated',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Airbnb? Brian Chesky, Joe Gebbia, and Nathan Blecharczyk',
    'The three Airbnb cofounders',
    'The two Uber founders',
    'The two Snapchat founders',
    'The three Stripe founders',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Stripe? Patrick and John Collison brothers',
    'The Collison brothers founded Stripe',
    'The Airbnb trio founders',
    'The Waxman brothers food founders',
    'The Bloomberg single founder',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Shopify? Tobias Lutke and Scott Lake',
    'Tobias Lutke the snowboard shop coder',
    'Jack Dorsey Square cofounder',
    'Ben Chestnut Mailchimp cofounder',
    'Stewart Butterfield Slack cofounder',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Mailchimp? Ben Chestnut and Dan Kurzius',
    'The Mailchimp duo from Atlanta',
    'The Shopify duo from Ottawa',
    'The Basecamp duo from Chicago',
    'The Hubspot trio from Boston',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who founded Slack origin company? Stewart Butterfield of Tiny Speck',
    'Stewart Butterfield who pivoted from Glitch',
    'Drew Houston Dropbox single founder',
    'Aaron Levie Box young founder',
    'Dharmesh HubSpot cofounder',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who founded Dropbox? Drew Houston and Arash Ferdowsi',
    'Drew Houston founded Dropbox',
    'Aaron Levie founded Box',
    'Stewart Butterfield founded Slack',
    'Dharmesh founded HubSpot',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Box? Aaron Levie and Dylan Smith',
    'Aaron Levie the Box cofounder',
    'Drew Houston Dropbox cofounder',
    'Stewart Butterfield Slack cofounder',
    'Palantir cofounder Thiel backed',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Palantir? Peter Thiel and Alex Karp and others',
    'Thiel and Karp cofounded Palantir',
    'Reid Hoffman LinkedIn cofounder',
    'Marc Andreessen Netscape cofounder',
    'Jensen Huang Nvidia cofounder',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded LinkedIn? Reid Hoffman',
    'Reid Hoffman the LinkedIn cofounder',
    'Jeff Weiner later CEO executive',
    'Marc Andreessen board investor',
    'Satya Nadella integration era CEO',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Netscape? Marc Andreessen and Jim Clark',
    'Andreessen and Clark founded Netscape',
    'Gates and Allen founded Microsoft',
    'Jobs and Wozniak founded Apple',
    'Page and Brin founded Google',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded AOL historic? case steve case',
    'Steve Case built America Online',
    'Ted Leonsis AOL executive later',
    'Barry Diller era executive later',
    'David Bohnett GeoCities founder different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who founded GeoCities? David Bohnett',
    'David Bohnett created GeoCities',
    'Steve Case created AOL',
    'Pierre Omidyar created eBay',
    'Jerry Yang created Yahoo',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who founded eBay? Pierre Omidyar',
    'Pierre Omidyar created AuctionWeb eBay',
    'Jeff Skoll first president eBay',
    'Meg Whitman later eBay CEO',
    'Jerry Yang Yahoo cofounder',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who cofounded Yahoo? Jerry Yang and David Filo',
    'Jerry Yang and David Filo',
    'Marissa Mayer later Yahoo CEO',
    'Carol Bartz earlier Yahoo CEO',
    'Terry Semel earlier Yahoo CEO',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who was the Marissa Mayer Yahoo era? A former Google exec CEO 2012-2017',
    'The ex-Google executive who led Yahoo',
    'The first Yahoo CEO Tim Koogle',
    'The media era CEO Terry Semel',
    'The Verizon sale era boss',
    'hard',
    'Celebrity Facts',
  ],
];

module.exports = { AIRLINES, HOTELS, BANKS, rows: DEALS_FACTS };
