'use strict';

const { distractors } = require('../lib');
const topup = require('./business-topup');
const topup2 = require('./business-topup2');
const topup3 = require('./business-topup3');
const topup4 = require('./business-topup4');

// [company, founder, industry, HQ]
const COMPANIES = [
  ['Ford', 'Henry Ford', 'automobiles', 'Dearborn, Michigan'],
  ['General Motors', 'William Durant', 'automobiles', 'Detroit, Michigan'],
  ['Tesla', 'Elon Musk leadership', 'electric vehicles', 'Austin, Texas'],
  ['Toyota', 'Kiichiro Toyoda', 'automobiles', 'Toyota City, Japan'],
  ['Volkswagen', 'the German government 1937', 'automobiles', 'Wolfsburg, Germany'],
  ['Boeing', 'William Boeing', 'aerospace', 'Chicago then Arlington'],
  ['Airbus', 'a European consortium', 'aerospace', 'Toulouse, France'],
  ['FedEx', 'Fred Smith', 'logistics', 'Memphis, Tennessee'],
  ['UPS', 'James Casey', 'logistics', 'Atlanta, Georgia'],
  ['DHL', 'Adrian Dalsey, Larry Hillblom, Robert Lynn', 'logistics', 'Bonn, Germany'],
  ['Maersk', 'the Maersk family', 'shipping', 'Copenhagen, Denmark'],
  ['Walmart', 'Sam Walton', 'retail', 'Bentonville, Arkansas'],
  ['Target', 'George Dayton', 'retail', 'Minneapolis, Minnesota'],
  ['Costco', 'James Sinegal and Jeffrey Brotman', 'warehouse retail', 'Issaquah, Washington'],
  ['Kroger', 'Bernard Kroger', 'grocery retail', 'Cincinnati, Ohio'],
  ['Aldi', 'the Albrecht brothers', 'discount grocery', 'Essen, Germany'],
  ['Lidl', 'the Schwarz group', 'discount grocery', 'Neckarsulm, Germany'],
  ['IKEA', 'Ingvar Kamprad', 'furniture retail', 'Delft, Netherlands HQ'],
  ['Home Depot', 'Bernie Marcus and Arthur Blank', 'home improvement', 'Atlanta, Georgia'],
  ["Lowe's", 'L. S. Lowe', 'home improvement', 'Mooresville, North Carolina'],
  ['Best Buy', 'Richard Schulze', 'electronics retail', 'Richfield, Minnesota'],
  ['Nike', 'Phil Knight and Bill Bowerman', 'apparel and footwear', 'Beaverton, Oregon'],
  ['Adidas', 'Adi Dassler', 'apparel and footwear', 'Herzogenaurach, Germany'],
  ['Zara', 'Amancio Ortega', 'fast fashion', 'Arteixo, Spain'],
  ['H&M', 'Erling Persson', 'fast fashion', 'Stockholm, Sweden'],
  ['Uniqlo', 'Tadashi Yanai', 'fast fashion', 'Tokyo, Japan'],
  ['LVMH', 'merger led by Bernard Arnault', 'luxury goods', 'Paris, France'],
  ['Kering', 'Francois Pinault', 'luxury goods', 'Paris, France'],
  ['Estee Lauder', 'Estee Lauder and Joseph Lauder', 'beauty', 'New York City'],
  ['L Oreal', 'Eugene Schueller', 'beauty', 'Paris, France'],
  ['Pfizer', 'Charles Pfizer and Charles Erhart', 'pharmaceuticals', 'New York City'],
  ['Johnson and Johnson', 'the Johnson brothers', 'pharmaceuticals', 'New Brunswick, New Jersey'],
  ['Moderna', 'Noubar Afeyan and Derrick Rossi and others', 'biotech', 'Cambridge, Massachusetts'],
  ['BioNTech', 'Ugur Sahin and Ozlem Tureci', 'biotech', 'Mainz, Germany'],
  ['Novartis', 'a merger of Ciba-Geigy and Sandoz', 'pharmaceuticals', 'Basel, Switzerland'],
  ['Roche', 'Fritz Hoffmann-La Roche', 'pharmaceuticals', 'Basel, Switzerland'],
  ['Bayer', 'Friedrich Bayer', 'pharma and chemicals', 'Leverkusen, Germany'],
  [
    'ExxonMobil',
    'John D. Rockefeller lineage Standard Oil',
    'oil and gas',
    'Irving then Spring, Texas',
  ],
  ['Shell', 'Marcus Samuel and Royal Dutch', 'oil and gas', 'London, United Kingdom'],
  ['BP', 'William Knox DArcy heritage', 'oil and gas', 'London, United Kingdom'],
  ['Chevron', 'Standard Oil California heritage', 'oil and gas', 'San Ramon, California'],
  ['Aramco', 'the Saudi government charter', 'oil and gas', 'Dhahran, Saudi Arabia'],
  [
    'Saudi Aramco value',
    'the worlds most valuable oil company',
    'oil and gas',
    'Dhahran, Saudi Arabia',
  ],
  ['Vitol', 'Ian Taylor leadership era', 'commodity trading', 'Geneva, Rotterdam roots'],
  ['Glencore', 'Marc Rich founder then renamed', 'commodity trading', 'Baar, Switzerland'],
  ['Cargill', 'William W. Cargill', 'agribusiness', 'Minneapolis, Minnesota'],
  ['Louis Dreyfus', 'Leopold Louis-Dreyfus', 'agribusiness', 'Rotterdam, Netherlands'],
  ['Archer Daniels Midland', 'John W. Daniels', 'agribusiness', 'Chicago, Illinois'],
  ['Bunge', 'Johann Peter Gottlieb Bunge', 'agribusiness', 'Chesterfield, Missouri'],
  ['Mastercard', 'a banker consortium Interbank', 'payments', 'Purchase, New York'],
  ['Visa', 'Dee Hock led BankAmericard', 'payments', 'Foster City, California'],
  ['American Express', 'a freight merger Wells Fargo era', 'payments', 'New York City'],
  ['PayPal', 'Max Levchin, Peter Thiel, and Luke Nosek', 'payments', 'San Jose, California'],
  ['Stripe', 'Patrick and John Collison', 'payments', 'South San Francisco'],
  ['Adyen', 'Pieter van der Does and Arnout Schuijff', 'payments', 'Amsterdam, Netherlands'],
  ['Ant Group', 'Jack Ma ecosystem', 'fintech', 'Hangzhou, China'],
  ['Klarna', 'Sebastian Siemiatkowski and others', 'fintech BNPL', 'Stockholm, Sweden'],
  ['Revolut', 'Nik Storonsky and Vlad Yatsenko', 'fintech', 'London, United Kingdom'],
  ['Nubank', 'David Velez and others', 'fintech', 'Sao Paulo, Brazil'],
];

// [term, definition]
const ECON_TERMS = [
  ['supply and demand', 'The model of price determination in a market'],
  ['inflation', 'A general rise in prices over time'],
  ['deflation', 'A general fall in prices over time'],
  ['stagflation', 'Stagnant growth with high inflation'],
  ['recession', 'A significant decline in economic activity'],
  ['depression', 'A severe prolonged recession'],
  ['GDP', 'The total value of goods and services produced'],
  ['GNP', 'GDP plus net income from abroad'],
  ['unemployment rate', 'The share of the labor force without work'],
  ['labor force participation', 'The share of people working or seeking work'],
  ['monetary policy', 'Central bank control of money and rates'],
  ['fiscal policy', 'Government spending and taxation policy'],
  ['quantitative easing', 'Central bank buying of assets to add liquidity'],
  ['interest rate', 'The cost of borrowing money'],
  ['compound interest', 'Interest earned on interest over time'],
  ['opportunity cost', 'The value of the next best alternative'],
  ['sunk cost', 'A cost already incurred that cannot be recovered'],
  ['economies of scale', 'Falling per-unit costs as output grows'],
  ['diseconomies of scale', 'Rising per-unit costs as output grows too large'],
  ['monopoly', 'A single seller dominating a market'],
  ['oligopoly', 'A few firms dominating a market'],
  ['perfect competition', 'A market with many sellers and identical products'],
  ['elasticity', 'How demand responds to price changes'],
  ['substitute goods', 'Products that replace each other'],
  ['complementary goods', 'Products used together'],
  ['invisible hand', 'Adam Smiths idea of market self-regulation'],
  ['comparative advantage', 'Producing goods at lower opportunity cost'],
  ['absolute advantage', 'Producing more output with the same inputs'],
  ['trade deficit', 'Importing more than exporting'],
  ['trade surplus', 'Exporting more than importing'],
  ['tariff', 'A tax on imports'],
  ['subsidy', 'Government support lowering producer costs'],
  ['quota', 'A limit on import quantities'],
  ['exchange rate', 'The price of one currency in another'],
  ['purchasing power parity', 'Exchange rates equalizing price levels'],
  ['hyperinflation', 'Extremely rapid price increases'],
  ['consumer price index', 'A basket-based measure of consumer inflation'],
  ['producer price index', 'A measure of wholesale price changes'],
  ['business cycle', 'The pattern of expansion and contraction'],
  ['demand-pull inflation', 'Inflation caused by excess demand'],
  ['cost-push inflation', 'Inflation caused by rising input costs'],
  ['Gini coefficient', 'A measure of income inequality'],
  ['utility', 'The satisfaction from consuming goods'],
  ['marginal utility', 'The extra satisfaction from one more unit'],
  ['diminishing returns', 'Smaller output gains from added inputs'],
  ['public good', 'A good that is non-excludable and non-rival'],
  ['externality', 'A cost or benefit affecting third parties'],
  ['moral hazard', 'Riskier behavior when protected from consequences'],
  ['adverse selection', 'Hidden information distorting transactions'],
  ['liquidity trap', 'When low rates fail to stimulate borrowing'],
];

// [term, definition]
const FINANCE = [
  ['stock', 'A share of ownership in a company'],
  ['bond', 'A loan to a company or government'],
  ['dividend', 'A distribution of company profits'],
  ['IPO', 'An initial public offering of stock'],
  ['market capitalization', 'Share price times shares outstanding'],
  ['P/E ratio', 'Price relative to earnings per share'],
  ['ETF', 'An exchange-traded fund basket'],
  ['index fund', 'A fund tracking a market index'],
  ['S&P 500', 'An index of 500 large US companies'],
  ['Dow Jones', 'An index of 30 major US companies'],
  ['Nasdaq', 'A tech-heavy US exchange and index'],
  ['bull market', 'A period of rising prices'],
  ['bear market', 'A period of falling prices'],
  ['volatility', 'The degree of price fluctuation'],
  ['diversification', 'Spreading investments to reduce risk'],
  ['asset allocation', 'How investments are divided among classes'],
  ['mutual fund', 'A pooled investment vehicle'],
  ['hedge fund', 'A lightly regulated pooled investment'],
  ['leverage', 'Using borrowed money to invest'],
  ['margin call', 'A demand for funds when collateral falls'],
  ['short selling', 'Betting on a price decline'],
  ['options', 'Contracts giving rights to buy or sell'],
  ['futures', 'Contracts to buy or sell at a set future price'],
  ['derivatives', 'Contracts deriving value from assets'],
  ['yield', 'The return on an investment'],
  ['coupon', 'The interest payment on a bond'],
  ['maturity', 'The date a bond repays principal'],
  ['credit rating', 'A grade of default risk'],
  ['junk bond', 'A high-yield high-risk bond'],
  ['Treasury bond', 'A US government long-term bond'],
  ['municipal bond', 'A bond issued by local governments'],
  ['liquidity', 'How easily assets convert to cash'],
  ['capital gain', 'Profit from selling an asset'],
  ['diversified portfolio', 'A mix of varied investments'],
  ['401k', 'A US employer retirement plan'],
  ['IRA', 'A US individual retirement account'],
  ['roth IRA', 'A retirement account with after-tax contributions'],
  ['compound annual growth rate', 'The smoothed yearly growth rate'],
  ['net present value', 'The value of future cash flows today'],
  ['internal rate of return', 'The discount rate making NPV zero'],
  ['arbitrage', 'Profiting from price differences across markets'],
  ['insider trading', 'Illegal trading on nonpublic information'],
  ['pump and dump', 'Inflating a price then selling out'],
  [' Ponzi scheme', 'A fraud paying old investors with new money'],
  ['crypto wallet', 'A tool storing digital asset keys'],
  ['blockchain', 'A distributed tamper-resistant ledger'],
  ['bitcoin', 'The first decentralized cryptocurrency'],
  ['ethereum', 'A blockchain supporting smart contracts'],
  ['stablecoin', 'A crypto pegged to a stable asset'],
  ['DeFi', 'Decentralized finance applications'],
];

// [leader, company]
const LEADERS = [
  ['Elon Musk', 'Tesla and SpaceX'],
  ['Tim Cook', 'Apple'],
  ['Satya Nadella', 'Microsoft'],
  ['Sundar Pichai', 'Google and Alphabet'],
  ['Jensen Huang', 'Nvidia'],
  ['Lisa Su', 'AMD'],
  ['Sam Altman', 'OpenAI'],
  ['Mark Zuckerberg', 'Meta'],
  ['Andy Jassy', 'Amazon'],
  ['Jeff Bezos', 'Amazon founder'],
  ['Reed Hastings', 'Netflix cofounder'],
  ['Brian Chesky', 'Airbnb'],
  ['Dara Khosrowshahi', 'Uber'],
  ['Tony Xu', 'DoorDash'],
  ['Max Levchin', 'Affirm'],
  ['Jack Dorsey', 'Twitter cofounder and Block'],
  ['Evan Spiegel', 'Snap'],
  ['Bobby Murphy', 'Snap cofounder'],
  ['Jensen, Su pairing', 'The GPU industry rivals'],
  ['Satya Nadella and Bill Gates', 'Microsoft CEO and founder'],
  ['Warren Buffett', 'Berkshire Hathaway'],
  ['Charlie Munger', 'Buffetts late partner'],
  ['Jamie Dimon', 'JPMorgan Chase'],
  ['Brian Moynihan', 'Bank of America'],
  ['David Solomon', 'Goldman Sachs'],
  ['Jane Fraser', 'Citigroup first woman CEO'],
  ['Adena Friedman', 'Nasdaq CEO'],
  ['Mary Barra', 'General Motors'],
  ['Ginni Rometty', 'former IBM CEO'],
  ['Safra Catz', 'Oracle CEO'],
  ['Sheryl Sandberg', 'former Meta COO'],
  ['Susan Wojcicki', 'former YouTube CEO'],
  ['Indra Nooyi', 'former PepsiCo CEO'],
  ['Mary Callahan Erdoes', 'JPMorgan wealth head'],
  ['Abigail Johnson', 'Fidelity CEO'],
  ['Christine Lagarde', 'European Central Bank president'],
  ['Jerome Powell', 'US Federal Reserve chair'],
  ['Janet Yellen', 'US Treasury Secretary'],
  ['Ben Bernanke', 'former Fed chair Nobel laureate'],
  ['Alan Greenspan', 'former longtime Fed chair'],
  ['Paul Volcker', 'former Fed chair who beat inflation'],
  ['Mario Draghi', 'former ECB president whatever it takes'],
  ['Tiff Macklem', 'Bank of Canada governor'],
  ['Andrew Bailey', 'Bank of England governor'],
  ['Ueda Kazuo', 'Bank of Japan governor'],
  ['Raghuram Rajan', 'former RBI governor economist'],
];

// [exchange, city]
const EXCHANGES = [
  ['the NYSE', 'New York'],
  ['the Nasdaq', 'New York'],
  ['the London Stock Exchange', 'London'],
  ['Euronext', 'Amsterdam headquarters'],
  ['Deutsche Boerse', 'Frankfurt'],
  ['Euronext Paris part', 'Paris'],
  ['the Tokyo Stock Exchange', 'Tokyo'],
  ['the Shanghai Stock Exchange', 'Shanghai'],
  ['the Shenzhen Stock Exchange', 'Shenzhen'],
  ['the Hong Kong Exchange', 'Hong Kong'],
  ['the Singapore Exchange', 'Singapore'],
  ['the ASX', 'Sydney'],
  ['the TSX', 'Toronto'],
  ['the B3', 'Sao Paulo'],
  ['the JSE', 'Johannesburg'],
];

// [brand, tagline]
const TAGLINES = [
  ['Nike', 'Just Do It'],
  ['Adidas', 'Impossible Is Nothing'],
  ['Apple', 'Think Different'],
  ['L Oreal', 'Because Youre Worth It'],
  ['McDonalds', 'Im Lovin It'],
  ['KFC', 'Finger Lickin Good'],
  ['Subway', 'Eat Fresh'],
  ['Red Bull', 'Gives You Wings'],
  ['Skittles', 'Taste the Rainbow'],
  ['M&Ms', 'Melts in Your Mouth Not in Your Hands'],
  ['Wheaties', 'Breakfast of Champions'],
  ['Milky Way', 'Chocolate Malt Milkshake in a Bar'],
  ['BMW', 'The Ultimate Driving Machine'],
  ['Audi', 'Vorsprung durch Technik'],
  ['Volkswagen', 'Das Auto era slogan'],
  ['Toyota', 'Lets Go Places'],
  ['Ford', 'Built Ford Tough trucks'],
  ['Chevrolet', 'Find New Roads'],
  ['Dodge', 'Never Neutral'],
  ['Rolex', 'A Crown for Every Achievement'],
  ['Tag Heuer', 'Dont Crack Under Pressure'],
  ['Maybelline', 'Maybe Shes Born With It'],
  ['Loreal confirmed', 'Because Youre Worth It again skip'],
  ['FedEx', 'When It Absolutely Positively Has to Be There Overnight'],
  ['UPS', 'What Can Brown Do for You'],
  ['DHL', 'Excellence Simply Delivered'],
  ['Mastercard', 'Priceless campaign'],
  ['Visa', 'Everywhere You Want to Be'],
  ['American Express', 'Dont Leave Home Without It'],
  ['Capital One', 'Whats in Your Wallet'],
  ['Burger King', 'Have It Your Way'],
  ['Wendys', 'Where is the Beef era famous'],
  ['Subway eat', 'Eat Fresh same'],
];

// [question, correct, d1, d2, d3, level, chapter]
const BUS_CONCEPTS = [
  [
    'What is a business model? How a company creates and captures value',
    'The plan for creating and capturing value',
    'A legal structure only',
    'An org chart',
    'A marketing campaign',
    'medium',
    'Business Concepts',
  ],
  [
    'What is B2B? Business selling to businesses',
    'Business-to-business sales',
    'Business to consumers',
    'Bank to business loans',
    'Brand to brand mergers',
    'easy',
    'Business Concepts',
  ],
  [
    'What is B2C? Business selling to consumers',
    'Business-to-consumer sales',
    'Bank to customer',
    'Broker to client',
    'Brand to company',
    'easy',
    'Business Concepts',
  ],
  [
    'What is D2C? Direct to consumer selling',
    'Direct-to-consumer channels',
    'Dropship to consumer',
    'Digital to commerce',
    'Demand to cash',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a franchise? Licensing a business format to operators',
    'A licensed business format model',
    'A joint venture',
    'A merger',
    'A leveraged buyout',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a joint venture? Two firms sharing a project entity',
    'A shared venture between companies',
    'A full merger',
    'A hostile takeover',
    'A franchise license',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an acquisition? Buying another company',
    'One company purchasing another',
    'Starting a company',
    'Selling a division only',
    'A stock split',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a merger? Two companies combining into one',
    'Two firms joining to form one',
    'An acquisition by a larger firm',
    'A spin-off split',
    'A bankruptcy sale',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a spin-off? Creating an independent company from part of one',
    'Separating a unit into a new stock',
    'Buying a competitor',
    'Merging two firms',
    'Laying off staff',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a hostile takeover? Acquiring against the boards wishes',
    'Buying control despite board opposition',
    'A friendly merger',
    'A golden parachute payout',
    'A poison pill defense',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a poison pill? A defense deterring takeovers',
    'A shareholder rights anti-takeover plan',
    'A hostile bid tactic',
    'A CEO contract',
    'A buyback program',
    'hard',
    'Business Concepts',
  ],
  [
    'What is a golden parachute? Generous exit pay for executives',
    'Large severance on a change of control',
    'A signing bonus',
    'A retirement 401k match',
    'An equity refresh',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a leveraged buyout? Buying a company with debt',
    'Acquiring a firm using borrowed funds',
    'Buying with cash only',
    'A stock swap deal',
    'A management spin-off',
    'medium',
    'Business Concepts',
  ],
  [
    'What is venture capital? Funding startups for equity',
    'Equity investment in young companies',
    'Bank lending to startups',
    'Government grants only',
    'Crowdfunding small gifts',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an angel investor? An early individual backer',
    'A wealthy early-stage individual investor',
    'A venture fund partner',
    'A bank lender',
    'A government agency',
    'medium',
    'Business Concepts',
  ],
  [
    'What is seed funding? The earliest institutional round',
    'The first funding stage after friends and family',
    'An IPO stage',
    'A buyout stage',
    'A debt refinancing',
    'medium',
    'Business Concepts',
  ],
  [
    'What is Series A? A first major venture round after seed',
    'The first big VC round',
    'The IPO round',
    'A mezzanine debt round',
    'An accelerator demo day',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an accelerator? A program with mentorship and demo day',
    'A startup program ending in a demo day',
    'A coworking space only',
    'A VC fund',
    'A startup conference',
    'medium',
    'Business Concepts',
  ],
  [
    'What is Y Combinator? A famous startup accelerator',
    'The well-known seed accelerator',
    'A venture capital fund only',
    'A tech conference',
    'A coding bootcamp',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a unicorn? A startup valued over one billion dollars',
    'A billion-dollar private startup',
    'A profitable public company',
    'A first-round fund',
    'A hundred-million revenue firm',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a decacorn? A startup valued over ten billion',
    'A company worth over ten billion',
    'A billion-dollar startup',
    'A trillion-dollar company',
    'A centaur revenue term',
    'medium',
    'Business Concepts',
  ],
  [
    'What is bootstrapping? Growing without outside investment',
    'Funding growth from revenue itself',
    'Raising venture rounds',
    'Taking bank loans',
    'Going public',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a burn rate? How fast a startup spends cash',
    'Monthly cash consumption pace',
    'Revenue growth speed',
    'Employee churn rate',
    'Server costs only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is runway? Months of cash remaining',
    'How long cash will last',
    'The runway at HQ',
    'A marketing timeline',
    'A stock vesting period',
    'medium',
    'Business Concepts',
  ],
  [
    'What is product-market fit? When demand matches the product',
    'A product satisfying a strong market need',
    'A marketing match',
    'A price match policy',
    'A distribution deal',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an MVP? A minimum viable product',
    'The smallest testable product version',
    'The final polished release',
    'A marketing video',
    'A pitch deck',
    'medium',
    'Business Concepts',
  ],
  [
    'What is pivoting? Changing strategy based on learnings',
    'Shifting the startup direction',
    'Raising more money',
    'Hiring faster',
    'Going global immediately',
    'medium',
    'Business Concepts',
  ],
  [
    'What is churn? Customers lost over a period',
    'The rate of customer attrition',
    'New customer growth',
    'Revenue per user',
    'Margins',
    'medium',
    'Business Concepts',
  ],
  [
    'What is LTV? Customer lifetime value',
    'The revenue a customer generates over time',
    'Labor turnover value',
    'Logistics total value',
    'Loan to value ratio real estate',
    'medium',
    'Business Concepts',
  ],
  [
    'What is CAC? Customer acquisition cost',
    'The cost to acquire a customer',
    'Compound annual cost',
    'Cost after commission',
    'Capital asset charge',
    'medium',
    'Business Concepts',
  ],
  [
    'What is ARR? Annual recurring revenue',
    'Yearly recurring subscription revenue',
    'Annual rate of return',
    'Average retail rate',
    'Asset recovery rate',
    'medium',
    'Business Concepts',
  ],
  [
    'What is MRR? Monthly recurring revenue',
    'Monthly subscription revenue',
    'Marginal rate of return',
    'Market risk rating',
    'Managed runway rate',
    'medium',
    'Business Concepts',
  ],
  [
    'What is GMV? Gross merchandise value',
    'Total sales value across a marketplace',
    'Gross margin value',
    'Global market value',
    'Growth metric variance',
    'hard',
    'Business Concepts',
  ],
  [
    'What is take rate? The platform fee percentage',
    'The commission a platform keeps',
    'Tax retained by government',
    'Consumer discount rate',
    'Supplier rebate',
    'hard',
    'Business Concepts',
  ],
  [
    'What is gross margin? Revenue minus cost of goods sold',
    'Profit after direct costs',
    'Revenue after all expenses',
    'Operating cash flow',
    'Net income',
    'medium',
    'Business Concepts',
  ],
  [
    'What is EBITDA? Earnings before interest, taxes, depreciation, and amortization',
    'Operating profitability before those items',
    'Net profit after taxes',
    'Gross sales',
    'Free cash flow',
    'hard',
    'Business Concepts',
  ],
  [
    'What is free cash flow? Cash left after capex and operations',
    'Operating cash minus capital spending',
    'Revenue minus COGS',
    'Net income plus debt',
    'Dividends paid',
    'medium',
    'Business Concepts',
  ],
  [
    'What is capex? Capital expenditure',
    'Spending on long-term assets',
    'Daily operational costs',
    'Marketing spend',
    'Payroll only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a balance sheet? Assets, liabilities, and equity snapshot',
    'A statement of financial position',
    'A profit statement',
    'A cash flow report',
    'A tax filing',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an income statement? Revenue and profit over a period',
    'The profit and loss statement',
    'A position snapshot',
    'A cash movement report',
    'An audit opinion',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a cash flow statement? Movement of cash in and out',
    'The report of cash movements',
    'A revenue report',
    'A balance sheet',
    'An equity statement',
    'medium',
    'Business Concepts',
  ],
  [
    'What are the Big Four accounting firms? Deloitte, PwC, EY, and KPMG',
    'Deloitte, PwC, EY, KPMG',
    'McKinsey, BCG, Bain, Accenture',
    'Goldman, Morgan, Citi, Barclays',
    'Visa, Mastercard, Amex, Discover',
    'medium',
    'Business Concepts',
  ],
  [
    'What is the MBB consulting trio? McKinsey, BCG, and Bain',
    'McKinsey, Boston Consulting, Bain',
    'Big Four accounting firms',
    'Goldman Sachs trio banks',
    'Accenture, Deloitte, Capgemini',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an IPO lock-up? A period insiders cannot sell shares',
    'The post-IPO insider selling ban',
    'A trading halt',
    'A dividend freeze',
    'A buyback window',
    'hard',
    'Business Concepts',
  ],
  [
    'What is a stock buyback? A company repurchasing its shares',
    'The company buying back its stock',
    'Issuing new shares',
    'Paying dividends',
    'Splitting stock',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a stock split? Dividing shares to lower price',
    'Increasing share count proportionally',
    'Merging share classes',
    'Canceling shares',
    'Issuing bonuses',
    'medium',
    'Business Concepts',
  ],
  [
    'What is vesting? Earning equity over time',
    'Gradual ownership of granted equity',
    'Selling shares immediately',
    'Buying stock at discount always',
    'A dividend reinvestment',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an ESOP? An employee stock ownership plan',
    'A plan giving employees stock',
    'An executive severance plan',
    'A supplier program',
    'A savings bond plan',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a co-founder split? Equity division among founders',
    'How founders divide equity',
    'An office lease split',
    'A product roadmap',
    'A marketing budget',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a cap table? The record of equity ownership',
    'The startup ownership ledger',
    'A market cap ranking',
    'A capital expense list',
    'A capital city table',
    'medium',
    'Business Concepts',
  ],
  [
    'What is due diligence? Investigating before a deal',
    'The pre-deal investigation process',
    'A compliance audit only',
    'A tax filing',
    'An HR review',
    'medium',
    'Business Concepts',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const MARKETS_FACTS = [
  [
    'What is the worlds largest stock exchange by market cap? The NYSE',
    'The New York Stock Exchange',
    'The Nasdaq second',
    'The London Stock Exchange',
    'The Tokyo Stock Exchange',
    'medium',
    'Markets & Finance',
  ],
  [
    'Which exchange is tech-heavy in the US? The Nasdaq',
    'The Nasdaq',
    'The NYSE',
    'The TSX',
    'The LSE',
    'easy',
    'Markets & Finance',
  ],
  [
    "What does S  ['What does S&P stand for? Standard and Poor's', 'Standard & Poor's analytics', 'Securities Pricing Panel', 'Stock Performance Platform', 'Standard Portfolio', 'hard', 'Markets & Finance'],P stand for?",
    'Standard and Poor',
    'A securities pricing panel',
    'A stock performance platform',
    'A standard portfolio',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is the Dow measured in? Points not dollars',
    'Index points',
    'Dollars',
    'Percent of GDP',
    'Shares',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is an IPO pop? A first-day price jump',
    'The first-day trading surge',
    'A dividend payout',
    'A pre-IPO discount',
    'A lockup expiry drop',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is a SPAC? A blank-check listing vehicle',
    'A shell company used to go public',
    'A sovereign wealth fund',
    'A stock exchange',
    'A preferred stock class',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is a short squeeze? Rising prices forcing short covering',
    'Shorts forced to buy as prices rise',
    'A fall from shorting',
    'A dividend trap',
    'A market holiday',
    'medium',
    'Markets & Finance',
  ],
  [
    'Which stock famously squeezed in 2021? GameStop',
    'GameStop via WallStreetBets',
    'AMC also squeezed same time',
    'Tesla never squeezed',
    'Nokia minor squeeze',
    'medium',
    'Markets & Finance',
  ],
  [
    'What subreddit drove the GameStop rally? WallStreetBets',
    'r/WallStreetBets',
    'r/Investing calm corner',
    'r/Stocks basic',
    'r/CryptoCurrency different',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is a meme stock? A stock moved by retail hype',
    'A stock driven by viral retail interest',
    'A comedy company stock',
    'An ETF meme basket',
    'A delisted stock',
    'easy',
    'Markets & Finance',
  ],
  [
    'What is the Fed funds rate? The overnight US bank lending rate target',
    'The central bank overnight rate target',
    'A mortgage rate',
    'A credit card APR',
    'A bond coupon',
    'medium',
    'Markets & Finance',
  ],
  [
    'Who sets the Fed funds target? The FOMC',
    'The Federal Open Market Committee',
    'The US Treasury',
    'Congress',
    'The President',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is QE tapering? Slowing asset purchases',
    'Gradually reducing bond buying',
    'Raising rates to 5 percent',
    'Selling all bonds at once',
    'Printing more money opposite',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is a yield curve inversion? Short rates above long rates recession signal',
    'Short-term yields exceeding long-term yields',
    'Flat yields always',
    'A bond default wave',
    'A dividend cut pattern',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is inflation targeting by many banks? Around 2 percent',
    'A 2 percent goal typical',
    'Zero percent exactly',
    '10 percent',
    'No target exists',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is a currency peg? Fixing a currency to another',
    'Linking a currency to another value',
    'Floating freely',
    'Printing new notes',
    'A gold standard always',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is the IMF role? Global financial stability and loans',
    'Lending to countries in crisis',
    'Setting US rates',
    'Regulating crypto only',
    'Running the UN',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is the World Bank focus? Development financing',
    'Funding development projects',
    'Setting exchange rates',
    'Issuing dollars',
    'Trading commodities',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is the WTO role? Trade rules between nations',
    'The global trade rules body',
    'A currency union',
    'An oil cartel',
    'A shipping regulator',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is OPEC? An oil producing cartel',
    'The petroleum exporters group',
    'A gold cartel',
    'A gas only group',
    'A shipping alliance',
    'easy',
    'Markets & Finance',
  ],
  [
    'What is the Brent benchmark? North Sea crude oil price',
    'The global crude oil benchmark',
    'US natural gas price',
    'Gold spot price',
    'Wheat futures price',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is WTI? The US crude oil benchmark',
    'The American crude benchmark',
    'European crude benchmark',
    'A metals index',
    'A currency basket',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is the gold standard? Currency backed by gold',
    'Money redeemable in gold',
    'A jewelry index',
    'A bond type',
    'A silver standard rival name',
    'medium',
    'Markets & Finance',
  ],
  [
    'Who left the gold standard last among majors? Switzerland in 2000 referencing',
    'Switzerland among the last in 2000',
    'The US in 1971 famous exit',
    'The UK in 1931 classic exit',
    'France in 1936 exit',
    'expert',
    'Markets & Finance',
  ],
  [
    'What was Bretton Woods? The 1944 monetary system conference',
    'The postwar currency system conference',
    'A trade war treaty',
    'An oil embargo event',
    'A stock exchange founding',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is the eurozone? Countries using the euro',
    'The euro currency member states',
    'All EU members including Poland false',
    'The Schengen travel area different',
    'The Nordic council different',
    'medium',
    'Markets & Finance',
  ],
  [
    'Which large EU country does not use the euro? Poland uses the zloty',
    'Poland still uses the zloty',
    'Germany uses the euro',
    'France uses the euro',
    'Spain uses the euro',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is the Swiss franc safe haven reputation? A crisis storage currency',
    'A store of value in crises',
    'A high-inflation currency',
    'A pegged yuan proxy',
    'A crypto-backed token',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is a currency devaluation? Lowering a pegged currencys value',
    'A deliberate official reduction',
    'Market floating freely',
    'Printing commemorative notes',
    'Raising interest rates',
    'medium',
    'Markets & Finance',
  ],
  [
    'What is the Cantillon effect? New money benefits first receivers',
    'Early money receivers gain most',
    'A tax on imports',
    'A real estate rule',
    'A payroll law',
    'expert',
    'Markets & Finance',
  ],
  [
    'What is Greshams law? Bad money drives out good',
    'Cheap money crowds out sound money',
    'Supply creates demand',
    'Bad banks fail fast',
    'Gold appreciates always',
    'expert',
    'Markets & Finance',
  ],
  [
    "What is Say's law?",
    'Supply creates its own demand',
    'Demand creates supply',
    'Money is neutral always',
    'Trade always balances',
    'expert',
    'Markets & Finance',
  ],
  [
    "What is Okun's law?",
    'GDP growth and unemployment are linked',
    'Inflation and jobs tradeoff is the Phillips curve',
    'Tax cuts always raise revenue',
    'Trade imbalances self-correct',
    'expert',
    'Markets & Finance',
  ],
  [
    'What is the Phillips curve? Inflation and unemployment tradeoff',
    'The inflation-jobs inverse relationship',
    'GDP and population link',
    'Rates and bonds link',
    'Trade and tariffs link',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is the Laffer curve? Tax rate versus revenue relationship',
    'Revenue peaks at an optimal tax rate',
    'A supply chain model',
    'A bond pricing curve',
    'An employment chart',
    'hard',
    'Markets & Finance',
  ],
  [
    'What is the Kuznets curve? Inequality rises then falls with development',
    'Development first raises then lowers inequality',
    'A yield curve shape',
    'A demand elasticity curve',
    'A currency corridor',
    'expert',
    'Markets & Finance',
  ],
];

const EXTREMES = [
  ['What does GDP stand for?', 'Gross domestic product', 'Economics Terms'],
  ['What does IPO stand for?', 'Initial public offering', 'Finance & Markets'],
  ['What is a bear market?', 'A period of falling prices', 'Finance & Markets'],
  ['What is a bull market?', 'A period of rising prices', 'Finance & Markets'],
  ['What does CEO stand for?', 'Chief executive officer', 'Business Leaders'],
  ['What does CFO stand for?', 'Chief financial officer', 'Business Leaders'],
  ['What is venture capital?', 'Equity funding for startups', 'Business Concepts'],
  ['What is a franchise?', 'A licensed business format', 'Business Concepts'],
  ['Which company did Warren Buffett lead?', 'Berkshire Hathaway', 'Business Leaders'],
  ['What is the US central bank called?', 'The Federal Reserve', 'Markets & Finance'],
  ['What does OPEC coordinate?', 'Oil production policies', 'Markets & Finance'],
  ['What is a monopoly?', 'A single dominant seller', 'Economics Terms'],
  ['What is inflation?', 'A general rise in prices', 'Economics Terms'],
  ['What is a dividend?', 'A share of company profits', 'Finance & Markets'],
  ['What is an exchange rate?', 'The price of one currency in another', 'Markets & Finance'],
  [
    'What is a unicorn startup?',
    'A private company valued over a billion dollars',
    'Business Concepts',
  ],
  ['What is a stock buyback?', 'A company repurchasing its own shares', 'Finance & Markets'],
  ['What is the S&P 500?', 'An index of 500 large US companies', 'Finance & Markets'],
  ['What is a tariff?', 'A tax on imports', 'Economics Terms'],
  [
    'What is EBITDA short for?',
    'Earnings before interest taxes depreciation and amortization',
    'Business Concepts',
  ],
];

function generate(rng) {
  const rows = [];

  const founderPool = COMPANIES.map((c) => c[1]);
  const industryPool = COMPANIES.map((c) => c[2]);
  const hqPool = COMPANIES.map((c) => c[3]);
  for (const [company, founder, industry, hq] of COMPANIES) {
    rows.push({
      q: `Who founded ${company}?`,
      correct: founder,
      ds: distractors(founderPool, founder, 3),
      level: 'medium',
      chapter: 'Companies & Founders',
    });
    rows.push({
      q: `Which industry is ${company} in?`,
      correct: industry,
      ds: distractors(industryPool, industry, 3),
      level: 'medium',
      chapter: 'Companies & Founders',
    });
    rows.push({
      q: `Where is ${company} headquartered?`,
      correct: hq,
      ds: distractors(hqPool, hq, 3),
      level: 'hard',
      chapter: 'Companies & Founders',
    });
  }

  const defPool = ECON_TERMS.map((t) => t[1]);
  for (const [term, def] of ECON_TERMS) {
    rows.push({
      q: `What does the economic term ${term} mean?`,
      correct: def,
      ds: distractors(defPool, def, 3),
      level: 'medium',
      chapter: 'Economics Terms',
    });
    rows.push({
      q: 'Which economic term matches: ' + def + '?',
      correct: term,
      ds: ECON_TERMS.filter((t) => t[0] !== term)
        .slice(0, 3)
        .map((t) => t[0]),
      level: 'hard',
      chapter: 'Economics Terms',
    });
  }

  const finPool = FINANCE.map((t) => t[1]);
  for (const [term, def] of FINANCE) {
    rows.push({
      q: `In finance, what is ${term}?`,
      correct: def,
      ds: distractors(finPool, def, 3),
      level: 'medium',
      chapter: 'Finance & Markets',
    });
    rows.push({
      q: 'Which finance term matches: ' + def + '?',
      correct: term,
      ds: FINANCE.filter((t) => t[0] !== term)
        .slice(0, 3)
        .map((t) => t[0]),
      level: 'hard',
      chapter: 'Finance & Markets',
    });
  }

  const companyPool = LEADERS.map((l) => l[1]);
  for (const [leader, company] of LEADERS) {
    rows.push({
      q: `Which company is ${leader} associated with?`,
      correct: company,
      ds: distractors(companyPool, company, 3),
      level: 'medium',
      chapter: 'Business Leaders',
    });
    rows.push({
      q: `Who leads or founded ${company}?`,
      correct: leader,
      ds: LEADERS.filter((l) => l[0] !== leader)
        .slice(0, 3)
        .map((l) => l[0]),
      level: 'hard',
      chapter: 'Business Leaders',
    });
  }

  const cityPool = EXCHANGES.map((e) => e[1]);
  for (const [exchange, city] of EXCHANGES) {
    rows.push({
      q: `In which city is ${exchange} based?`,
      correct: city,
      ds: distractors(cityPool, city, 3),
      level: 'medium',
      chapter: 'Exchanges & Hubs',
    });
  }

  const tagPool = TAGLINES.map((t) => t[1]);
  for (const [brand, tag] of TAGLINES) {
    rows.push({
      q: `Which brand used the slogan ${tag}?`,
      correct: brand,
      ds: distractors(tagPool, brand, 3),
      level: 'medium',
      chapter: 'Slogans & Brands',
    });
    rows.push({
      q: 'What is the famous slogan of ' + brand + '?',
      correct: tag,
      ds: distractors(tagPool, tag, 3),
      level: 'medium',
      chapter: 'Slogans & Brands',
    });
  }

  for (const f of topup.rows)
    rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  for (const [q, text, chapter] of EXTREMES) rows.push({ q, text, chapter });
  for (const [airline, country, hub] of topup2.AIRLINES) {
    rows.push({
      q: 'Which country is ' + airline + ' from?',
      correct: country,
      ds: distractors(
        topup2.AIRLINES.map((a) => a[1]),
        country,
        3
      ),
      level: 'medium',
      chapter: 'Airlines & Hotels',
    });
    rows.push({
      q: 'What is the hub of ' + airline + '?',
      correct: hub,
      ds: distractors(
        topup2.AIRLINES.map((a) => a[2]),
        hub,
        3
      ),
      level: 'hard',
      chapter: 'Airlines & Hotels',
    });
  }
  for (const [hotel, fact, extra] of topup2.HOTELS) {
    rows.push({
      q: 'What is a key fact about ' + hotel + '?',
      correct: fact,
      ds: distractors(
        topup2.HOTELS.map((h) => h[1]),
        fact,
        3
      ),
      level: 'medium',
      chapter: 'Hotels & Travel Brands',
    });
    rows.push({
      q: 'Which loyalty or sub-brand belongs to ' + hotel + '?',
      correct: extra,
      ds: distractors(
        topup2.HOTELS.map((h) => h[2]),
        extra,
        3
      ),
      level: 'hard',
      chapter: 'Hotels & Travel Brands',
    });
  }
  for (const [bank, country, fact] of topup2.BANKS) {
    rows.push({
      q: 'Which country is ' + bank + ' from?',
      correct: country,
      ds: distractors(
        topup2.BANKS.map((b) => b[1]),
        country,
        3
      ),
      level: 'medium',
      chapter: 'Banks & Banking',
    });
    rows.push({
      q: 'What is ' + bank + ' known for?',
      correct: fact,
      ds: distractors(
        topup2.BANKS.map((b) => b[2]),
        fact,
        3
      ),
      level: 'hard',
      chapter: 'Banks & Banking',
    });
  }
  for (const f of topup2.rows)
    rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  for (const f of topup3.rows)
    rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  for (const f of topup4.rows)
    rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });

  return rows;
}

module.exports = { subject: 'Business', generate };

module.exports = { subject: 'Business', generate };
