'use strict';

const rows = [
  [
    'What is a pitch deck? A startup presentation for investors',
    'The slide presentation for fundraising',
    'A baseball term',
    'A roofing estimate',
    'A sales receipt',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a term sheet? A summary of investment deal terms',
    'The nonbinding deal terms outline',
    'A glossary of finance words',
    'A school exam paper',
    'A lease agreement',
    'medium',
    'Business Concepts',
  ],
  [
    'What is dilution? Ownership shrinking after new shares',
    'Founders stake reduced by new issuance',
    'A chemical process',
    'A tax credit',
    'A stock split synonym',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a down round? Raising at a lower valuation',
    'A funding round at a lower valuation',
    'An IPO discount',
    'A dividend cut',
    'A layoffs event',
    'hard',
    'Business Concepts',
  ],
  [
    'What is a bridge round? Short-term funding to the next round',
    'Interim financing between rounds',
    'A bond issuance',
    'A bridge loan for homes only',
    'An acquisition bridge',
    'hard',
    'Business Concepts',
  ],
  [
    'What is a lead investor? The round anchor setting terms',
    'The main investor structuring the round',
    'The first employee',
    'The oldest investor',
    'The legal counsel',
    'medium',
    'Business Concepts',
  ],
  [
    'What is pro-rata rights? Investors maintaining their ownership share',
    'The right to invest in later rounds equally',
    'A dividend right',
    'A board seat guarantee',
    'A veto over exits',
    'hard',
    'Business Concepts',
  ],
  [
    'What is liquidation preference? Investors paid first in exits',
    'Preferred payout before common shareholders',
    'A salary guarantee',
    'A debt covenant',
    'A tax preference',
    'hard',
    'Business Concepts',
  ],
  [
    'What is an acquirer? The company buying another',
    'The purchasing company in a deal',
    'The company being bought',
    'The regulator approving',
    'The banker advising',
    'easy',
    'Business Concepts',
  ],
  [
    'What is goodwill in accounting? The premium paid above asset value',
    'The excess paid over book assets',
    'Kindness to staff',
    'Brand equity only',
    'A charity line item',
    'hard',
    'Business Concepts',
  ],
  [
    'What is depreciation? Allocating asset cost over its life',
    'Spreading asset costs over time',
    'Asset value rising',
    'Cash decline',
    'Debt repayment',
    'medium',
    'Business Concepts',
  ],
  [
    'What is amortization? Spreading intangible costs over time',
    'Allocating intangible costs gradually',
    'Physical asset wear',
    'A loan payoff only',
    'An interest charge',
    'medium',
    'Business Concepts',
  ],
  [
    'What is working capital? Current assets minus current liabilities',
    'Short-term operating liquidity measure',
    'Long-term debt total',
    'Fixed assets value',
    'Equity issuance proceeds',
    'medium',
    'Business Concepts',
  ],
  [
    'What is inventory turnover? How fast stock sells through',
    'The rate stock is sold and replaced',
    'Employee rotation speed',
    'Cash conversion days',
    'Purchase discount rate',
    'medium',
    'Business Concepts',
  ],
  [
    'What is just in time? Inventory arriving exactly when needed',
    'The Toyota lean inventory approach',
    'Panic buying method',
    'Bulk warehousing approach',
    'Dropshipping method',
    'medium',
    'Business Concepts',
  ],
  [
    'What is kaizen? Continuous improvement philosophy',
    'The Japanese continuous improvement practice',
    'A martial art',
    'A sushi cut',
    'A tea ceremony',
    'medium',
    'Business Concepts',
  ],
  [
    'What is Six Sigma? A quality improvement methodology',
    'The defect-reduction methodology',
    'A sigma algebra concept only',
    'A stock index',
    'A six-part strategy deck',
    'medium',
    'Business Concepts',
  ],
  [
    'What is lean startup? Build measure learn methodology',
    'The rapid-test iterative startup approach',
    'A minimalist office design',
    'A staffing plan',
    'A bootstrapping tax method',
    'medium',
    'Business Concepts',
  ],
  [
    'What is agile? Iterative software development methodology',
    'The sprint-based iterative development way',
    'A gymnastics program',
    'A supply chain term',
    'A sales technique',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a sprint in agile? A fixed short work cycle',
    'A time-boxed development cycle',
    'A running race',
    'A hiring sprint',
    'A marketing blitz',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a scrum master? An agile team facilitator',
    'The agile process facilitator role',
    'A rugby position',
    'A helpdesk agent',
    'A QA tester',
    'medium',
    'Business Concepts',
  ],
  [
    'What is DevOps? Combined development and operations practice',
    'Engineering plus operations culture',
    'A data team',
    'A design team',
    'A support desk',
    'medium',
    'Business Concepts',
  ],
  [
    'What is SaaS churn? Subscription cancellation rate',
    'The subscription cancellation metric',
    'A kitchen churn rate',
    'An AI model metric',
    'A churned credit score',
    'medium',
    'Business Concepts',
  ],
  [
    'What is ARPU? Average revenue per user',
    'Revenue divided by users',
    'Assets per unit',
    'Annual rate percentage',
    'Advertising rate per unit',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a freemium model? Free basic tier with paid upgrades',
    'Free tier plus paid premium features',
    'Free trials only',
    'Fully free charity product',
    'Ad-free paid model',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a paywall? Restricted content behind payment',
    'Charging access to content',
    'A fire wall of servers',
    'A payroll wall chart',
    'A stock wall display',
    'easy',
    'Business Concepts',
  ],
  [
    'What is dropshipping? Selling without holding inventory',
    'The supplier ships directly for you',
    'Shipping drops from planes',
    'Discounting shipping',
    'Dropping loss-making SKUs',
    'medium',
    'Business Concepts',
  ],
  [
    'What is affiliate marketing? Earning commissions promoting others products',
    'Commission-based referral selling',
    'Affiliate college programs',
    'Buying ad agencies',
    'Merging with affiliates',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an influencer partnership? Paid promotion via creators',
    'Brands paying creators to promote',
    'A dating service for stars',
    'An investor syndicate',
    'A merger of influencers',
    'easy',
    'Business Concepts',
  ],
  [
    'What is viral marketing? Campaigns designed to spread socially',
    'Promotion designed to self-replicate',
    'Virus-themed advertising',
    'Malware marketing',
    'Influencer marketing exactly',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a brand ambassador? A long-term representative partner',
    'A contracted brand spokesperson',
    'An embassy role only',
    'A short cameo star',
    'A store greeter',
    'medium',
    'Business Concepts',
  ],
  [
    'What is co-branding? Two brands collaborating on a product',
    'Joint branding between two brands',
    'Counterfeit branding',
    'Rebranding solo',
    'Private labeling only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is white labeling? Selling others products under your brand',
    'Rebranding a generic product as yours',
    'Painting products white',
    'Labeling organic only',
    'Government labeling',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a private label? A retailer-owned brand made by others',
    'Store brand produced by third parties',
    'Luxury designer brand',
    'Government brand',
    'Celebrity brand always',
    'medium',
    'Business Concepts',
  ],
  [
    'What is vertical integration? Owning supply chain stages',
    'Controlling upstream and downstream stages',
    'Tall buildings integration',
    'Merging with rivals horizontal',
    'Outsourcing everything',
    'medium',
    'Business Concepts',
  ],
  [
    'What is outsourcing? Hiring external providers for work',
    'Contracting work to third parties',
    'Promoting internally',
    'Offshoring factories only',
    'Automating with robots',
    'easy',
    'Business Concepts',
  ],
  [
    'What is offshoring? Moving operations to another country',
    'Relocating operations abroad',
    'Shutting down operations',
    'Nearby country move nearshoring different',
    'Automating processes',
    'medium',
    'Business Concepts',
  ],
  [
    'What is nearshoring? Moving operations to nearby countries',
    'Relocating to closer countries',
    'Moving far offshore',
    'Outsourcing domestically',
    'Selling operations',
    'medium',
    'Business Concepts',
  ],
  [
    'What is reshoring? Bringing operations back home',
    'Returning production domestically',
    'First offshore move',
    'Domestic outsourcing',
    'Selling the home market',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a supply chain? The network producing and delivering goods',
    'End-to-end production delivery network',
    'A bicycle chain',
    'A management chain of command',
    'A retail shelf chain',
    'easy',
    'Business Concepts',
  ],
  [
    'What is logistics? Managing transport and storage of goods',
    'Planning movement and warehousing',
    'Marketing logistics branding',
    'HR logistics hiring',
    'Legal compliance work',
    'easy',
    'Business Concepts',
  ],
  [
    'What is warehousing? Storing goods for distribution',
    'Storage facilities for inventory',
    'Retail shelf stocking only',
    'Manufacturing assembly',
    'Last-mile delivery',
    'easy',
    'Business Concepts',
  ],
  [
    'What is last-mile delivery? Final leg to the customer',
    'The final delivery to the doorstep',
    'First warehouse leg',
    'Ocean shipping leg',
    'Return shipping leg',
    'easy',
    'Business Concepts',
  ],
  [
    'What is reverse logistics? Handling returns back up the chain',
    'The returns and recall flow',
    'Faster forward shipping',
    'Reverse auctions bidding',
    'Recycling marketing only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a distribution center? A hub moving goods to stores',
    'The warehouse hub for store replenishment',
    'A factory outlet',
    'A corporate office',
    'A port terminal only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is cross-docking? Transferring goods without storage',
    'Moving inbound goods straight to outbound',
    'Storing goods long-term',
    'Docking pay deductions',
    'Cross-border trucking',
    'hard',
    'Business Concepts',
  ],
  [
    'What is JIT inventory approach? Just-in-time minimal stock',
    'Minimal stock arriving when needed',
    'Just-in-case bulk stock opposite',
    'Job-in-transfer system',
    'Joint-investment trust',
    'medium',
    'Business Concepts',
  ],
  [
    'What is safety stock? Buffer inventory for variability',
    'Extra stock against uncertainty',
    'Retired warehouse stock',
    'Damaged goods stock',
    'Seasonal decor stock',
    'medium',
    'Business Concepts',
  ],
  [
    'What is SKU? Stock keeping unit identifier',
    'A unique product tracking code',
    'A stock market unit',
    'A SKU storage keg unit',
    'A supplier key user',
    'medium',
    'Business Concepts',
  ],
  [
    'What is barcoding for? Tracking products automatically',
    'Machine-readable product tracking',
    'Decorative packaging',
    'Pricing labels only',
    'Legal compliance marks',
    'easy',
    'Business Concepts',
  ],
  [
    'What is RFID tracking? Radio tag-based inventory tracking',
    'Wireless chip inventory tracking',
    'Barcode scanning different',
    'GPS vehicle tracking',
    'Wi-Fi positioning',
    'medium',
    'Business Concepts',
  ],
  [
    'What is omnichannel retail? Seamless online and offline selling',
    'Unified shopping across all channels',
    'Online only selling',
    'Store only selling',
    'Catalog only selling',
    'medium',
    'Business Concepts',
  ],
  [
    'What is brick and click? Stores plus online sales model',
    'Physical stores with e-commerce',
    'Bricklaying e-commerce metaphor',
    'Click farms fake traffic',
    'Popup shops only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a popup shop? A temporary retail space',
    'A short-term pop-up store',
    'An online flash shop',
    'A mall anchor store',
    'A kiosk franchise',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a flagship store? A brands main showcase location',
    'The brand showcase megastore',
    'A discount outlet',
    'An airport kiosk',
    'A warehouse club',
    'medium',
    'Business Concepts',
  ],
  [
    'What is an anchor store? The major mall draw tenant',
    'The big department store drawing traffic',
    'A food court stall',
    'A parking structure',
    'A movie theater screen',
    'medium',
    'Business Concepts',
  ],
  [
    'What is foot traffic? The number of store visitors',
    'Customer visits to a location',
    'Walking speed studies',
    'Shoe sales volume',
    'Website visits',
    'medium',
    'Business Concepts',
  ],
  [
    'What is conversion rate in retail? Visitors who buy percentage',
    'The share of visitors who purchase',
    'Currency conversion rate',
    'Store layout metric',
    'Loyalty sign-ups only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a loyalty program? Rewards for repeat customers',
    'Points and perks for repeat buying',
    'A rewards credit card only',
    'An employee bonus plan',
    'A supplier rebate scheme',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a gift card? Prepaid store value card',
    'A prepaid shopping card',
    'A credit card type',
    'A coupon stack',
    'A store credit line',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a coupon? A discount voucher',
    'A redeemable discount ticket',
    'A gift card',
    'A loyalty point',
    'A cashback app',
    'easy',
    'Business Concepts',
  ],
  [
    'What is cashback? Money returned on purchases',
    'A rebate of spending percentage',
    'ATM cash withdrawal',
    'Cash discount at tills',
    'Store credit only',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a layaway plan? Paying over time before receiving goods',
    'Reserving goods via installments',
    'Buying on credit card',
    'Lay-away fire sale',
    'Gift wrapping service',
    'medium',
    'Business Concepts',
  ],
  [
    'What is BNPL? Buy now pay later installment shopping',
    'Installment payments at checkout',
    'Bank loans only',
    'Gift card plans',
    'Layaway paper contracts',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a subscription box? Recurring curated product deliveries',
    'Periodic curated product shipments',
    'A single gift box',
    'A magazine only',
    'A meal kit only',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a meal kit? Pre-portioned recipe ingredient boxes',
    'Recipe ingredient delivery boxes',
    'Restaurant delivery app',
    'Frozen TV dinners',
    'Grocery store club',
    'medium',
    'Business Concepts',
  ],
  [
    'What is dark kitchen? Delivery-only restaurant kitchen',
    'A delivery-only ghost kitchen',
    'A midnight diner',
    'A closed restaurant',
    'A haunted kitchen meme',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a food truck? A mobile food vendor',
    'A vehicle-based food business',
    'A catering hall',
    'A drive-thru only',
    'A vending machine',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a franchise fee? The upfront license payment',
    'The initial franchise rights payment',
    'A royalty percentage ongoing',
    'An advertising levy',
    'An equipment rebate',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a royalty fee? Ongoing percent of franchise sales',
    'Continuing sales percentage payments',
    'The upfront license payment',
    'A supplier discount',
    'An advertising fund only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a co-op? A member-owned business',
    'A business owned by its members',
    'A corporate subsidiary',
    'A PE-owned chain',
    'A government store',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a sole proprietorship? A single-owner unincorporated business',
    'The simplest single-owner business form',
    'A two-partner firm',
    'A limited liability company',
    'A public corporation',
    'easy',
    'Business Concepts',
  ],
  [
    'What is an LLC? A limited liability company',
    'A flexible limited-liability structure',
    'A corporation listed on exchanges',
    'A nonprofit charity',
    'A sole proprietorship',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a nonprofit? An organization reinvesting surpluses into mission',
    'A mission-driven non-distributing entity',
    'A loss-making startup',
    'A tax-evading shell',
    'A government agency',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a B Corp? A certified social and environmental business',
    'The certified benefit corporation',
    'A bankrupt corporation',
    'A B-share company',
    'A blockchain corporation',
    'medium',
    'Business Concepts',
  ],
  [
    'What is ESG? Environmental social and governance criteria',
    'Sustainability and governance investing lens',
    'A stock exchange',
    'An earnings measure',
    'An employee survey',
    'medium',
    'Business Concepts',
  ],
  [
    'What is CSR? Corporate social responsibility programs',
    'Company social responsibility efforts',
    'A customer service rating',
    'A compliance requirement only',
    'A cost saving report',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a carbon offset? Funding reductions to balance emissions',
    'Paying for emission cuts elsewhere',
    'A carbon tax payment',
    'A carbon-neutral label claim',
    'A carbon capture machine only',
    'medium',
    'Business Concepts',
  ],
  [
    'What is net zero? Balancing emitted and removed greenhouse gases',
    'Emissions balanced by removals',
    'Zero emissions always instantly',
    'Zero carbon products only',
    'A zero interest rate policy',
    'medium',
    'Business Concepts',
  ],
  [
    'What is renewable energy? Power from naturally replenishing sources',
    'Solar, wind, and hydro power',
    'Coal with filters',
    'Natural gas',
    'Nuclear fission debated category',
    'easy',
    'Business Concepts',
  ],
  [
    'What is a power purchase agreement? A long-term energy offtake contract',
    'A long-term electricity purchase contract',
    'A utility bill',
    'A solar panel lease',
    'A grid maintenance fee',
    'hard',
    'Business Concepts',
  ],
  [
    'What is a PPA in sports different context? Players association union',
    'The players association in leagues',
    'A power purchase agreement different',
    'A performance bonus plan',
    'A public private alliance',
    'expert',
    'Business Concepts',
  ],
  [
    'What is a collective bargaining agreement? The union-management labor contract',
    'The negotiated labor contract',
    'A sponsorship deal',
    'A supply agreement',
    'A franchise disclosure doc',
    'hard',
    'Business Concepts',
  ],
  [
    'What is a collective bargaining unit? The union negotiating group',
    'The union representation group',
    'A corporate board committee',
    'A supplier consortium',
    'A sports league office',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a salary cap? A limit on team player payrolls',
    'The payroll ceiling in leagues',
    'An executive pay floor',
    'A ticket price cap',
    'A stadium naming fee',
    'medium',
    'Business Concepts',
  ],
  [
    'What is a luxury tax in sports? A penalty over payroll thresholds',
    'The surcharge above spending limits',
    'A ticket surcharge',
    'A merchandising levy',
    'A stadium tax',
    'hard',
    'Business Concepts',
  ],
];

module.exports = { rows };
