'use strict';

const rows = [
  [
    'Who founded Amazon? Jeff Bezos in his garage',
    'Jeff Bezos 1994',
    'Marc Lore Jet founder later',
    'Jack Ma Alibaba rival',
    'eBay Pierre different',
    'easy',
    'Founders',
  ],
  [
    'Who founded Alibaba? Jack Ma',
    'Jack Ma English teacher founder',
    'Pony Ma Tencent founder',
    'Lei Jun Xiaomi founder',
    'Robin Li Baidu founder',
    'easy',
    'Founders',
  ],
  [
    'Who founded Tencent? Pony Ma',
    'Pony Ma Huateng founded QQ',
    'Jack Ma Alibaba founder',
    'Lei Jun Xiaomi',
    'Zhang Yiming ByteDance',
    'medium',
    'Founders',
  ],
  [
    'Who founded ByteDance? Zhang Yiming',
    'Zhang Yiming TikTok parent founder',
    'Pony Ma Tencent',
    'Jack Ma Alibaba',
    'Robin Li Baidu',
    'medium',
    'Founders',
  ],
  [
    'Who founded Baidu? Robin Li',
    'Robin Li the Chinese search founder',
    'Zhang Yiming ByteDance',
    'Jack Ma Alibaba',
    'Pony Ma Tencent',
    'medium',
    'Founders',
  ],
  [
    'Who founded Xiaomi? Lei Jun',
    'Lei Jun the smartphone founder',
    'Ren Zhengfei Huawei founder',
    'Zhang Yiming ByteDance',
    'Liu Chuanzhi Lenovo legend',
    'medium',
    'Founders',
  ],
  [
    'Who founded Huawei? Ren Zhengfei',
    'Ren Zhengfei ex-military engineer',
    'Lei Jun Xiaomi',
    'Liu Chuanzhi Lenovo',
    'Zhang Ruimin Haier',
    'medium',
    'Founders',
  ],
  [
    'Who founded Lenovo? Liu Chuanzhi',
    'Liu Chuanzhi from the Chinese Academy of Sciences',
    'Ren Zhengfei Huawei',
    'Lei Jun Xiaomi',
    'Zhang Ruimin Haier',
    'hard',
    'Founders',
  ],
  [
    'Who is the Haier CEO famous for smashing fridges? Zhang Ruimin',
    'Zhang Ruimin the quality smashing legend',
    'Ren Zhengfei Huawei founder',
    'Liu Chuanzhi Lenovo founder',
    'Jack Welch GE different',
    'expert',
    'Founders',
  ],
  [
    'Who is Jack Welch? The legendary GE CEO Neutron Jack',
    'The GE CEO of the 80s-90s',
    'Jeff Immelt his successor',
    'Larry Culp current CEO',
    'Jim McNerney 3M then Boeing',
    'hard',
    'Founders',
  ],
  [
    'Who succeeded Jack Welch at GE? Jeff Immelt',
    'Jeff Immelt led through 9-11 and crisis',
    'Larry Culp took over 2018',
    'John Flannery brief CEO',
    'Jack Welch returned never',
    'hard',
    'Founders',
  ],
  [
    'Who is the current GE Aerospace CEO? Larry Culp',
    'Larry Culp leads GE Aerospace',
    'Jeff Immelt predecessor',
    'John Flannery brief predecessor',
    'Calhoun Boeing different',
    'expert',
    'Founders',
  ],
  [
    'Who is the Boeing CEO during the 737 MAX crises? Dennis Muilenburg then fired',
    'Dennis Muilenburg ousted in 2019-20',
    'David Calhoun successor CEO',
    'Kelly Ortberg newest CEO',
    'Ray Conner commercial earlier',
    'hard',
    'Founders',
  ],
  [
    'Who is the newest Boeing CEO 2024? Kelly Ortberg',
    'Kelly Ortberg from QuantumScape board fame engineer',
    'David Calhoun predecessor',
    'Dennis Muilenburg ousted earlier',
    'Ted Colbert defense unit',
    'expert',
    'Founders',
  ],
  [
    'Who founded FedEx idea in a Yale paper? Fred Smith',
    'Fred Smith wrote the Yale paper',
    'Jim Casey UPS founder different',
    'DHL three founders different',
    'Adrian Dalsey DHL cofounder',
    'medium',
    'Founders',
  ],
  [
    'Who founded UPS? James Casey as American Messenger',
    'Jim Casey started as messenger company',
    'Fred Smith FedEx founder different',
    'Adrian Dalsey DHL cofounder',
    'Larry Hillblom DHL H initial',
    'medium',
    'Founders',
  ],
  [
    'Who founded IKEA? Ingvar Kamprad as a teenager',
    'Ingvar started IKEA at 17',
    'Ernst Freska cabinet maker colleague',
    'Kamprad Elmtaryd Agunnaryd acronym',
    'Sten Ake Lysell early designer',
    'medium',
    'Founders',
  ],
  [
    'What does IKEA stand for? Ingvar Kamprad Elmtaryd Agunnaryd',
    'His initials plus farm and village',
    'Swedish design phrase',
    'Innovation Kea',
    'Nothing it is invented Swedish',
    'hard',
    'Founders',
  ],
  [
    'Who founded H&M? Erling Persson',
    'Erling Persson Hennes Maurits origins',
    'Stefan Persson son chair',
    'Karl-Johan Persson grandson CEO era',
    'Helena Helmersson newer CEO',
    'hard',
    'Founders',
  ],
  [
    'What did H in H&M originally mean? Hennes meaning hers',
    'Hennes the womens shop name',
    'Hugo mens line partner',
    'H&M Harris brand',
    'Herald fashion house',
    'hard',
    'Founders',
  ],
  [
    'Who founded Zara? Amancio Ortega with Rosalia Mera',
    'Amancio Ortega and then-wife Rosalia',
    'Pablo Isla later executive chair',
    'Sandra Ortega his daughter',
    'Marta Ortega newer chair daughter',
    'hard',
    'Founders',
  ],
  [
    'Who is the current Zara chairman era? Marta Ortega daughter took chair 2022',
    'Marta Ortega became chairwoman',
    'Amancio stepped back fully',
    'Pablo Isla executive chair before',
    'Oscar Garcia Maceiras CEO',
    'expert',
    'Founders',
  ],
  [
    'Who founded Lidl ancestor? Dieter Schwarz father Josef',
    'The Schwarz family built Lidl',
    'Albrecht brothers Aldi separate',
    'Coop Swiss different',
    'Rewe German different',
    'hard',
    'Founders',
  ],
  [
    'Who founded Aldi? The Albrecht brothers Karl and Theo',
    'Karl and Theo split Aldi Nord Sud',
    'Dieter Schwarz Lidl rival',
    'Coop founders Swiss',
    'Tesco founders UK different',
    'medium',
    'Founders',
  ],
  [
    'What famous discount feud split a family? Aldi brothers divided Germany',
    'The Albrecht brothers split Nord and Sud',
    'Adidas Puma town rivalry brothers Dassler',
    'Nike founders were coach and runner',
    'Puma Adi vs Rudi Dassler feud',
    'expert',
    'Founders',
  ],
  [
    'Which brothers founded Adidas and Puma respectfully feuding? Adi and Rudolf Dassler',
    'The Dassler brothers split into rivals',
    'The Albrecht brothers grocery feud',
    'The Walton brothers none',
    'The Koch brothers industrial politics',
    'expert',
    'Founders',
  ],
  [
    'Who founded Nike? Phil Knight and Bill Bowerman',
    'The runner and his coach founded Blue Ribbon',
    'Adi Dassler Adidas founder',
    'Jesse Owens athlete era',
    'Steve Prefontaine runner endorsed',
    'medium',
    'Founders',
  ],
  [
    'Who founded Starbucks? Three founders including Jerry Baldwin',
    'Baldwin, Siegl, and Bowker started it',
    'Howard Schultz joined later bought it',
    'Gordon Bowker also Redhook beer',
    'Zev Siegl teacher cofounder',
    'hard',
    'Founders',
  ],
  [
    'Who took Starbucks global? Howard Schultz',
    'Howard Schultz bought and scaled Starbucks',
    'Howard Behar president culture',
    'Orin Smith operations CEO',
    'Jim Donald brief CEO',
    'medium',
    'Founders',
  ],
  [
    'Who founded Dunkin? William Rosenberg',
    'William Rosenberg Open Kettle 1950',
    'Howard Schultz Starbucks different',
    'Fred DeLuca Subway different',
    'Dave Thomas Wendys founder different',
    'hard',
    'Founders',
  ],
  [
    'Who founded Subway? Fred DeLuca and Peter Buck',
    'DeLuca with Dr Buck funding Subway',
    'Wendy Dave Thomas different',
    'Burger King founders Kramer and Matic',
    'McDonalds brothers Richard and Maurice',
    'medium',
    'Founders',
  ],
  [
    'Who founded McDonalds original restaurant? The McDonald brothers',
    'Richard and Maurice McDonald 1940',
    'Ray Kroc who franchised it globally',
    'Colonel Sanders KFC different',
    'Dave Thomas Wendys different',
    'medium',
    'Founders',
  ],
  [
    'Who scaled McDonalds worldwide? Ray Kroc',
    'Ray Kroc the milkshake machine salesman',
    'The McDonald brothers original founders',
    'Fred Turner early operations legend',
    'Jim Cantalupo later CEO',
    'medium',
    'Founders',
  ],
  [
    'Who founded Wendys? Dave Thomas',
    'Dave Thomas named after his daughter',
    'Ray Kroc McDonalds different',
    'Colonel Sanders KFC different',
    'Harland Sanders same KFC',
    'easy',
    'Founders',
  ],
  [
    'Who founded KFC? Harland Sanders',
    'The Colonel started at a gas station',
    'Dave Thomas worked for him early',
    'Ray Kroc different chain',
    'In-N_OUT founders different',
    'easy',
    'Founders',
  ],
  [
    'Who founded In-N-Out? Harry and Esther Snyder',
    'The Snyder family drive-thru pioneers',
    'Whataburger Harmon Dobson founder',
    'Whataburger user different',
    'Five Guys Jerry Murrell founder',
    'medium',
    'Founders',
  ],
  [
    'Who founded Five Guys? Jerry Murrell and his sons',
    'The Murrell family burger chain',
    'In-N_OUT Snyders different',
    'Shake Shack Danny Meyer founder',
    'Smash Shake founders UK',
    'medium',
    'Founders',
  ],
  [
    'Who founded Shake Shack? Danny Meyer of Union Square',
    'The restaurateur started a Madison Square kiosk',
    'Five Guys Murrells different',
    'In-N_OUT Snyders different',
    'Bobby Flay chef different',
    'medium',
    'Founders',
  ],
  [
    'Who founded Chipotle? Steve Ells',
    'Steve Ells culinary school burrito start',
    'Monty Moran co-CEO era',
    'Brian Niccol later CEO Taco Bell past',
    'Jack Hartung CFO',
    'medium',
    'Founders',
  ],
  [
    'Who is the current Chipotle CEO? Brian Niccol',
    'Brian Niccol ex-Taco Bell revived Chipotle',
    'Steve Ells founder stepped back',
    'Monty Moran former co-CEO',
    'Starbucks poached Niccol 2024 news',
    'hard',
    'Founders',
  ],
  [
    'Who founded Godiva? The Draps family in Brussels',
    'The Brussels Draps family chocolatiers',
    'Zurich Lindt founders different',
    'Turin Ferrero founders different',
    'Pennsylvania Hershey founders different',
    'hard',
    'Founders',
  ],
  [
    'Who founded Cadbury? John Cadbury Quaker tea merchant',
    'The Quaker tea and cocoa merchant',
    'Rowntree York rival Quaker too',
    'Fry oldest chocolate bar Quaker too',
    'Thorntons family chocolatier',
    'medium',
    'Founders',
  ],
  [
    'Who founded Rowntree? Henry Isaac Rowntree',
    'The York cocoa maker Quaker heritage',
    'Cadbury Birmingham rival',
    'Frys Bristol pioneer',
    'Thorntons Sheffield family',
    'hard',
    'Founders',
  ],
  [
    'Who makes KitKat? Nestle globally and Hershey in the US',
    'Nestle worldwide except US Hershey license',
    'Mars owns MMs different',
    'Mondelez Cadbury different',
    'Ferrero Rocher different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who owns KitKat in the United States? Hershey under license',
    'Hershey holds the US license',
    'Nestle owns US too false',
    'Mondelez owns false',
    'Ferrero owns false',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who owns Reese Pieces? Hershey owns the brand',
    'Hershey owns Reese',
    'Mars owns MMs different',
    'Mondelez different',
    'Ferrero different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who owns M&Ms? Mars owns the candy',
    'Mars owns M&Ms and Snickers',
    'Hershey owns Reese different',
    'Mondelez owns Cadbury different',
    'Ferrero owns Rocher different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who owns Cadbury now? Mondelez since Kraft 2010 deal',
    'Mondelez after the Kraft acquisition',
    'Nestle lost the bid drama',
    'Hershey also tried bidding',
    'Ferrero newer acquisitions separate',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who owns Panera? JAB holding era then private shifts',
    'JAB took Panera private',
    'Starbucks owned Panera false',
    'Yum owns KFC Taco Bell',
    'Restaurant Brands owns Burger King',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Restaurant Brands International? Burger King and Tim Hortons parent',
    'The BK Tim Hortons Popeyes parent',
    'Yum Brands KFC Pizza Hut Taco Bell',
    'McDonalds corporate',
    'Wendys corporate',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Yum Brands portfolio? KFC, Pizza Hut, and Taco Bell',
    'KFC Pizza Hut Taco Bell',
    'Burger King Popeyes Tim Hortons',
    'McDonalds Chipotle stakes sold',
    'Subway privately owned now Roark',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who bought Subway recently? Roark Capital agreed 2024',
    'Roark Capital the private equity buyer',
    'Yum Brands rumored earlier',
    'Restaurant Brands rumored earlier',
    'Inspire Brands Dunkin owner Arbys',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Inspire Brands?',
    'The Arbys Dunkin Sonic parent company',
    'Roark owned Inspire umbrella',
    'Yum rival portfolio',
    'Restaurant Brands rival portfolio',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Roark Capital? The private equity firm focused on franchises',
    'The franchise-focused PE firm',
    'A hedge fund activist',
    'A venture capital firm',
    'A sovereign fund',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is 3G Capital? The Brazilian firm behind Kraft Heinz and BK deals',
    'The Brazilian PE firm of 3G',
    'Roark franchise PE',
    'K KR PE then KKR',
    'Blackstone alternative giant',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who are the 3G Capital principals? Jorge Paulo Lemann, Marcel Telles, and Beto Sicupira',
    'Lemann, Telles, and Sicupira',
    'Henrique and Pedro brewers dynasty',
    'Abilio Diniz Brazilian retail',
    'Joseph Safra banker family',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which beer giant did 3G create? AB InBev',
    'AmBev InBev AB InBev empire',
    'Heineken independent Dutch rival',
    'Molson Coors merger different',
    'Carlsberg Danish group',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which ketchup giant did 3G merge with Kraft? Heinz and Kraft merger',
    'The Heinz Kraft 2015 merger',
    'Unilever hostile bid rejected',
    'Danone WhiteWave acquisition different',
    'General Mills Blue Buffalo purchase different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Abilio Diniz? The Brazilian retail giant of Grupo Pao de Acucar',
    'The Brazilian supermarket magnate',
    'The Brazilian beer king Lemann',
    'The Brazilian banker Safra',
    'The Brazilian tycoon Batista Eike',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Eike Batista? The Brazilian tycoon who lost his fortune',
    'The EBX oil tycoon boom bust',
    'The beer tycoon Lemann',
    'The banker Safra',
    'The retail magnate Diniz',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Joseph Safra? The Brazilian-Lebanese banker',
    'The Safra banking patriarch late',
    'Abilio Diniz retail',
    'Lemann beer',
    'Batista oil',
    'expert',
    'Celebrity Facts',
  ],
];

module.exports = { rows };
