'use strict';

const rows = [
  [
    'What is a consomme? A clarified rich soup',
    'Crystal-clear strained broth',
    'A cream soup',
    'A chilled soup',
    'A seafood stew',
    'hard',
    'Techniques',
  ],
  [
    'What clarifies consomme? Egg whites raft',
    'An egg white raft traps impurities',
    'Gelatin sheets',
    'Charcoal filter',
    'Cheesecloth only',
    'expert',
    'Techniques',
  ],
  [
    'What is a court bouillon? A quick aromatic poaching liquid',
    'Short-simmered vegetable poaching liquid',
    'A fish stock long simmered',
    'A brown beef stock',
    'A cold jelly aspic',
    'hard',
    'Techniques',
  ],
  [
    'What is aspic? A savory jelly from clarified stock',
    'Meat stock set in jelly',
    'A pate spread',
    'A terrine loaf',
    'A rillettes shred',
    'hard',
    'Techniques',
  ],
  [
    'What is a terrine? A pressed layered pate loaf',
    'A forced-meat loaf served sliced',
    'A sausage casing',
    'A wrapped roast',
    'A cured ham',
    'medium',
    'Techniques',
  ],
  [
    'What is pate? A seasoned ground meat spread',
    'A rich spreadable meat paste',
    'A whole cured ham',
    'A dried sausage',
    'A blood pudding',
    'medium',
    'Techniques',
  ],
  [
    'What is rillette? Meat slowly cooked and shredded in fat',
    'Pulled meat set in its fat',
    'A pate smooth puree',
    'A smoked sausage',
    'A dried ham slice',
    'hard',
    'Techniques',
  ],
  [
    'What is prosciutto? Dry-cured Italian ham',
    'The air-dried Italian ham',
    'Cooked ham sliced',
    'Smoked pork shoulder',
    'Fresh pork loin',
    'easy',
    'Ingredients',
  ],
  [
    'What is pancetta? Italian cured pork belly',
    'The Italian cured belly bacon',
    'Smoked American bacon',
    'Cured ham leg',
    'Pork loin cured',
    'medium',
    'Ingredients',
  ],
  [
    'What is guanciale? Cured pork jowl',
    'The cured cheek used in carbonara',
    'Pancetta belly',
    'Prosciutto leg',
    'Lard back fat rendered',
    'medium',
    'Ingredients',
  ],
  [
    'What is lardo? Cured pork back fat',
    'The herbed cured fatback delicacy',
    'Rendered lard jars',
    'Pancetta rolled',
    'Guanciale jowl',
    'hard',
    'Ingredients',
  ],
  [
    'What is Spanish chorizo? Cured paprika pork sausage',
    'The cured paprika sausage sliceable',
    'Fresh Mexican crumble sausage',
    'Blood sausage morcilla',
    'Longaniza thin style',
    'medium',
    'Ingredients',
  ],
  [
    'What is morcilla? Spanish blood sausage',
    'The Spanish blood sausage',
    'Chorizo paprika',
    'Longaniza thin',
    'Salchichon salami',
    'medium',
    'Ingredients',
  ],
  [
    'What is jamon iberico? Cured Iberian ham',
    'The prized acorn-fed Spanish ham',
    'Serrano white pig version',
    'Prosciutto Italian',
    'Parma same as prosciutto region',
    'medium',
    'Ingredients',
  ],
  [
    'What is prosciutto di parma? Parma cured ham',
    'The Parma-region cured ham',
    'San Daniele region',
    'Iberico Spain',
    'Serrano generic Spain',
    'hard',
    'Ingredients',
  ],
  [
    'What is bresaola? Cured air-dried beef',
    'The lean air-dried beef',
    'Pork prosciutto',
    'Lamb cured leg',
    'Goat cured',
    'medium',
    'Ingredients',
  ],
  [
    'What is pastirma? Cured spiced pressed beef',
    'The air-dried spiced beef',
    'Bresaola Italian',
    'Pastrami smoked',
    'Corned beef brined',
    'hard',
    'Ingredients',
  ],
  [
    'What is pastrami? Smoked cured spiced beef',
    'Brined smoked spiced beef',
    'Corned beef unsmoked',
    'Bresaola air-dried',
    'Salami fermented',
    'medium',
    'Ingredients',
  ],
  [
    'What is corned beef? Brine-cured beef brisket',
    'Salt-brine cured beef',
    'Pastrami smoked',
    'Roast beef',
    'Dried beef',
    'medium',
    'Ingredients',
  ],
  [
    'What is beef jerky? Dried marinated beef strips',
    'Low-moisture dried beef strips',
    'Biltong cousin',
    'Corned beef',
    'Salami',
    'easy',
    'Ingredients',
  ],
  [
    'What is biltong? South African air-dried meat',
    'The vinegar-spice air-dried meat',
    'American jerky',
    'Carne seca',
    'Landjager',
    'medium',
    'Ingredients',
  ],
  [
    'What is carne seca? Latin dried beef',
    'Salt-dried Latin beef',
    'Biltong',
    'Jerky marinade',
    'Cecina smoked',
    'hard',
    'Ingredients',
  ],
  [
    'What is cecina? Italian cured smoked beef',
    'The Tuscan smoked beef',
    'Bresaola specific',
    'Carpaccio raw',
    'Vitello tonnato',
    'hard',
    'Ingredients',
  ],
  [
    'What is vitello tonnato? Chilled veal with tuna sauce',
    'The Piedmont veal tuna dish',
    'Carpaccio raw',
    'Ossobuco',
    'Saltimbocca',
    'expert',
    'Ingredients',
  ],
  [
    'What is carpaccio? Thin raw beef appetizer',
    'The thinly sliced raw beef dish',
    'Tartare chopped',
    'Tonnato cooked',
    'Poke cubed',
    'medium',
    'Ingredients',
  ],
  [
    'What is steak tartare? Chopped raw beef dish',
    'The raw minced beef preparation',
    'Carpaccio sliced',
    'Poke fish',
    'Pilaf rice',
    'medium',
    'Ingredients',
  ],
  [
    'What is poke? Hawaiian cubed raw fish salad',
    'The Hawaiian raw fish bowl',
    'Ceviche citrus',
    'Tartare beef',
    'Sashimi slices',
    'easy',
    'Ingredients',
  ],
  [
    'What is ceviche curing agent? Lime juice acid',
    'Citrus acid denatures the fish',
    'Heat cooking',
    'Soy marinade',
    'Smoke',
    'medium',
    'Ingredients',
  ],
  [
    'What is kinilaw? The Filipino ceviche',
    'Filipino vinegar-cured fish',
    'Peruvian ceviche',
    'Hawaiian poke',
    'Thai larb',
    'hard',
    'Ingredients',
  ],
  [
    'What is larb? A Lao minced meat salad',
    'The toasted-rice herb meat salad',
    'Som tam salad',
    'Satay skewers',
    'Pad kra pao',
    'medium',
    'Ingredients',
  ],
  [
    'What is satay served with? Peanut sauce',
    'Peanut dipping sauce',
    'Tare glaze',
    'Tzatziki',
    'Chimichurri',
    'easy',
    'Ingredients',
  ],
  [
    'What is souvlaki? Greek meat skewers',
    'The Greek lemon-oregano skewers',
    'Gyros cone',
    'Satay',
    'Shawarma',
    'easy',
    'Ingredients',
  ],
  [
    'What is gyros cooked on? A vertical rotating spit',
    'A vertical broiler spit',
    'Charcoal grill',
    'Clay tandoor',
    'Flat top',
    'medium',
    'Ingredients',
  ],
  [
    'What is shawarma cooked on? A vertical spit',
    'The rotating vertical spit',
    'Skewers',
    'Tandoor wall',
    'Plancha',
    'medium',
    'Ingredients',
  ],
  [
    'What is doner kebab? Turkish rotating spit meat',
    'The Turkish vertical spit meat',
    'Shawarma cousin',
    'Gyros cousin',
    'Al pastor adapted',
    'medium',
    'Ingredients',
  ],
  [
    'What is al pastor adapted from? Lebanese shawarma technique',
    'The Lebanese spit technique',
    'Spanish roast',
    'Satay grill',
    'BBQ smoke',
    'hard',
    'Ingredients',
  ],
  [
    'What is tandoor cooking? Clay oven high heat',
    'A cylindrical clay oven',
    'Stone pizza oven',
    'Pit barbacoa',
    'Rotisserie',
    'medium',
    'Ingredients',
  ],
  [
    'What is barbacoa? Pit slow-cooked meat',
    'Meat wrapped and pit cooked',
    'Spit al pastor',
    'Tandoor',
    'Texas brisket',
    'medium',
    'Ingredients',
  ],
  [
    'What is cochinita pibil? Yucatan achiote pit pork',
    'The achiote banana-leaf pork',
    'Carnitas lard',
    'Barbacoa lamb',
    'Al pastor spit',
    'medium',
    'Ingredients',
  ],
  [
    'What are carnitas? Pork confit then crisped',
    'Lard-simmered crisped pork',
    'Pit lamb',
    'Spit pork',
    'Grilled beef',
    'medium',
    'Ingredients',
  ],
  [
    'What is carne asada? Grilled marinated beef',
    'Flame-grilled marinated beef',
    'Braised stew',
    'Fried rinds',
    'Stewed birria',
    'easy',
    'Ingredients',
  ],
  [
    'What is birria served with consomme? The Jalisco braised meat dip',
    'The braised meat with dipping broth',
    'Asada grilled',
    'Carnitas lard',
    'Al pastor spit',
    'medium',
    'Games',
  ],
  [
    'What is chicharron? Fried pork rinds',
    'Crispy fried pork skin',
    'Dried beef',
    'Grilled flank',
    'Cured ham',
    'easy',
    'Ingredients',
  ],
  [
    'What is machaca? Dried shredded beef dish',
    'The rehydrated dried beef',
    'Fried rinds',
    'Stewed birria',
    'Pit barbacoa',
    'hard',
    'Ingredients',
  ],
  [
    'What is pozole? A hominy stew',
    'The hominy soup with garnishes',
    'Tripe menudo',
    'Birria dip',
    'Tortilla soup',
    'medium',
    'Ingredients',
  ],
  [
    'What is menudo? A tripe soup with hominy',
    'The red tripe hominy soup',
    'Pozole pork',
    'Chicken caldo',
    'Tortilla soup',
    'medium',
    'Ingredients',
  ],
  [
    'What is sopa azteca? Tortilla soup',
    'The tortilla strips chile soup',
    'Menudo',
    'Tlalpeno',
    'Pozole',
    'medium',
    'Games',
  ],
  [
    'What is caldo tlalpeno? Chicken vegetable chile soup',
    'The chipotle chicken soup',
    'Tortilla soup',
    'Pozole',
    'Menudo',
    'hard',
    'Games',
  ],
  [
    'What is consomme? Clarified broth',
    'The perfectly clear broth',
    'Canned broth',
    'Cream soup',
    'Fruit soup',
    'medium',
    'Techniques',
  ],
  [
    'What is bouillabaisse? Provencal fish stew',
    'The Marseille seafood stew',
    'Cioppino SF',
    'Caldeirada',
    'Cacciucco',
    'medium',
    'Ingredients',
  ],
  [
    'What is rouille? Saffron chile mayo',
    'The red pepper garlic mayo',
    'Plain aioli',
    'Remoulade',
    'Gribiche',
    'hard',
    'Ingredients',
  ],
  [
    'What is cioppino? Italian-American fish stew',
    'The San Francisco fish stew',
    'Bouillabaisse',
    'Caldeirada',
    'Cacciucco',
    'medium',
    'Games',
  ],
  [
    'What is cacciucco? Livorno seafood stew',
    'The Tuscan seafood stew',
    'Cioppino',
    'Bouillabaisse',
    'Zuppa di pesce',
    'hard',
    'Games',
  ],
  [
    'What is zuppa inglese? Italian trifle dessert',
    'The layered custard dessert',
    'Tiramisu cousin',
    'Panforte',
    'Cannoli',
    'medium',
    'Games',
  ],
  [
    'What is granita? Semi-frozen ice dessert',
    'The scraped Sicilian ice',
    'Gelato churned',
    'Sorbet churned',
    'Semifreddo mousse',
    'medium',
    'Games',
  ],
  [
    'What is semifreddo? Semi-frozen dessert',
    'The frozen mousse-style dessert',
    'Granita ice',
    'Gelato',
    'Sorbet',
    'hard',
    'Games',
  ],
  [
    'What is gelato vs ice cream? Denser, less fat, served warmer',
    'Denser with less air and fat',
    'More cream always',
    'More air',
    'Always egg yolks',
    'medium',
    'Games',
  ],
  [
    'What is sorbet? Fruit and sugar frozen dessert',
    'A dairy-free fruit ice',
    'Milk gelato',
    'Custard frozen',
    'Yogurt frozen',
    'easy',
    'Games',
  ],
  [
    'What is sherbet? Sorbet with a little dairy',
    'Fruit ice with small dairy',
    'Full ice cream',
    'No dairy',
    'Frozen yogurt',
    'medium',
    'Games',
  ],
  [
    'What is frozen yogurt? Yogurt-based frozen dessert',
    'Cultured frozen dessert',
    'Swirl ice cream',
    'Sherbet',
    'Sorbet',
    'easy',
    'Games',
  ],
  [
    'What is a strainer chinois? A fine conical strainer',
    'The cone fine-mesh strainer',
    'A skimmer spider',
    'A colander',
    'A sifter',
    'hard',
    'Kitchen Tools',
  ],
  [
    'What is a tamis? A drum sieve for purees',
    'The flat drum sieve strainer',
    'A chinois cone',
    'A china cap blunt cone',
    'A spider skimmer',
    'expert',
    'Kitchen Tools',
  ],
  [
    'What is a china cap? A pointed conical strainer',
    'The blunt cone stock strainer',
    'A tamis drum',
    'A chinois fine cone',
    'A food mill rotating',
    'hard',
    'Kitchen Tools',
  ],
  [
    'What is a food mill? A crank strainer for purees',
    'The hand-crank puree strainer',
    'A blender jar',
    'A mortar',
    'A ricer only potatoes',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is an immersion blender? A stick blender',
    'The handheld blending wand',
    'A countertop blender',
    'A food processor bowl',
    'A stand mixer',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a food processor for? Chopping slicing and pureeing with blades',
    'The bowl appliance for prep work',
    'A stick blender',
    'A stand mixer with hooks',
    'A coffee grinder',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a stand mixer attachment for kneading? The dough hook',
    'The dough hook attachment',
    'The whisk attachment',
    'The paddle attachment',
    'The blender shaft',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is paddle attachment for? Creaming and mixing batters',
    'The flat beater for batters',
    'The dough hook',
    'The wire whip',
    'The meat grinder',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is whisk attachment for? Aerating creams and whites',
    'The balloon whip for air',
    'The paddle flat',
    'The hook dough',
    'The scraper paddle',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a fish slice UK term? A slotted spatula',
    'The British slotted turner',
    'A knife for fish',
    'A scaling tool',
    'A filleting blade',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a lemon zester microplane difference? Zester makes strips; microplane makes fine grate',
    'Strips versus fine shavings',
    'Same cut exactly',
    'One is for juice',
    'One is Japanese only',
    'hard',
    'Kitchen Tools',
  ],
  [
    'What is a mezzaluna? A curved double-handled chopper',
    'The half-moon rocking blade',
    'A cleaver rectangle',
    'A filleting knife',
    'A bread saw',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a butter curler? A tool making butter curls',
    'The decorative butter shaper',
    'A melon baller scoop',
    'A zester',
    'A peeler',
    'hard',
    'Kitchen Tools',
  ],
  [
    'What is a melon baller? A small sphere scoop',
    'The ball-shaped fruit scoop',
    'An ice cream scoop large',
    'A cookie scoop portion',
    'A zester',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a cookie scoop? A portioning trigger scoop',
    'The spring-loaded dough scoop',
    'A melon baller tiny',
    'A ladle large',
    'A measuring cup liquid',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a pastry bag tip set for? Different piping shapes',
    'Interchangeable piping nozzles',
    'Measuring spoons',
    'Cookie cutters',
    'Cake levelers',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a cake leveler? A wire to even cake tops',
    'The adjustable wire cake trimmer',
    'A serrated knife only',
    'A turntable',
    'A spatula',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a turntable for cake decorating? A rotating stand',
    'The spinning frosting stand',
    'A mixer attachment',
    'An oven tray',
    'A cooling rack',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a cooling rack for? Air circulation under bakes',
    'Elevating baked goods to cool',
    'Draining pasta',
    'Resting meat only',
    'Sifting flour',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is parchment paper for? Nonstick baking liner',
    'The nonstick oven liner',
    'Aluminum foil brand',
    'Wax paper oven safe wrong',
    'Silicone mat brand',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a silicone baking mat? A reusable nonstick liner',
    'The reusable oven-safe mat',
    'Parchment disposable',
    'Wax paper',
    'Foil paper',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a ramekin? A small individual baking dish',
    'The single-serve ceramic dish',
    'A large roasting pan',
    'A sheet tray',
    'A mixing bowl',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a cocotte? A small Dutch oven pot',
    'The individual covered casserole pot',
    'A ramekin tiny',
    'A skillet',
    'A sheet pan',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a sheet pan? A rimmed baking tray',
    'The rimmed oven tray',
    'A flat cookie sheet without rim old',
    'A roasting pan with handles high',
    'A loaf tin',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a loaf pan? A rectangular bread pan',
    'The rectangle bread tin',
    'A round cake tin',
    'A muffin tin wells',
    'A bundt ring',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a bundt pan? A ring-shaped fluted cake pan',
    'The fluted ring cake mold',
    'A loaf pan',
    'A muffin tin',
    'A springform latch pan',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a springform pan? A latch-side removable pan',
    'The detachable-base cheesecake pan',
    'A bundt ring',
    'A loaf tin',
    'A muffin tin',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a muffin tin? A multi-well baking pan',
    'The cupcake well pan',
    'A loaf tin',
    'A springform',
    'A sheet tray only',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a tart pan with removable bottom? A fluted tart ring pan',
    'The fluted loose-base tart pan',
    'A springform latch',
    'A bundt flutes',
    'A pie plate sloped',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a pie dish? A sloped-sided baking dish',
    'The classic sloped pie plate',
    'A straight tart ring',
    'A bundt mold',
    'A sheet tray',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a roasting pan? A large deep oven pan',
    'The big meat roasting tray',
    'A sheet pan thin',
    'A Dutch oven pot',
    'A skillet',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a broiler pan? A two-part pan for broiler drips',
    'The slotted broiler tray pair',
    'A roasting pan deep',
    'A sheet pan',
    'A grill grate outdoor',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a wok ladle spatula called? A chuan spatula',
    'The wok spatula chuan',
    'A hoak ladle',
    'A spider skimmer',
    'A strainer',
    'expert',
    'Kitchen Tools',
  ],
  [
    'What is a ladle hoak in wok cooking? The wok ladle',
    'The metal wok ladle',
    'The spatula chuan',
    'The skimmer spider',
    'The strainer mesh',
    'expert',
    'Kitchen Tools',
  ],
  [
    'What is a tea infuser? A perforated ball or basket for leaves',
    'The mesh holder for loose tea',
    'A kettle',
    'A press pot',
    'A strainer cup',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a french press vs infuser? Press plunges; infuser holds leaves',
    'One plunges, one cages the leaves',
    'Same tool',
    'One for coffee only ever',
    'One heats water',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a kettle gooseneck for? Controlled pour-over spouts',
    'The precision pour-over kettle',
    'Espresso steaming',
    'Boiling pasta',
    'Tea bags only',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a milk frother? A device aerating milk',
    'The foam-making tool',
    'A coffee grinder',
    'A kettle',
    'A scale',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a portafilter? The espresso handle basket',
    'The espresso machine handle basket',
    'A moka pot',
    'A kettle',
    'A frother',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a tamper? A tool pressing espresso grounds',
    'The espresso ground press',
    'A frother',
    'A grinder burr',
    'A scale',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a burr grinder? A grinder with crushing burrs',
    'The consistent coffee grinder type',
    'A blade chopper grinder',
    'A mortar',
    'A blender',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is blade grinder downside? Uneven coffee grounds',
    'Inconsistent particle sizes',
    'Too expensive',
    'Too slow',
    'Too quiet',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a kitchen torch for? Caramelizing and charring surfaces',
    'Browning sugar and tops with flame',
    'Lighting the stove',
    'Boiling water',
    'Grilling kebabs',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is creme brulee torched for? The caramel glass top',
    'Crisping the sugar lid',
    'Cooking the custard',
    'Toasting the dish',
    'Melting chocolate',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a mandoline guard used for? Protecting fingers',
    'The hand safety guard',
    'Blade storage',
    'Thickness dial',
    'Cleaning blade',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is cut resistant glove? A protective glove for slicing',
    'The safety glove for mandoline work',
    'An oven mitt',
    'A dish glove',
    'A grill glove',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is an oven mitt? A heat-resistant hand cover',
    'The heat glove for hot pans',
    'A cut glove',
    'A cleaning glove',
    'A serving glove',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is trivet? A hot pan rest',
    'The stand protecting tables from hot pots',
    'A pot lid holder',
    'A burner cover',
    'A pan scraper',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a splatter guard? A mesh screen over pans',
    'The oil-splatter shield screen',
    'A lid only solid',
    'A trivet',
    'A funnel',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a funnel used for? Transferring liquids cleanly',
    'Guiding liquids into containers',
    'Measuring dry goods',
    'Grating',
    'Whipping',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is a fat separator? A pitcher straining drippings fat',
    'The gravy jug separating fat',
    'A colander',
    'A scale',
    'A ladle',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a baster used for? Suctioning juices for basting',
    'Drawing up pan juices',
    'Injecting brine',
    'Spraying oil',
    'Skimming fat float',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is a turkey baster alternate use? Cheesecake water bath method sometimes',
    'Filling pans in water baths',
    'Lighting torches',
    'Cleaning blades',
    'Measuring spoons',
    'expert',
    'Kitchen Tools',
  ],
  [
    'What is a kitchen shears? Heavy-duty scissors',
    'The food-safe scissors',
    'A cleaver small',
    'A boning knife',
    'A peeler',
    'easy',
    'Kitchen Tools',
  ],
  [
    'What is shears used for poultry? Spatchcocking cutting backbone',
    'Snipping out the backbone',
    'Slicing breast meat',
    'Removing skin only',
    'Trussing with string',
    'medium',
    'Kitchen Tools',
  ],
  [
    'What is spatchcocking? Removing backbone to flatten bird',
    'Butterflying a whole bird flat',
    'Brining a bird',
    'Rotisserie skewering',
    'Deep frying whole',
    'medium',
    'Techniques',
  ],
  [
    'What is trussing? Tying a bird for even roasting',
    'Tying legs with string',
    'Stuffing the cavity',
    'Basting with butter',
    'Brining in salt water',
    'medium',
    'Techniques',
  ],
  [
    'What is brining? Soaking in salt solution for moisture',
    'Salt-water soaking for juicy meat',
    'Dry rubbing spices',
    'Smoking low slow',
    'Marinating acid only',
    'medium',
    'Techniques',
  ],
  [
    'What is a dry brine? Salting ahead without water',
    'Salt-only pre-salting',
    'Wet bucket soak',
    'Sugar glaze',
    'Vinegar splash',
    'medium',
    'Techniques',
  ],
  [
    'What is injection brining? Pumping brine deep into meat',
    'Syringing brine inside',
    'Surface salt only',
    'Vacuum tumbling',
    'Sprinkle curing',
    'hard',
    'Techniques',
  ],
  [
    'What is tumbling in meat processing? Vacuum massaging brined meat',
    'Rotary massaging meat with brine',
    'Dry aging air',
    'Freezing fast',
    'Grill marking',
    'expert',
    'Techniques',
  ],
];

module.exports = { rows };
