'use strict';

const rows = [
  [
    'What is the main ingredient in bread?',
    'Flour',
    'Sugar',
    'Butter',
    'Eggs',
    'easy',
    'Ingredients',
  ],
  [
    'What is pasta made from? Durum wheat semolina',
    'Durum wheat semolina',
    'Rice flour',
    'Corn flour',
    'Buckwheat',
    'medium',
    'Ingredients',
  ],
  [
    'What is soba made from? Buckwheat',
    'Buckwheat noodles',
    'Wheat noodles',
    'Rice noodles',
    'Egg noodles',
    'medium',
    'Ingredients',
  ],
  [
    'What is couscous cooked by? Steaming over liquid',
    'Steaming over simmering liquid',
    'Boiling like pasta',
    'Baking dry',
    'Frying',
    'medium',
    'Ingredients',
  ],
  [
    'What is sushi rice seasoned with? Rice vinegar, sugar, and salt',
    'Vinegar, sugar, and salt',
    'Soy sauce',
    'Mirin only',
    'Sesame oil',
    'medium',
    'Ingredients',
  ],
  [
    'What is nori made from? Seaweed sheets',
    'Dried seaweed sheets',
    'Rice paper',
    'Soy paper',
    'Kelp powder pressed',
    'easy',
    'Ingredients',
  ],
  [
    'What is tofu pressed from? Soybean curd',
    'Coagulated soy milk',
    'Chickpea flour',
    'Wheat gluten',
    'Pea protein',
    'easy',
    'Ingredients',
  ],
  [
    'What is edamame? Young soybeans',
    'Immature soybeans in pods',
    'Dried soybeans',
    'Soy sprouts',
    'Fermented soybeans',
    'easy',
    'Ingredients',
  ],
  [
    'What is hummus garnished classically with? Olive oil and paprika',
    'Olive oil and paprika swirl',
    'Sesame seeds only',
    'Zaatar always',
    'Parmesan',
    'medium',
    'Ingredients',
  ],
  [
    'What is falafel usually served in? Pita bread',
    'Pita or flatbread',
    'Tortilla',
    'Brioche bun',
    'Rice paper',
    'easy',
    'Ingredients',
  ],
  [
    'What is pita known for? Puffing into a pocket',
    'Creating a pocket when baked',
    'Being fried',
    'Being boiled',
    'Being steamed',
    'medium',
    'Ingredients',
  ],
  [
    'What is focaccia dimpled with? Fingers before baking',
    'Finger dents holding oil',
    'A rolling pin',
    'Fork pricks',
    'Knife scoring',
    'medium',
    'Ingredients',
  ],
  [
    'What is baguette shaped like? A long thin loaf',
    'A long thin stick loaf',
    'A round boule',
    'An oval batard',
    'A small roll',
    'easy',
    'Ingredients',
  ],
  [
    'What is a boule? A round loaf',
    'A round rustic loaf shape',
    'A baguette stick',
    'A braided challah',
    'A flatbread',
    'medium',
    'Ingredients',
  ],
  [
    'What is brioche rich with? Eggs and butter',
    'Egg and butter enrichment',
    'Olive oil',
    'Lard',
    'Cream cheese',
    'medium',
    'Ingredients',
  ],
  [
    'What is sourdough leavened by? Wild yeast culture',
    'A wild yeast starter',
    'Commercial yeast only',
    'Baking powder',
    'Soda and buttermilk',
    'easy',
    'Ingredients',
  ],
  [
    'What is rye bread flavor from? Rye flour and sometimes caraway',
    'Rye flour often with caraway seeds',
    'Wheat only',
    'Oats',
    'Barley malt only',
    'medium',
    'Ingredients',
  ],
  [
    'What is pumpernickel? A dark dense rye bread',
    'A dark coarse rye loaf',
    'A light wheat bread',
    'A sour white loaf',
    'A sweet brioche',
    'medium',
    'Ingredients',
  ],
  [
    'What is ciabatta known for? Its slipper shape and open crumb',
    'A slipper-shaped airy loaf',
    'A baguette stick',
    'A round boule',
    'A flat focaccia',
    'medium',
    'Games',
  ],
  [
    'What is bruschetta? Grilled bread with toppings',
    'Toasted bread rubbed with garlic topped',
    'A soup with bread',
    'A bread pudding',
    'A fried dough',
    'easy',
    'Ingredients',
  ],
  [
    'What is crostini? Small toasted bread slices',
    'Little crisp toasts for toppings',
    'A garlic bread loaf',
    'Bread soup',
    'Croutons in salad',
    'medium',
    'Ingredients',
  ],
  [
    'What are croutons? Cubed toasted bread',
    'Small seasoned bread cubes',
    'Bread pudding cubes',
    'Raw dough bits',
    'Pasta shapes',
    'easy',
    'Ingredients',
  ],
  [
    'What is a crouton alternative in Caesar? Skip real: What dressing does Caesar salad use? Caesar dressing with anchovy',
    'A creamy anchovy garlic dressing',
    'Thousand island',
    'Ranch dressing',
    'Vinaigrette only',
    'medium',
    'Ingredients',
  ],
  [
    'What is ranch dressing base? Buttermilk and herbs',
    'Buttermilk mayo herb base',
    'Tomato ketchup base',
    'Yogurt mint',
    'Vinegar oil',
    'medium',
    'Ingredients',
  ],
  [
    'What is thousand island made with? Mayo, ketchup, and relish',
    'Mayo ketchup relish blend',
    'Buttermilk herbs',
    'Oil vinegar',
    'Yogurt cucumber',
    'medium',
    'Ingredients',
  ],
  [
    'What is vinaigrette ratio classic? Three parts oil to one vinegar',
    'Three to one oil to vinegar',
    'One to one',
    'One to three',
    'All oil',
    'medium',
    'Ingredients',
  ],
  [
    'What is emulsifier in vinaigrette? Mustard commonly',
    'Mustard or honey as stabilizer',
    'Salt',
    'Sugar only',
    'Pepper',
    'medium',
    'Ingredients',
  ],
  [
    'What is mayonnaise emulsified by? Egg yolk lecithin',
    'Yolk lecithin stabilizing oil',
    'Mustard seeds',
    'Vinegar acid',
    'Gelatin',
    'medium',
    'Ingredients',
  ],
  [
    'What is hollandaise emulsified by? Egg yolks',
    'Yolk lecithin warm emulsion',
    'Cream',
    'Flour',
    'Gelatin',
    'medium',
    'Ingredients',
  ],
  [
    'What is aioli? A garlic emulsion sauce',
    'Garlic olive oil emulsion',
    'Egg yolk mayo only',
    'Herb yogurt',
    'Chile oil',
    'medium',
    'Ingredients',
  ],
  [
    'What is pesto made with? Basil, pine nuts, garlic, cheese, and oil',
    'Basil pine nuts garlic parmesan oil',
    'Parsley walnuts',
    'Cilantro peanuts',
    'Sun-dried tomatoes',
    'easy',
    'Ingredients',
  ],
  [
    'What is romesco nut? Almonds and hazelnuts',
    'Almonds and hazelnuts',
    'Pine nuts',
    'Peanuts',
    'Cashews',
    'medium',
    'Ingredients',
  ],
  [
    'What is chimichurri herb base? Parsley and oregano',
    'Fresh parsley and oregano',
    'Basil',
    'Cilantro',
    'Mint',
    'medium',
    'Ingredients',
  ],
  [
    'What is gremolata? Lemon zest parsley garlic',
    'Zesty lemon parsley garlic topping',
    'Basil oil drizzle',
    'Sage butter',
    'Chili crisp',
    'hard',
    'Ingredients',
  ],
  [
    'What is salsa verde Italian herb base? Parsley capers anchovy',
    'Parsley capers anchovy vinaigrette',
    'Tomatillo verde Mexican',
    'Basil pesto',
    'Mint yogurt',
    'hard',
    'Ingredients',
  ],
  [
    'What is gremolata served with? Osso buco traditionally',
    'Osso buco veal shank',
    'Pizza',
    'Sushi',
    'Tacos',
    'medium',
    'Ingredients',
  ],
  [
    'What is osso buco? Braised veal shank',
    'Cross-cut braised veal shanks',
    'Pork shoulder braise',
    'Lamb rack roast',
    'Beef ribeye grill',
    'medium',
    'Ingredients',
  ],
  [
    'What is carbonara cheese? Pecorino romano',
    'Pecorino romano sheep cheese',
    'Parmesan only by tradition debate',
    'Mozzarella',
    'Gorgonzola',
    'medium',
    'Ingredients',
  ],
  [
    'What is cacio e pepe? Pecorino and black pepper pasta',
    'Cheese and pepper pasta',
    'Tomato basil pasta',
    'Butter sage pasta',
    'Carbonara with eggs',
    'easy',
    'Ingredients',
  ],
  [
    'What is aglio e olio? Garlic and oil pasta',
    'Garlic olive oil pasta',
    'Butter sage pasta',
    'Tomato pasta',
    'Cream pasta',
    'easy',
    'Games',
  ],
  [
    'What is pasta water used for? Emulsifying sauces',
    'Starchy water binding sauces',
    'Watering plants only',
    'Boiling eggs',
    'Cleaning pans',
    'medium',
    'Ingredients',
  ],
  [
    'What is a roux ratio for mac cheese base? Butter flour then milk',
    'Cooked butter-flour then milk',
    'Eggs then cheese',
    'Cream only',
    'Yogurt base',
    'medium',
    'Ingredients',
  ],
  [
    'What cheese melt is classic for mac? Cheddar',
    'Cheddar',
    'Feta',
    'Halloumi',
    'Parmesan alone',
    'easy',
    'Ingredients',
  ],
  [
    'What is quesadilla folded with? Tortilla and melted cheese',
    'A tortilla filled with melting cheese',
    'Pita pocket',
    'Brioche bun',
    'Rice paper',
    'easy',
    'Ingredients',
  ],
  [
    'What is an enchilada? Rolled tortillas in sauce baked',
    'Sauce-covered rolled tortillas baked',
    'Fried tortilla chips',
    'Folded taco eaten fresh',
    'Stacked casserole casserole style',
    'medium',
    'Ingredients',
  ],
  [
    'What is a chimichanga? A deep-fried burrito',
    'A fried burrito',
    'A soft taco',
    'A tostada flat fried tortilla',
    'An enchilada baked',
    'medium',
    'Ingredients',
  ],
  [
    'What is a tostada? A flat fried tortilla with toppings',
    'A crispy flat tortilla base',
    'A rolled enchilada',
    'A folded taco',
    'A steamed tamale',
    'medium',
    'Ingredients',
  ],
  [
    'What is guajillo chile? A mild dried Mexican chile',
    'A smooth mild dried chile',
    'The hottest chile pepper',
    'A fresh green chile',
    'A smoked chipotle dried jalapeno actually',
    'medium',
    'Ingredients',
  ],
  [
    'What is chipotle? A smoked dried jalapeno',
    'Smoked dried jalapeno',
    'Fresh green jalapeno',
    'Poblano fresh',
    'Habanero fresh',
    'medium',
    'Ingredients',
  ],
  [
    'What is a poblano when dried called? An ancho chile',
    'Ancho when dried',
    'Chipotle when dried',
    'Guajillo when dried',
    'Pasilla fresh name confusion',
    'hard',
    'Ingredients',
  ],
  [
    'What is a habanero heat level? Very hot',
    'Extremely hot pepper',
    'Mild pepper',
    'Bell pepper level',
    'Jalapeno level',
    'medium',
    'Ingredients',
  ],
  [
    'What is the hottest chili pepper as of recent lists? Pepper X recently overtook Carolina Reaper',
    'Pepper X newest champion',
    'Carolina Reaper prior record',
    'Ghost pepper older record',
    'Trinidad Scorpion earlier',
    'expert',
    'Ingredients',
  ],
  [
    'What is capsaicin? The heat compound in chiles',
    'The spicy compound in peppers',
    'A sweetener',
    'A vitamin',
    'An acid',
    'medium',
    'Ingredients',
  ],
  [
    'What cools capsaicin heat best? Dairy like milk',
    'Milk casein binds the heat',
    'Water spreading it',
    'Soda always',
    'Beer neutralizing claim',
    'medium',
    'Ingredients',
  ],
  [
    'What is wasabi heat different from chili? It hits the nose and fades fast',
    'A nose-tingling vapor that fades',
    'Long mouth burn',
    'Sweet heat',
    'No sensation',
    'medium',
    'Ingredients',
  ],
  [
    'What is piperine? The heat compound in black pepper',
    'Peppers pungent compound piperine',
    'Capsaicin chili compound',
    'Gingerol ginger compound',
    'Allicin garlic compound',
    'hard',
    'Ingredients',
  ],
  [
    'What is allicin? The compound from crushed garlic',
    'Garlics pungent sulfur compound',
    'Chili capsaicin',
    'Onion sugar',
    'Gingerol',
    'hard',
    'Ingredients',
  ],
  [
    'What is gingerol? The pungent compound in ginger',
    'Gingers spicy aromatic compound',
    'Garlic allicin',
    'Pepper piperine',
    'Cinnamon cinnamaldehyde',
    'hard',
    'Ingredients',
  ],
  [
    'What is cinnamaldehyde? Cinnamons flavor compound',
    'The compound flavoring cinnamon',
    'Gingerol',
    'Piperine',
    'Allicin',
    'hard',
    'Ingredients',
  ],
  [
    'What is citral? The lemon aroma compound',
    'The lemony compound in lemongrass',
    'Limonene orange peel oil',
    'Capsaicin',
    'Allicin',
    'hard',
    'Ingredients',
  ],
  [
    'What is limonene? Citrus peel aroma compound',
    'The compound in citrus peels',
    'Citric acid sourness',
    'Vitamin C nutrient',
    'Malic acid in apples',
    'hard',
    'Ingredients',
  ],
  [
    'What is malic acid? The acid in apples',
    'The main apple acid',
    'Citric acid citrus',
    'Tartaric acid grapes',
    'Lactic acid dairy',
    'medium',
    'Ingredients',
  ],
  [
    'What is citric acid dominant in? Lemons and limes',
    'Citrus fruits sourness',
    'Apples',
    'Grapes',
    'Dairy',
    'easy',
    'Ingredients',
  ],
  [
    'What is lactic acid from? Fermentation by bacteria',
    'Bacterial fermentation of sugars',
    'Citrus pressing',
    'Roasting coffee',
    'Caramelizing sugar',
    'medium',
    'Ingredients',
  ],
  [
    'What is acetic acid from? Fermenting ethanol into vinegar',
    'Bacterial conversion of alcohol to vinegar',
    'Citrus fermentation',
    'Milk fermentation to cheese',
    'Meat aging dry',
    'medium',
    'Ingredients',
  ],
  [
    'What is dry aging beef? Aging in controlled air for flavor',
    'Hanging beef to concentrate flavor',
    'Wet aging in vacuum bags different',
    'Curing with salt',
    'Smoking over wood',
    'medium',
    'Ingredients',
  ],
  [
    'What is wet aging? Vacuum-sealed refrigerated aging',
    'Aging beef in sealed bags',
    'Open-air hanging',
    'Salt curing',
    'Cold smoking',
    'medium',
    'Games',
  ],
  [
    'What is curing meat? Preserving with salt often nitrites',
    'Salt preserving meat safely',
    'Freezing meat',
    'Boiling in brine only',
    'Coating in flour',
    'medium',
    'Ingredients',
  ],
  [
    'What do nitrites do in cured meat? Prevent botulism and fix color',
    'Guard against botulism and keep pink',
    'Add sweetness',
    'Tenderize fibers',
    'Speed cooking',
    'hard',
    'Ingredients',
  ],
  [
    'What is botulism risk from? Anaerobic bacteria toxins',
    'Clostridium toxin in low-oxygen foods',
    'Surface mold on cheese rind only',
    'Undercooked rice only',
    'Raw honey in adults',
    'hard',
    'Ingredients',
  ],
  [
    'What temperature kills most bacteria in food? 165 F for poultry guidance',
    'Poultry safe at 165 degrees F',
    '120 F',
    '100 F',
    '212 F required for all foods',
    'medium',
    'Nutrition',
  ],
  [
    'What is the danger zone temperature range? 40 to 140 F for food safety',
    'Between 40 and 140 degrees F',
    'Below freezing',
    'Above boiling',
    '0 to 32 F',
    'medium',
    'Nutrition',
  ],
  [
    'How long can food sit in the danger zone guidance? No more than two hours',
    'Two hours maximum guideline',
    'Six hours',
    'One full day',
    'Ten minutes only',
    'hard',
    'Nutrition',
  ],
  [
    'What is cross-contamination? Transferring germs between foods',
    'Bacteria spreading between items',
    'Mixing flavors intentionally',
    'Sharing recipes',
    'Marinating two meats together',
    'easy',
    'Nutrition',
  ],
  [
    'What is pasteurization? Heat treating to kill pathogens',
    'Heating liquids to make them safe',
    'Freezing sterilization',
    'Irradiation only',
    'Adding preservatives',
    'easy',
    'Nutrition',
  ],
  [
    'Who is pasteurization named after? Louis Pasteur',
    'Louis Pasteur the scientist',
    'Robert Koch',
    'Alexander Fleming',
    'Joseph Lister',
    'easy',
    'Nutrition',
  ],
  [
    'What is UHT milk? Ultra heat treated shelf-stable milk',
    'Ultra-pasteurized long-life milk',
    'Unpasteurized raw milk',
    'Ultra filtered water milk',
    'Evaporated canned milk',
    'medium',
    'Nutrition',
  ],
  [
    'What is evaporated milk? Milk with about 60 percent water removed',
    'Concentrated unsweetened milk',
    'Sweetened condensed milk different',
    'Powdered milk',
    'Buttermilk',
    'medium',
    'Nutrition',
  ],
  [
    'What is condensed milk? Sweetened thickened milk',
    'Sugar-sweetened reduced milk',
    'Unsweetened evaporated milk',
    'Powdered milk',
    'Cream reduced',
    'medium',
    'Ingredients',
  ],
  [
    'What is buttermilk today? Cultured low-fat milk product',
    'Tangy cultured milk for baking',
    'Butter churn leftover only traditionally',
    'Melted butter plus milk',
    'Heavy cream soured',
    'medium',
    'Ingredients',
  ],
  [
    'What is clarified butter milk solid free? Ghee is that',
    'Ghee is the clarified form',
    'Brown butter with solids',
    'Beurre noisette same as brown',
    'Whipped butter airy',
    'medium',
    'Ingredients',
  ],
  [
    'What is a roux color stages? White, blonde, and brown',
    'White, blond, and brown stages',
    'Pale, gold, dark only for gumbo',
    'Only one color',
    'Green tint possible',
    'medium',
    'Techniques',
  ],
  [
    'What is gumbo roux traditionally? Dark chocolate-brown roux',
    'A very dark brown roux',
    'White roux cream sauces',
    'Blond roux light',
    'No roux okra only',
    'medium',
    'Ingredients',
  ],
  [
    'What is file powder used in? Gumbo thickening with sassafras',
    'Sassafras leaf powder for gumbo',
    'Cajun spice rub only',
    'Jambalaya rice seasoning',
    'Beignet sugar dusting',
    'hard',
    'Ingredients',
  ],
  [
    'What is jambalaya? A Louisiana rice dish',
    'Rice cooked with meats and spices',
    'A stew over rice served separately',
    'A fried rice Chinese dish',
    'A bean stew only',
    'easy',
    'Ingredients',
  ],
  [
    'What is etouffee? A smothered seafood rice dish',
    'Shellfish smothered in roux sauce over rice',
    'A gumbo soup thinner',
    'A jambalaya baked',
    'A po-boy sandwich',
    'medium',
    'Games',
  ],
  [
    'What is a po-boy? A Louisiana sandwich loaf',
    'A dressed sub-style sandwich',
    'A rice bowl',
    'A fried pie',
    'A beignet sandwich sweet',
    'medium',
    'Ingredients',
  ],
  [
    'What are beignets dusted with? Powdered sugar',
    'Powdered sugar piles',
    'Cinnamon sugar only',
    'Cocoa powder',
    'Glaze icing',
    'easy',
    'Ingredients',
  ],
  [
    'What is king cake season? Mardi Gras',
    'The Mardi Gras season treat',
    'Christmas only',
    'Easter only',
    'Thanksgiving only',
    'medium',
    'Ingredients',
  ],
  [
    'What is hidden inside king cake? A small plastic baby figure',
    'A tiny baby figurine',
    'A coin',
    'A bean only',
    'A ring',
    'medium',
    'Ingredients',
  ],
  [
    'What is a galette des rois? An Epiphany kings cake in France',
    'The French puff pastry kings cake',
    'A Mardi Gras colored braid',
    'A German stollen fruit loaf',
    'An Italian panettone tall loaf',
    'hard',
    'Ingredients',
  ],
  [
    'What is stollen? A German Christmas fruit bread',
    'The German holiday fruit loaf',
    'A French kings cake puff',
    'An Italian panettone tall',
    'A Spanish rocon reyes ring',
    'medium',
    'Ingredients',
  ],
  [
    'What is panettone? An Italian tall Christmas bread',
    'The Milanese holiday dome loaf',
    'A German stollen flat',
    'A French brioche plain',
    'A Greek tsoureki braided',
    'easy',
    'Ingredients',
  ],
  [
    'What is rocon de reyes? The Spanish kings ring cake',
    'The Spanish Epiphany ring cake',
    'Italian panettone cousin',
    'German stollen',
    'Portuguese bolo rei similar',
    'hard',
    'Ingredients',
  ],
  [
    'What is bolo rei? The Portuguese kings cake',
    'The Portuguese Christmas ring cake',
    'Spanish ring same',
    'French galette',
    'Italian pandoro star shaped different',
    'expert',
    'Ingredients',
  ],
  [
    'What is pandoro? The star-shaped Italian Christmas cake',
    'The Verona star-shaped holiday cake',
    'Milan panettone raisin version',
    'German stollen',
    'Portuguese bolo rei',
    'hard',
    'Ingredients',
  ],
  [
    'What is panforte? A dense Sienese fruit nut cake',
    'The chewy Sienese fruit-nut round',
    'Tiramisu coffee dessert',
    'Cannoli fried tubes',
    'Gelato frozen churn',
    'hard',
    'Ingredients',
  ],
  [
    'What is cannoli shell fried? A fried pastry tube filled with ricotta',
    'The fried tube with sweet ricotta',
    'A choux eclair baked',
    'A sfogliatella layered shell',
    'A zeppole fried puff',
    'medium',
    'Games',
  ],
  [
    'What is sfogliatella? A layered shell pastry from Naples',
    'The Naples clam-shell flaky pastry',
    'Cannoli tube Sicily',
    'Zeppole round fried',
    'Baba rum soaked',
    'hard',
    'Games',
  ],
  [
    'What is a rum baba? A yeast cake soaked in rum syrup',
    'The rum-soaked yeast dessert',
    'A tiramisu rum layer',
    'A zuppa inglese trifle',
    'A marsala zabaglione sauce',
    'medium',
    'Games',
  ],
  [
    'What is zabaglione? A whipped egg and Marsala custard',
    'The airy Marsala egg custard',
    'Lemon curd tart filling',
    'Pastry cream thick',
    'Ganache glossy',
    'hard',
    'Games',
  ],
  [
    'What is marsala? A fortified Sicilian wine',
    'The Sicilian fortified wine',
    'Port from Portugal',
    'Sherry from Spain',
    'Madeira from Madeira island',
    'medium',
    'Ingredients',
  ],
  [
    'What is sherry? A fortified wine from Spain Jerez',
    'The fortified wine of Jerez Spain',
    'Port Portugal',
    'Marsala Sicily',
    'Madeira island wine',
    'medium',
    'Ingredients',
  ],
  [
    'What is port fortified during fermentation? A sweet Portuguese fortified wine',
    'The Portuguese sweet fortified wine',
    'Sherry dry often',
    'Marsala cooking classic',
    'Vermouth aromatized',
    'medium',
    'Ingredients',
  ],
  [
    'What is vermouth? An aromatized fortified wine',
    'The herb-infused fortified wine for cocktails',
    'Port style sweet',
    'Sherry style',
    'Prosecco sparkling',
    'medium',
    'Ingredients',
  ],
  [
    'What is prosecco? An Italian sparkling wine',
    'The Italian sparkling wine from Veneto',
    'Champagne French region only',
    'Cava Spanish sparkling',
    'Asti sweet sparkling different DOCG',
    'medium',
    'Ingredients',
  ],
  [
    'What is Champagne? Sparkling wine from Champagne France only',
    'The French region sparkling wine proper',
    'Any sparkling wine',
    'Italian prosecco',
    'Spanish cava',
    'easy',
    'Ingredients',
  ],
  [
    'What is cava? Spanish sparkling wine',
    'The Spanish sparkling wine',
    'Italian prosecco',
    'French champagne',
    'German sekt',
    'easy',
    'Ingredients',
  ],
  [
    'What is sekt? German sparkling wine',
    'The German sparkling wine',
    'Italian prosecco',
    'Spanish cava',
    'French champagne',
    'hard',
    'Ingredients',
  ],
  [
    'What is sake made from? Fermented rice',
    'Brewed rice with koji mold',
    'Barley malt',
    'Wheat',
    'Grapes',
    'medium',
    'Ingredients',
  ],
  [
    'What is soju? A Korean distilled spirit',
    'The Korean distilled spirit',
    'Japanese sake brewed',
    'Chinese baijiu strong aroma',
    'Thai rum cane',
    'medium',
    'Ingredients',
  ],
  [
    'What is baijiu? A Chinese distilled grain spirit',
    'The potent Chinese grain spirit',
    'Korean soju lighter',
    'Japanese shochu distilled',
    'Vietnamese rice wine',
    'medium',
    'Ingredients',
  ],
  [
    'What is shochu? A Japanese distilled spirit',
    'The Japanese distilled liquor',
    'Sake brewed rice wine',
    'Korean soju cousin',
    'Awamori Okinawan long grain',
    'medium',
    'Ingredients',
  ],
  [
    'What is awamori? The Okinawan distilled rice spirit',
    'The Okinawan indigenous spirit',
    'Mainland shochu standard',
    'Sake premium class',
    'Umeshu plum liqueur different',
    'expert',
    'Ingredients',
  ],
  [
    'What is umeshu? A Japanese plum liqueur',
    'The sweet ume plum liqueur',
    'Shochu base spirit dry',
    'Sake rice wine',
    'Yuzu citrus liqueur',
    'medium',
    'Ingredients',
  ],
  [
    'What is raki? The Turkish anise spirit',
    'The Turkish anise-flavored spirit',
    'Greek ouzo cousin similar',
    'Arak Middle East anise',
    'Mastika resin spirit',
    'medium',
    'Ingredients',
  ],
  [
    'What is arak? The Levantine anise spirit',
    'The Middle Eastern anise spirit',
    'Turkish raki same style different country',
    'Greek ouzo similar',
    'Italian sambuca sweet',
    'medium',
    'Ingredients',
  ],
  [
    'What is mastika? A resin-flavored spirit',
    'The mastic resin liqueur',
    'Anise ouzo style',
    'Herb chartreuse blend',
    'Honey mead ferment',
    'expert',
    'Ingredients',
  ],
  [
    'What is mead? A fermented honey drink',
    'Wine made from honey',
    'Barley beer',
    'Apple cider',
    'Rice wine',
    'easy',
    'Ingredients',
  ],
  [
    'What is cider fermented from? Apples',
    'Fermented apple juice',
    'Pears perry different',
    'Grapes wine',
    'Honey mead',
    'easy',
    'Ingredients',
  ],
  [
    'What is perry? A fermented pear drink',
    'Pear-based cider cousin',
    'Apple cider standard',
    'Berry wine',
    'Ginger beer plant ferment',
    'medium',
    'Ingredients',
  ],
  [
    'What is ginger beer? A fermented ginger drink',
    'Traditionally fermented ginger brew',
    'Ginger ale carbonated soft drink milder',
    'Root beer sassafras drink',
    'Kombucha tea ferment',
    'medium',
    'Ingredients',
  ],
  [
    'What is root beer flavor historically from? Sassafras roots',
    'Sassafras root flavoring',
    'Ginger root',
    'Licorice root only',
    'Birch bark only',
    'hard',
    'Ingredients',
  ],
  [
    'What is birch beer? A birch-flavored soda',
    'A soda from birch sap flavors',
    'Root beer sassafras',
    'Ginger ale',
    'Cream soda vanilla',
    'expert',
    'Ingredients',
  ],
  [
    'What is cream soda flavor? Vanilla-flavored soda',
    'A vanilla soft drink',
    'Butterscotch candy flavor',
    'Caramel cola',
    'Malt shake',
    'medium',
    'Ingredients',
  ],
];

module.exports = { rows };
