'use strict';

const { distractors } = require('../lib');

// [country, capital, currency, continent]
const COUNTRIES = [
  ['France', 'Paris', 'Euro', 'Europe'],
  ['Germany', 'Berlin', 'Euro', 'Europe'],
  ['Italy', 'Rome', 'Euro', 'Europe'],
  ['Spain', 'Madrid', 'Euro', 'Europe'],
  ['Portugal', 'Lisbon', 'Euro', 'Europe'],
  ['Netherlands', 'Amsterdam', 'Euro', 'Europe'],
  ['Belgium', 'Brussels', 'Euro', 'Europe'],
  ['Switzerland', 'Bern', 'Swiss Franc', 'Europe'],
  ['Austria', 'Vienna', 'Euro', 'Europe'],
  ['Greece', 'Athens', 'Euro', 'Europe'],
  ['Sweden', 'Stockholm', 'Swedish Krona', 'Europe'],
  ['Norway', 'Oslo', 'Norwegian Krone', 'Europe'],
  ['Denmark', 'Copenhagen', 'Danish Krone', 'Europe'],
  ['Finland', 'Helsinki', 'Euro', 'Europe'],
  ['Iceland', 'Reykjavik', 'Icelandic Krona', 'Europe'],
  ['Ireland', 'Dublin', 'Euro', 'Europe'],
  ['United Kingdom', 'London', 'Pound Sterling', 'Europe'],
  ['Poland', 'Warsaw', 'Zloty', 'Europe'],
  ['Czech Republic', 'Prague', 'Czech Koruna', 'Europe'],
  ['Hungary', 'Budapest', 'Forint', 'Europe'],
  ['Romania', 'Bucharest', 'Romanian Leu', 'Europe'],
  ['Bulgaria', 'Sofia', 'Lev', 'Europe'],
  ['Ukraine', 'Kyiv', 'Hryvnia', 'Europe'],
  ['Russia', 'Moscow', 'Ruble', 'Europe'],
  ['Serbia', 'Belgrade', 'Serbian Dinar', 'Europe'],
  ['Croatia', 'Zagreb', 'Euro', 'Europe'],
  ['Slovakia', 'Bratislava', 'Euro', 'Europe'],
  ['Slovenia', 'Ljubljana', 'Euro', 'Europe'],
  ['Estonia', 'Tallinn', 'Euro', 'Europe'],
  ['Latvia', 'Riga', 'Euro', 'Europe'],
  ['Lithuania', 'Vilnius', 'Euro', 'Europe'],
  ['Albania', 'Tirana', 'Lek', 'Europe'],
  ['North Macedonia', 'Skopje', 'Denar', 'Europe'],
  ['Bosnia and Herzegovina', 'Sarajevo', 'Convertible Mark', 'Europe'],
  ['Montenegro', 'Podgorica', 'Euro', 'Europe'],
  ['Malta', 'Valletta', 'Euro', 'Europe'],
  ['Cyprus', 'Nicosia', 'Euro', 'Europe'],
  ['Luxembourg', 'Luxembourg City', 'Euro', 'Europe'],
  ['Belarus', 'Minsk', 'Belarusian Ruble', 'Europe'],
  ['Moldova', 'Chisinau', 'Moldovan Leu', 'Europe'],
  ['Japan', 'Tokyo', 'Yen', 'Asia'],
  ['China', 'Beijing', 'Renminbi', 'Asia'],
  ['South Korea', 'Seoul', 'South Korean Won', 'Asia'],
  ['North Korea', 'Pyongyang', 'North Korean Won', 'Asia'],
  ['India', 'New Delhi', 'Indian Rupee', 'Asia'],
  ['Pakistan', 'Islamabad', 'Pakistani Rupee', 'Asia'],
  ['Bangladesh', 'Dhaka', 'Taka', 'Asia'],
  ['Sri Lanka', 'Colombo', 'Sri Lankan Rupee', 'Asia'],
  ['Nepal', 'Kathmandu', 'Nepalese Rupee', 'Asia'],
  ['Bhutan', 'Thimphu', 'Ngultrum', 'Asia'],
  ['Thailand', 'Bangkok', 'Baht', 'Asia'],
  ['Vietnam', 'Hanoi', 'Dong', 'Asia'],
  ['Cambodia', 'Phnom Penh', 'Riel', 'Asia'],
  ['Laos', 'Vientiane', 'Kip', 'Asia'],
  ['Myanmar', 'Naypyidaw', 'Kyat', 'Asia'],
  ['Malaysia', 'Kuala Lumpur', 'Ringgit', 'Asia'],
  ['Singapore', 'Singapore', 'Singapore Dollar', 'Asia'],
  ['Indonesia', 'Jakarta', 'Rupiah', 'Asia'],
  ['Philippines', 'Manila', 'Philippine Peso', 'Asia'],
  ['Mongolia', 'Ulaanbaatar', 'Tugrik', 'Asia'],
  ['Kazakhstan', 'Astana', 'Tenge', 'Asia'],
  ['Uzbekistan', 'Tashkent', 'Uzbek Som', 'Asia'],
  ['Afghanistan', 'Kabul', 'Afghani', 'Asia'],
  ['Iran', 'Tehran', 'Iranian Rial', 'Asia'],
  ['Iraq', 'Baghdad', 'Iraqi Dinar', 'Asia'],
  ['Saudi Arabia', 'Riyadh', 'Saudi Riyal', 'Asia'],
  ['United Arab Emirates', 'Abu Dhabi', 'Dirham', 'Asia'],
  ['Qatar', 'Doha', 'Qatari Riyal', 'Asia'],
  ['Kuwait', 'Kuwait City', 'Kuwaiti Dinar', 'Asia'],
  ['Oman', 'Muscat', 'Omani Rial', 'Asia'],
  ['Jordan', 'Amman', 'Jordanian Dinar', 'Asia'],
  ['Lebanon', 'Beirut', 'Lebanese Pound', 'Asia'],
  ['Israel', 'Jerusalem', 'Shekel', 'Asia'],
  ['Turkey', 'Ankara', 'Turkish Lira', 'Asia'],
  ['Georgia', 'Tbilisi', 'Lari', 'Asia'],
  ['Armenia', 'Yerevan', 'Dram', 'Asia'],
  ['Azerbaijan', 'Baku', 'Manat', 'Asia'],
  ['Egypt', 'Cairo', 'Egyptian Pound', 'Africa'],
  ['Morocco', 'Rabat', 'Moroccan Dirham', 'Africa'],
  ['Algeria', 'Algiers', 'Algerian Dinar', 'Africa'],
  ['Tunisia', 'Tunis', 'Tunisian Dinar', 'Africa'],
  ['Libya', 'Tripoli', 'Libyan Dinar', 'Africa'],
  ['Sudan', 'Khartoum', 'Sudanese Pound', 'Africa'],
  ['Ethiopia', 'Addis Ababa', 'Birr', 'Africa'],
  ['Kenya', 'Nairobi', 'Kenyan Shilling', 'Africa'],
  ['Tanzania', 'Dodoma', 'Tanzanian Shilling', 'Africa'],
  ['Uganda', 'Kampala', 'Ugandan Shilling', 'Africa'],
  ['Nigeria', 'Abuja', 'Naira', 'Africa'],
  ['Ghana', 'Accra', 'Cedi', 'Africa'],
  ['Senegal', 'Dakar', 'CFA Franc', 'Africa'],
  ['Cameroon', 'Yaounde', 'CFA Franc', 'Africa'],
  ['Democratic Republic of the Congo', 'Kinshasa', 'Congolese Franc', 'Africa'],
  ['Angola', 'Luanda', 'Kwanza', 'Africa'],
  ['Zambia', 'Lusaka', 'Kwacha', 'Africa'],
  ['South Africa', 'Pretoria', 'Rand', 'Africa'],
  ['Namibia', 'Windhoek', 'Namibian Dollar', 'Africa'],
  ['Botswana', 'Gaborone', 'Pula', 'Africa'],
  ['Mozambique', 'Maputo', 'Metical', 'Africa'],
  ['Madagascar', 'Antananarivo', 'Ariary', 'Africa'],
  ['Mauritius', 'Port Louis', 'Mauritian Rupee', 'Africa'],
  ['United States', 'Washington D.C.', 'US Dollar', 'North America'],
  ['Canada', 'Ottawa', 'Canadian Dollar', 'North America'],
  ['Mexico', 'Mexico City', 'Mexican Peso', 'North America'],
  ['Cuba', 'Havana', 'Cuban Peso', 'North America'],
  ['Jamaica', 'Kingston', 'Jamaican Dollar', 'North America'],
  ['Haiti', 'Port-au-Prince', 'Gourde', 'North America'],
  ['Dominican Republic', 'Santo Domingo', 'Dominican Peso', 'North America'],
  ['Guatemala', 'Guatemala City', 'Quetzal', 'North America'],
  ['Panama', 'Panama City', 'Balboa', 'North America'],
  ['Costa Rica', 'San Jose', 'Colon', 'North America'],
  ['Colombia', 'Bogota', 'Colombian Peso', 'North America'],
  ['Venezuela', 'Caracas', 'Bolivar', 'South America'],
  ['Brazil', 'Brasilia', 'Real', 'South America'],
  ['Argentina', 'Buenos Aires', 'Argentine Peso', 'South America'],
  ['Chile', 'Santiago', 'Chilean Peso', 'South America'],
  ['Peru', 'Lima', 'Sol', 'South America'],
  ['Bolivia', 'La Paz', 'Boliviano', 'South America'],
  ['Ecuador', 'Quito', 'US Dollar', 'South America'],
  ['Uruguay', 'Montevideo', 'Uruguayan Peso', 'South America'],
  ['Paraguay', 'Asuncion', 'Guarani', 'South America'],
  ['Australia', 'Canberra', 'Australian Dollar', 'Oceania'],
  ['New Zealand', 'Wellington', 'New Zealand Dollar', 'Oceania'],
  ['Fiji', 'Suva', 'Fijian Dollar', 'Oceania'],
  ['Papua New Guinea', 'Port Moresby', 'Kina', 'Oceania'],
];

// [landmark, country, location]
const LANDMARKS = [
  ['the Eiffel Tower', 'France', 'Paris'],
  ['the Louvre Museum', 'France', 'Paris'],
  ['the Palace of Versailles', 'France', 'Versailles'],
  ['Big Ben', 'United Kingdom', 'London'],
  ['Tower Bridge', 'United Kingdom', 'London'],
  ['Buckingham Palace', 'United Kingdom', 'London'],
  ['Stonehenge', 'United Kingdom', 'Salisbury'],
  ['the Colosseum', 'Italy', 'Rome'],
  ['the Leaning Tower of Pisa', 'Italy', 'Pisa'],
  ['the Trevi Fountain', 'Italy', 'Rome'],
  ['the Sagrada Familia', 'Spain', 'Barcelona'],
  ['the Alhambra', 'Spain', 'Granada'],
  ['the Brandenburg Gate', 'Germany', 'Berlin'],
  ['Neuschwanstein Castle', 'Germany', 'Fussen'],
  ['the Acropolis', 'Greece', 'Athens'],
  ['the Parthenon', 'Greece', 'Athens'],
  ['the Statue of Liberty', 'United States', 'New York'],
  ['the Empire State Building', 'United States', 'New York'],
  ['the Golden Gate Bridge', 'United States', 'San Francisco'],
  ['the Grand Canyon', 'United States', 'Arizona'],
  ['the White House', 'United States', 'Washington D.C.'],
  ['Mount Rushmore', 'United States', 'South Dakota'],
  ['the CN Tower', 'Canada', 'Toronto'],
  ['Chichen Itza', 'Mexico', 'Yucatan'],
  ['Christ the Redeemer', 'Brazil', 'Rio de Janeiro'],
  ['Sugarloaf Mountain', 'Brazil', 'Rio de Janeiro'],
  ['Machu Picchu', 'Peru', 'Cusco'],
  ['the Taj Mahal', 'India', 'Agra'],
  ['the Golden Temple', 'India', 'Amritsar'],
  ['the Great Wall of China', 'China', 'Beijing'],
  ['the Forbidden City', 'China', 'Beijing'],
  ['the Terracotta Army', 'China', "Xi'an"],
  ['Mount Fuji', 'Japan', 'Honshu'],
  ['Fushimi Inari Shrine', 'Japan', 'Kyoto'],
  ['the Petronas Towers', 'Malaysia', 'Kuala Lumpur'],
  ['Marina Bay Sands', 'Singapore', 'Singapore'],
  ['Borobudur', 'Indonesia', 'Magelang'],
  ['Angkor Wat', 'Cambodia', 'Siem Reap'],
  ['the Burj Khalifa', 'United Arab Emirates', 'Dubai'],
  ['Palm Jumeirah', 'United Arab Emirates', 'Dubai'],
  ['the Pyramids of Giza', 'Egypt', 'Giza'],
  ['the Great Sphinx of Giza', 'Egypt', 'Giza'],
  ['Table Mountain', 'South Africa', 'Cape Town'],
  ['Mount Kilimanjaro', 'Tanzania', 'Kilimanjaro'],
  ['the Sydney Opera House', 'Australia', 'Sydney'],
  ['the Sydney Harbour Bridge', 'Australia', 'Sydney'],
  ['Uluru', 'Australia', 'Northern Territory'],
  ['the Great Barrier Reef', 'Australia', 'Queensland'],
  ['Milford Sound', 'New Zealand', 'Fiordland'],
  ['Hagia Sophia', 'Turkey', 'Istanbul'],
  ['the Blue Mosque', 'Turkey', 'Istanbul'],
  ["St. Basil's Cathedral", 'Russia', 'Moscow'],
  ['the Hermitage Museum', 'Russia', 'Saint Petersburg'],
  ['Red Square', 'Russia', 'Moscow'],
  ['the Charles Bridge', 'Czech Republic', 'Prague'],
  ['Prague Castle', 'Czech Republic', 'Prague'],
  ['the Atomium', 'Belgium', 'Brussels'],
  ['the Little Mermaid Statue', 'Denmark', 'Copenhagen'],
  ['the Sistine Chapel', 'Vatican City', 'Vatican City'],
];

// [river, continent, main country]
const RIVERS = [
  ['the Nile', 'Africa', 'Egypt'],
  ['the Amazon River', 'South America', 'Brazil'],
  ['the Yangtze River', 'Asia', 'China'],
  ['the Mississippi River', 'North America', 'United States'],
  ['the Danube', 'Europe', 'Germany'],
  ['the Rhine', 'Europe', 'Switzerland'],
  ['the Seine', 'Europe', 'France'],
  ['the River Thames', 'Europe', 'United Kingdom'],
  ['the Volga River', 'Europe', 'Russia'],
  ['the Ganges', 'Asia', 'India'],
  ['the Mekong River', 'Asia', 'China'],
  ['the Indus River', 'Asia', 'Pakistan'],
  ['the Tigris River', 'Asia', 'Iraq'],
  ['the Euphrates River', 'Asia', 'Iraq'],
  ['the Congo River', 'Africa', 'Democratic Republic of the Congo'],
  ['the Zambezi River', 'Africa', 'Zambia'],
  ['the Niger River', 'Africa', 'Nigeria'],
  ['the Orange River', 'Africa', 'South Africa'],
  ['the Murray River', 'Oceania', 'Australia'],
  ['the Yukon River', 'North America', 'Canada'],
  ['the Colorado River', 'North America', 'United States'],
  ['the Loire', 'Europe', 'France'],
  ['the Tiber', 'Europe', 'Italy'],
  ['the Dnieper River', 'Europe', 'Ukraine'],
];

// [mountain, continent, country]
const MOUNTAINS = [
  ['Mount Everest', 'Asia', 'Nepal'],
  ['K2', 'Asia', 'Pakistan'],
  ['Kangchenjunga', 'Asia', 'Nepal'],
  ['Annapurna', 'Asia', 'Nepal'],
  ['Mount Kilimanjaro', 'Africa', 'Tanzania'],
  ['Mount Kenya', 'Africa', 'Kenya'],
  ['Mont Blanc', 'Europe', 'France'],
  ['the Matterhorn', 'Europe', 'Switzerland'],
  ['Mount Elbrus', 'Europe', 'Russia'],
  ['Ben Nevis', 'Europe', 'United Kingdom'],
  ['Mount Etna', 'Europe', 'Italy'],
  ['Mount Vesuvius', 'Europe', 'Italy'],
  ['Denali', 'North America', 'United States'],
  ['Mount Logan', 'North America', 'Canada'],
  ['Mount Whitney', 'North America', 'United States'],
  ['Mount St. Helens', 'North America', 'United States'],
  ['Aconcagua', 'South America', 'Argentina'],
  ['Mount Kosciuszko', 'Oceania', 'Australia'],
  ['Aoraki Mount Cook', 'Oceania', 'New Zealand'],
  ['Mount Ararat', 'Asia', 'Turkey'],
];

// [desert, continent]
const DESERTS = [
  ['the Sahara Desert', 'Africa'],
  ['the Kalahari Desert', 'Africa'],
  ['the Namib Desert', 'Africa'],
  ['the Gobi Desert', 'Asia'],
  ['the Arabian Desert', 'Asia'],
  ['the Thar Desert', 'Asia'],
  ['the Karakum Desert', 'Asia'],
  ['the Atacama Desert', 'South America'],
  ['the Patagonian Desert', 'South America'],
  ['the Mojave Desert', 'North America'],
  ['the Sonoran Desert', 'North America'],
  ['the Chihuahuan Desert', 'North America'],
  ['the Great Victoria Desert', 'Oceania'],
  ['the Great Sandy Desert', 'Oceania'],
  ['the Antarctic Desert', 'Antarctica'],
];

// [lake, continent, country]
const LAKES = [
  ['Lake Superior', 'North America', 'United States'],
  ['Lake Victoria', 'Africa', 'Tanzania'],
  ['Lake Tanganyika', 'Africa', 'Tanzania'],
  ['the Caspian Sea', 'Asia', 'Kazakhstan'],
  ['Lake Baikal', 'Asia', 'Russia'],
  ['Great Bear Lake', 'North America', 'Canada'],
  ['Lake Michigan', 'North America', 'United States'],
  ['Lake Titicaca', 'South America', 'Peru'],
  ['Lake Geneva', 'Europe', 'Switzerland'],
  ['Lake Como', 'Europe', 'Italy'],
  ['Loch Ness', 'Europe', 'United Kingdom'],
  ['Great Slave Lake', 'North America', 'Canada'],
];

const CONTINENTS = [
  'Europe',
  'Asia',
  'Africa',
  'North America',
  'South America',
  'Oceania',
  'Antarctica',
];

// [question, correct, d1, d2, d3, level, chapter]
const FACTS = [
  [
    'Which is the largest country in the world by area?',
    'Russia',
    'Canada',
    'China',
    'United States',
    'easy',
    'World Records',
  ],
  [
    'Which is the smallest country in the world?',
    'Vatican City',
    'Monaco',
    'Nauru',
    'San Marino',
    'easy',
    'World Records',
  ],
  [
    'Which country has the largest population in the world?',
    'India',
    'China',
    'United States',
    'Indonesia',
    'medium',
    'World Records',
  ],
  [
    'Which is the largest island in the world?',
    'Greenland',
    'New Guinea',
    'Borneo',
    'Madagascar',
    'medium',
    'World Records',
  ],
  [
    'Which is the largest desert in the world?',
    'Antarctic Desert',
    'Sahara',
    'Arabian Desert',
    'Gobi',
    'hard',
    'World Records',
  ],
  [
    'Which is the largest hot desert in the world?',
    'Sahara',
    'Kalahari',
    'Arabian Desert',
    'Mojave',
    'easy',
    'World Records',
  ],
  [
    'Which is the longest river in the world?',
    'the Nile',
    'the Amazon River',
    'the Yangtze River',
    'the Mississippi River',
    'easy',
    'World Records',
  ],
  [
    'Which is the largest river by water volume?',
    'the Amazon River',
    'the Nile',
    'the Yangtze River',
    'the Congo River',
    'medium',
    'World Records',
  ],
  [
    'Which is the largest lake in the world by area?',
    'the Caspian Sea',
    'Lake Superior',
    'Lake Victoria',
    'Lake Baikal',
    'medium',
    'World Records',
  ],
  [
    'Which is the deepest lake in the world?',
    'Lake Baikal',
    'Lake Tanganyika',
    'the Caspian Sea',
    'Lake Superior',
    'medium',
    'World Records',
  ],
  [
    'Which is the highest waterfall in the world?',
    'Angel Falls',
    'Niagara Falls',
    'Victoria Falls',
    'Iguazu Falls',
    'medium',
    'World Records',
  ],
  [
    'Which is the largest ocean in the world?',
    'Pacific Ocean',
    'Atlantic Ocean',
    'Indian Ocean',
    'Arctic Ocean',
    'easy',
    'World Records',
  ],
  [
    'Which is the smallest ocean in the world?',
    'Arctic Ocean',
    'Indian Ocean',
    'Southern Ocean',
    'Atlantic Ocean',
    'medium',
    'World Records',
  ],
  [
    'Which is the deepest point in the ocean?',
    'Mariana Trench',
    'Puerto Rico Trench',
    'Java Trench',
    'Tonga Trench',
    'medium',
    'World Records',
  ],
  [
    'Which is the most populous city in the world?',
    'Tokyo',
    'Delhi',
    'Shanghai',
    'Sao Paulo',
    'medium',
    'World Records',
  ],
  [
    'Which country is the largest in Asia?',
    'China',
    'India',
    'Indonesia',
    'Japan',
    'easy',
    'World Records',
  ],
  [
    'Which is the largest country entirely in Europe?',
    'Ukraine',
    'France',
    'Spain',
    'Germany',
    'hard',
    'World Records',
  ],
  [
    'Which country has the most natural lakes?',
    'Canada',
    'Russia',
    'United States',
    'Finland',
    'hard',
    'World Records',
  ],
  [
    'Which is the coldest continent on Earth?',
    'Antarctica',
    'Europe',
    'Asia',
    'North America',
    'easy',
    'World Records',
  ],
  [
    'Which continent has the most countries?',
    'Africa',
    'Asia',
    'Europe',
    'South America',
    'medium',
    'World Records',
  ],
  [
    'Which is the highest mountain in the world?',
    'Mount Everest',
    'K2',
    'Kangchenjunga',
    'Lhotse',
    'easy',
    'World Records',
  ],
  [
    'Which is the highest mountain in Africa?',
    'Mount Kilimanjaro',
    'Mount Kenya',
    'Mount Stanley',
    'Atlas Peak',
    'easy',
    'World Records',
  ],
  [
    'Which is the highest mountain in North America?',
    'Denali',
    'Mount Logan',
    'Mount Whitney',
    'Mount Elbrus',
    'medium',
    'World Records',
  ],
  [
    'Which is the highest mountain in South America?',
    'Aconcagua',
    'Ojos del Salado',
    'Huascaran',
    'Chimborazo',
    'hard',
    'World Records',
  ],
  [
    'Which is the highest mountain in Europe?',
    'Mount Elbrus',
    'Mont Blanc',
    'the Matterhorn',
    'Ben Nevis',
    'medium',
    'World Records',
  ],
  [
    'Which is the highest peak in Antarctica?',
    'Vinson Massif',
    'Mount Sidley',
    'Mount Erebus',
    'Mount Kirkpatrick',
    'expert',
    'World Records',
  ],
  [
    'Which country is home to the most volcanoes?',
    'Indonesia',
    'Japan',
    'United States',
    'Chile',
    'hard',
    'World Records',
  ],
  [
    'Which is the driest non-polar desert in the world?',
    'Atacama Desert',
    'Sahara',
    'Namib',
    'Gobi',
    'expert',
    'World Records',
  ],
  [
    'Which country has the longest coastline in the world?',
    'Canada',
    'Russia',
    'Indonesia',
    'Australia',
    'hard',
    'World Records',
  ],
  [
    'Which is the largest bay in the world?',
    'Bay of Bengal',
    'Hudson Bay',
    'Gulf of Mexico',
    'Bay of Biscay',
    'expert',
    'World Records',
  ],
  [
    'Which strait separates Asia from North America?',
    'Bering Strait',
    'Strait of Malacca',
    'Strait of Gibraltar',
    'Strait of Hormuz',
    'medium',
    'World Records',
  ],
  [
    'Which strait separates Europe from Africa?',
    'Strait of Gibraltar',
    'Bosporus Strait',
    'Strait of Hormuz',
    'Bering Strait',
    'easy',
    'World Records',
  ],
  [
    'Which canal connects the Mediterranean Sea to the Red Sea?',
    'Suez Canal',
    'Panama Canal',
    'Kiel Canal',
    'Corinth Canal',
    'easy',
    'World Records',
  ],
  [
    'Which canal connects the Atlantic Ocean to the Pacific Ocean?',
    'Panama Canal',
    'Suez Canal',
    'Erie Canal',
    'Panama city canal',
    'easy',
    'World Records',
  ],
  [
    'Which sea is the saltiest body of water on Earth?',
    'the Dead Sea',
    'the Red Sea',
    'the Caspian Sea',
    'the Black Sea',
    'medium',
    'World Records',
  ],
  [
    'Which country is known as the Land of the Rising Sun?',
    'Japan',
    'China',
    'South Korea',
    'Thailand',
    'easy',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Land of Fire and Ice?',
    'Iceland',
    'Norway',
    'Greenland',
    'Chile',
    'easy',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Land of the Maple Leaf?',
    'Canada',
    'United States',
    'Norway',
    'Switzerland',
    'easy',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Land of Kangaroos?',
    'Australia',
    'New Zealand',
    'South Africa',
    'Argentina',
    'easy',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Land of a Thousand Lakes?',
    'Finland',
    'Canada',
    'Sweden',
    'Norway',
    'medium',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Roof of the World?',
    'Tibet region of China',
    'Nepal',
    'Bhutan',
    'Mongolia',
    'hard',
    'Country Nicknames',
  ],
  [
    'Which country is called the Land of Smiles?',
    'Thailand',
    'Philippines',
    'Malaysia',
    'Indonesia',
    'medium',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Emerald Isle?',
    'Ireland',
    'Scotland',
    'Wales',
    'New Zealand',
    'easy',
    'Country Nicknames',
  ],
  [
    'Which country is known as the Pearl of Africa?',
    'Uganda',
    'Kenya',
    'Tanzania',
    'Rwanda',
    'expert',
    'Country Nicknames',
  ],
  [
    'Which capital city is known as the City of Light?',
    'Paris',
    'Rome',
    'Vienna',
    'Madrid',
    'easy',
    'City Nicknames',
  ],
  [
    'Which capital city is known as the Eternal City?',
    'Rome',
    'Athens',
    'Cairo',
    'Jerusalem',
    'easy',
    'City Nicknames',
  ],
  [
    'Which city is known as the City of Canals?',
    'Venice',
    'Amsterdam',
    'Bruges',
    'Stockholm',
    'easy',
    'City Nicknames',
  ],
  [
    'Which capital city is known as the Big Apple?',
    'New York City',
    'Boston',
    'Chicago',
    'Los Angeles',
    'medium',
    'City Nicknames',
  ],
  [
    'Which capital city is known as the City of a Hundred Spires?',
    'Prague',
    'Vienna',
    'Budapest',
    'Warsaw',
    'medium',
    'City Nicknames',
  ],
  [
    'Which capital city is known as the Pearl of the Danube?',
    'Budapest',
    'Vienna',
    'Belgrade',
    'Bratislava',
    'medium',
    'City Nicknames',
  ],
  [
    'Which capital city is known as the City of Music?',
    'Vienna',
    'Berlin',
    'Paris',
    'Milan',
    'medium',
    'City Nicknames',
  ],
  [
    'Which city is known as the Lion City?',
    'Singapore',
    'Hong Kong',
    'Bangkok',
    'Jakarta',
    'medium',
    'City Nicknames',
  ],
  [
    'Which imaginary line divides the Earth into Northern and Southern Hemispheres?',
    'the Equator',
    'the Prime Meridian',
    'the Tropic of Cancer',
    'the International Date Line',
    'easy',
    'Maps & Lines',
  ],
  [
    'Which line of longitude is at zero degrees?',
    'the Prime Meridian',
    'the Equator',
    'the Tropic of Capricorn',
    'the International Date Line',
    'medium',
    'Maps & Lines',
  ],
  [
    'Through which country does the Prime Meridian pass?',
    'United Kingdom',
    'France',
    'Spain',
    'Portugal',
    'medium',
    'Maps & Lines',
  ],
  [
    'The Tropic of Cancer lies in which hemisphere?',
    'Northern Hemisphere',
    'Southern Hemisphere',
    'Eastern Hemisphere only',
    'Western Hemisphere only',
    'medium',
    'Maps & Lines',
  ],
  [
    'How many continents are there on Earth?',
    'Seven',
    'Five',
    'Six',
    'Eight',
    'easy',
    'Maps & Lines',
  ],
  ['How many oceans are there on Earth?', 'Five', 'Four', 'Three', 'Seven', 'easy', 'Maps & Lines'],
  [
    'Which ocean lies between Africa and Australia?',
    'Indian Ocean',
    'Atlantic Ocean',
    'Pacific Ocean',
    'Southern Ocean',
    'easy',
    'Maps & Lines',
  ],
  [
    'Which ocean is the largest by surface area?',
    'Pacific Ocean',
    'Atlantic Ocean',
    'Indian Ocean',
    'Arctic Ocean',
    'easy',
    'Maps & Lines',
  ],
  [
    'Which continent surrounds the South Pole?',
    'Antarctica',
    'Australia',
    'South America',
    'Africa',
    'easy',
    'Maps & Lines',
  ],
  [
    'Which continent contains the North Pole?',
    'None',
    'Europe',
    'Asia',
    'North America',
    'medium',
    'Maps & Lines',
  ],
  [
    'What does a cartographer make?',
    'Maps',
    'Ships',
    'Compasses',
    'Globes only',
    'medium',
    'Maps & Lines',
  ],
  [
    'Which direction does the Danube flow toward?',
    'the Black Sea',
    'the Mediterranean Sea',
    'the Baltic Sea',
    'the North Sea',
    'expert',
    'Maps & Lines',
  ],
  [
    'Which is the largest gulf in the world?',
    'Gulf of Mexico',
    'Persian Gulf',
    'Gulf of Alaska',
    'Gulf of Guinea',
    'expert',
    'Maps & Lines',
  ],
  [
    'Mount Everest sits on the border of Nepal and which other country?',
    'China',
    'India',
    'Bhutan',
    'Pakistan',
    'medium',
    'World Records',
  ],
  [
    'Which desert is the largest in Asia?',
    'the Arabian Desert',
    'the Gobi Desert',
    'the Thar Desert',
    'the Karakum Desert',
    'medium',
    'World Records',
  ],
  [
    'Which desert is the largest in South America?',
    'the Patagonian Desert',
    'the Atacama Desert',
    'the Sechura Desert',
    'the Monte Desert',
    'hard',
    'World Records',
  ],
  [
    'Which is the largest waterfall by water flow?',
    'Iguazu Falls',
    'Niagara Falls',
    'Victoria Falls',
    'Angel Falls',
    'hard',
    'World Records',
  ],
  [
    'In which country would you find the city of Marrakech?',
    'Morocco',
    'Tunisia',
    'Egypt',
    'Algeria',
    'medium',
    'World Records',
  ],
  [
    'Which European capital stands on both sides of the Danube River?',
    'Budapest',
    'Vienna',
    'Belgrade',
    'Bratislava',
    'medium',
    'City Nicknames',
  ],
  [
    'Which two continents does Russia span?',
    'Europe and Asia',
    'Asia and Africa',
    'Europe and Africa',
    'Asia and North America',
    'easy',
    'World Records',
  ],
  [
    'Which city is famous for its canals and gondolas?',
    'Venice',
    'Amsterdam',
    'Bangkok',
    'Stockholm',
    'easy',
    'City Nicknames',
  ],
];

// [question, free-text answer, chapter]
const EXTREMES = [
  ['How many states make up the United States of America?', 'Fifty', 'World Basics'],
  ['How many countries are there in the United Kingdom?', 'Four', 'World Basics'],
  ['What is the capital of Australia?', 'Canberra', 'Capitals'],
  ['What is the capital of Canada?', 'Ottawa', 'Capitals'],
  ['What is the capital of Brazil?', 'Brasilia', 'Capitals'],
  ['What is the capital of Turkey?', 'Ankara', 'Capitals'],
  ['What is the capital of Switzerland?', 'Bern', 'Capitals'],
  ['What is the capital of New Zealand?', 'Wellington', 'Capitals'],
  ['How many emirates make up the United Arab Emirates?', 'Seven', 'World Basics'],
  ['How many provinces does Canada have?', 'Ten', 'World Basics'],
  ['How many states does Australia have?', 'Six', 'World Basics'],
  ['How many Great Lakes are there in North America?', 'Five', 'World Basics'],
  ['How many time zones does Russia span?', 'Eleven', 'World Basics'],
  [
    'How many countries are currently members of the European Union?',
    'Twenty-seven',
    'World Basics',
  ],
  ['What is the smallest country in the world by area?', 'Vatican City', 'World Records'],
  ['What is the largest ocean on Earth?', 'Pacific Ocean', 'World Records'],
  ['Which desert is the largest hot desert in the world?', 'Sahara', 'World Records'],
  ['How many continents are there on Earth?', 'Seven', 'World Basics'],
  ['How many oceans are there on Earth?', 'Five', 'World Basics'],
  ['How many countries share a land border with Germany?', 'Nine', 'World Basics'],
  ['How many states are in India?', 'Twenty-eight', 'World Basics'],
  ['How many countries does China share a land border with?', 'Fourteen', 'World Basics'],
];

// Extra MCQ facts appended below
const FACTS_EXTRA = [
  [
    'Which country is entirely surrounded by South Africa?',
    'Lesotho',
    'Eswatini',
    'Botswana',
    'Zimbabwe',
    'hard',
    'World Records',
  ],
  [
    'Which two countries share the longest international border?',
    'Canada and the United States',
    'Russia and China',
    'Argentina and Chile',
    'India and Bangladesh',
    'hard',
    'World Records',
  ],
  [
    'Which African country has the most pyramids?',
    'Sudan',
    'Egypt',
    'Libya',
    'Morocco',
    'hard',
    'World Records',
  ],
  [
    'Which capital city sits at the highest altitude?',
    'La Paz',
    'Quito',
    'Bogota',
    'Kathmandu',
    'hard',
    'World Records',
  ],
  [
    'Which sea has no coastline?',
    'the Sargasso Sea',
    'the Dead Sea',
    'the Red Sea',
    'the Black Sea',
    'expert',
    'World Records',
  ],
  [
    'Which is the largest archipelago in the world?',
    'Indonesia',
    'the Philippines',
    'Japan',
    'the Maldives',
    'medium',
    'World Records',
  ],
];

function generate(rng) {
  const rows = [];
  const capitals = COUNTRIES.map((c) => c[1]);
  const countryNames = COUNTRIES.map((c) => c[0]);
  const currencies = [...new Set(COUNTRIES.map((c) => c[2]))];
  const landmarkNames = LANDMARKS.map((l) => l[0]);

  for (const [country, capital, currency, continent] of COUNTRIES) {
    const contPool = CONTINENTS.filter((c) => c !== continent);
    rows.push({
      q: `What is the capital city of ${country}?`,
      correct: capital,
      ds: distractors(capitals, capital, 3, rng),
      level: 'easy',
      chapter: 'Capitals',
    });
    rows.push({
      q: `${capital} is the capital city of which country?`,
      correct: country,
      ds: distractors(countryNames, country, 3, rng),
      level: 'medium',
      chapter: 'Capitals',
    });
    rows.push({
      q: `What is the official currency of ${country}?`,
      correct: currency,
      ds: distractors(currencies, currency, 3, rng),
      level: 'medium',
      chapter: 'Currencies',
    });
    // Skip the continent question for transcontinental countries to avoid disputed answers.
    if (country !== 'Russia' && country !== 'Turkey') {
      rows.push({
        q: `On which continent is ${country} located?`,
        correct: continent,
        ds: distractors(contPool, continent, 3, rng),
        level: 'easy',
        chapter: 'Countries & Continents',
      });
    }
    // Currency-to-country question only when the currency name does not give the country away.
    const cur = currency.toLowerCase();
    const cty = country.toLowerCase();
    const givesAway =
      cur.includes('dollar') === false &&
      (cty.split(' ').some((w) => w.length > 3 && cur.includes(w)) ||
        cur.split(' ').some((w) => w.length > 3 && cty.includes(w)));
    if (!givesAway) {
      rows.push({
        q: `The ${currency} is the official currency of which country?`,
        correct: country,
        ds: distractors(countryNames, country, 3, rng),
        level: 'hard',
        chapter: 'Currencies',
      });
    }
  }

  const contByCountry = Object.fromEntries(COUNTRIES.map((c) => [c[0], c[3]]));
  for (const [landmark, country, place] of LANDMARKS) {
    const contPool = CONTINENTS.filter((c) => c !== contByCountry[country]);
    rows.push({
      q: `In which country is ${landmark} located?`,
      correct: country,
      ds: distractors(countryNames, country, 3, rng),
      level: 'easy',
      chapter: 'Famous Landmarks',
    });
    rows.push({
      q: `In which city or region is ${landmark} located?`,
      correct: place,
      ds: distractors(
        LANDMARKS.map((l) => l[2]),
        place,
        3,
        rng
      ),
      level: 'medium',
      chapter: 'Famous Landmarks',
    });
    rows.push({
      q: `Which famous landmark is found in ${place}, ${country}?`,
      correct: landmark,
      ds: distractors(landmarkNames, landmark, 3, rng),
      level: 'hard',
      chapter: 'Famous Landmarks',
    });
    rows.push({
      q: `On which continent is ${landmark} located?`,
      correct: contByCountry[country],
      ds: distractors(contPool, contByCountry[country], 3, rng),
      level: 'easy',
      chapter: 'Famous Landmarks',
    });
  }

  for (const [river, continent, country] of RIVERS) {
    const contPool = CONTINENTS.filter((c) => c !== continent);
    rows.push({
      q: `On which continent is ${river} located?`,
      correct: continent,
      ds: distractors(contPool, continent, 3, rng),
      level: 'easy',
      chapter: 'Rivers & Mountains',
    });
    rows.push({
      q: `${river} flows mainly through which country?`,
      correct: country,
      ds: distractors(countryNames, country, 3, rng),
      level: 'medium',
      chapter: 'Rivers & Mountains',
    });
  }

  for (const [mountain, continent, country] of MOUNTAINS) {
    const contPool = CONTINENTS.filter((c) => c !== continent);
    rows.push({
      q: `On which continent is ${mountain} located?`,
      correct: continent,
      ds: distractors(contPool, continent, 3, rng),
      level: 'easy',
      chapter: 'Rivers & Mountains',
    });
    rows.push({
      q: `In which country is ${mountain} located?`,
      correct: country,
      ds: distractors(countryNames, country, 3, rng),
      level: 'medium',
      chapter: 'Rivers & Mountains',
    });
  }

  for (const [desert, continent] of DESERTS) {
    const contPool = CONTINENTS.filter((c) => c !== continent);
    rows.push({
      q: `On which continent is ${desert} located?`,
      correct: continent,
      ds: distractors(contPool, continent, 3, rng),
      level: 'medium',
      chapter: 'Deserts & Lakes',
    });
  }

  for (const [lake, continent, country] of LAKES) {
    const contPool = CONTINENTS.filter((c) => c !== continent);
    rows.push({
      q: `On which continent is ${lake} located?`,
      correct: continent,
      ds: distractors(contPool, continent, 3, rng),
      level: 'easy',
      chapter: 'Deserts & Lakes',
    });
    rows.push({
      q: `${lake} lies mainly in which country?`,
      correct: country,
      ds: distractors(countryNames, country, 3, rng),
      level: 'medium',
      chapter: 'Deserts & Lakes',
    });
  }

  for (const f of FACTS)
    rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  for (const f of FACTS_EXTRA)
    rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  for (const [q, text, chapter] of EXTREMES) rows.push({ q, text, chapter });

  return rows;
}

module.exports = { subject: 'Geography', generate };
