'use strict';

// Companion banks for the General Knowledge subject.
// Each bank: [question, correct, d1, d2, d3, level, chapter]

const MONTHS = [
  ['January', 31, 1],
  ['February', 28, 2],
  ['March', 31, 3],
  ['April', 30, 4],
  ['May', 31, 5],
  ['June', 30, 6],
  ['July', 31, 7],
  ['August', 31, 8],
  ['September', 30, 9],
  ['October', 31, 10],
  ['November', 30, 11],
  ['December', 31, 12],
];

const GODS = [
  ['Zeus', 'Jupiter', 'king of the gods and sky', 'a thunderbolt'],
  ['Hera', 'Juno', 'queen of the gods and marriage', 'a diadem'],
  ['Poseidon', 'Neptune', 'the sea', 'a trident'],
  ['Hades', 'Pluto', 'the underworld', 'a helm of darkness'],
  ['Athena', 'Minerva', 'wisdom and war strategy', 'an owl'],
  ['Apollo', 'Apollo', 'the sun, music, and prophecy', 'a lyre'],
  ['Artemis', 'Diana', 'the hunt and the moon', 'a bow and arrow'],
  ['Ares', 'Mars', 'war', 'a spear and shield'],
  ['Aphrodite', 'Venus', 'love and beauty', 'a dove'],
  ['Hermes', 'Mercury', 'messengers and travelers', 'winged sandals'],
  ['Hephaestus', 'Vulcan', 'fire and the forge', 'a hammer'],
  ['Demeter', 'Ceres', 'harvest and agriculture', 'sheaves of wheat'],
  ['Dionysus', 'Bacchus', 'wine and festivities', 'grapevines'],
  ['Eros', 'Cupid', 'love and desire', 'a bow of love'],
];

const NORSE = [
  ['Odin', 'the all-father god of wisdom and war', 'Gungnir, his spear'],
  ['Thor', 'the god of thunder', 'Mjolnir, his hammer'],
  ['Loki', 'the trickster god', 'shapeshifting and mischief'],
  ['Freya', 'the goddess of love and fertility', 'a chariot of cats'],
  ['Freyr', 'the god of prosperity and sunshine', 'a magic ship'],
  ['Heimdall', 'the watchman of the gods', 'the horn Gjallarhorn'],
  ['Tyr', 'the god of law and heroic glory', 'one hand, lost to a wolf'],
  ['Baldr', 'the god of light and purity', 'his invulnerability to harm'],
];

const PLURALS = [
  ['child', 'children'],
  ['person', 'people'],
  ['mouse', 'mice'],
  ['goose', 'geese'],
  ['foot', 'feet'],
  ['tooth', 'teeth'],
  ['man', 'men'],
  ['woman', 'women'],
  ['ox', 'oxen'],
  ['sheep', 'sheep'],
  ['deer', 'deer'],
  ['fish', 'fish'],
  ['cactus', 'cacti'],
  ['focus', 'foci'],
  ['criterion', 'criteria'],
  ['phenomenon', 'phenomena'],
  ['datum', 'data'],
  ['alumnus', 'alumni'],
  ['crisis', 'crises'],
  ['analysis', 'analyses'],
  ['thesis', 'theses'],
  ['basis', 'bases'],
  ['knife', 'knives'],
  ['leaf', 'leaves'],
  ['wolf', 'wolves'],
  ['loaf', 'loaves'],
  ['shelf', 'shelves'],
  ['wife', 'wives'],
  ['louse', 'lice'],
  ['die', 'dice'],
];

const OPPOSITES = [
  ['ancient', 'modern'],
  ['brave', 'cowardly'],
  ['generous', 'stingy'],
  ['humble', 'arrogant'],
  ['noisy', 'quiet'],
  ['rapid', 'slow'],
  ['victory', 'defeat'],
  ['arrive', 'depart'],
  ['ascend', 'descend'],
  ['artificial', 'natural'],
  ['bright', 'dim'],
  ['candid', 'secretive'],
  ['diligent', 'lazy'],
  ['expand', 'contract'],
  ['foreign', 'domestic'],
  ['genuine', 'fake'],
  ['hostile', 'friendly'],
  ['innocent', 'guilty'],
  ['large', 'small'],
  ['majority', 'minority'],
  ['obsolete', 'current'],
  ['permanent', 'temporary'],
  ['rare', 'common'],
  ['scarce', 'abundant'],
  ['superior', 'inferior'],
  ['tame', 'wild'],
  ['vague', 'clear'],
  ['wealthy', 'poor'],
  ['winter', 'summer'],
  ['youth', 'old age'],
];

const IDIOMS = [
  ['to let the cat out of the bag', 'To reveal a secret'],
  ['to bite the bullet', 'To endure something painful bravely'],
  ['to break the ice', 'To start a conversation in a social setting'],
  ['to hit the nail on the head', 'To be exactly right'],
  ['to spill the beans', 'To reveal a secret'],
  ['to burn the midnight oil', 'To work late into the night'],
  ['to be under the weather', 'To feel slightly ill'],
  ['to cost an arm and a leg', 'To be very expensive'],
  ['to be a piece of cake', 'To be very easy'],
  ['to cry over spilled milk', 'To be upset over something unchangeable'],
  ['to be in hot water', 'To be in trouble'],
  ['to kill two birds with one stone', 'To achieve two things with one action'],
  ['to go the extra mile', 'To make more effort than expected'],
  ['to be on cloud nine', 'To be extremely happy'],
  ['to be in the same boat', 'To share the same difficult situation'],
  ['to beat around the bush', 'To avoid the main topic'],
  ['to add fuel to the fire', 'To make a bad situation worse'],
  ['to be a blessing in disguise', 'To be something good that seemed bad'],
  ['to bite off more than you can chew', 'To take on too much'],
  ['to blow off steam', 'To release stress or anger'],
  ['to cut corners', 'To do something cheaply or carelessly'],
  ['to face the music', 'To accept the consequences'],
  ['to get cold feet', 'To become nervous and back out'],
  ['to hit the sack', 'To go to bed'],
  ['to jump on the bandwagon', 'To join a popular trend'],
  ['to keep an eye on', 'To watch carefully'],
  ['to make a long story short', 'To summarize briefly'],
  ['to be once in a blue moon', 'To happen very rarely'],
  ['to pull someones leg', 'To joke playfully with someone'],
  ['to see eye to eye', 'To agree with someone'],
];

const ABBREV = [
  ['ATM', 'Automated teller machine'],
  ['DVD', 'Digital versatile disc'],
  ['GPS', 'Global positioning system'],
  ['LED', 'Light-emitting diode'],
  ['FAQ', 'Frequently asked questions'],
  ['DIY', 'Do it yourself'],
  ['BYOD', 'Bring your own device'],
  ['NASA', 'National Aeronautics and Space Administration'],
  ['UNICEF', 'United Nations Childrens Fund'],
  ['WHO', 'World Health Organization'],
  ['WWF', 'World Wide Fund for Nature'],
  ['FBI', 'Federal Bureau of Investigation'],
  ['CIA', 'Central Intelligence Agency'],
  ['BBC', 'British Broadcasting Corporation'],
  ['CNN', 'Cable News Network'],
  ['BMW', 'Bayerische Motoren Werke'],
  ['VW', 'Volkswagen'],
  ['IBM', 'International Business Machines'],
  ['HP', 'Hewlett-Packard'],
  ['UPS', 'United Parcel Service'],
  ['IKEA', 'Ingvar Kamprad Elmtaryd Agunnaryd'],
  ['NASCAR', 'National Association for Stock Car Auto Racing'],
  ['PETA', 'People for the Ethical Treatment of Animals'],
  ['NATO', 'North Atlantic Treaty Organization'],
  ['UNESCO', 'United Nations Educational, Scientific and Cultural Organization'],
  ['IMF', 'International Monetary Fund'],
  ['OPEC', 'Organization of the Petroleum Exporting Countries'],
  ['ASEAN', 'Association of Southeast Asian Nations'],
  ['EU', 'European Union'],
  ['AC', 'Alternating current'],
  ['DC', 'Direct current'],
  ['TV', 'Television'],
  ['PC', 'Personal computer'],
  ['USB', 'Universal serial bus'],
  ['Wi-Fi', 'Wireless fidelity branding'],
  ['PDF', 'Portable document format'],
  ['JPEG', 'Joint photographic experts group'],
  ['GIF', 'Graphics interchange format'],
  ['HTTP', 'Hypertext transfer protocol'],
  ['ISBN', 'International standard book number'],
];

const BOOKS = [
  ['Pride and Prejudice', 'Jane Austen'],
  ['1984', 'George Orwell'],
  ['Animal Farm', 'George Orwell'],
  ['Jane Eyre', 'Charlotte Bronte'],
  ['Wuthering Heights', 'Emily Bronte'],
  ['Great Expectations', 'Charles Dickens'],
  ['Oliver Twist', 'Charles Dickens'],
  ['War and Peace', 'Leo Tolstoy'],
  ['Crime and Punishment', 'Fyodor Dostoevsky'],
  ['Moby-Dick', 'Herman Melville'],
  ['The Adventures of Tom Sawyer', 'Mark Twain'],
  ['Adventures of Huckleberry Finn', 'Mark Twain'],
  ['The Great Gatsby', 'F. Scott Fitzgerald'],
  ['To Kill a Mockingbird', 'Harper Lee'],
  ['The Catcher in the Rye', 'J.D. Salinger'],
  ['The Lord of the Rings', 'J.R.R. Tolkien'],
  ['The Hobbit', 'J.R.R. Tolkien'],
  ['Harry Potter and the Philosophers Stone', 'J.K. Rowling'],
  ['The Chronicles of Narnia', 'C.S. Lewis'],
  ['The Little Prince', 'Antoine de Saint-Exupery'],
  ['Don Quixote', 'Miguel de Cervantes'],
  ['The Odyssey', 'Homer'],
  ['The Iliad', 'Homer'],
  ['Divine Comedy', 'Dante Alighieri'],
  ['Frankenstein', 'Mary Shelley'],
  ['Dracula', 'Bram Stoker'],
  ['The Picture of Dorian Gray', 'Oscar Wilde'],
  ['The Time Machine', 'H.G. Wells'],
  ['The War of the Worlds', 'H.G. Wells'],
  ['Twenty Thousand Leagues Under the Sea', 'Jules Verne'],
  ['Around the World in Eighty Days', 'Jules Verne'],
  ['The Old Man and the Sea', 'Ernest Hemingway'],
  ['For Whom the Bell Tolls', 'Ernest Hemingway'],
  ['Of Mice and Men', 'John Steinbeck'],
  ['The Grapes of Wrath', 'John Steinbeck'],
  ['Brave New World', 'Aldous Huxley'],
  ['Fahrenheit 451', 'Ray Bradbury'],
  ['The Alchemist', 'Paulo Coelho'],
  ['One Hundred Years of Solitude', 'Gabriel Garcia Marquez'],
  ['Things Fall Apart', 'Chinua Achebe'],
];

const SHAKESPEARE = [
  ['Romeo and Juliet', 'two feuding families lovers tragedy'],
  ['Hamlet', 'the prince of Denmark seeking revenge'],
  ['Macbeth', 'a Scottish thane seized by ambition'],
  ['Othello', 'the Moor of Venice undone by jealousy'],
  ['King Lear', 'an aging king dividing his kingdom'],
  ['A Midsummer Nights Dream', 'lovers and fairies in a forest'],
  ['The Tempest', 'a magician duke on an island'],
  ['Julius Caesar', 'the assassination of a Roman leader'],
  ['Twelfth Night', 'shipwrecked twins and mistaken identity'],
  ['Much Ado About Nothing', 'witty lovers sparring in Messina'],
];

// [question, correct, d1, d2, d3, level, chapter]
const TIME_CALENDAR = [
  ['How many days are in a common year?', '365', '364', '366', '360', 'easy', 'Time & Calendar'],
  ['How many days are in a leap year?', '366', '365', '364', '367', 'easy', 'Time & Calendar'],
  [
    'Which month has 28 days usually and 29 in a leap year?',
    'February',
    'January',
    'April',
    'June',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which month is named after Julius Caesar?',
    'July',
    'June',
    'January',
    'August',
    'medium',
    'Time & Calendar',
  ],
  [
    'Which month is named after Augustus Caesar?',
    'August',
    'October',
    'July',
    'September',
    'medium',
    'Time & Calendar',
  ],
  [
    'What do we call the rule that adds a day every four years?',
    'The leap year rule',
    'The calendar shift',
    'The solar fix',
    'The equinox rule',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is a century leap year exception? Years divisible by 100 are not leap unless divisible by 400',
    'Divisible by 100 but not 400 are common years',
    'Every 100th year is leap',
    'Leap years skip every century',
    'Century years are always leap',
    'expert',
    'Time & Calendar',
  ],
  ['How many hours are in a day on average?', '24', '12', '20', '26', 'easy', 'Time & Calendar'],
  ['How many minutes are in an hour?', '60', '50', '100', '30', 'easy', 'Time & Calendar'],
  ['How many seconds are in a minute?', '60', '100', '50', '24', 'easy', 'Time & Calendar'],
  ['How many weeks are in a year roughly?', '52', '50', '48', '56', 'easy', 'Time & Calendar'],
  [
    'Which day is the first day of the week in most Western calendars?',
    'Sunday or Monday by convention',
    'Saturday',
    'Friday',
    'Thursday',
    'medium',
    'Time & Calendar',
  ],
  [
    'What does AM stand for?',
    'Ante meridiem, before noon',
    'After morning',
    'All morning',
    'At midnight',
    'medium',
    'Time & Calendar',
  ],
  [
    'What does PM stand for?',
    'Post meridiem, after noon',
    'Past morning',
    'Prime meridian',
    'Plus midnight',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is the summer solstice in the Northern Hemisphere?',
    'The longest day of the year',
    'The shortest day',
    'The first frost',
    'An eclipse day',
    'easy',
    'Time & Calendar',
  ],
  [
    'What is the winter solstice in the Northern Hemisphere?',
    'The shortest day of the year',
    'The longest day',
    'The first snow',
    'A new moon',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday falls on December 25 in many countries?',
    'Christmas',
    'Thanksgiving',
    'Easter',
    'Halloween',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday falls on January 1?',
    'New Years Day',
    'Valentines Day',
    'Easter',
    'Labor Day',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday falls on October 31?',
    'Halloween',
    'Thanksgiving',
    'Christmas Eve',
    'Boxing Day',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday falls on February 14?',
    'Valentines Day',
    'April Fools Day',
    'Mothers Day',
    'Independence Day',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday falls on April 1?',
    'April Fools Day',
    'May Day',
    'Groundhog Day',
    'Veterans Day',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday is celebrated on the fourth Thursday of November in the United States?',
    'Thanksgiving',
    'Halloween',
    'Labor Day',
    'Flag Day',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which holiday follows Thanksgiving Friday in the US shopping calendar?',
    'Black Friday',
    'Cyber Monday',
    'Boxing Day',
    'Green Monday',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which lunar new year animal cycle has twelve animals?',
    'The Chinese zodiac',
    'The Aztec calendar',
    'The Mayan round',
    'The Celtic wheel',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which animal begins the Chinese zodiac cycle?',
    'The rat',
    'The ox',
    'The tiger',
    'The dragon',
    'medium',
    'Time & Calendar',
  ],
  [
    'Which calendar do most countries use today?',
    'The Gregorian calendar',
    'The Julian calendar',
    'The lunar calendar',
    'The Mayan calendar',
    'medium',
    'Time & Calendar',
  ],
  [
    'Who introduced the Gregorian calendar in 1582?',
    'Pope Gregory XIII',
    'Julius Caesar',
    'Augustus',
    'King James',
    'hard',
    'Time & Calendar',
  ],
  [
    'Which calendar did Julius Caesar introduce?',
    'The Julian calendar',
    'The Gregorian calendar',
    'The solar-only calendar',
    'The Roman lunar year',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is a fortnight?',
    'Two weeks',
    'One week',
    'A month',
    'Four days',
    'medium',
    'Time & Calendar',
  ],
  [
    'What does decade mean?',
    'Ten years',
    'A hundred years',
    'A thousand years',
    'Twenty years',
    'easy',
    'Time & Calendar',
  ],
  [
    'What does century mean?',
    'A hundred years',
    'Ten years',
    'A thousand years',
    'Fifty years',
    'easy',
    'Time & Calendar',
  ],
  [
    'What does millennium mean?',
    'A thousand years',
    'A hundred years',
    'Ten years',
    'Ten thousand years',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which time zone is the reference for UTC?',
    'Coordinated Universal Time',
    'Universal Total Clock',
    'United Time Code',
    'Universal Territorial Count',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is daylight saving time?',
    'Shifting clocks forward in summer',
    'Adding a leap second',
    'Doubling noon',
    'A polar phenomenon',
    'easy',
    'Time & Calendar',
  ],
  [
    'Which direction do clocks move for daylight saving in spring?',
    'Forward one hour',
    'Backward one hour',
    'Forward one day',
    'They do not change',
    'easy',
    'Time & Calendar',
  ],
  [
    'What is an equinox?',
    'When day and night are nearly equal',
    'The longest day',
    'The shortest day',
    'A lunar event',
    'medium',
    'Time & Calendar',
  ],
  [
    'How many equinoxes occur each year?',
    'Two',
    'One',
    'Four',
    'Three',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is a solar year roughly?',
    '365.24 days',
    '360 days',
    '370 days',
    '365.9 days',
    'hard',
    'Time & Calendar',
  ],
  [
    'What is the zodiac sign for people born in early April?',
    'Aries',
    'Taurus',
    'Pisces',
    'Gemini',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is the zodiac sign for late December births?',
    'Capricorn',
    'Sagittarius',
    'Aquarius',
    'Scorpio',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is a blue moon?',
    'The second full moon in a month',
    'A lunar eclipse',
    'A new moon',
    'A red moon',
    'medium',
    'Time & Calendar',
  ],
  [
    'What is a supermoon?',
    'A full moon at its closest to Earth',
    'A double moon',
    'A partial eclipse',
    'A moon halo',
    'medium',
    'Time & Calendar',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const EVERYDAY_SCIENCE = [
  [
    'Why does metal feel colder than wood at the same temperature?',
    'Metal conducts heat away from skin faster',
    'Metal is always colder',
    'Wood generates heat',
    'Metal reflects cold',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does ice float on water?',
    'Ice is less dense than water',
    'Ice is heavier',
    'Water pushes it up magnetically',
    'Ice is warmer',
    'easy',
    'Everyday Science',
  ],
  [
    'Why do we see lightning before thunder?',
    'Light travels faster than sound',
    'Thunder waits',
    'Sound bends away',
    'Lightning is louder first',
    'easy',
    'Everyday Science',
  ],
  [
    'Why does bread rise?',
    'Yeast produces carbon dioxide gas',
    'Heat expands flour',
    'Sugar melts',
    'Salt reacts with air',
    'easy',
    'Everyday Science',
  ],
  [
    'Why does a fridge cool food?',
    'A heat pump moves heat outside',
    'Cold is pumped in',
    'Ice inside absorbs heat only',
    'Chemicals absorb warmth once',
    'medium',
    'Everyday Science',
  ],
  [
    'Why do clothes dry faster on a windy day?',
    'Wind carries moisture away',
    'Sun strengthens',
    'Wind cools water only',
    'Fabric stretches',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does a mirror flip left and right but not up and down?',
    'It reverses front to back, which we read as left-right',
    'Mirrors flip vertically only',
    'Light bends upward',
    'Eyes swap the image',
    'hard',
    'Everyday Science',
  ],
  [
    'Why do we sweat?',
    'To cool the body by evaporation',
    'To remove salt only',
    'To fight germs',
    'To grow hair',
    'easy',
    'Everyday Science',
  ],
  [
    'Why do onions make us cry?',
    'They release sulfur compounds that irritate eyes',
    'They spray acid',
    'Their smell hurts nerves',
    'They carry dust',
    'easy',
    'Everyday Science',
  ],
  [
    'Why does coffee keep us awake?',
    'Caffeine blocks sleepiness signals',
    'Sugar gives energy',
    'Heat wakes the brain',
    'Aroma stimulates eyes',
    'easy',
    'Everyday Science',
  ],
  [
    'Why does salt melt ice on roads?',
    'It lowers the freezing point of water',
    'It heats the surface',
    'It absorbs ice like a sponge',
    'It adds friction only',
    'medium',
    'Everyday Science',
  ],
  [
    'Why do pressure cookers cook faster?',
    'Higher pressure raises waters boiling point',
    'They use more power',
    'Sealed steam adds flavor only',
    'They stir automatically',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does soap clean grease?',
    'Molecules attach to oil and water both',
    'Soap melts grease chemically',
    'Soap adds friction only',
    'Soap freezes grease',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does a straw look bent in water?',
    'Light refracts at the surface',
    'Water pushes the straw',
    'The eye bends',
    'Glass distorts the top',
    'easy',
    'Everyday Science',
  ],
  [
    'Why are sunsets red?',
    'Light scatters differently through more atmosphere',
    'The sun cools at dusk',
    'Clouds tint it red',
    'Ozone turns red',
    'medium',
    'Everyday Science',
  ],
  [
    'Why is the sky blue?',
    'Blue light scatters most in the air',
    'Oceans reflect upward',
    'Oxygen is blue',
    'Clouds dye it',
    'easy',
    'Everyday Science',
  ],
  [
    'Why do stars twinkle?',
    'Air turbulence bends their light',
    'They flash on and off',
    'Moisture lens effect',
    'Earth wobbles',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does the Moon look bigger near the horizon?',
    'A visual illusion of the brain',
    'It really is closer',
    'Air magnifies it',
    'Earth bends light there',
    'hard',
    'Everyday Science',
  ],
  [
    'Why does static electricity shock us in winter?',
    'Dry air lets charge build up',
    'Cold creates electricity',
    'Wool generates power',
    'Heaters emit sparks',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does a ball bounce lower each time?',
    'Energy is lost to heat and sound',
    'Air pushes it down',
    'Gravity strengthens',
    'The ball shrinks',
    'easy',
    'Everyday Science',
  ],
  [
    'Why do sharp knives cut better?',
    'Pressure is higher on a small edge',
    'They are heavier',
    'Steel is colder',
    'They are smoother',
    'easy',
    'Everyday Science',
  ],
  [
    'Why do wheels reduce friction?',
    'Rolling friction is less than sliding friction',
    'Wheels cool the road',
    'Rubber repels ground',
    'Spokes add lift',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does a siphon move water uphill then down?',
    'Atmospheric pressure and gravity drive the flow',
    'Capillary action',
    'Magnetism',
    'Air pressure only upward',
    'expert',
    'Everyday Science',
  ],
  [
    'Why does hot water sometimes freeze faster than cold? The Mpemba effect under certain conditions',
    'Under special conditions called the Mpemba effect',
    'Hot water is purer always',
    'It never can',
    'Fridges favor warmth',
    'expert',
    'Everyday Science',
  ],
  [
    'Why do we hear the ocean in shells?',
    'Ambient noise resonates in the shell',
    'The shell stores sea sounds',
    'Water echoes inside',
    'Ears imagine the sea',
    'hard',
    'Everyday Science',
  ],
  [
    'Why does chewing gum stick to hair?',
    'Its polymers bond with hair proteins',
    'Heat melts it in',
    'Sugar glues it',
    'Static attracts it',
    'medium',
    'Everyday Science',
  ],
  [
    'Why do bubbles form in boiling water?',
    'Water vapor forms inside the liquid',
    'Air escapes from the pot only',
    'Salt releases gas',
    'Heat splits hydrogen',
    'medium',
    'Everyday Science',
  ],
  [
    'Why do flies rub their front legs?',
    'They clean sensory receptors',
    'They are cold',
    'They signal others',
    'They sharpen claws',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does popcorn pop?',
    'Steam builds until the kernel bursts',
    'Heat explodes starch directly',
    'Oil cracks the shell',
    'Salt reacts inside',
    'medium',
    'Everyday Science',
  ],
  [
    'Why does a refrigerator door stick shut sometimes?',
    'Warm air cools, lowering pressure inside',
    'Magnetism increases',
    'Rubber melts slightly',
    'Cold fuses the seal',
    'medium',
    'Everyday Science',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const ARTS = [
  [
    'Who painted the Mona Lisa?',
    'Leonardo da Vinci',
    'Michelangelo',
    'Raphael',
    'Donatello',
    'easy',
    'Arts & Music',
  ],
  [
    'Who painted the Starry Night?',
    'Vincent van Gogh',
    'Claude Monet',
    'Pablo Picasso',
    'Salvador Dali',
    'easy',
    'Arts & Music',
  ],
  [
    'Who painted the Sistine Chapel ceiling?',
    'Michelangelo',
    'Leonardo da Vinci',
    'Raphael',
    'Botticelli',
    'easy',
    'Arts & Music',
  ],
  [
    'Who painted The Persistence of Memory with melting clocks?',
    'Salvador Dali',
    'Rene Magritte',
    'Joan Miro',
    'Pablo Picasso',
    'medium',
    'Arts & Music',
  ],
  [
    'Who painted Girl with a Pearl Earring?',
    'Johannes Vermeer',
    'Rembrandt',
    'Frans Hals',
    'Jan Steen',
    'medium',
    'Arts & Music',
  ],
  [
    'Who painted water lilies at Giverny?',
    'Claude Monet',
    'Vincent van Gogh',
    'Camille Pissarro',
    'Edouard Manet',
    'medium',
    'Arts & Music',
  ],
  [
    'Who painted Guernica?',
    'Pablo Picasso',
    'Diego Rivera',
    'Joan Miro',
    'Francisco Goya',
    'medium',
    'Arts & Music',
  ],
  [
    'Who painted The Night Watch?',
    'Rembrandt',
    'Vermeer',
    'Van Gogh',
    'Rubens',
    'medium',
    'Arts & Music',
  ],
  [
    'Who sculpted David in Florence?',
    'Michelangelo',
    'Donatello made a bronze version',
    'Bernini',
    'Rodin',
    'medium',
    'Arts & Music',
  ],
  [
    'Who sculpted The Thinker?',
    'Auguste Rodin',
    'Camille Claudel',
    'Henri Matisse',
    'Alberto Giacometti',
    'medium',
    'Arts & Music',
  ],
  [
    'Who founded Impressionism naming from Impression Sunrise?',
    'Claude Monet',
    'Edgar Degas',
    'Pierre-Auguste Renoir',
    'Paul Cezanne',
    'medium',
    'Arts & Music',
  ],
  [
    'Who co-founded Cubism with Georges Braque?',
    'Pablo Picasso',
    'Henri Matisse',
    'Fernand Leger',
    'Juan Gris',
    'medium',
    'Arts & Music',
  ],
  [
    'Who painted The Scream?',
    'Edvard Munch',
    'Gustav Klimt',
    'Egon Schiele',
    'Otto Dix',
    'medium',
    'Arts & Music',
  ],
  [
    'Who painted the Mona Lisa of the north called Arnolfini Portrait?',
    'Jan van Eyck',
    'Hans Holbein',
    'Rogier van der Weyden',
    'Pieter Bruegel',
    'expert',
    'Arts & Music',
  ],
  [
    'Who painted Sunflowers in Arles?',
    'Vincent van Gogh',
    'Paul Gauguin',
    'Claude Monet',
    'Henri Rousseau',
    'easy',
    'Arts & Music',
  ],
  [
    'Which composer wrote the Ninth Symphony with Ode to Joy?',
    'Ludwig van Beethoven',
    'Wolfgang Mozart',
    'Franz Schubert',
    'Johannes Brahms',
    'easy',
    'Arts & Music',
  ],
  [
    'Which composer wrote The Magic Flute?',
    'Wolfgang Amadeus Mozart',
    'Richard Wagner',
    'Giuseppe Verdi',
    'Gioachino Rossini',
    'medium',
    'Arts & Music',
  ],
  [
    'Which composer wrote The Four Seasons?',
    'Antonio Vivaldi',
    'Johann Sebastian Bach',
    'George Handel',
    'Arcangelo Corelli',
    'medium',
    'Arts & Music',
  ],
  [
    'Which composer wrote the Moonlight Sonata?',
    'Ludwig van Beethoven',
    'Franz Liszt',
    'Frederic Chopin',
    'Robert Schumann',
    'medium',
    'Arts & Music',
  ],
  [
    'Which composer wrote the Brandenburg Concertos?',
    'Johann Sebastian Bach',
    'Antonio Vivaldi',
    'George Handel',
    'Joseph Haydn',
    'medium',
    'Arts & Music',
  ],
  [
    'Which composer wrote Swan Lake and The Nutcracker?',
    'Pyotr Tchaikovsky',
    'Sergei Prokofiev',
    'Igor Stravinsky',
    'Rimsky-Korsakov',
    'medium',
    'Arts & Music',
  ],
  [
    'Which composer wrote Rhapsody in Blue?',
    'George Gershwin',
    'Cole Porter',
    'Aaron Copland',
    'Duke Ellington',
    'medium',
    'Arts & Music',
  ],
  [
    'Which composer went deaf late in life?',
    'Ludwig van Beethoven',
    'Joseph Haydn',
    'Franz Schubert',
    'Richard Strauss',
    'easy',
    'Arts & Music',
  ],
  [
    'Which opera did Mozart write last?',
    'The Magic Flute among his final works',
    'Don Giovanni',
    'The Marriage of Figaro',
    'Cosi fan tutte',
    'expert',
    'Arts & Music',
  ],
  [
    'What does a conductor lead?',
    'An orchestra or choir',
    'A painting class',
    'A film crew',
    'A marching band only',
    'easy',
    'Arts & Music',
  ],
  [
    'How many strings does a standard violin have?',
    'Four',
    'Five',
    'Six',
    'Three',
    'easy',
    'Arts & Music',
  ],
  [
    'How many strings does a standard guitar have?',
    'Six',
    'Four',
    'Seven',
    'Twelve in all cases',
    'easy',
    'Arts & Music',
  ],
  ['How many keys does a standard piano have?', '88', '76', '61', '96', 'medium', 'Arts & Music'],
  [
    'Which instrument is the largest in a standard orchestra?',
    'The pipe organ in halls; in orchestra the double bass commonly',
    'The harp',
    'The tuba',
    'The timpani',
    'expert',
    'Arts & Music',
  ],
  [
    'Which brass instrument has a slide?',
    'The trombone',
    'The trumpet',
    'The French horn',
    'The tuba',
    'easy',
    'Arts & Music',
  ],
  [
    'Which woodwind uses a double reed?',
    'The oboe',
    'The clarinet',
    'The flute',
    'The saxophone',
    'medium',
    'Arts & Music',
  ],
  [
    'Which percussion instrument has tuned kettles?',
    'The timpani',
    'The snare drum',
    'The bass drum',
    'The xylophone',
    'medium',
    'Arts & Music',
  ],
  [
    'What does tempo mean in music?',
    'Speed',
    'Volume',
    'Pitch',
    'Rhythm pattern',
    'easy',
    'Arts & Music',
  ],
  ['What does forte mean in music?', 'Loud', 'Soft', 'Fast', 'Slow', 'easy', 'Arts & Music'],
  [
    'What does piano mean as a dynamic?',
    'Soft',
    'Loud',
    'Quick',
    'Gentle only',
    'easy',
    'Arts & Music',
  ],
  [
    'What is a lullaby?',
    'A soothing song for sleep',
    'A marching tune',
    'A folk dance song',
    'A wedding song',
    'easy',
    'Arts & Music',
  ],
  [
    'What is a duet?',
    'A performance by two people',
    'Three performers',
    'A solo act',
    'A full choir',
    'easy',
    'Arts & Music',
  ],
  [
    'What is an orchestra section of violins called?',
    'The string section',
    'The brass section',
    'The woodwinds',
    'The percussion',
    'easy',
    'Arts & Music',
  ],
  [
    'What is a fresco?',
    'A painting on wet plaster',
    'A marble statue',
    'A stained glass panel',
    'An etched print',
    'medium',
    'Arts & Music',
  ],
  [
    'What is a self-portrait?',
    'An artist painting themselves',
    'A royal portrait',
    'A landscape',
    'A still life',
    'easy',
    'Arts & Music',
  ],
  [
    'What is a triptych?',
    'A three-panel artwork',
    'A single canvas',
    'A folded sketchbook',
    'A carved column',
    'medium',
    'Arts & Music',
  ],
  [
    'What is pottery fired in?',
    'A kiln',
    'An oven only',
    'A forge',
    'A smelter',
    'easy',
    'Arts & Music',
  ],
  [
    'What is origami?',
    'The art of paper folding',
    'Japanese calligraphy',
    'Flower arranging',
    'Tea ceremony',
    'easy',
    'Arts & Music',
  ],
  [
    'What is henna used for culturally?',
    'Decorative skin art',
    'Hair removal only',
    'Fabric dyeing only',
    'Food coloring',
    'medium',
    'Arts & Music',
  ],
  [
    'What is a mural?',
    'A large wall painting',
    'A framed portrait',
    'A sculpture garden',
    'A mosaic floor only',
    'easy',
    'Arts & Music',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const TECH_INVENTIONS = [
  [
    'Which country invented paper money first?',
    'China',
    'Sweden',
    'Italy',
    'India',
    'medium',
    'Tech & Inventions',
  ],
  [
    'Which country invented ice cream cones at the 1904 fair commonly credited?',
    'The United States',
    'Italy',
    'France',
    'China',
    'expert',
    'Tech & Inventions',
  ],
  [
    'Which civilization invented soap earliest known?',
    'The Babylonians',
    'The Romans',
    'The Greeks',
    'The Egyptians',
    'expert',
    'Tech & Inventions',
  ],
  [
    'Which ancient people invented the 24-hour day division? The Egyptians',
    'The Egyptians',
    'The Babylonians only',
    'The Greeks',
    'The Romans',
    'expert',
    'Tech & Inventions',
  ],
  [
    'Which civilization first used玻璃 windows widely? None until Roman era glass',
    'The Romans pioneered glass windows',
    'The Chinese',
    'The Persians',
    'The Aztecs',
    'expert',
    'Tech & Inventions',
  ],
  [
    'Which culture invented the abacus ancestors around 2700 BC?',
    'The Sumerians',
    'The Chinese',
    'The Greeks',
    'The Egyptians',
    'expert',
    'Tech & Inventions',
  ],
  [
    'Which Chinese invention aided navigation after the compass?',
    'Gunpowder',
    'Paper',
    'Printing',
    'The kite',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Alessandro Volta invent in 1800 that changed science?',
    'The electric battery',
    'The light bulb',
    'The motor',
    'The generator',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Samuel Morse invent the practical version of in America?',
    'The telegraph',
    'The telephone',
    'The radio',
    'The typewriter',
    'easy',
    'Tech & Inventions',
  ],
  [
    'What did Alexander Graham Bell invent in 1876?',
    'The telephone',
    'The telegraph',
    'The phonograph',
    'The radio',
    'easy',
    'Tech & Inventions',
  ],
  [
    'What did Thomas Edison invent in 1877?',
    'The phonograph',
    'The telephone',
    'The camera',
    'The television',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did the Lumiere brothers debut in 1895?',
    'Cinema projection',
    'The radio',
    'The television',
    'The phonograph',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Guglielmo Marconi develop?',
    'Radio transmission',
    'Television',
    'Radar',
    'The telephone',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Karl Benz invent in 1885-86?',
    'The gasoline automobile',
    'The diesel engine',
    'The motorcycle',
    'The assembly line',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Orville and Wilbur Wright invent in 1903?',
    'The airplane',
    'The helicopter',
    'The glider hang glider',
    'The jet engine',
    'easy',
    'Tech & Inventions',
  ],
  [
    'What did John Logie Baird demonstrate in 1926?',
    'Mechanical television',
    'Radio broadcasting',
    'Color film',
    'The video recorder',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did ENIAC become in 1945?',
    'A general-purpose electronic computer',
    'The first robot',
    'A nuclear reactor',
    'A satellite computer',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Douglas Engelbart invent in the 1960s?',
    'The computer mouse',
    'The keyboard',
    'The monitor',
    'The floppy disk',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Steve Wozniak and Steve Jobs found in 1976?',
    'Apple',
    'Microsoft',
    'IBM PC division',
    'Commodore',
    'easy',
    'Tech & Inventions',
  ],
  [
    'What did Tim Berners-Lee create in 1989?',
    'The World Wide Web',
    'Email',
    'The search engine',
    'Social media',
    'easy',
    'Tech & Inventions',
  ],
  [
    'What did the Wright brothers first flight last?',
    'About 12 seconds',
    'About 2 minutes',
    'About 30 minutes',
    'About one hour',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What everyday item did Earl Tupper invent containers from?',
    'Polyethylene plastic',
    'Glass',
    'Aluminum',
    'Rubber',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did King Gillette invent the disposable version of in 1901?',
    'The safety razor blade',
    'The toothbrush',
    'The comb',
    'Scissors',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Willis Carrier design in 1902?',
    'Modern air conditioning',
    'The refrigerator',
    'The freezer',
    'The radiator',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Josephine Cochrane invent in 1886?',
    'The practical dishwasher',
    'The washing machine',
    'The vacuum cleaner',
    'The sewing machine',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Mary Anderson invent in 1903?',
    'The windshield wiper',
    'The rearview mirror',
    'Car headlights',
    'Traffic lights',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Hedy Lamarr co-invent that led to Wi-Fi and Bluetooth?',
    'Frequency hopping spread spectrum',
    'The semiconductor',
    'The laser',
    'Fiber optics',
    'hard',
    'Tech & Inventions',
  ],
  [
    'What did Grace Hopper pioneer in computing?',
    'The compiler concept',
    'The microchip',
    'The keyboard layout',
    'The modem',
    'hard',
    'Tech & Inventions',
  ],
  [
    'What did Garrett Morgan invent besides the safety hood?',
    'An early traffic signal',
    'The elevator brake',
    'The escalator',
    'The turnstile',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Alfred Nobel invent in 1867?',
    'Dynamite',
    'Gunpowder',
    'Nitroglycerin discovered by others',
    'The grenade',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Charles Macintosh invent in 1823?',
    'Waterproof fabric',
    'The rain umbrella modern',
    'The zipper',
    'Velcro',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Levi Strauss and Jacob Davis patent in 1873?',
    'Riveted blue jeans',
    'The belt',
    'The hoodie',
    'Sneakers',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did John Harvey Kellogg invent accidentally with his brother?',
    'Corn flakes',
    'Potato chips',
    'Coca-Cola',
    'Cotton candy',
    'easy',
    'Tech & Inventions',
  ],
  [
    'What did George Crum reportedly invent in 1853?',
    'Potato chips',
    'Corn flakes',
    'Cotton candy',
    'Peanut butter',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Frank Epperson invent by accident in 1905?',
    'The popsicle',
    'Ice cream sandwich',
    'Cotton candy',
    'Jelly beans',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Percy Spencer use to invent the microwave in 1945?',
    'Radar magnetron research',
    'X-ray machines',
    'Radio towers',
    'Light bulbs',
    'hard',
    'Tech & Inventions',
  ],
  [
    'What did Walter Hunt invent in 1849 and sell the rights cheaply?',
    'The safety pin',
    'The paper clip',
    'The stapler',
    'The zipper',
    'hard',
    'Tech & Inventions',
  ],
  [
    'What did Johan Vaaler and others design around 1899?',
    'The paper clip',
    'The safety pin',
    'The staple',
    'The binder clip',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Cyrus West Field lay across the Atlantic in 1858 first attempt?',
    'A telegraph cable',
    'A pipeline',
    'A radio tower chain',
    'A shipping lane marker',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did John Loud patent an early version of in 1888?',
    'The ballpoint pen',
    'The fountain pen',
    'The pencil eraser',
    'The marker',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Lazlo Biro improve for the RAF in the 1930s?',
    'The ballpoint pen',
    'The fountain pen',
    'The pencil',
    'The typewriter ribbon',
    'medium',
    'Tech & Inventions',
  ],
  [
    'What did Whitcomb Judson invent an early version of in 1893?',
    'The zipper',
    'The velcro',
    'The button',
    'The snap',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did William Addis invent in prison in 1770?',
    'The modern toothbrush',
    'Dental floss',
    'Toothpaste tube',
    'Mouthwash',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Eric Rotheim invent in 1926 that changed packaging?',
    'The aerosol spray can',
    'The juice box',
    'The plastic bottle',
    'The can opener',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Chester Greenwood invent at age 15 in 1873?',
    'Earmuffs',
    'The thermometer cover',
    'The scarf clip',
    'Snow goggles',
    'expert',
    'Tech & Inventions',
  ],
  [
    'What did Melitta Bentz invent in 1908?',
    'The paper coffee filter',
    'The espresso machine',
    'The teabag',
    'Instant coffee',
    'expert',
    'Tech & Inventions',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const MIXED = [
  [
    'What is the hardest natural substance?',
    'Diamond',
    'Quartz',
    'Titanium',
    'Obsidian',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the softest mineral on Mohs scale?',
    'Talc',
    'Gypsum',
    'Graphite',
    'Chalk',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What metal is liquid at room temperature?',
    'Mercury',
    'Lead',
    'Tin',
    'Aluminum',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What gas makes up most of the sun?',
    'Hydrogen',
    'Helium',
    'Oxygen',
    'Nitrogen',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the most abundant metal in the Earth crust?',
    'Aluminum',
    'Iron',
    'Copper',
    'Zinc',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the rarest naturally occurring element on Earth roughly?',
    'Astatine',
    'Gold',
    'Platinum',
    'Iridium',
    'expert',
    'Mixed Trivia',
  ],
  [
    'What is the hardest tissue in the human body?',
    'Tooth enamel',
    'Bone',
    'Cartilage',
    'Nail',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the fastest land animal over short distances?',
    'The cheetah',
    'The lion',
    'The horse',
    'The antelope',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the largest internal organ?',
    'The liver',
    'The stomach',
    'The lungs',
    'The brain',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the smallest bone in the body?',
    'The stapes',
    'The clavicle',
    'The kneecap',
    'The pinky bone',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which planet spins backward relative to most?',
    'Venus',
    'Mars',
    'Mercury',
    'Jupiter',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which planet has the most moons confirmed recently?',
    'Saturn',
    'Jupiter',
    'Uranus',
    'Neptune',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the closest star system to Earth?',
    'Alpha Centauri',
    'Sirius',
    'Betelgeuse',
    'Procyon',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What constellation is Orion the hunter part of? It is one itself',
    'Orion is its own constellation',
    'Ursa Major',
    'Cassiopeia',
    'Pegasus',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the largest desert in Africa?',
    'The Sahara',
    'The Kalahari',
    'The Namib',
    'The Danakil',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the largest bay in India?',
    'The Bay of Bengal',
    'The Gulf of Khambhat',
    'The Gulf of Kutch',
    'The Palk Bay',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the currency of Japan?',
    'The yen',
    'The yuan',
    'The won',
    'The ringgit',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the currency of the United Kingdom?',
    'The pound sterling',
    'The euro',
    'The franc',
    'The krona',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the currency of Switzerland?',
    'The Swiss franc',
    'The euro',
    'The krona',
    'The forint',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the currency of India?',
    'The rupee',
    'The taka',
    'The ringgit',
    'The rial',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the currency of Russia?',
    'The ruble',
    'The hryvnia',
    'The zloty',
    'The mark',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the currency of Mexico?',
    'The Mexican peso',
    'The bolivar',
    'The sol',
    'The quetzal',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the currency of Saudi Arabia?',
    'The riyal',
    'The dirham',
    'The dinar',
    'The rial',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the currency of South Africa?',
    'The rand',
    'The shilling',
    'The naira',
    'The cedi',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the currency of Australia?',
    'The Australian dollar',
    'The pound',
    'The franc',
    'The kina',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What color is a classic school bus in the United States?',
    'Yellow',
    'Blue',
    'Red',
    'White',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What color is the Black Box flight recorder actually?',
    'Orange',
    'Black',
    'Red',
    'Gray',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What color is a polar bears fur actually? Transparent hairs over black skin',
    'White-looking hollow hairs',
    'Pink',
    'Gray only',
    'Brown',
    'medium',
    'Mixed Trivia',
  ],
  ['What color is the sunset on Mars?', 'Blue', 'Red', 'Yellow', 'Green', 'expert', 'Mixed Trivia'],
  [
    'What fruit is used to make guacamole?',
    'Avocado',
    'Lime only',
    'Tomatillo',
    'Mango',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which fruit has its seeds on the outside?',
    'Strawberry',
    'Blueberry',
    'Grape',
    'Cherry',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which fruit is known as the king of fruits in Southeast Asia?',
    'Durian',
    'Mango',
    'Jackfruit',
    'Rambutan',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which vegetable is Popeye famous for eating?',
    'Spinach',
    'Broccoli',
    'Carrot',
    'Kale',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which spice is the most expensive by weight?',
    'Saffron',
    'Vanilla',
    'Cardamom',
    'Cinnamon',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which nut is used to make marzipan?',
    'Almond',
    'Cashew',
    'Walnut',
    'Pecan',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which drink is made from fermented grapes?',
    'Wine',
    'Beer',
    'Cider',
    'Mead',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which drink is made from fermented barley and hops?',
    'Beer',
    'Wine',
    'Rum',
    'Vodka',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which spirit is made from sugarcane?',
    'Rum',
    'Vodka',
    'Gin',
    'Whisky',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which drink is traditionally brewed from tea leaves and bacteria culture?',
    'Kombucha',
    'Kefir',
    'Kvass',
    'Chai',
    'hard',
    'Mixed Trivia',
  ],
  ['What is tofu made from?', 'Soybeans', 'Chickpeas', 'Lentils', 'Rice', 'easy', 'Mixed Trivia'],
  [
    'What is hummus made from?',
    'Chickpeas',
    'Lentils',
    'Fava beans',
    'Peas',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which country invented tea drinking culture earliest?',
    'China',
    'India',
    'Japan',
    'England',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country is the largest tea producer?',
    'China',
    'India',
    'Kenya',
    'Sri Lanka',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which bean is used in traditional chocolate?',
    'Cacao',
    'Coffee',
    'Vanilla',
    'Soy',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which country consumes the most coffee per capita?',
    'Finland',
    'Brazil',
    'The United States',
    'Italy',
    'expert',
    'Mixed Trivia',
  ],
  [
    'Which insect makes honey?',
    'The honeybee',
    'The wasp',
    'The hornet',
    'The ant',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which breakfast food is made from beaten eggs cooked flat?',
    'An omelet',
    'A frittata baked',
    'A quiche in pastry',
    'A pancake',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which Italian dish is a baked layered pasta?',
    'Lasagna',
    'Ravioli',
    'Risotto',
    'Carbonara',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which Mexican dish is a folded tortilla with filling?',
    'A taco',
    'A burrito rolled large',
    'A nacho',
    'A tamale in husk',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which Japanese dish is vinegared rice with fish?',
    'Sushi',
    'Sashimi raw fish only',
    'Ramen soup',
    'Tempura fried',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which country invented pizza as known today?',
    'Italy',
    'Greece',
    'The United States',
    'Turkey',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which French soup is made with onions and beef stock?',
    'French onion soup',
    'Bouillabaisse seafood',
    'Vichyssoise cold leek',
    'Ratatouille stew',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which Indian dish is lentil stew?',
    'Dal',
    'Biryani rice dish',
    'Naan bread',
    'Samosa pastry',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which Middle Eastern food is ground chickpea fritters?',
    'Falafel',
    'Shawarma meat',
    'Baba ganoush eggplant',
    'Tabbouleh salad',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which African country is injera flatbread from?',
    'Ethiopia',
    'Nigeria',
    'Morocco',
    'Kenya',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country eats the most ice cream per capita? The United States or New Zealand by source',
    'The United States by many measures',
    'Italy',
    'Japan',
    'Australia',
    'expert',
    'Mixed Trivia',
  ],
  [
    'What is the main ingredient in guacamole besides avocado? Lime and cilantro',
    'Lime juice',
    'Onion only',
    'Garlic only',
    'Tomato only',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which tree gives maple syrup?',
    'The sugar maple',
    'The oak',
    'The birch',
    'The pine',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country produces the most maple syrup?',
    'Canada',
    'The United States',
    'Sweden',
    'Russia',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the most consumed drink in the world after water?',
    'Tea',
    'Coffee',
    'Beer',
    'Milk',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which fruit floats because it is 25 percent air?',
    'An apple',
    'An orange',
    'A banana',
    'A pear',
    'expert',
    'Mixed Trivia',
  ],
  [
    'What color is a ripe banana peel?',
    'Yellow',
    'Green',
    'Red',
    'Brown from the start',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which berry is actually a false berry botanically? Bananas are berries too',
    'The strawberry is an accessory fruit',
    'Blueberry',
    'Cranberry',
    'Raspberry',
    'expert',
    'Mixed Trivia',
  ],
  [
    'Which food is fermented to make kimchi?',
    'Cabbage',
    'Cucumber',
    'Radish only',
    'Spinach',
    'medium',
    'Mixed Trivia',
  ],
  ['Which country is kimchi from?', 'Korea', 'China', 'Japan', 'Thailand', 'easy', 'Mixed Trivia'],
  [
    'What is the hottest chili pepper as of recent years?',
    'The Carolina Reaper',
    'The Ghost Pepper',
    'The Habanero',
    'The Jalapeno',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country gifted the Statue of Liberty to the US? France',
    'France',
    'Britain',
    'Spain',
    'Italy',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which tower is the tallest in Paris?',
    'The Eiffel Tower',
    'Montparnasse Tower',
    'Notre-Dame',
    'The Arc de Triomphe',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which London clock tower is famous?',
    'The Elizabeth Tower with Big Ben bell',
    'The Victoria Tower',
    'St. Pauls tower',
    'The Shard',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which bridge is famous in San Francisco?',
    'The Golden Gate Bridge',
    'The Bay Bridge',
    'The Brooklyn Bridge',
    'The Tower Bridge',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which monument is in Agra, India?',
    'The Taj Mahal',
    'The Red Fort in Delhi',
    'The Amber Fort in Jaipur',
    'Qutub Minar in Delhi',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which ancient city is carved into rose-red rock in Jordan?',
    'Petra',
    'Palmyra',
    'Baalbek',
    'Jerash',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which wall runs across northern England?',
    'Hadrians Wall',
    'The Antonine Wall in Scotland',
    'Offas Dyke',
    'The Great Wall',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which famous stone heads are on Easter Island?',
    'The moai',
    'The Olmec heads in Mexico',
    'The sphinxes',
    'The terracotta army',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which terracotta army guards an emperor in China?',
    'Qin Shi Huangs army in Xian',
    'The Ming tombs army',
    'The Forbidden City guards',
    'The Great Wall statues',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which island has the Colosseum? Rome is on mainland Italy',
    'None; it is in Rome on the mainland',
    'Sicily',
    'Sardinia',
    'Capri',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which palace is in Versailles?',
    'The Palace of Versailles',
    'The Louvre',
    'The Elysee Palace',
    'Fontainebleau',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which museum holds the Mona Lisa?',
    'The Louvre',
    'The Prado',
    'The Uffizi',
    'The Hermitage',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which museum is in Saint Petersburg?',
    'The Hermitage',
    'The Kremlin museums only',
    'The Tretyakov in Moscow',
    'The Pushkin in Moscow',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which tower leans in Italy?',
    'The Tower of Pisa',
    'The Tower of Bologna',
    'The Mole Antonelliana',
    'The Torre Agbar',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which bridge crosses the River Thames near the Tower of London?',
    'Tower Bridge',
    'London Bridge',
    'Westminster Bridge',
    'Waterloo Bridge',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which opera house is famous in Sydney?',
    'The Sydney Opera House',
    'The Sydney Theatre',
    'The Capitol Theatre',
    'The State Theatre',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which canyon is in Arizona?',
    'The Grand Canyon',
    'Bryce Canyon in Utah',
    'Zion Canyon in Utah',
    'Copper Canyon in Mexico',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which falls straddle Canada and the United States?',
    'Niagara Falls',
    'Victoria Falls',
    'Iguazu Falls',
    'Angel Falls',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which falls is the tallest uninterrupted in the world?',
    'Angel Falls in Venezuela',
    'Niagara Falls',
    'Victoria Falls',
    'Tugela Falls partially segmented',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which reef is the largest in the world?',
    'The Great Barrier Reef',
    'The Belize Barrier Reef',
    'The Red Sea reefs',
    'The Maldives reefs',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which volcano buried Pompeii?',
    'Mount Vesuvius',
    'Mount Etna',
    'Mount Stromboli',
    'Mount Etna again',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which island nation is known as the Land of Fire and Ice?',
    'Iceland',
    'Greenland',
    'Norway',
    'Japan',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which animals pull sleds in the Iditarod race?',
    'Dogs',
    'Horses',
    'Reindeer',
    'Wolves',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which city hosts the famous running of the bulls?',
    'Pamplona',
    'Madrid',
    'Barcelona',
    'Seville',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country hosts the Rio Carnival?',
    'Brazil',
    'Argentina',
    'Colombia',
    'Venezuela',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which festival is known as the festival of colors in India?',
    'Holi',
    'Diwali',
    'Onam',
    'Eid',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which festival is known as the festival of lights in India?',
    'Diwali',
    'Holi',
    'Navratri',
    'Raksha Bandhan',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which festival features giant lanterns in Thailand?',
    'Yi Peng and Loy Krathong',
    'Songkran water festival',
    'Chingay parade',
    'Gion festival',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which Spanish festival features tomato throwing?',
    'La Tomatina',
    'San Fermin',
    'Las Fallas',
    'Feria de Abril',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country celebrates Songkran with water fights?',
    'Thailand',
    'Vietnam',
    'Laos only',
    'Myanmar',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which American festival features music and art in the desert?',
    'Burning Man',
    'Coachella music only',
    'Bonnaroo',
    'Lollapalooza',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which Irish festival is celebrated worldwide in March?',
    'St. Patricks Day',
    'Bloomsday',
    'Halloween origins',
    'May Day',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which Mexican holiday honors the dead?',
    'Day of the Dead',
    'Cinco de Mayo',
    'Independence Day',
    'Las Posadas',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which Jewish holiday is known as the Festival of Lights?',
    'Hanukkah',
    'Passover',
    'Purim',
    'Yom Kippur',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which Jewish holiday commemorates the Exodus?',
    'Passover',
    'Hanukkah',
    'Rosh Hashanah',
    'Sukkot',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which Muslim month involves fasting?',
    'Ramadan',
    'Muharram',
    'Shawwal',
    'Rajab',
    'easy',
    'Mixed Trivia',
  ],
  [
    'Which festival follows Ramadan?',
    'Eid al-Fitr',
    'Eid al-Adha',
    'Ashura',
    'Mawlid',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which festival celebrates the sacrifice feast in Islam?',
    'Eid al-Adha',
    'Eid al-Fitr',
    'Mawlid',
    'Laylat al-Qadr',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country invented the fortune cookie? The United States via Japanese bakers',
    'The United States',
    'China',
    'Japan originally',
    'Taiwan',
    'expert',
    'Mixed Trivia',
  ],
  [
    'What is the national animal of Scotland unicorn? It is officially the unicorn',
    'The unicorn',
    'The lion',
    'The stag',
    'The eagle',
    'expert',
    'Mixed Trivia',
  ],
  [
    'What is the national animal of India?',
    'The Bengal tiger',
    'The lion',
    'The elephant',
    'The peacock is the bird',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the national bird of India?',
    'The peacock',
    'The parrot',
    'The eagle',
    'The crane',
    'medium',
    'Mixed Trivia',
  ],
  [
    'What is the national animal of China?',
    'The giant panda',
    'The tiger',
    'The dragon mythical',
    'The crane',
    'easy',
    'Mixed Trivia',
  ],
  [
    'What is the national flower of Japan commonly?',
    'The cherry blossom',
    'The chrysanthemum is the imperial seal',
    'The lotus',
    'The rose',
    'expert',
    'Mixed Trivia',
  ],
  [
    'What is the national flower of India?',
    'The lotus',
    'The rose',
    'The jasmine',
    'The marigold',
    'medium',
    'Mixed Trivia',
  ],
  [
    'Which country has a unicorn on its coat of arms with Britain? Scotland uses it',
    'Scotland',
    'Wales',
    'Ireland',
    'France',
    'expert',
    'Mixed Trivia',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const LANGUAGE_WORDS = [
  [
    'What is a synonym for happy?',
    'Joyful',
    'Angry',
    'Sleepy',
    'Hungry',
    'easy',
    'Language & Words',
  ],
  ['What is a synonym for fast?', 'Quick', 'Slow', 'Heavy', 'Late', 'easy', 'Language & Words'],
  ['What is a synonym for smart?', 'Clever', 'Dull', 'Foolish', 'Lazy', 'easy', 'Language & Words'],
  ['What is a synonym for big?', 'Large', 'Tiny', 'Narrow', 'Short', 'easy', 'Language & Words'],
  ['What is a synonym for afraid?', 'Scared', 'Brave', 'Calm', 'Angry', 'easy', 'Language & Words'],
  ['What is a synonym for begin?', 'Start', 'End', 'Pause', 'Finish', 'easy', 'Language & Words'],
  ['What is a synonym for wealthy?', 'Rich', 'Poor', 'Needy', 'Broke', 'easy', 'Language & Words'],
  ['What is a synonym for quiet?', 'Silent', 'Loud', 'Noisy', 'Bright', 'easy', 'Language & Words'],
  [
    'What is a synonym for difficult?',
    'Hard',
    'Easy',
    'Simple',
    'Plain',
    'easy',
    'Language & Words',
  ],
  [
    'What is a synonym for beautiful?',
    'Gorgeous',
    'Ugly',
    'Plain',
    'Dull',
    'easy',
    'Language & Words',
  ],
  ['What is an antonym for hot?', 'Cold', 'Warm', 'Boiling', 'Mild', 'easy', 'Language & Words'],
  [
    'What is an antonym for full?',
    'Empty',
    'Complete',
    'Packed',
    'Filled',
    'easy',
    'Language & Words',
  ],
  [
    'What is an antonym for winner?',
    'Loser',
    'Champion',
    'Leader',
    'Hero',
    'easy',
    'Language & Words',
  ],
  ['What is an antonym for early?', 'Late', 'Soon', 'Prompt', 'Quick', 'easy', 'Language & Words'],
  [
    'What is an antonym for remember?',
    'Forget',
    'Recall',
    'Memorize',
    'Replay',
    'easy',
    'Language & Words',
  ],
  [
    'What is an antonym for accept?',
    'Reject',
    'Receive',
    'Approve',
    'Admit',
    'easy',
    'Language & Words',
  ],
  [
    'What is an antonym for brave?',
    'Fearful',
    'Bold',
    'Daring',
    'Bold again',
    'easy',
    'Language & Words',
  ],
  [
    'What is an antonym for vertical?',
    'Horizontal',
    'Diagonal',
    'Upright',
    'Elevated',
    'easy',
    'Language & Words',
  ],
  [
    'What is an antonym for import?',
    'Export',
    'Ship',
    'Buy',
    'Sell abroad',
    'easy',
    'Language & Words',
  ],
  [
    'What is an antonym for artificial?',
    'Natural',
    'Fake',
    'Plastic',
    'Manufactured',
    'easy',
    'Language & Words',
  ],
  ['What is the plural of mouse?', 'Mice', 'Mouses', 'Mices', 'Mouse', 'easy', 'Language & Words'],
  [
    'What is the plural of goose?',
    'Geese',
    'Gooses',
    'Goosen',
    'Goose',
    'easy',
    'Language & Words',
  ],
  [
    'What is the plural of child?',
    'Children',
    'Childs',
    'Childes',
    'Childrens',
    'easy',
    'Language & Words',
  ],
  [
    'What is the plural of tooth?',
    'Teeth',
    'Tooths',
    'Teeths',
    'Tooth',
    'easy',
    'Language & Words',
  ],
  [
    'What is the plural of cactus?',
    'Cacti',
    'Cactuses only',
    'Cactae',
    'Cactus',
    'medium',
    'Language & Words',
  ],
  [
    'What is the plural of crisis?',
    'Crises',
    'Crisises',
    'Crisis',
    'Criseses',
    'medium',
    'Language & Words',
  ],
  [
    'What is the plural of phenomenon?',
    'Phenomena',
    'Phenomenons only',
    'Phenomenae',
    'Phenomenon',
    'medium',
    'Language & Words',
  ],
  [
    'What is the plural of alumnus?',
    'Alumni',
    'Alumnuses',
    'Alumni only for males',
    'Alumnae',
    'medium',
    'Language & Words',
  ],
  ['What is the past tense of go?', 'Went', 'Goed', 'Gone', 'Going', 'easy', 'Language & Words'],
  ['What is the past tense of eat?', 'Ate', 'Eated', 'Eaten', 'Eating', 'easy', 'Language & Words'],
  [
    'What is the past tense of buy?',
    'Bought',
    'Buyed',
    'Boughten',
    'Buying',
    'easy',
    'Language & Words',
  ],
  [
    'What is the past tense of run?',
    'Ran',
    'Runned',
    'Runned',
    'Running',
    'easy',
    'Language & Words',
  ],
  [
    'What is the past tense of bring?',
    'Brought',
    'Bringed',
    'Brung standard',
    'Bringing',
    'medium',
    'Language & Words',
  ],
  [
    'What is the superlative of good?',
    'Best',
    'Goodest',
    'Better',
    'Most good',
    'easy',
    'Language & Words',
  ],
  [
    'What is the comparative of bad?',
    'Worse',
    'Badder',
    'Worst',
    'More bad',
    'easy',
    'Language & Words',
  ],
  [
    'What does the prefix un- mean?',
    'Not or opposite',
    'Again',
    'Before',
    'Many',
    'medium',
    'Language & Words',
  ],
  [
    'What does the prefix re- mean?',
    'Again',
    'Not',
    'Before',
    'Against',
    'easy',
    'Language & Words',
  ],
  [
    'What does the prefix pre- mean?',
    'Before',
    'After',
    'Again',
    'Against',
    'easy',
    'Language & Words',
  ],
  [
    'What does the suffix -less mean?',
    'Without',
    'Full of',
    'Many',
    'Relating to',
    'medium',
    'Language & Words',
  ],
  [
    'What does the suffix -able mean?',
    'Capable of',
    'Without',
    'Full of',
    'Past tense',
    'medium',
    'Language & Words',
  ],
  [
    'What does biography mean?',
    'A life story written about someone',
    'A story about yourself',
    'A map of a place',
    'A science of life',
    'medium',
    'Language & Words',
  ],
  [
    'What does autobiography mean?',
    'The story of ones own life',
    'A life story by another',
    'A book of maps',
    'A study of life',
    'easy',
    'Language & Words',
  ],
  [
    'What does triangle mean?',
    'A shape with three angles',
    'A shape with four sides',
    'A musical instrument only',
    'A type of circle',
    'easy',
    'Language & Words',
  ],
  [
    'What does aquarium mean?',
    'A tank for water life',
    'A bird enclosure',
    'A plant house',
    'A desert exhibit',
    'easy',
    'Language & Words',
  ],
  [
    'What does vegetarian mean?',
    'One who eats no meat',
    'One who eats only meat',
    'One who eats fish only',
    'One who eats anything',
    'easy',
    'Language & Words',
  ],
  [
    'What does visible mean?',
    'Able to be seen',
    'Able to be heard',
    'Hidden',
    'Touchable',
    'easy',
    'Language & Words',
  ],
  [
    'What does audible mean?',
    'Able to be heard',
    'Able to be seen',
    'Able to be touched',
    'Able to be read',
    'easy',
    'Language & Words',
  ],
  [
    'What does portable mean?',
    'Able to be carried',
    'Able to be eaten',
    'Able to be broken',
    'Able to be seen',
    'easy',
    'Language & Words',
  ],
  [
    'What does Incredible mean strictly?',
    'Not believable',
    'Very believable',
    'Beautiful',
    'Strong',
    'medium',
    'Language & Words',
  ],
  [
    'What is a palindrome?',
    'A word spelled the same backward',
    'A very long word',
    'A rhyming pair',
    'A made-up word',
    'medium',
    'Language & Words',
  ],
  ['Which word is a palindrome?', 'Level', 'Hello', 'World', 'Apple', 'easy', 'Language & Words'],
  [
    'Which sentence is a famous palindrome?',
    'A man, a plan, a canal, Panama',
    'The quick brown fox',
    'To be or not to be',
    'Once upon a time',
    'medium',
    'Language & Words',
  ],
  ['What is the most common letter in English?', 'E', 'A', 'T', 'S', 'medium', 'Language & Words'],
  [
    'Which letter appears least often in English texts?',
    'Z or Q among the rarest',
    'E',
    'A',
    'T',
    'medium',
    'Language & Words',
  ],
  [
    'What is the only English word ending in -MT? Dramt, attempt is -MPT',
    'Dreamt',
    'Attempt',
    'Bespoke',
    'Prompt',
    'expert',
    'Language & Words',
  ],
  [
    'What do you call a word like buzz that imitates sound?',
    'Onomatopoeia',
    'Alliteration',
    'Simile',
    'Hyperbole',
    'medium',
    'Language & Words',
  ],
  [
    'What is a simile?',
    'A comparison using like or as',
    'A direct comparison',
    'An exaggeration',
    'A repeated sound',
    'medium',
    'Language & Words',
  ],
  [
    'What is a metaphor?',
    'A direct comparison without like or as',
    'A comparison using like',
    'An exaggeration',
    'A question form',
    'medium',
    'Language & Words',
  ],
  [
    'What is hyperbole?',
    'Deliberate exaggeration',
    'A small understatement',
    'A rhyme scheme',
    'A literal statement',
    'medium',
    'Language & Words',
  ],
  [
    'What is alliteration?',
    'Repeated starting sounds',
    'Repeated ending sounds',
    'A comparison',
    'An opposite phrase',
    'medium',
    'Language & Words',
  ],
  [
    'What is an oxymoron?',
    'Two opposite words together',
    'A very long word',
    'A wise saying',
    'A grammar error',
    'medium',
    'Language & Words',
  ],
  [
    'Which phrase is an oxymoron?',
    'Deafening silence',
    'Beautiful garden',
    'Loud music',
    'Slow walk',
    'easy',
    'Language & Words',
  ],
  [
    'What is a thesaurus used for?',
    'Finding synonyms',
    'Finding word origins',
    'Checking spelling only',
    'Counting words',
    'easy',
    'Language & Words',
  ],
  [
    'What is etymology?',
    'The study of word origins',
    'The study of insects',
    'The study of names only',
    'The study of grammar',
    'medium',
    'Language & Words',
  ],
  [
    'What does SOS stand for in distress use? It was chosen for simplicity',
    'Nothing officially; chosen as a Morse pattern',
    'Save Our Souls officially',
    'Save Our Ship officially',
    'Send Our Signal',
    'expert',
    'Language & Words',
  ],
  [
    'What does the word karaoke literally mean in Japanese?',
    'Empty orchestra',
    'Sing along',
    'Voice box',
    'Music hall',
    'expert',
    'Language & Words',
  ],
  [
    'What does tsunami literally mean in Japanese?',
    'Harbor wave',
    'Big wave',
    'Ocean fire',
    'Water dragon',
    'medium',
    'Language & Words',
  ],
  [
    'What does karate literally mean in Japanese?',
    'Empty hand',
    'Fighting art',
    'Strong fist',
    'Way of the warrior',
    'medium',
    'Language & Words',
  ],
  [
    'What does ballet mean originally?',
    'A dance form from Italy and France',
    'A Japanese art',
    'A Russian opera',
    'A Roman sport',
    'expert',
    'Language & Words',
  ],
  [
    'What does kindergarten literally mean in German?',
    'Childrens garden',
    'School house',
    'Play time',
    'Learning hall',
    'medium',
    'Language & Words',
  ],
  [
    'What does wanderlust mean?',
    'A strong desire to travel',
    'A fear of travel',
    'Lost luggage',
    'A travel guide',
    'easy',
    'Language & Words',
  ],
  [
    'What does deja vu mean?',
    'The feeling of having experienced something before',
    'A bad memory',
    'A dream state',
    'Double vision',
    'easy',
    'Language & Words',
  ],
  ['What does bona fide mean?', 'Genuine', 'Fake', 'Broken', 'Rare', 'medium', 'Language & Words'],
  [
    'What does ad hoc mean?',
    'For a specific purpose',
    'Permanent',
    'Formal only',
    'Ancient',
    'medium',
    'Language & Words',
  ],
  [
    'What does per se mean?',
    'By itself',
    'Again',
    'Later',
    'Against',
    'medium',
    'Language & Words',
  ],
  [
    'What does vice versa mean?',
    'The other way around',
    'As agreed',
    'For example',
    'In summary',
    'easy',
    'Language & Words',
  ],
  [
    'What does et cetera mean?',
    'And the rest',
    'And so I say',
    'Exactly so',
    'By that very act',
    'easy',
    'Language & Words',
  ],
  [
    'What does alma mater mean?',
    'Nurturing mother, ones school',
    'Wise teacher',
    'Old friend',
    'Great book',
    'medium',
    'Language & Words',
  ],
  [
    'What does curriculum mean?',
    'A course of study',
    'A school building',
    'A teachers guide only',
    'A test paper',
    'medium',
    'Language & Words',
  ],
  [
    'What does veto mean?',
    'To forbid',
    'To approve',
    'To delay',
    'To repeat',
    'easy',
    'Language & Words',
  ],
  [
    'What does status quo mean?',
    'The existing state',
    'A new order',
    'A legal rule',
    'A vote count',
    'medium',
    'Language & Words',
  ],
  [
    'What does graffiti come from? An Italian word for scratchings',
    'Italian for scratchings',
    'Greek for writings',
    'Latin for drawings',
    'French for walls',
    'expert',
    'Language & Words',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const MYTHS = [
  [
    'Who is the king of the Greek gods?',
    'Zeus',
    'Poseidon',
    'Hades',
    'Apollo',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who is the Greek god of the sea?',
    'Poseidon',
    'Zeus',
    'Hades',
    'Hermes',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who is the Greek god of the underworld?',
    'Hades',
    'Ares',
    'Dionysus',
    'Hephaestus',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who is the Greek goddess of wisdom?',
    'Athena',
    'Hera',
    'Aphrodite',
    'Artemis',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who is the Greek goddess of love?',
    'Aphrodite',
    'Athena',
    'Hera',
    'Demeter',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who is the messenger god with winged sandals?',
    'Hermes',
    'Apollo',
    'Ares',
    'Eros',
    'easy',
    'Myths & Legends',
  ],
  ['Who is the Greek god of war?', 'Ares', 'Zeus', 'Hades', 'Poseidon', 'easy', 'Myths & Legends'],
  [
    'Who is the god of fire and forge?',
    'Hephaestus',
    'Apollo',
    'Hermes',
    'Dionysus',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who is the god of wine and festivity?',
    'Dionysus',
    'Apollo',
    'Eros',
    'Hades',
    'medium',
    'Myths & Legends',
  ],
  [
    'What is Zeus weapon?',
    'The thunderbolt',
    'The trident',
    'The spear',
    'The bow',
    'easy',
    'Myths & Legends',
  ],
  [
    'What is Poseidons weapon?',
    'The trident',
    'The thunderbolt',
    'The hammer',
    'The shield',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which Roman god matches Zeus?',
    'Jupiter',
    'Mars',
    'Neptune',
    'Mercury',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which Roman god matches Poseidon?',
    'Neptune',
    'Jupiter',
    'Pluto',
    'Vulcan',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which Roman goddess matches Aphrodite?',
    'Venus',
    'Juno',
    'Minerva',
    'Diana',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which Roman god matches Ares?',
    'Mars',
    'Jupiter',
    'Saturn',
    'Neptune',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which Roman god matches Hermes?',
    'Mercury',
    'Mars',
    'Apollo',
    'Vulcan',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who was the strongest hero of Greek myth performing twelve labors?',
    'Heracles also called Hercules',
    'Theseus',
    'Perseus',
    'Achilles',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who slew the Gorgon Medusa?',
    'Perseus',
    'Heracles',
    'Theseus',
    'Jason',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who killed the Minotaur in the labyrinth?',
    'Theseus',
    'Perseus',
    'Achilles',
    'Odysseus',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who led the Argonauts seeking the Golden Fleece?',
    'Jason',
    'Hercules',
    'Odysseus',
    'Perseus',
    'medium',
    'Myths & Legends',
  ],
  [
    'Whose weak spot was his heel?',
    'Achilles',
    'Hector',
    'Paris',
    'Odysseus',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who flew too close to the sun with wax wings?',
    'Icarus',
    'Daedalus his father',
    'Perseus',
    'Bellerophon',
    'medium',
    'Myths & Legends',
  ],
  [
    'What sealed Pandora box that she opened?',
    'Evils escaped; hope remained',
    'Gold spilled out',
    'Winds carried her away',
    'Nothing happened',
    'medium',
    'Myths & Legends',
  ],
  [
    'Which horse was tamed by Bellerophon?',
    'Pegasus',
    'Arion',
    'Sleipnir',
    'Shadowfax',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who is the king of the Norse gods?',
    'Odin',
    'Thor',
    'Loki',
    'Freyr',
    'easy',
    'Myths & Legends',
  ],
  ['Who wields the hammer Mjolnir?', 'Thor', 'Odin', 'Loki', 'Baldr', 'easy', 'Myths & Legends'],
  ['Who is the Norse trickster god?', 'Loki', 'Odin', 'Heimdall', 'Tyr', 'easy', 'Myths & Legends'],
  [
    'What is the Norse end-of-world battle called?',
    'Ragnarok',
    'Valhalla',
    'Yggdrasil',
    'Midgard',
    'medium',
    'Myths & Legends',
  ],
  [
    'What is the Norse tree of life called?',
    'Yggdrasil',
    'Ashpool',
    'Worldpine',
    'Odins oak',
    'medium',
    'Myths & Legends',
  ],
  [
    'Where do slain warriors feast in Norse myth?',
    'Valhalla',
    'Asgard throne',
    'Helheim',
    'Niflheim',
    'medium',
    'Myths & Legends',
  ],
  ['Who is the Egyptian sun god?', 'Ra', 'Osiris', 'Anubis', 'Horus', 'easy', 'Myths & Legends'],
  [
    'Who is the Egyptian god of the afterlife with green skin?',
    'Osiris',
    'Ra',
    'Set',
    'Thoth',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who is the Egyptian jackal-headed god of mummification?',
    'Anubis',
    'Horus',
    'Set',
    'Thoth',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who is the Egyptian falcon god of kingship?',
    'Horus',
    'Ra',
    'Anubis',
    'Sobek',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who is the Egyptian god of wisdom and writing?',
    'Thoth',
    'Ra',
    'Anubis',
    'Ptah',
    'medium',
    'Myths & Legends',
  ],
  [
    'Who is the Egyptian goddess of magic and motherhood?',
    'Isis',
    'Nephthys',
    'Hathor',
    'Bastet',
    'medium',
    'Myths & Legends',
  ],
  [
    'Which Egyptian god caused chaos as a desert storm?',
    'Set',
    'Osiris',
    'Horus',
    'Anubis',
    'medium',
    'Myths & Legends',
  ],
  [
    'What creature guarded Egyptian pyramids with a human head?',
    'The Sphinx',
    'The Griffin',
    'The Chimera',
    'The Manticore',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which mythical bird burns and is reborn?',
    'The phoenix',
    'The roc',
    'The simurgh',
    'The thunderbird',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which creature is half human, half horse?',
    'The centaur',
    'The minotaur',
    'The satyr',
    'The faun',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which creature has one horn on its forehead?',
    'The unicorn',
    'The pegasus',
    'The griffin',
    'The wyvern',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which nine-headed serpent did Heracles fight?',
    'The Hydra',
    'The Python',
    'The Nemean beast',
    'The Erymanthian boar',
    'medium',
    'Myths & Legends',
  ],
  [
    'Which monster is half lion, half eagle?',
    'The griffin',
    'The sphinx',
    'The chimera',
    'The harpy',
    'easy',
    'Myths & Legends',
  ],
  [
    'What did King Midas wish for that became a curse?',
    'Everything he touched turned to gold',
    'Eternal youth',
    'Endless wisdom',
    'Immortality',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who opened the box releasing evils in Greek myth?',
    'Pandora',
    'Helen',
    'Cassandra',
    'Medusa',
    'easy',
    'Myths & Legends',
  ],
  [
    'Which gift never left Pandoras box?',
    'Hope',
    'Love',
    'Wealth',
    'Wisdom',
    'easy',
    'Myths & Legends',
  ],
  [
    'The wooden horse was used to trick which side in the Trojan War?',
    'The Trojans were tricked by the Greeks',
    'The Greeks were tricked by the Trojans',
    'The Persians',
    'The Spartans',
    'easy',
    'Myths & Legends',
  ],
  [
    'Who bewept her lost love and turned to stone in myth? Niobe wept for children',
    'None matches; Niobe wept for her children',
    'Echo',
    'Daphne',
    'Psyche',
    'expert',
    'Myths & Legends',
  ],
  [
    'Which nymph faded to a voice in Greek myth?',
    'Echo',
    'Daphne',
    'Syrinx',
    'Callisto',
    'medium',
    'Myths & Legends',
  ],
  [
    'Which maiden was turned into a laurel tree?',
    'Daphne',
    'Echo',
    'Ariadne',
    'Clytemnestra',
    'medium',
    'Myths & Legends',
  ],
  [
    'What amulet did Aphrodite use to charm Zeus in myth? The magic girdle',
    'Her magic girdle',
    'A golden apple',
    'A silver mirror',
    'A rose crown',
    'expert',
    'Myths & Legends',
  ],
];

function build() {
  const rows = [];

  const dayPool = MONTHS.map((m) => String(m[1]));
  const orderPool = MONTHS.map((m) => String(m[2]));
  for (const [name, days, order] of MONTHS) {
    rows.push({
      q: `How many days are in ${name} usually?`,
      correct: String(days),
      ds: distract(dayPool, String(days), 3),
      level: 'easy',
      chapter: 'Time & Calendar',
    });
    rows.push({
      q: `Which number month is ${name}?`,
      correct: String(order),
      ds: distract(orderPool, String(order), 3),
      level: 'easy',
      chapter: 'Time & Calendar',
    });
  }

  const domainPool = GODS.map((g) => g[2]);
  const romanPool = GODS.map((g) => g[1]);
  for (const [greek, roman, domain, symbol] of GODS) {
    rows.push({
      q: `What is the Roman equivalent of ${greek}?`,
      correct: roman,
      ds: distract(romanPool, roman, 3),
      level: 'easy',
      chapter: 'Myths & Legends',
    });
    rows.push({
      q: `${greek} is the god or goddess of what?`,
      correct: domain,
      ds: distract(domainPool, domain, 3),
      level: 'medium',
      chapter: 'Myths & Legends',
    });
    rows.push({
      q: `What symbol or item is associated with ${greek}?`,
      correct: symbol,
      ds: distract(
        GODS.map((g) => g[3]),
        symbol,
        3
      ),
      level: 'medium',
      chapter: 'Myths & Legends',
    });
  }

  for (const [name, role, item] of NORSE) {
    rows.push({
      q: `What is ${name} known for in Norse mythology?`,
      correct: role,
      ds: GODS.map((g) => g[2])
        .filter((d) => d !== role)
        .slice(0, 3),
      level: 'hard',
      chapter: 'Myths & Legends',
    });
    rows.push({
      q: `What item or trait is linked to ${name}?`,
      correct: item,
      ds: NORSE.map((n) => n[2])
        .filter((i) => i !== item)
        .slice(0, 3),
      level: 'hard',
      chapter: 'Myths & Legends',
    });
  }

  for (const [singular, plural] of PLURALS) {
    rows.push({
      q: `What is the plural of ${singular}?`,
      correct: plural,
      ds: PLURALS.map((p) => p[1])
        .filter((p) => p !== plural)
        .slice(0, 3),
      level: 'easy',
      chapter: 'Language & Words',
    });
  }

  for (const [word, opposite] of OPPOSITES) {
    rows.push({
      q: `What is the opposite of ${word}?`,
      correct: opposite,
      ds: OPPOSITES.map((o) => o[1])
        .filter((o) => o !== opposite)
        .slice(0, 3),
      level: 'easy',
      chapter: 'Language & Words',
    });
  }

  const meaningPool = IDIOMS.map((i) => i[1]);
  for (const [idiom, meaning] of IDIOMS) {
    rows.push({
      q: `What does the idiom ${idiom} mean?`,
      correct: meaning,
      ds: distract(meaningPool, meaning, 3),
      level: 'medium',
      chapter: 'Language & Words',
    });
  }

  const abbrPool = ABBREV.map((a) => a[1]);
  for (const [abbr, meaning] of ABBREV) {
    rows.push({
      q: `What does ${abbr} stand for?`,
      correct: meaning,
      ds: distract(abbrPool, meaning, 3),
      level: 'medium',
      chapter: 'Language & Words',
    });
  }

  const authorPool = BOOKS.map((b) => b[1]);
  for (const [book, author] of BOOKS) {
    rows.push({
      q: `Who wrote ${book}?`,
      correct: author,
      ds: distract(authorPool, author, 3),
      level: 'medium',
      chapter: 'Literature & Books',
    });
    rows.push({
      q: `Which book is by ${author}?`,
      correct: book,
      ds: BOOKS.map((b) => b[0])
        .filter((b) => b !== book)
        .slice(0, 3),
      level: 'hard',
      chapter: 'Literature & Books',
    });
  }

  for (const [play, about] of SHAKESPEARE) {
    rows.push({
      q: `What is the Shakespeare play ${play} about?`,
      correct: about,
      ds: SHAKESPEARE.map((s) => s[1])
        .filter((s) => s !== about)
        .slice(0, 3),
      level: 'medium',
      chapter: 'Literature & Books',
    });
  }

  const banks = [
    TIME_CALENDAR,
    EVERYDAY_SCIENCE,
    ARTS,
    TECH_INVENTIONS,
    MIXED,
    LANGUAGE_WORDS,
    MYTHS,
  ];
  for (const bank of banks) {
    for (const f of bank)
      rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  }

  return rows;
}

function distract(pool, correct, n) {
  const out = [];
  const seen = new Set([String(correct).toLowerCase()]);
  for (const cand of pool) {
    const key = String(cand).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(cand);
    if (out.length === n) break;
  }
  const fallback = ['None of these', 'Cannot say'];
  let fi = 0;
  while (out.length < n && fi < fallback.length) {
    if (!seen.has(fallback[fi].toLowerCase())) {
      out.push(fallback[fi]);
      seen.add(fallback[fi].toLowerCase());
    }
    fi++;
  }
  return out;
}

module.exports = { rows: build() };
