'use strict';

const { distractors } = require('../lib');

// [title, year, director, lead star]
const FILMS = [
  ['The Godfather', 1972, 'Francis Ford Coppola', 'Marlon Brando'],
  ['The Godfather Part II', 1974, 'Francis Ford Coppola', 'Al Pacino'],
  ['Titanic', 1997, 'James Cameron', 'Leonardo DiCaprio'],
  ['Avatar', 2009, 'James Cameron', 'Sam Worthington'],
  ['Jurassic Park', 1993, 'Steven Spielberg', 'Sam Neill'],
  ['Jaws', 1975, 'Steven Spielberg', 'Roy Scheider'],
  ['E.T. the Extra-Terrestrial', 1982, 'Steven Spielberg', 'Henry Thomas'],
  ['Star Wars: A New Hope', 1977, 'George Lucas', 'Mark Hamill'],
  ['Raiders of the Lost Ark', 1981, 'Steven Spielberg', 'Harrison Ford'],
  ['Back to the Future', 1985, 'Robert Zemeckis', 'Michael J. Fox'],
  ['Forrest Gump', 1994, 'Robert Zemeckis', 'Tom Hanks'],
  ['The Shawshank Redemption', 1994, 'Frank Darabont', 'Tim Robbins'],
  ['Pulp Fiction', 1994, 'Quentin Tarantino', 'John Travolta'],
  ['Fight Club', 1999, 'David Fincher', 'Brad Pitt'],
  ['The Matrix', 1999, 'The Wachowskis', 'Keanu Reeves'],
  ['Gladiator', 2000, 'Ridley Scott', 'Russell Crowe'],
  ['The Lord of the Rings: The Fellowship of the Ring', 2001, 'Peter Jackson', 'Elijah Wood'],
  ['The Lord of the Rings: The Two Towers', 2002, 'Peter Jackson', 'Elijah Wood'],
  ['The Lord of the Rings: The Return of the King', 2003, 'Peter Jackson', 'Elijah Wood'],
  ['The Dark Knight', 2008, 'Christopher Nolan', 'Christian Bale'],
  ['Inception', 2010, 'Christopher Nolan', 'Leonardo DiCaprio'],
  ['Interstellar', 2014, 'Christopher Nolan', 'Matthew McConaughey'],
  ['The Avengers', 2012, 'Joss Whedon', 'Robert Downey Jr.'],
  ['Iron Man', 2008, 'Jon Favreau', 'Robert Downey Jr.'],
  ['Black Panther', 2018, 'Ryan Coogler', 'Chadwick Boseman'],
  ['Harry Potter and the Sorcerers Stone', 2001, 'Chris Columbus', 'Daniel Radcliffe'],
  ['The Silence of the Lambs', 1991, 'Jonathan Demme', 'Jodie Foster'],
  ['Schindlers List', 1993, 'Steven Spielberg', 'Liam Neeson'],
  ['Goodfellas', 1990, 'Martin Scorsese', 'Ray Liotta'],
  ['Taxi Driver', 1976, 'Martin Scorsese', 'Robert De Niro'],
  ['The Departed', 2006, 'Martin Scorsese', 'Leonardo DiCaprio'],
  ['Rocky', 1976, 'John G. Avildsen', 'Sylvester Stallone'],
  ['First Blood', 1982, 'Ted Kotcheff', 'Sylvester Stallone'],
  ['The Terminator', 1984, 'James Cameron', 'Arnold Schwarzenegger'],
  ['Terminator 2: Judgment Day', 1991, 'James Cameron', 'Arnold Schwarzenegger'],
  ['Die Hard', 1988, 'John McTiernan', 'Bruce Willis'],
  ['Speed', 1994, 'Jan de Bont', 'Keanu Reeves'],
  ['Ghostbusters', 1984, 'Ivan Reitman', 'Bill Murray'],
  ['Groundhog Day', 1993, 'Harold Ramis', 'Bill Murray'],
  ['Home Alone', 1990, 'Chris Columbus', 'Macaulay Culkin'],
  ['Jurassic World', 2015, 'Colin Trevorrow', 'Chris Pratt'],
  ['Guardians of the Galaxy', 2014, 'James Gunn', 'Chris Pratt'],
  ['Mad Max: Fury Road', 2015, 'George Miller', 'Tom Hardy'],
  ['Parasite', 2019, 'Bong Joon-ho', 'Song Kang-ho'],
  ['La La Land', 2016, 'Damien Chazelle', 'Ryan Gosling'],
  ['Scarface', 1983, 'Brian De Palma', 'Al Pacino'],
  ['The Shining', 1980, 'Stanley Kubrick', 'Jack Nicholson'],
  ['2001: A Space Odyssey', 1968, 'Stanley Kubrick', 'Keir Dullea'],
  ['A Clockwork Orange', 1971, 'Stanley Kubrick', 'Malcolm McDowell'],
  ['Casino Royale', 2006, 'Martin Campbell', 'Daniel Craig'],
  ['Skyfall', 2012, 'Sam Mendes', 'Daniel Craig'],
  ['Goldfinger', 1964, 'Guy Hamilton', 'Sean Connery'],
  ['Wonder Woman', 2017, 'Patty Jenkins', 'Gal Gadot'],
  ['Spider-Man', 2002, 'Sam Raimi', 'Tobey Maguire'],
  ['X-Men', 2000, 'Bryan Singer', 'Hugh Jackman'],
  ['Logan', 2017, 'James Mangold', 'Hugh Jackman'],
  ['Deadpool', 2016, 'Tim Miller', 'Ryan Reynolds'],
  ['The Hunger Games', 2012, 'Gary Ross', 'Jennifer Lawrence'],
  ['Twilight', 2008, 'Catherine Hardwicke', 'Kristen Stewart'],
  ['Mean Girls', 2004, 'Mark Waters', 'Lindsay Lohan'],
  ['The Notebook', 2004, 'Nick Cassavetes', 'Ryan Gosling'],
  ['Casablanca', 1942, 'Michael Curtiz', 'Humphrey Bogart'],
  ['Gone with the Wind', 1939, 'Victor Fleming', 'Vivien Leigh'],
  ['The Wizard of Oz', 1939, 'Victor Fleming', 'Judy Garland'],
  ['Singin in the Rain', 1952, 'Stanley Donen', 'Gene Kelly'],
  ['Psycho', 1960, 'Alfred Hitchcock', 'Anthony Perkins'],
  ['Vertigo', 1958, 'Alfred Hitchcock', 'James Stewart'],
  ['North by Northwest', 1959, 'Alfred Hitchcock', 'Cary Grant'],
  ['Rear Window', 1954, 'Alfred Hitchcock', 'Grace Kelly'],
  ['Alien', 1979, 'Ridley Scott', 'Sigourney Weaver'],
  ['Blade Runner', 1982, 'Ridley Scott', 'Harrison Ford'],
  ['Braveheart', 1995, 'Mel Gibson', 'Mel Gibson'],
  ['The Sixth Sense', 1999, 'M. Night Shyamalan', 'Bruce Willis'],
  ['Saving Private Ryan', 1998, 'Steven Spielberg', 'Tom Hanks'],
  ['Apollo 13', 1995, 'Ron Howard', 'Tom Hanks'],
  ['A Few Good Men', 1992, 'Rob Reiner', 'Tom Cruise'],
  ['Top Gun', 1986, 'Tony Scott', 'Tom Cruise'],
  ['Jerry Maguire', 1996, 'Cameron Crowe', 'Tom Cruise'],
  ['Dirty Dancing', 1987, 'Emile Ardolino', 'Patrick Swayze'],
  ['Grease', 1978, 'Randal Kleiser', 'John Travolta'],
  ['The Karate Kid', 1984, 'John G. Avildsen', 'Ralph Macchio'],
  ['Footloose', 1984, 'Herbert Ross', 'Kevin Bacon'],
  ['The Breakfast Club', 1985, 'John Hughes', 'Molly Ringwald'],
  ['Ferris Buellers Day Off', 1986, 'John Hughes', 'Matthew Broderick'],
  ['Dumb and Dumber', 1994, 'Peter Farrelly', 'Jim Carrey'],
  ['The Mask', 1994, 'Chuck Russell', 'Jim Carrey'],
  ['Ace Ventura: Pet Detective', 1994, 'Tom Shadyac', 'Jim Carrey'],
  ['Men in Black', 1997, 'Barry Sonnenfeld', 'Will Smith'],
  ['Independence Day', 1996, 'Roland Emmerich', 'Will Smith'],
  ['The Pursuit of Happyness', 2006, 'Gabriele Muccino', 'Will Smith'],
  ['Pretty Woman', 1990, 'Garry Marshall', 'Julia Roberts'],
  ['When Harry Met Sally', 1989, 'Rob Reiner', 'Billy Crystal'],
  ['Misery', 1990, 'Rob Reiner', 'Kathy Bates'],
  ['Kill Bill: Vol. 1', 2003, 'Quentin Tarantino', 'Uma Thurman'],
  ['Django Unchained', 2012, 'Quentin Tarantino', 'Jamie Foxx'],
  ['Once Upon a Time in Hollywood', 2019, 'Quentin Tarantino', 'Leonardo DiCaprio'],
  ['Whiplash', 2014, 'Damien Chazelle', 'Miles Teller'],
  ['Joker', 2019, 'Todd Phillips', 'Joaquin Phoenix'],
  ['Aquaman', 2018, 'James Wan', 'Jason Momoa'],
  ['Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'Gore Verbinski', 'Johnny Depp'],
  ['Dune', 2021, 'Denis Villeneuve', 'Timothee Chalamet'],
  ['Everything Everywhere All at Once', 2022, 'The Daniels', 'Michelle Yeoh'],
  ['Oppenheimer', 2023, 'Christopher Nolan', 'Cillian Murphy'],
  ['Barbie', 2023, 'Greta Gerwig', 'Margot Robbie'],
];

// [show, fact answer, network, d1, d2, d3, level]
const TV_SHOWS = [
  ['Friends', 'six friends in New York City', 'NBC', 'CBS', 'ABC', 'FOX', 'easy'],
  [
    'The Office (US)',
    'employees of the Dunder Mifflin paper company',
    'NBC',
    'CBS',
    'FOX',
    'HBO',
    'easy',
  ],
  ['Breaking Bad', 'a chemistry teacher turned meth maker', 'AMC', 'FX', 'HBO', 'Netflix', 'easy'],
  [
    'Game of Thrones',
    'noble families fighting for the Iron Throne',
    'HBO',
    'Netflix',
    'AMC',
    'Showtime',
    'easy',
  ],
  [
    'Stranger Things',
    'kids facing supernatural events in Hawkins, Indiana',
    'Netflix',
    'Hulu',
    'Amazon',
    'HBO',
    'easy',
  ],
  ['The Big Bang Theory', 'scientists living in Pasadena', 'CBS', 'NBC', 'FOX', 'ABC', 'easy'],
  [
    'How I Met Your Mother',
    'Ted telling his kids a long story',
    'CBS',
    'NBC',
    'FOX',
    'ABC',
    'medium',
  ],
  [
    'Sherlock (BBC)',
    'a modern consulting detective in London',
    'BBC',
    'ITV',
    'Channel 4',
    'Netflix',
    'medium',
  ],
  [
    'Doctor Who',
    'a time-traveling alien called the Doctor',
    'BBC',
    'ITV',
    'Sky',
    'Channel 4',
    'easy',
  ],
  ['Black Mirror', 'a dark anthology about technology', 'Netflix', 'BBC', 'AMC', 'Hulu', 'medium'],
  ['The Crown', 'the reign of Queen Elizabeth II', 'Netflix', 'BBC', 'ITV', 'HBO', 'easy'],
  [
    'Squid Game',
    'desperate players in deadly Korean games',
    'Netflix',
    'tvN',
    'KBS',
    'Disney+',
    'easy',
  ],
  [
    'Money Heist',
    'a heist led by the Professor in Spain',
    'Netflix',
    'Antena 3',
    'HBO',
    'Amazon',
    'medium',
  ],
  ['Dark', 'time travel mysteries in a German town', 'Netflix', 'Sky', 'ZDF', 'ARD', 'hard'],
  [
    'Wednesday',
    'the Addams Family daughter at Nevermore Academy',
    'Netflix',
    'Hulu',
    'CW',
    'HBO',
    'easy',
  ],
  [
    'The Witcher',
    'the monster hunter Geralt of Rivia',
    'Netflix',
    'HBO',
    'Amazon',
    'Starz',
    'easy',
  ],
  ['Narcos', 'the rise of Pablo Escobar', 'Netflix', 'HBO', 'AMC', 'FX', 'medium'],
  [
    'Peaky Blinders',
    'a Birmingham gang led by Thomas Shelby',
    'BBC',
    'ITV',
    'Netflix',
    'Sky',
    'medium',
  ],
  [
    'The Mandalorian',
    'a bounty hunter protecting Grogu',
    'Disney+',
    'Netflix',
    'HBO Max',
    'Amazon',
    'easy',
  ],
  ['Lost', 'plane crash survivors on a mysterious island', 'ABC', 'NBC', 'CBS', 'FOX', 'easy'],
  [
    'Prison Break',
    'a man engineered to break his brother out of jail',
    'FOX',
    'NBC',
    'ABC',
    'CBS',
    'easy',
  ],
  ['24', 'counter-terrorist agent Jack Bauer in real time', 'FOX', 'CBS', 'NBC', 'HBO', 'medium'],
  ['The Walking Dead', 'survivors in a zombie apocalypse', 'AMC', 'FOX', 'HBO', 'Netflix', 'easy'],
  ['Dexter', 'a forensic analyst who is a serial killer', 'Showtime', 'HBO', 'AMC', 'FX', 'medium'],
  ['Greys Anatomy', 'surgical interns at a Seattle hospital', 'ABC', 'NBC', 'CBS', 'FOX', 'easy'],
  ['House', 'a brilliant, grumpy diagnostician', 'FOX', 'NBC', 'CBS', 'ABC', 'easy'],
  ['Modern Family', 'three branches of one family', 'ABC', 'NBC', 'CBS', 'FOX', 'easy'],
  [
    'Brooklyn Nine-Nine',
    'detectives of a New York precinct',
    'FOX then NBC',
    'CBS',
    'ABC',
    'TBS',
    'medium',
  ],
  [
    'The Simpsons',
    'a yellow animated family in Springfield',
    'FOX',
    'CBS',
    'NBC',
    'Comedy Central',
    'easy',
  ],
  ['Family Guy', 'the Griffins of Quahog', 'FOX', 'Comedy Central', 'TBS', 'Adult Swim', 'easy'],
  [
    'South Park',
    'four boys in a Colorado mountain town',
    'Comedy Central',
    'FOX',
    'MTV',
    'Adult Swim',
    'easy',
  ],
  [
    'Rick and Morty',
    'a mad scientist and his grandson',
    'Adult Swim',
    'Comedy Central',
    'FOX',
    'Netflix',
    'medium',
  ],
  ['Seinfeld', 'a comedian and friends in New York', 'NBC', 'CBS', 'ABC', 'FOX', 'easy'],
  ['Cheers', 'a Boston bar where everybody knows your name', 'NBC', 'CBS', 'ABC', 'FOX', 'medium'],
  [
    'The Fresh Prince of Bel-Air',
    'a West Philly teen sent to rich relatives',
    'NBC',
    'FOX',
    'ABC',
    'WB',
    'easy',
  ],
  [
    'Suits',
    'a law firm hiring a college dropout genius',
    'USA Network',
    'FX',
    'AMC',
    'HBO',
    'medium',
  ],
  [
    'Fargo',
    'crimes in a snowy Minnesota inspired by the film',
    'FX',
    'AMC',
    'HBO',
    'Netflix',
    'medium',
  ],
  [
    'The Crown actor',
    'Claire Foy and Olivia Colman and Imelda Staunton played Elizabeth',
    'Netflix',
    'BBC',
    'HBO',
    'ITV',
    'expert',
  ],
];

// [film, studio, year]
const ANIMATION = [
  ['Toy Story', 'Pixar', 1995],
  ['Finding Nemo', 'Pixar', 2003],
  ['Up', 'Pixar', 2009],
  ['WALL-E', 'Pixar', 2008],
  ['Ratatouille', 'Pixar', 2007],
  ['Monsters, Inc.', 'Pixar', 2001],
  ['Inside Out', 'Pixar', 2015],
  ['Coco', 'Pixar', 2017],
  ['The Incredibles', 'Pixar', 2004],
  ['Shrek', 'DreamWorks', 2001],
  ['Kung Fu Panda', 'DreamWorks', 2008],
  ['How to Train Your Dragon', 'DreamWorks', 2010],
  ['Madagascar', 'DreamWorks', 2005],
  ['Frozen', 'Disney', 2013],
  ['Moana', 'Disney', 2016],
  ['Tangled', 'Disney', 2010],
  ['Aladdin', 'Disney', 1992],
  ['Beauty and the Beast', 'Disney', 1991],
  ['The Little Mermaid', 'Disney', 1989],
  ['Mulan', 'Disney', 1998],
  ['The Lion King', 'Disney', 1994],
  ['Snow White and the Seven Dwarfs', 'Disney', 1937],
  ['Spirited Away', 'Studio Ghibli', 2001],
  ['My Neighbor Totoro', 'Studio Ghibli', 1988],
  ['Princess Mononoke', 'Studio Ghibli', 1997],
  ['Howls Moving Castle', 'Studio Ghibli', 2004],
  ['Despicable Me', 'Illumination', 2010],
  ['The Secret Life of Pets', 'Illumination', 2016],
  ['The Emoji Movie', 'Sony Animation', 2017],
  ['Spider-Man: Into the Spider-Verse', 'Sony Animation', 2018],
];

// [actor, role]
const ACTORS = [
  ['Daniel Radcliffe', 'Harry Potter'],
  ['Emma Watson', 'Hermione Granger'],
  ['Rupert Grint', 'Ron Weasley'],
  ['Hugh Jackman', 'Wolverine'],
  ['Robert Downey Jr.', 'Iron Man'],
  ['Chris Evans', 'Captain America'],
  ['Chris Hemsworth', 'Thor'],
  ['Scarlett Johansson', 'Black Widow'],
  ['Tom Holland', 'Spider-Man (MCU)'],
  ['Tobey Maguire', 'Spider-Man (2002)'],
  ['Andrew Garfield', 'The Amazing Spider-Man'],
  ['Christian Bale', 'Batman (Dark Knight trilogy)'],
  ['Michael Keaton', 'Batman (1989)'],
  ['Heath Ledger', 'The Joker (The Dark Knight)'],
  ['Gal Gadot', 'Wonder Woman'],
  ['Henry Cavill', 'Superman (2013)'],
  ['Christopher Reeve', 'Superman (1978)'],
  ['Tom Cruise', 'Ethan Hunt (Mission: Impossible)'],
  ['Keanu Reeves', 'Neo (The Matrix)'],
  ['Carrie Fisher', 'Princess Leia'],
  ['Mark Hamill', 'Luke Skywalker'],
  ['Harrison Ford', 'Han Solo and Indiana Jones'],
  ['Sean Connery', 'James Bond (1962-1971)'],
  ['Daniel Craig', 'James Bond (2006-2021)'],
  ['Arnold Schwarzenegger', 'The Terminator'],
  ['Sylvester Stallone', 'Rocky Balboa'],
  ['Bruce Willis', 'John McClane (Die Hard)'],
  ['Will Smith', 'The Fresh Prince and Men in Black'],
  ['Jim Carrey', 'The Mask'],
  ['Eddie Murphy', 'Axel Foley (Beverly Hills Cop)'],
  ['Robin Williams', 'The Genie (Aladdin)'],
  ['Tom Hanks', 'Forrest Gump'],
  ['Julia Roberts', 'Vivian (Pretty Woman)'],
  ['Richard Gere', 'Edward (Pretty Woman)'],
  ['Sandra Bullock', 'Annie (Speed)'],
  ['Kate Winslet', 'Rose (Titanic)'],
  ['Morgan Freeman', 'Red (The Shawshank Redemption)'],
  ['Tim Robbins', 'Andy Dufresne'],
  ['Anthony Hopkins', 'Hannibal Lecter'],
  ['Jodie Foster', 'Clarice Starling'],
  ['Jack Nicholson', 'Jack Torrance (The Shining)'],
  ['Kathy Bates', 'Annie Wilkes (Misery)'],
  ['Uma Thurman', 'The Bride (Kill Bill)'],
  ['Samuel L. Jackson', 'Jules (Pulp Fiction) and Nick Fury'],
  ['Patrick Swayze', 'Johnny (Dirty Dancing)'],
  ['Kevin Bacon', 'Ren (Footloose)'],
  ['Winona Ryder', 'Lydia (Beetlejuice) and Joyce (Stranger Things)'],
  ['Millie Bobby Brown', 'Eleven (Stranger Things)'],
  ['Cillian Murphy', 'Thomas Shelby (Peaky Blinders)'],
  ['Bryan Cranston', 'Walter White'],
  ['Aaron Paul', 'Jesse Pinkman'],
  ['Emilia Clarke', 'Daenerys Targaryen'],
  ['Kit Harington', 'Jon Snow'],
  ['Peter Dinklage', 'Tyrion Lannister'],
  ['Maisie Williams', 'Arya Stark'],
  ['Sophie Turner', 'Sansa Stark'],
  ['Lena Headey', 'Cersei Lannister'],
  ['Jason Momoa', 'Khal Drogo and Aquaman'],
  ['Jennifer Lawrence', 'Katniss Everdeen'],
  ['Josh Hutcherson', 'Peeta Mellark'],
  ['Kristen Stewart', 'Bella Swan'],
  ['Robert Pattinson', 'Edward Cullen'],
  ['Taylor Lautner', 'Jacob Black'],
  ['Emma Stone', 'Mia (La La Land)'],
  ['Anne Hathaway', 'Mia (The Princess Diaries)'],
  ['Colin Firth', 'Mr. Darcy (Pride and Prejudice)'],
  ['Keira Knightley', 'Elizabeth Bennet and Elizabeth Swann'],
  ['Orlando Bloom', 'Legolas and Will Turner'],
  ['Johnny Depp', 'Captain Jack Sparrow'],
  ['Zoe Saldana', 'Neytiri and Gamora'],
  ['Vin Diesel', 'Dominic Toretto and Groot voice'],
  ['Dwayne Johnson', 'Luke Hobbs (Fast and Furious)'],
  ['Zendaya', 'MJ (Spider-Man) and Rue (Euphoria)'],
  ['Timothee Chalamet', 'Paul Atreides (Dune)'],
  ['Daisy Ridley', 'Rey (Star Wars)'],
  ['Adam Driver', 'Kylo Ren'],
  ['Margot Robbie', 'Barbie and Harley Quinn'],
  ['Michelle Yeoh', 'Evelyn (Everything Everywhere All at Once)'],
];

// [question, correct, d1, d2, d3, level, chapter]
const QUOTES = [
  [
    'Which film features the line May the Force be with you?',
    'Star Wars',
    'Star Trek',
    'Dune',
    'The Matrix',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features the line Ill be back?',
    'The Terminator',
    'Die Hard',
    'Rambo',
    'Predator',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features Heres looking at you, kid?',
    'Casablanca',
    'Gone with the Wind',
    'Citizen Kane',
    'The Maltese Falcon',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Youre gonna need a bigger boat?',
    'Jaws',
    'Titanic',
    'Moby Dick',
    'The Abyss',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features the shout Im king of the world?',
    'Titanic',
    'Avatar',
    'The Beach',
    'Cast Away',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features Why so serious?',
    'The Dark Knight',
    'Joker',
    'Batman Begins',
    'Suicide Squad',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features I see dead people?',
    'The Sixth Sense',
    'The Others',
    'Ghost',
    'Poltergeist',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features the phrase My precious?',
    'The Lord of the Rings',
    'Harry Potter',
    'The Hobbit film only',
    'Willow',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features To infinity and beyond?',
    'Toy Story',
    'Space Jam',
    'Interstellar',
    'Wall-E',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features Just keep swimming?',
    'Finding Nemo',
    'Moana',
    'The Little Mermaid',
    'Shark Tale',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film popularized Hakuna Matata?',
    'The Lion King',
    'Madagascar',
    'Tarzan',
    'Jungle Book',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features Say hello to my little friend?',
    'Scarface',
    'The Godfather',
    'Goodfellas',
    'Casino',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features Show me the money?',
    'Jerry Maguire',
    'Wall Street',
    'The Wolf of Wall Street',
    'Moneyball',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features You cant handle the truth?',
    'A Few Good Men',
    'Judgment at Nuremberg',
    'A Time to Kill',
    '12 Angry Men',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Houston, we have a problem?',
    'Apollo 13',
    'Gravity',
    'The Martian',
    'First Man',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Life is like a box of chocolates?',
    'Forrest Gump',
    'Big Fish',
    'The Curious Case of Benjamin Button',
    'Rain Man',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features May the odds be ever in your favor?',
    'The Hunger Games',
    'Divergent',
    'The Maze Runner',
    'Twilight',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which series features Winter is coming?',
    'Game of Thrones',
    'The Witcher',
    'Vikings',
    'The Last Kingdom',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film reveals I am your father?',
    'The Empire Strikes Back',
    'Star Wars: A New Hope',
    'Return of the Jedi',
    'Rogue One',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features Theres no place like home?',
    'The Wizard of Oz',
    'Cinderella',
    'E.T.',
    'Home Alone',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film series features Bond, James Bond?',
    'James Bond',
    'Mission: Impossible',
    'The Bourne Identity',
    'Kingsman',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features E.T. phone home?',
    'E.T. the Extra-Terrestrial',
    'Close Encounters',
    'Alien',
    'Arrival',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features the need for speed line?',
    'Top Gun',
    'Fast and Furious',
    'Days of Thunder',
    'Le Mans 66',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Nobody puts Baby in a corner?',
    'Dirty Dancing',
    'Grease',
    'Footloose',
    'Flashdance',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Ill make him an offer he cant refuse?',
    'The Godfather',
    'Scarface',
    'Casino',
    'Goodfellas',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features You talking to me?',
    'Taxi Driver',
    'Raging Bull',
    'Mean Streets',
    'The King of Comedy',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Heres Johnny?',
    'The Shining',
    'Psycho',
    'Misery',
    'Scream',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Wax on, wax off?',
    'The Karate Kid',
    'Kung Fu Panda',
    'The Matrix',
    'Crouching Tiger',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features You had me at hello?',
    'Jerry Maguire',
    'Sleepless in Seattle',
    'Notting Hill',
    'When Harry Met Sally',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features With great power comes great responsibility?',
    'Spider-Man',
    'Batman',
    'Superman',
    'X-Men',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features This is Sparta!',
    '300',
    'Troy',
    'Gladiator',
    'Alexander',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features I am Iron Man?',
    'Iron Man',
    'The Avengers',
    'Captain America',
    'Doctor Strange',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features We are Groot?',
    'Guardians of the Galaxy',
    'The Avengers',
    'Thor',
    'Eternals',
    'easy',
    'Quotes & Moments',
  ],
  [
    'Which film features I could do this all day?',
    'Captain America: The First Avenger',
    'Iron Man',
    'Thor',
    'Black Widow',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features Theres no crying in baseball?',
    'A League of Their Own',
    'Field of Dreams',
    'The Natural',
    'Bull Durham',
    'hard',
    'Quotes & Moments',
  ],
  [
    'Which film features If you build it, he will come?',
    'Field of Dreams',
    'The Natural',
    'Cobb',
    'The Sandlot',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features I feel the need for speed exactly? Top Gun variant',
    'Top Gun',
    'The Fast and the Furious',
    'Top Gun: Maverick',
    'Days of Thunder',
    'expert',
    'Quotes & Moments',
  ],
  [
    'Which series features the line I am the one who knocks?',
    'Breaking Bad',
    'The Sopranos',
    'Better Call Saul',
    'Ozark',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which series features Valar Morghulis?',
    'Game of Thrones',
    'The Witcher',
    'His Dark Materials',
    'Vikings',
    'medium',
    'Quotes & Moments',
  ],
  [
    'Which film features All those moments will be lost in time, like tears in rain?',
    'Blade Runner',
    '2001: A Space Odyssey',
    'Solaris',
    'Ex Machina',
    'expert',
    'Quotes & Moments',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const OSCARS = [
  [
    'Which film won the most Oscars with 11 including Best Picture in 2004?',
    'The Return of the King',
    'Titanic',
    'Ben-Hur',
    'Chicago',
    'hard',
    'Awards & Records',
  ],
  [
    'Which films are tied with 11 Oscars alongside The Return of the King?',
    'Titanic and Ben-Hur',
    'Gone with the Wind and Rocky',
    'West Side Story and Forrest Gump',
    'Chicago and Slumdog Millionaire',
    'expert',
    'Awards & Records',
  ],
  [
    'Who has won the most acting Oscars with four?',
    'Katharine Hepburn',
    'Meryl Streep',
    'Jack Nicholson',
    'Daniel Day-Lewis',
    'hard',
    'Awards & Records',
  ],
  [
    'How many Oscars did Walt Disney win in total?',
    '26 including honorary awards',
    '11',
    '22',
    '30',
    'expert',
    'Awards & Records',
  ],
  [
    'Which studio has won the most Academy Awards overall?',
    'Disney',
    'Warner Bros.',
    'Universal',
    'Paramount',
    'expert',
    'Awards & Records',
  ],
  [
    'Who holds the record for most Oscar nominations for acting?',
    'Meryl Streep',
    'Katharine Hepburn',
    'Jack Nicholson',
    'Bette Davis',
    'medium',
    'Awards & Records',
  ],
  [
    'Which film first won Best Picture for a non-English language film?',
    'Parasite in 2020',
    'Roma',
    'Crouching Tiger',
    'Life is Beautiful',
    'medium',
    'Awards & Records',
  ],
  [
    'Which animated film won Best Animated Feature first for Japan?',
    'Spirited Away in 2003',
    'Your Name',
    'Princess Mononoke',
    'Akira',
    'hard',
    'Awards & Records',
  ],
  [
    'Who was the first woman to win Best Director?',
    'Kathryn Bigelow for The Hurt Locker',
    'Greta Gerwig',
    'Ava DuVernay',
    'Jane Campion later',
    'hard',
    'Awards & Records',
  ],
  [
    'Which actor refused his Oscar for The Godfather in 1973?',
    'Marlon Brando',
    'George C. Scott',
    'Dudley Moore',
    'Richard Burton',
    'medium',
    'Awards & Records',
  ],
  [
    'Which actor won Best Actor for Lincoln and There Will Be Blood twice overall?',
    'Daniel Day-Lewis with three total',
    'Tom Hanks',
    'Denzel Washington',
    'Sean Penn',
    'expert',
    'Awards & Records',
  ],
  [
    'Which film won the first Academy Award for Best Picture?',
    'Wings in 1929',
    'Sunrise',
    'The Jazz Singer',
    'Metropolis',
    'expert',
    'Awards & Records',
  ],
  [
    'Which actor won posthumously for Network?',
    'Peter Finch',
    'James Dean nominated only',
    'Heath Ledger won for Joker role',
    'Spencer Tracy',
    'expert',
    'Awards & Records',
  ],
  [
    'Heath Ledger won a posthumous Oscar for which role?',
    'The Joker in The Dark Knight',
    'Candy',
    'Brokeback Mountain',
    'Ned Kelly',
    'easy',
    'Awards & Records',
  ],
  [
    'Which 2017 ceremony famously announced the wrong Best Picture?',
    'La La Land instead of Moonlight',
    'Barbie instead of Oppenheimer',
    'Roma instead of Green Book',
    'La La Land instead of Birdman',
    'easy',
    'Awards & Records',
  ],
  [
    'Which film gave Halle Berry her historic Best Actress win?',
    'Monsters Ball in 2002',
    'X-Men',
    'Die Another Day',
    'Swordfish',
    'medium',
    'Awards & Records',
  ],
  [
    'Who was the first Black actor to win Best Actor?',
    'Sidney Poitier in 1964',
    'Denzel Washington in 2002',
    'Sidney Poitier again 1967',
    'Forest Whitaker',
    'medium',
    'Awards & Records',
  ],
  [
    'Which studio created the first fully computer-animated feature?',
    'Pixar with Toy Story',
    'DreamWorks',
    'Disney classics',
    'Illumination',
    'medium',
    'Awards & Records',
  ],
  [
    'Which award honors animated features at the Oscars since 2002 ceremony?',
    'Best Animated Feature',
    'Best Cartoon',
    'Best Animation',
    'Best Visual Story',
    'medium',
    'Awards & Records',
  ],
  [
    'Which three films won the Big Five Oscars: Picture, Director, Actor, Actress, and Screenplay?',
    'It Happened One Night, One Flew Over the Cuckoos Nest, and The Silence of the Lambs',
    'Gone with the Wind and Titanic',
    'Godfather I and II',
    'Rocky and Forrest Gump',
    'expert',
    'Awards & Records',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const MOVIE_FACTS = [
  [
    'Which film became the highest-grossing film worldwide in 2009?',
    'Avatar',
    'Titanic',
    'Avengers: Endgame',
    'Star Wars: The Force Awakens',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film held the highest-grossing record from 1998 to 2009?',
    'Titanic',
    'Jurassic Park',
    'The Lion King',
    'Gone with the Wind',
    'medium',
    'Movie Facts',
  ],
  [
    'Which film overtook Titanic in 2019 briefly before Avatar reclaimed the spot?',
    'Avengers: Endgame',
    'Star Wars: Force Awakens',
    'Avatar 2',
    'Infinity War',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1975 film is credited with creating the summer blockbuster?',
    'Jaws',
    'Star Wars',
    'Superman',
    'Rocky',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1927 film was the first major talking picture?',
    'The Jazz Singer',
    'Metropolis',
    'Wings',
    'The Crowd',
    'medium',
    'Movie Facts',
  ],
  [
    'Which year did the first movies screen publicly by the Lumiere brothers?',
    '1895',
    '1888',
    '1901',
    '1910',
    'hard',
    'Movie Facts',
  ],
  [
    'Who is considered the father of special effects with 1902s A Trip to the Moon?',
    'Georges Melies',
    'Edison',
    'Griffith',
    'Porter',
    'hard',
    'Movie Facts',
  ],
  [
    'Which film series began with Dr. No in 1962?',
    'James Bond',
    'Mission Impossible',
    'Pink Panther',
    'Matt Helm',
    'medium',
    'Movie Facts',
  ],
  [
    'Which actor played James Bond the most times officially?',
    'Roger Moore with seven',
    'Sean Connery with six official EON',
    'Daniel Craig with five',
    'Pierce Brosnan with four',
    'hard',
    'Movie Facts',
  ],
  [
    'Which company bought Lucasfilm in 2012?',
    'Disney',
    'Warner Bros.',
    'Universal',
    'Paramount',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film started the Marvel Cinematic Universe in 2008?',
    'Iron Man',
    'The Hulk',
    'Thor',
    'Captain America',
    'easy',
    'Movie Facts',
  ],
  [
    'How many MCU films led to Avengers: Endgame in the Infinity Saga?',
    'Twenty-three',
    'Twenty',
    'Twenty-five',
    'Eighteen',
    'hard',
    'Movie Facts',
  ],
  [
    'Which 2019 film became the fastest to gross two billion dollars?',
    'Avengers: Endgame',
    'Avatar',
    'Force Awakens',
    'Titanic',
    'medium',
    'Movie Facts',
  ],
  [
    'Which directing brothers made The Matrix?',
    'The Wachowskis',
    'The Coen brothers',
    'The Farrelly brothers',
    'The Russo brothers',
    'medium',
    'Movie Facts',
  ],
  [
    'Which brothers directed Avengers: Endgame?',
    'The Russo brothers',
    'The Wachowskis',
    'The Coen brothers',
    'The Hughes brothers',
    'medium',
    'Movie Facts',
  ],
  [
    'Which director is known for twisted endings like The Sixth Sense?',
    'M. Night Shyamalan',
    'David Fincher',
    'Denis Villeneuve',
    'James Wan',
    'easy',
    'Movie Facts',
  ],
  [
    'Which director is known for horrors like Saw and Aquaman?',
    'James Wan',
    'Rob Zombie',
    'Sam Raimi',
    'Wes Craven',
    'medium',
    'Movie Facts',
  ],
  [
    'Which director made Nightmare on Elm Street and Scream?',
    'Wes Craven',
    'John Carpenter',
    'Tobe Hooper',
    'George Romero',
    'medium',
    'Movie Facts',
  ],
  [
    'Which director made Halloween in 1978?',
    'John Carpenter',
    'Wes Craven',
    'Sean Cunningham',
    'Joe Dante',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1968 zombie film founded the modern zombie genre?',
    'Night of the Living Dead',
    'Dawn of the Dead',
    'The Last Man on Earth',
    'White Zombie',
    'hard',
    'Movie Facts',
  ],
  [
    'Which Alfred Hitchcock film shows a shower murder?',
    'Psycho',
    'Frenzy',
    'Dial M for Murder',
    'Blackmail',
    'easy',
    'Movie Facts',
  ],
  [
    'What was Alfred Hitchcocks famous TV anthology called?',
    'Alfred Hitchcock Presents',
    'The Hitchcock Hour',
    'Suspense Theatre',
    'Thriller',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Studio Ghibli founder directed My Neighbor Totoro?',
    'Hayao Miyazaki',
    'Isao Takahata',
    'Mamoru Hosoda',
    'Makoto Shinkai',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 2016 animated film is set in the world of the dead in Mexico?',
    'Coco',
    'The Book of Life',
    'Encanto',
    'Maya and the Three',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Disney film is set in Colombia with the Madrigal family?',
    'Encanto',
    'Coco',
    'Moana',
    'Raya',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Disney film features the Polynesian wayfinder Moana? Moana itself',
    'Moana is the film',
    'Frozen',
    'Raya',
    'Lilo and Stitch',
    'medium',
    'Movie Facts',
  ],
  [
    'Which princess film features Rapunzel?',
    'Tangled',
    'Frozen',
    'Brave',
    'Enchanted',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Pixar film is set inside a girls mind with emotions?',
    'Inside Out',
    'Soul',
    'Coco',
    'Up',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Pixar film follows a robot cleaning Earth?',
    'WALL-E',
    'Ratatouille',
    'Cars',
    'Eve story',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Pixar film features a rat who wants to cook?',
    'Ratatouille',
    'Chef',
    'Cloudy with Meatballs',
    'The Bear and the Bee',
    'easy',
    'Movie Facts',
  ],
  [
    'Which animated ogre film parodies fairy tales?',
    'Shrek',
    'Hoodwinked',
    'Igor',
    'Trolls',
    'easy',
    'Movie Facts',
  ],
  [
    'Which animated film features Po the panda learning kung fu?',
    'Kung Fu Panda',
    'Mulan',
    'Big Hero 6',
    'Raya',
    'easy',
    'Movie Facts',
  ],
  [
    'Which animated film features Hiccup and Toothless?',
    'How to Train Your Dragon',
    'Brave',
    'Eragon',
    'Pete and His Dragon',
    'easy',
    'Movie Facts',
  ],
  [
    'Which anime film became a global phenomenon in 2001 Japan release worldwide fame?',
    'Spirited Away',
    'Your Name',
    'Princess Mononoke',
    'Akira',
    'medium',
    'Movie Facts',
  ],
  [
    'Which anime director co-founded Studio Ghibli?',
    'Hayao Miyazaki',
    'Osamu Tezuka',
    'Katsuhiro Otomo',
    'Satoshi Kon',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1988 anime film influenced cyberpunk worldwide?',
    'Akira',
    'Ghost in the Shell',
    'Ninja Scroll',
    'Perfect Blue',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1995 anime film inspired The Matrix aesthetics?',
    'Ghost in the Shell',
    'Akira',
    'Cowboy Bebop film',
    'Macross',
    'hard',
    'Movie Facts',
  ],
  [
    'Which Bollywood star is called King Khan?',
    'Shah Rukh Khan',
    'Salman Khan',
    'Aamir Khan',
    'Saif Ali Khan',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Indian film won Best Original Song Oscar for Naatu Naatu?',
    'RRR',
    'Slumdog Millionaire',
    'Dangal',
    'Baahubali',
    'hard',
    'Movie Facts',
  ],
  [
    'Which 2008 film won eight Oscars including Slumdog Milionaire music? Slumdog Millionaire itself',
    'Slumdog Millionaire',
    'Lagaan',
    'RRR',
    'Gandhi',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Korean actor starred in Parasite as the father?',
    'Song Kang-ho',
    'Lee Sun-kyun',
    'Choi Woo-shik',
    'Park So-dam',
    'expert',
    'Movie Facts',
  ],
  [
    'Which Hong Kong star performed his own stunts in Rush Hour?',
    'Jackie Chan',
    'Jet Li',
    'Donnie Yen',
    'Tony Jaa',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Thai star is known for Ong-Bak martial arts?',
    'Tony Jaa',
    'Jet Li',
    'Iko Uwais',
    'Scott Adkins',
    'hard',
    'Movie Facts',
  ],
  [
    'Which Indonesian film features Iko Uwais in The Raid?',
    'The Raid: Redemption',
    'Headshot',
    'Merantau',
    'The Night Comes for Us',
    'hard',
    'Movie Facts',
  ],
  [
    'Which Nigerian film industry is called Nollywood?',
    'Nigerias film industry',
    'Ghanas',
    'Kenyas',
    'South Africas',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 2023 film paired Barbie with Oppenheimer in Barbenheimer?',
    'Barbie',
    'Dune',
    'Killers of the Flower Moon',
    'Poor Things',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film franchise features Dominic Toretto and family?',
    'Fast and Furious',
    'Mission Impossible',
    'Expendables',
    'Ocean movies',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film franchise features John Wick as a retired hitman?',
    'John Wick',
    'The Equalizer',
    'Taken',
    'Leon',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film franchise features Ethan Hunt?',
    'Mission: Impossible',
    'James Bond',
    'The Bourne Identity',
    'Jack Reacher',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film franchise features Jason Bourne?',
    'The Bourne Identity series',
    'Mission Impossible',
    'Bond',
    'The Transporter',
    'easy',
    'Movie Facts',
  ],
  [
    'Which horror franchise features Pennywise the clown?',
    'It',
    'Poltergeist',
    'The Conjuring',
    'Killer Klowns',
    'easy',
    'Movie Facts',
  ],
  [
    'Which horror franchise features the Warrens as paranormal investigators?',
    'The Conjuring',
    'Insidious',
    'Sinister',
    'Annabelle alone',
    'easy',
    'Movie Facts',
  ],
  [
    'Which horror franchise features Jigsaw and traps?',
    'Saw',
    'Hostel',
    'Final Destination',
    'Cube',
    'easy',
    'Movie Facts',
  ],
  [
    'Which horror franchise features Death designing elaborate accidents?',
    'Final Destination',
    'Saw',
    'Wrong Turn',
    'Cabin Fever',
    'medium',
    'Movie Facts',
  ],
  [
    'Which sci-fi franchise features xenomorphs and Ripley?',
    'Alien',
    'Predator',
    'The Thing',
    'Prometheus alone',
    'easy',
    'Movie Facts',
  ],
  [
    'Which sci-fi franchise features the Predator hunting humans?',
    'Predator',
    'Aliens vs Predator alone',
    'Alien',
    'The Predator only',
    'easy',
    'Movie Facts',
  ],
  [
    'Which franchise features cyborgs called Terminators played by Arnold?',
    'The Terminator series',
    'RoboCop',
    'Universal Soldier',
    'Westworld film',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film series is set in Panem with districts?',
    'The Hunger Games',
    'Divergent',
    'Maze Runner',
    'The Giver',
    'easy',
    'Movie Facts',
  ],
  [
    'Which series features Tris in faction-based Chicago?',
    'Divergent',
    'The Hunger Games',
    'Maze Runner',
    'Uglies',
    'medium',
    'Movie Facts',
  ],
  [
    'Which series features Thomas in a deadly maze?',
    'The Maze Runner',
    'Divergent',
    'The Hunger Games',
    'Lord of the Flies',
    'easy',
    'Movie Facts',
  ],
  [
    'Which fantasy series features a ring of power?',
    'The Lord of the Rings',
    'Harry Potter',
    'Narnia',
    'His Dark Materials',
    'easy',
    'Movie Facts',
  ],
  [
    'Which series features a boy wizard at Hogwarts?',
    'Harry Potter',
    'Percy Jackson',
    'Artemis Fowl',
    'Eragon',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film features the wardrobe leading to Narnia?',
    'The Lion, the Witch and the Wardrobe',
    'Prince Caspian',
    'The Voyage of the Dawn Treader',
    'The Silver Chair',
    'easy',
    'Movie Facts',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const TV_FACTS = [
  [
    'Which animated family has run since 1989 making it the longest-running American sitcom?',
    'The Simpsons',
    'Family Guy',
    'South Park',
    'The Flintstones',
    'medium',
    'TV Facts',
  ],
  [
    'What is the Simpsons town called?',
    'Springfield',
    'Shelbyville',
    'Quahog',
    'Arlen',
    'easy',
    'TV Facts',
  ],
  [
    'Which Friends cast member played Ross Geller?',
    'David Schwimmer',
    'Matthew Perry',
    'Matt LeBlanc',
    'Jennifer Aniston',
    'medium',
    'TV Facts',
  ],
  [
    'What was the Friends coffee shop called?',
    'Central Perk',
    'Central Cafe',
    'Monks',
    'The Coffee Bean',
    'easy',
    'TV Facts',
  ],
  [
    'Which show is set at Dunder Mifflin?',
    'The Office',
    'Parks and Recreation',
    'Superstore',
    '30 Rock',
    'easy',
    'TV Facts',
  ],
  [
    'Who played Michael Scott in The Office?',
    'Steve Carell',
    'Ricky Gervais',
    'Rainn Wilson',
    'John Krasinski',
    'easy',
    'TV Facts',
  ],
  [
    'Which actor played Dwight Schrute?',
    'Rainn Wilson',
    'John Krasinski',
    'BJ Novak',
    'Ed Helms',
    'medium',
    'TV Facts',
  ],
  [
    'Which spin-off of The Office ran for seven seasons? Parks and Recreation shares the universe loosely',
    'Parks and Recreation is not a spin-off but shares creators',
    'Brooklyn Nine-Nine',
    'Superstore',
    'American Vandal',
    'expert',
    'TV Facts',
  ],
  [
    'Which HBO crime drama starred Matthew McConaughey and Woody Harrelson in season one?',
    'True Detective',
    'The Night Of',
    'Sharp Objects',
    'Mare of Easttown',
    'medium',
    'TV Facts',
  ],
  [
    'Which show about advertising men in the 1960s starred Jon Hamm?',
    'Mad Men',
    'Better Call Saul',
    'Suits',
    'Masters of Sex',
    'easy',
    'TV Facts',
  ],
  [
    'Which HBO mob drama starred James Gandolfini?',
    'The Sopranos',
    'Boardwalk Empire',
    'Oz',
    'The Wire',
    'easy',
    'TV Facts',
  ],
  [
    'Which Baltimore crime series examined institutions?',
    'The Wire',
    'The Corner',
    'Homicide: Life on the Street',
    'Treme',
    'medium',
    'TV Facts',
  ],
  [
    'Which Netflix series made chess popular in 2020?',
    'The Queens Gambit',
    'The Scope',
    'Magnus',
    'Endgame series',
    'easy',
    'TV Facts',
  ],
  [
    'Which Star Wars series stars Pedro Pascal as Din Djarin?',
    'The Mandalorian',
    'The Book of Boba Fett',
    'Andor',
    'Obi-Wan Kenobi',
    'easy',
    'TV Facts',
  ],
  [
    'Which Star Wars series follows Cassian Andor?',
    'Andor',
    'Rogue One prequel series The Mandalorian',
    'The Bad Batch',
    'Ahsoka',
    'medium',
    'TV Facts',
  ],
  [
    'Which Breaking Bad spin-off follows Saul Goodman?',
    'Better Call Saul',
    'El Camino',
    'No Half Measures',
    'Slipping Jimmy',
    'easy',
    'TV Facts',
  ],
  [
    'Which Breaking Bad sequel film follows Jesse Pinkman?',
    'El Camino',
    'Better Call Saul',
    'Black Mail',
    'The Reward',
    'medium',
    'TV Facts',
  ],
  [
    'Which star Trek series rebooted in 2017 with Jason Isaacs and Sonequa Martin-Green?',
    'Star Trek: Discovery',
    'Star Trek: Picard',
    'Star Trek: Strange New Worlds',
    'Star Trek: Lower Decks',
    'hard',
    'TV Facts',
  ],
  [
    'Which series features Sherlock Holmes in modern London with Benedict Cumberbatch?',
    'Sherlock',
    'Elementary',
    'House MD',
    'Lucifer',
    'easy',
    'TV Facts',
  ],
  [
    'Which US series reimagined Holmes as a New York recovering addict with Lucy Liu?',
    'Elementary',
    'Sherlock',
    'Watson',
    'The Irregulars',
    'hard',
    'TV Facts',
  ],
  [
    'Which long-running British sci-fi features the TARDIS?',
    'Doctor Who',
    'Torchwood',
    'Red Dwarf',
    'Blake 7',
    'easy',
    'TV Facts',
  ],
  [
    'Which Doctor Who spin-off followed Captain Jack Harkness?',
    'Torchwood',
    'The Sarah Jane Adventures',
    'Class',
    'K9 and Company',
    'hard',
    'TV Facts',
  ],
  [
    'Which reality show features contestants surviving on an island for immunity?',
    'Survivor',
    'Big Brother',
    'The Challenge alone',
    'Alone',
    'easy',
    'TV Facts',
  ],
  [
    'Which reality show locks housemates in a house with live cameras?',
    'Big Brother',
    'Survivor',
    'The Amazing Race',
    'Love Island',
    'easy',
    'TV Facts',
  ],
  [
    'Which reality competition finds a fashion designer?',
    'Project Runway',
    'Top Chef',
    'The Voice',
    'Ink Master',
    'medium',
    'TV Facts',
  ],
  [
    'Which reality competition is for chefs hosted famously with judges?',
    'Top Chef',
    'MasterChef only',
    'HellKitchen',
    'Chopped',
    'medium',
    'TV Facts',
  ],
  [
    'Which singing competition features blind auditions with chairs?',
    'The Voice',
    'American Idol',
    'X Factor',
    'The Four',
    'easy',
    'TV Facts',
  ],
  [
    'Which talent show features a golden buzzer?',
    'Americas Got Talent',
    'American Idol',
    'The X Factor',
    'The Four',
    'medium',
    'TV Facts',
  ],
  [
    'Which dance competition features stars paired with pros?',
    'Dancing with the Stars',
    'So You Think You Can Dance',
    'World of Dance',
    'Americas Best Dance Crew',
    'easy',
    'TV Facts',
  ],
  [
    'Which quiz show features answering questions for a million dollars?',
    'Who Wants to Be a Millionaire',
    'Jeopardy',
    'The Weakest Link',
    'Deal or No Deal',
    'easy',
    'TV Facts',
  ],
  [
    'Which quiz show features answers phrased as questions?',
    'Jeopardy',
    'Millionaire',
    'Trivial Pursuit show',
    'Family Feud',
    'easy',
    'TV Facts',
  ],
  [
    'Which game show features two families guessing survey answers?',
    'Family Feud',
    'Wheel of Fortune',
    'The Price is Right',
    'Press Your Luck',
    'easy',
    'TV Facts',
  ],
  [
    'Which game show asks contestants to guess prices?',
    'The Price is Right',
    'Family Feud',
    'Wheel of Fortune',
    "Let's Make a Deal",
    'easy',
    'TV Facts',
  ],
  [
    'Which word game features a letter board and hangman-style play?',
    'Wheel of Fortune',
    'Scrabble show',
    'Wordle TV',
    'Countdown',
    'medium',
    'TV Facts',
  ],
  [
    'Which cartoon featured a stone age family?',
    'The Flintstones',
    'The Jetsons future family',
    'Yogi Bear',
    'Huckleberry Hound',
    'easy',
    'TV Facts',
  ],
  [
    'Which cartoon featured a space age family?',
    'The Jetsons',
    'The Flintstones',
    'Futurama',
    'Duck Dodgers',
    'easy',
    'TV Facts',
  ],
  [
    'Which adult cartoon is set in the 31st century with Fry and Leela?',
    'Futurama',
    'The Simpsons',
    'Family Guy',
    'Solar Opposites',
    'easy',
    'TV Facts',
  ],
  [
    'Which Looney Tunes character says Whats up, Doc?',
    'Bugs Bunny',
    'Daffy Duck',
    'Porky Pig',
    'Elmer Fudd',
    'easy',
    'TV Facts',
  ],
  [
    'Which cartoon cat chases Tweety?',
    'Sylvester',
    'Tom',
    'Scratchy',
    'Heathcliff',
    'easy',
    'TV Facts',
  ],
  [
    'Which cat-and-mouse duo ran since 1940 MGM cartoons?',
    'Tom and Jerry',
    'Itchy and Scratchy',
    'Herman and Katnip',
    'Pixie and Dixie',
    'easy',
    'TV Facts',
  ],
  [
    'Which 1960s cartoon family featured George, Jane, Judy, and Elroy?',
    'The Jetsons',
    'The Flintstones',
    'The Incredibles',
    'Meet the Robinsons',
    'medium',
    'TV Facts',
  ],
  [
    'Which HBO series featured dragons and west of Westeros prequel House of the Dragon?',
    'House of the Dragon',
    'The Rings of Power',
    'The Witcher',
    'Shadow and Bone',
    'easy',
    'TV Facts',
  ],
  [
    'Which Amazon series adapts Tolkien the second age? The Rings of Power',
    'The Rings of Power',
    'The Witcher',
    'Wheel of Time',
    'Shadow and Bone',
    'medium',
    'TV Facts',
  ],
  [
    'Which Amazon series adapts Robert Jordan novels?',
    'The Wheel of Time',
    'The Rings of Power',
    'The Witcher',
    'The Shannara Chronicles',
    'medium',
    'TV Facts',
  ],
  [
    'Which Netflix fantasy adapts Andrzej Sapkowski novels?',
    'The Witcher',
    'The Wheel of Time',
    'Shadow and Bone',
    'Cursed',
    'easy',
    'TV Facts',
  ],
  [
    'Which Netflix series adapts Leigh Bardugo novels?',
    'Shadow and Bone',
    'The Witcher',
    'Cursed',
    'The Letters of Fire',
    'hard',
    'TV Facts',
  ],
  [
    'Which superhero series on Amazon satirizes Vought and the Seven?',
    'The Boys',
    'Invincible',
    'Umbrella Academy',
    'Jupiter’s Legacy',
    'medium',
    'TV Facts',
  ],
  [
    'Which animated superhero series on Amazon adapts Robert Kirkman comics?',
    'Invincible',
    'The Boys presents Diabolical',
    'Umbrella Academy',
    'Harley Quinn',
    'medium',
    'TV Facts',
  ],
  [
    'Which Netflix series features the Hargreeves siblings?',
    'The Umbrella Academy',
    'The Boys',
    'Doom Patrol',
    'Titans',
    'medium',
    'TV Facts',
  ],
  [
    'Which DC series features a dysfunctional team of superheroes with Brendan Fraser and Diane Guerrero?',
    'Doom Patrol',
    'Titans',
    'Swamp Thing',
    'Stargirl',
    'hard',
    'TV Facts',
  ],
  [
    'Which comedy featured a Spanish teacher turned meth maker? That is Breaking Bad drama',
    'No such comedy; Breaking Bad is the drama',
    'Weeds',
    'Narcos comedy',
    'Barry',
    'expert',
    'TV Facts',
  ],
  [
    'Which dark comedy features a hitman wanting to act, starring Bill Hader?',
    'Barry',
    'Fargo',
    'The Bear',
    'Atlanta',
    'medium',
    'TV Facts',
  ],
  [
    'Which series follows a fine-dining chef returning to his family sandwich shop?',
    'The Bear',
    'Chef series',
    'Sweetbitter',
    'Salt Fat Acid Heat',
    'medium',
    'TV Facts',
  ],
  [
    'Which Donald Glover series won Emmys for Atlanta?',
    'Atlanta',
    'Brooklyn Nine-Nine',
    'Insecure',
    'Ramy',
    'medium',
    'TV Facts',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const SUPERHERO = [
  [
    'Which Infinity Stone does Vision have in his forehead?',
    'The Mind Stone',
    'The Time Stone',
    'The Power Stone',
    'The Reality Stone',
    'medium',
    'Superheroes',
  ],
  [
    'Who wields the Time Stone in Doctor Strange?',
    'The Eye of Agamotto',
    'The Darkhold',
    'The Orb',
    'The Tesseract',
    'medium',
    'Superheroes',
  ],
  [
    'What is the Tesseract?',
    'The container of the Space Stone',
    'A shield',
    'An Infinity Gauntlet',
    'A vibranium core',
    'medium',
    'Superheroes',
  ],
  [
    'Which metal is Wolverines skeleton laced with?',
    'Adamantium',
    'Vibranium',
    'Titanium',
    'Carbonadium',
    'easy',
    'Superheroes',
  ],
  [
    'Which metal is Captain Americas shield made of?',
    'Vibranium',
    'Adamantium',
    'Steel',
    'Uru',
    'easy',
    'Superheroes',
  ],
  [
    'Which fictional country hides vibranium as Wakanda?',
    'Wakanda',
    'Zamunda comedy',
    'Genosha mutant state',
    'Latveria',
    'easy',
    'Superheroes',
  ],
  [
    'What is the Black Panther royal name?',
    'TChalla',
    'MBaku',
    'Killmonger',
    'Zuri',
    'medium',
    'Superheroes',
  ],
  [
    'Who plays Killmonger in Black Panther?',
    'Michael B. Jordan',
    'Chadwick Boseman',
    'Daniel Kaluuya',
    'John Boyega',
    'medium',
    'Superheroes',
  ],
  [
    'Who is Tony Starks father in the MCU?',
    'Howard Stark',
    'Nick Fury',
    'Obadiah Stane',
    'Aldrich Killian',
    'medium',
    'Superheroes',
  ],
  [
    'What is Spider-Mans real name in the main comics?',
    'Peter Parker',
    'Miles Morales',
    'Ben Reilly',
    'Miguel OHara',
    'easy',
    'Superheroes',
  ],
  [
    'Which Spider-Man villain is the Green Goblin?',
    'Norman Osborn',
    'Otto Octavius',
    'Eddie Brock',
    'Adrian Toomes',
    'easy',
    'Superheroes',
  ],
  [
    'Which Spider-Man villain has mechanical tentacles?',
    'Doctor Octopus',
    'Green Goblin',
    'Venom',
    'Electro',
    'easy',
    'Superheroes',
  ],
  [
    'Which symbiote bonds with Eddie Brock?',
    'Venom',
    'Carnage',
    'Riot',
    'Toxin',
    'easy',
    'Superheroes',
  ],
  [
    'Which superhero is known as the Man of Steel?',
    'Superman',
    'Steel',
    'Captain Marvel DC',
    'Martian Manhunter',
    'easy',
    'Superheroes',
  ],
  [
    'What is Supermans Kryptonian birth name?',
    'Kal-El',
    'Jor-El',
    'Zor-El',
    'Nam-Ek',
    'medium',
    'Superheroes',
  ],
  [
    'What is Batmans loyal butler called?',
    'Alfred Pennyworth',
    'James Gordon',
    'Lucius Fox',
    'Harvey Dent',
    'easy',
    'Superheroes',
  ],
  [
    'What is Batmans home city?',
    'Gotham City',
    'Metropolis',
    'Star City',
    'Central City',
    'easy',
    'Superheroes',
  ],
  [
    'Which villain broke Batmans back in Knightfall?',
    'Bane',
    'Joker',
    'Two-Face',
    'Ra al Ghul',
    'medium',
    'Superheroes',
  ],
  [
    'Which team assembles in the Hall of Justice?',
    'The Justice League',
    'The Avengers',
    'The X-Men',
    'The Guardians',
    'easy',
    'Superheroes',
  ],
  [
    'Which team is called Earths Mightiest Heroes?',
    'The Avengers',
    'The Justice League',
    'The Suicide Squad',
    'The Eternals',
    'easy',
    'Superheroes',
  ],
  [
    'Which aquatic hero rules Atlantis in DC films?',
    'Aquaman',
    'Namor',
    'Triton',
    'Mera',
    'easy',
    'Superheroes',
  ],
  [
    'Which speedster protects Central City?',
    'The Flash',
    'Quicksilver',
    'Zoom',
    'Speedball',
    'easy',
    'Superheroes',
  ],
  [
    'Which green hero grows stronger with rage?',
    'The Hulk',
    'Beast Boy',
    'Martian Manhunter',
    'Doc Samson',
    'easy',
    'Superheroes',
  ],
  [
    'Which god of mischief does Tom Hiddleston play?',
    'Loki',
    'Thor',
    'Odin',
    'Heimdall',
    'easy',
    'Superheroes',
  ],
  [
    'Which axe does Thor wield in Endgame?',
    'Stormbreaker',
    'Gungnir',
    'The Chitauri scepter',
    'The Casket sword',
    'medium',
    'Superheroes',
  ],
  [
    'Which villain collects the Infinity Stones in Infinity War?',
    'Thanos',
    'Loki',
    'Ultron',
    'Ronan',
    'easy',
    'Superheroes',
  ],
  [
    'What did Thanos snap do?',
    'Erase half of all life',
    'Destroy only the Avengers',
    'Reset one timeline',
    'Merge two universes',
    'easy',
    'Superheroes',
  ],
  [
    'Which Avenger lifts Mjolnir in Endgame?',
    'Captain America',
    'Iron Man',
    'Hulk',
    'Hawkeye',
    'easy',
    'Superheroes',
  ],
  [
    'Who receives Caps shield at the end of Endgame?',
    'Sam Wilson',
    'Bucky Barnes',
    'Rhodey',
    'Peter Parker',
    'medium',
    'Superheroes',
  ],
  [
    'Which Disney+ series places Wanda and Vision in sitcom worlds?',
    'WandaVision',
    'Loki',
    'Hawkeye',
    'Moon Knight',
    'easy',
    'Superheroes',
  ],
  [
    'Which Disney+ series follows Loki with the TVA?',
    'Loki',
    'WandaVision',
    'What If',
    'Secret Invasion',
    'easy',
    'Superheroes',
  ],
  [
    'What does TVA stand for in Loki?',
    'Time Variance Authority',
    'Temporal Vanguard Agency',
    'Time Verification Alliance',
    'Timeline Vigilance Administration',
    'medium',
    'Superheroes',
  ],
  [
    'Which DC series stars John Cena as Peacemaker?',
    'Peacemaker',
    'The Suicide Squad film only',
    'Harley Quinn series',
    'Superman and Lois',
    'medium',
    'Superheroes',
  ],
  [
    'Which 2016 film assembles villains for black-ops missions?',
    'Suicide Squad',
    'The Avengers',
    'Guardians of the Galaxy',
    'X-Force',
    'easy',
    'Superheroes',
  ],
  [
    'Which mutant team does Professor Xavier lead?',
    'The X-Men',
    'The Brotherhood',
    'Excalibur',
    'X-Factor',
    'easy',
    'Superheroes',
  ],
  [
    'Which school do the X-Men attend?',
    'Xaviers School for Gifted Youngsters',
    'Midtown High',
    'S.T.A.R. Labs academy',
    'Ivy University',
    'easy',
    'Superheroes',
  ],
  [
    'Which X-Men villain controls magnetism?',
    'Magneto',
    'Apocalypse',
    'Mystique',
    'Juggernaut',
    'easy',
    'Superheroes',
  ],
  [
    'Which shapeshifting X-Men villain-ally is blue?',
    'Mystique',
    'Rogue',
    'Jean Grey',
    'Emma Frost',
    'easy',
    'Superheroes',
  ],
  [
    'Which X-Men absorbs powers and memories by touch?',
    'Rogue',
    'Mystique',
    'Jubilee',
    'Dazzler',
    'medium',
    'Superheroes',
  ],
  ['Which X-Men controls weather?', 'Storm', 'Cyclops', 'Iceman', 'Bishop', 'easy', 'Superheroes'],
  [
    'Which X-Men leader fires optic beams?',
    'Cyclops',
    'Havok',
    'Gambit',
    'Beast',
    'easy',
    'Superheroes',
  ],
  [
    'Which telekinetic X-Men becomes the Phoenix?',
    'Jean Grey',
    'Storm',
    'Psylocke',
    'Rogue',
    'easy',
    'Superheroes',
  ],
  [
    'Which Fantastic Four member stretches?',
    'Mister Fantastic',
    'The Thing',
    'Invisible Woman',
    'Human Torch',
    'easy',
    'Superheroes',
  ],
  [
    'Which Fantastic Four member is made of orange rock?',
    'The Thing',
    'Mister Fantastic',
    'Human Torch',
    'Silver Surfer',
    'easy',
    'Superheroes',
  ],
  [
    'Which cosmic herald rides a surfboard toward Galactus?',
    'The Silver Surfer',
    'Nova',
    'The Watcher',
    'Quasar',
    'medium',
    'Superheroes',
  ],
  [
    'Which young hero is Kamala Khan?',
    'Ms. Marvel',
    'Captain Marvel Carol Danvers',
    'Monica Rambeau',
    'America Chavez',
    'medium',
    'Superheroes',
  ],
  [
    'Which blind lawyer is Daredevil?',
    'Matt Murdock',
    'Frank Castle',
    'Danny Rand',
    'Foggy Nelson',
    'easy',
    'Superheroes',
  ],
  [
    'Which Harlem hero has unbreakable skin?',
    'Luke Cage',
    'Iron Fist',
    'Blade',
    'Colleen Wing',
    'medium',
    'Superheroes',
  ],
  [
    'Which daywalker hunts vampires with a sword?',
    'Blade',
    'Moon Knight',
    'Ghost Rider',
    'Punisher',
    'medium',
    'Superheroes',
  ],
  [
    'Which vigilante uses a skull logo and guns?',
    'The Punisher',
    'Deadpool',
    'Moon Knight',
    'Jessica Jones',
    'easy',
    'Superheroes',
  ],
  [
    'Which hero rides a flaming motorcycle with a vengeance spirit?',
    'Ghost Rider',
    'Spawn',
    'Hellboy',
    'Lobo',
    'medium',
    'Superheroes',
  ],
  [
    'Which private investigator hero is Jessica Jones alias Jewel?',
    'Jessica Jones',
    'Typhoid Mary',
    'Black Cat',
    'Colleen Wing',
    'medium',
    'Superheroes',
  ],
  [
    'Which underwater antihero fights Wakanda in the sequel?',
    'Namor',
    'Attuma',
    'MBaku',
    'Killmonger',
    'expert',
    'Superheroes',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const CLASSIC_TV = [
  [
    'Which 1950s sitcom starred Lucille Ball?',
    'I Love Lucy',
    'The Honeymooners',
    'Our Miss Brooks',
    'Bewitched',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom starred Jackie Gleason as Ralph Kramden?',
    'The Honeymooners',
    'I Love Lucy',
    'All in the Family',
    'The Dick Van Dyke Show',
    'hard',
    'Classic TV',
  ],
  [
    'Which classic sitcom tackled bigotry via Archie Bunker?',
    'All in the Family',
    'The Jeffersons',
    'Maude',
    'Sanford and Son',
    'medium',
    'Classic TV',
  ],
  [
    'Which show featured Mary Tyler Moore in a Minneapolis newsroom?',
    'The Mary Tyler Moore Show',
    'The Dick Van Dyke Show',
    'That Girl',
    'Murphy Brown',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom featured a witch married to a mortal man?',
    'Bewitched',
    'I Dream of Jeannie',
    'Sabrina the Teenage Witch',
    'Dark Shadows',
    'easy',
    'Classic TV',
  ],
  [
    'Which sitcom featured a genie named Jeannie?',
    'I Dream of Jeannie',
    'Bewitched',
    'Mork and Mindy',
    'The Flying Nun',
    'easy',
    'Classic TV',
  ],
  [
    'Which 80s sitcom featured a furry alien from Melmac?',
    'ALF',
    'Mork and Mindy',
    '3rd Rock from the Sun',
    'Perfect Strangers',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom made Fonzie and the Ayyy a pop culture icon?',
    'Happy Days',
    'Laverne and Shirley',
    'Mork and Mindy',
    'Joanie Loves Chachi',
    'easy',
    'Classic TV',
  ],
  [
    'Which spin-off followed two women at a Milwaukee brewery?',
    'Laverne and Shirley',
    'Alice',
    'One Day at a Time',
    'Kate and Allie',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom featured Arnold and Willis with the famous line about Willis?',
    'Diffrent Strokes',
    'Webster',
    'Gimme a Break',
    'Family Matters',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom made Steve Urkel a breakout character?',
    'Family Matters',
    'Full House',
    'Step by Step',
    'Hangin with Mr. Cooper',
    'easy',
    'Classic TV',
  ],
  [
    'Which sitcom followed the Tanner household in San Francisco?',
    'Full House',
    'Family Matters',
    'Boy Meets World',
    'Growing Pains',
    'easy',
    'Classic TV',
  ],
  [
    'Which nostalgia series followed Kevin Arnold in the 1960s-70s?',
    'The Wonder Years',
    'Boy Meets World',
    'Doogie Howser M.D.',
    'Freaks and Geeks later',
    'medium',
    'Classic TV',
  ],
  [
    'Which series followed Cory Matthews from middle school to college?',
    'Boy Meets World',
    'The Wonder Years',
    'Saved by the Bell',
    'Sabrina the Teenage Witch',
    'easy',
    'Classic TV',
  ],
  [
    'Which teen sitcom was set at Bayside High with Zack Morris?',
    'Saved by the Bell',
    'Beverly Hills 90210',
    'California Dreams',
    'Hang Time',
    'easy',
    'Classic TV',
  ],
  [
    'Which 90s drama followed teens at West Beverly High?',
    'Beverly Hills 90210',
    'Melrose Place',
    'Dawsons Creek',
    'Party of Five',
    'easy',
    'Classic TV',
  ],
  [
    'Which drama followed friends in Capeside starring Katie Holmes?',
    'Dawsons Creek',
    'Felicity',
    'Everwood',
    'One Tree Hill',
    'medium',
    'Classic TV',
  ],
  [
    'Which series starred Neil Patrick Harris as a teenage doctor?',
    'Doogie Howser M.D.',
    'House',
    'ER',
    'Chicago Hope',
    'medium',
    'Classic TV',
  ],
  [
    'Which spin-off followed Frasier Crane back in Seattle on radio?',
    'Frasier',
    'Cheers',
    'Wings',
    'Becker',
    'medium',
    'Classic TV',
  ],
  [
    'Which workplace sitcom starred Dave Foley at a New York radio station?',
    'NewsRadio',
    'Frasier',
    'WKRP in Cincinnati',
    'Murphy Brown',
    'hard',
    'Classic TV',
  ],
  [
    'Which sitcom starred Candice Bergen as a TV journalist?',
    'Murphy Brown',
    'NewsRadio',
    'Sports Night',
    'The Mary Tyler Moore Show',
    'medium',
    'Classic TV',
  ],
  [
    'Which 90s sitcom featured Ellen Morgans coming out episode?',
    'Ellen',
    'Will and Grace',
    'The Ellen Show',
    'Friends',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom starred Eric McCormack and Debra Messing in New York?',
    'Will and Grace',
    'Ellen',
    'Sex and the City',
    'Partners',
    'easy',
    'Classic TV',
  ],
  [
    'Which HBO series followed Carrie Bradshaw and friends?',
    'Sex and the City',
    'Girls',
    'The L Word',
    'Curb Your Enthusiasm',
    'easy',
    'Classic TV',
  ],
  [
    'Which sitcom paired Felix Unger and Oscar Madison?',
    'The Odd Couple',
    'Three is Company',
    'The Honeymooners',
    'Mork and Mindy',
    'medium',
    'Classic TV',
  ],
  [
    'Which classic sitcom was set in Mayberry with Sheriff Taylor?',
    'The Andy Griffith Show',
    'Green Acres',
    'Petticoat Junction',
    'Gomer Pyle U.S.M.C.',
    'medium',
    'Classic TV',
  ],
  [
    'Which sitcom followed the Clampett family after striking oil?',
    'The Beverly Hillbillies',
    'Green Acres',
    'Petticoat Junction',
    'Dallas',
    'easy',
    'Classic TV',
  ],
  [
    'Which sitcom featured a robot daughter named V.I.C.I.?',
    'Small Wonder',
    'Punky Brewster',
    'My Living Doll',
    'Weird Science',
    'expert',
    'Classic TV',
  ],
  [
    'Which sitcom featured Punky Brewster a spirited orphan?',
    'Punky Brewster',
    'Small Wonder',
    'Out of This World',
    'Mr. Belvedere',
    'hard',
    'Classic TV',
  ],
  [
    'Which show featured a Martian living with a reporter? My Favorite Martian',
    'My Favorite Martian',
    'ALF',
    'Mork and Mindy',
    '3rd Rock from the Sun',
    'hard',
    'Classic TV',
  ],
  [
    'Which show gave a teacher an alien superhero suit? The Greatest American Hero',
    'The Greatest American Hero',
    'The Incredible Hulk series',
    'The Six Million Dollar Man',
    'Automan',
    'hard',
    'Classic TV',
  ],
  [
    'Which Korean War dramedy followed Hawkeye and Hot Lips?',
    'MASH',
    'McHales Navy',
    'Hogans Heroes',
    'Car 54 Where Are You',
    'expert',
    'Classic TV',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const KIDS_ANIME = [
  [
    'Which anime features Goku hunting Dragon Balls?',
    'Dragon Ball',
    'Naruto',
    'One Piece',
    'Bleach',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime follows Naruto Uzumaki toward Hokage?',
    'Naruto',
    'Dragon Ball Z',
    'Bleach',
    'My Hero Academia',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime follows Luffy and the Straw Hats for treasure?',
    'One Piece',
    'Hunter x Hunter',
    'Fairy Tail',
    'Black Clover',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime features soul reaper Ichigo Kurosaki?',
    'Bleach',
    'Naruto',
    'Death Note',
    'Yu Yu Hakusho',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features Light Yagami and a deadly notebook?',
    'Death Note',
    'Code Geass',
    'Future Diary',
    'Psycho-Pass',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime features Eren fighting man-eating Titans?',
    'Attack on Titan',
    'Tokyo Ghoul',
    'Parasyte',
    'Kabaneri of the Iron Fortress',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime follows quirkless Izuku at UA High?',
    'My Hero Academia',
    'One Punch Man',
    'Black Clover',
    'Mob Psycho 100',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime features Saitama finishing foes with one punch?',
    'One Punch Man',
    'My Hero Academia',
    'Mob Psycho 100',
    'Baki',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime follows the Elric brothers seeking the Philosophers Stone?',
    'Fullmetal Alchemist',
    'D.Gray-man',
    'Magi',
    'Soul Eater',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime film swaps Taki and Mitsuha across time?',
    'Your Name',
    'Weathering with You',
    'A Silent Voice',
    'Suzume',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features volleyball ace Hinata Shoyo?',
    'Haikyuu',
    'Kuroko no Basket',
    'Free',
    'Yowamushi Pedal',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features phantom sixth man Kuroko in basketball?',
    'Kuroko no Basket',
    'Haikyuu',
    'Slam Dunk',
    'Ahiru no Sora',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which classic 90s anime followed Shohoku High basketball?',
    'Slam Dunk',
    'Kuroko no Basket',
    'Dear Boys',
    'Buzzer Beater',
    'hard',
    'Kids & Anime',
  ],
  [
    'Which shinigami drops the Death Note into the human world?',
    'Ryuk',
    'Rem',
    'Sidoh',
    'Jealous',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features giant Eva robots and Angels?',
    'Neon Genesis Evangelion',
    'Gundam Wing',
    'Code Geass',
    'Gurren Lagann',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which long-running detective anime stars a shrunken Shinichi? Case Closed',
    'Detective Conan',
    'Inuyasha',
    'Yu Yu Hakusho',
    'City Hunter',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime sends Kagome through a well to feudal Japan?',
    'Inuyasha',
    'Yashahime',
    'Rurouni Kenshin',
    'Fruits Basket',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime follows Tohru and the cursed Sohma zodiac family?',
    'Fruits Basket',
    'Nana',
    'Ouran High School Host Club',
    'Kimi ni Todoke',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features bounty hunter Spike Spiegel in space?',
    'Cowboy Bebop',
    'Trigun',
    'Samurai Champloo',
    'Outlaw Star',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features Vash the Stampede with a huge bounty?',
    'Trigun',
    'Cowboy Bebop',
    'Gungrave',
    'Baccano',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which magical girl anime features Usagi Tsukino?',
    'Sailor Moon',
    'Cardcaptor Sakura',
    'Tokyo Mew Mew',
    'Mermaid Melody',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which anime features Sakura Kinomoto capturing Clow Cards?',
    'Cardcaptor Sakura',
    'Sailor Moon',
    'Shugo Chara',
    'Magic Knight Rayearth',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which anime features Ash Ketchum and Pikachu?',
    'Pokemon',
    'Digimon',
    'Yo-kai Watch',
    'Monster Rancher',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which digital-monster anime features Tai and Agumon?',
    'Digimon Adventure',
    'Pokemon',
    'Medabots',
    'Beyblade',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which kids show features a sponge living in a pineapple under the sea?',
    'SpongeBob SquarePants',
    'The Fairly OddParents',
    'Jimmy Neutron',
    'Danny Phantom',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which kids show features Timmy Turner and his fairy godparents?',
    'The Fairly OddParents',
    'Jimmy Neutron',
    'Danny Phantom',
    'ChalkZone',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which kids show features a boy genius named after neutron science?',
    'Jimmy Neutron',
    'Dexters Laboratory',
    'Johnny Test',
    'Edd Ed n Eddy',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which kids show features a boy with a secret laboratory and a rival Dee Dee?',
    'Dexters Laboratory',
    'Jimmy Neutron',
    'Codename Kids Next Door',
    'Johnny Bravo',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which cartoon features Blossom, Bubbles, and Buttercup?',
    'The Powerpuff Girls',
    'Totally Spies',
    'Kim Possible',
    'Atomic Betty',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which cartoon features teen spy Kim Possible and Ron Stoppable?',
    'Kim Possible',
    'Totally Spies',
    'Atomic Betty',
    '6teen',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which cartoon features spy Sam, Clover, and Alex from Beverly Hills?',
    'Totally Spies',
    'Kim Possible',
    'Winx Club',
    'WITCH',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which series features Aang mastering all four elements?',
    'Avatar: The Last Airbender',
    'The Legend of Korra',
    'Ninjago',
    'Xiaolin Showdown',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which sequel series follows Avatar Korra?',
    'The Legend of Korra',
    'Avatar: The Last Airbender',
    'Yu-Gi-Oh GX',
    'Dragon Ball Super',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which show centers on the Millennium Puzzle and duel monsters?',
    'Yu-Gi-Oh',
    'Pokemon',
    'Bakugan',
    'Medabots',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which show features spinning battle tops and Bit Beasts?',
    'Beyblade',
    'Yu-Gi-Oh',
    'Bakugan',
    'Medabots',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which show features Ben Tennyson and the Omnitrix?',
    'Ben 10',
    'Generator Rex',
    'The Secret Saturdays',
    'Danny Phantom',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which show features Danny Fenton becoming a ghost hero?',
    'Danny Phantom',
    'American Dragon: Jake Long',
    'The Life and Times of Juniper Lee',
    'El Tigre',
    'easy',
    'Kids & Anime',
  ],
  [
    'Which show features Jake Long as a dragon protecting New York?',
    'American Dragon: Jake Long',
    'Danny Phantom',
    'Juniper Lee',
    'Jackie Chan Adventures',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which cartoon features the Eds scheming for jawbreakers?',
    'Ed, Edd n Eddy',
    'Billy and Mandy',
    'Kids Next Door',
    'Fosters Home',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which cartoon features Sector V of the Kids Next Door?',
    'Codename: Kids Next Door',
    'Ed, Edd n Eddy',
    'Fosters Home for Imaginary Friends',
    'Chowder',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which cartoon features Bloo at a home for imaginary friends?',
    'Fosters Home for Imaginary Friends',
    'Chowder',
    'Flapjack',
    'Camp Lazlo',
    'medium',
    'Kids & Anime',
  ],
  [
    'Which cartoon features a young cook apprenticing in Marzipan City?',
    'Chowder',
    'Flapjack',
    'Camp Lazlo',
    'Squirrel Boy',
    'hard',
    'Kids & Anime',
  ],
  [
    'Which cartoon follows Flapjack and Captain K nuckles to Candied Island?',
    'The Marvelous Misadventures of Flapjack',
    'Chowder',
    'Camp Lazlo',
    'Squirrel Boy',
    'hard',
    'Kids & Anime',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const CINEMA_HISTORY = [
  [
    'Who directed Citizen Kane in 1941?',
    'Orson Welles',
    'Alfred Hitchcock',
    'John Ford',
    'Billy Wilder',
    'medium',
    'Cinema History',
  ],
  [
    'Which film is frequently ranked the greatest ever from 1941?',
    'Citizen Kane',
    'Casablanca',
    'Vertigo',
    'Sunrise',
    'medium',
    'Cinema History',
  ],
  [
    'Who directed Casablanca?',
    'Michael Curtiz',
    'Howard Hawks',
    'Billy Wilder',
    'John Huston',
    'medium',
    'Cinema History',
  ],
  [
    'Which 1946 Frank Capra film shows a world where George Bailey was never born?',
    'Its a Wonderful Life',
    'Mr. Smith Goes to Washington',
    'Meet John Doe',
    'Arsenic and Old Lace',
    'medium',
    'Cinema History',
  ],
  [
    'Which director was famous for westerns like The Searchers?',
    'John Ford',
    'Howard Hawks',
    'Sergio Leone',
    'Anthony Mann',
    'medium',
    'Cinema History',
  ],
  [
    'Which Italian director pioneered spaghetti westerns?',
    'Sergio Leone',
    'Federico Fellini',
    'Michelangelo Antonioni',
    'Dario Argento',
    'medium',
    'Cinema History',
  ],
  [
    'Who scored The Good, the Bad and the Ugly?',
    'Ennio Morricone',
    'Nino Rota',
    'Hans Zimmer',
    'John Barry',
    'medium',
    'Cinema History',
  ],
  [
    'Who composed the Godfather score?',
    'Nino Rota',
    'Ennio Morricone',
    'John Williams',
    'Franco Ferrara',
    'expert',
    'Cinema History',
  ],
  [
    'Who composed the scores for Star Wars, Jaws, and Jurassic Park?',
    'John Williams',
    'Hans Zimmer',
    'James Horner',
    'Jerry Goldsmith',
    'easy',
    'Cinema History',
  ],
  [
    'Who composed The Lion King and Dune scores?',
    'Hans Zimmer',
    'John Williams',
    'Alan Menken',
    'Danny Elfman',
    'easy',
    'Cinema History',
  ],
  [
    'Who composed Batman 1989 and The Nightmare Before Christmas?',
    'Danny Elfman',
    'Hans Zimmer',
    'Alan Silvestri',
    'Howard Shore',
    'medium',
    'Cinema History',
  ],
  [
    'Who composed the Lord of the Rings trilogy music?',
    'Howard Shore',
    'John Williams',
    'James Newton Howard',
    'Patrick Doyle',
    'medium',
    'Cinema History',
  ],
  [
    'Which Elton John song won an Oscar for The Lion King?',
    'Can You Feel the Love Tonight',
    'Hakuna Matata',
    'Circle of Life',
    'Be Prepared',
    'expert',
    'Cinema History',
  ],
  [
    'Which composer wrote Beauty and the Beast songs with Howard Ashman?',
    'Alan Menken',
    'Elton John',
    'Phil Collins',
    'Lin-Manuel Miranda',
    'medium',
    'Cinema History',
  ],
  [
    'Which rock artist scored Tarzan with Youll Be in My Heart?',
    'Phil Collins',
    'Elton John',
    'Alan Menken',
    'Randy Newman',
    'medium',
    'Cinema History',
  ],
  [
    'Which composer wrote Youve Got a Friend in Me for Toy Story?',
    'Randy Newman',
    'Phil Collins',
    'Alan Menken',
    'John Powell',
    'medium',
    'Cinema History',
  ],
  [
    'Which Indian composer won an Oscar for the Slumdog Millionaire score?',
    'A.R. Rahman',
    'Zakir Hussain',
    'Ravi Shankar',
    'Ilaiyaraaja',
    'medium',
    'Cinema History',
  ],
  [
    'Which chart hit from Slumdog Millionaire won Best Original Song?',
    'Jai Ho',
    'O Saya',
    'Chaiyya Chaiyya',
    'Naatu Naatu',
    'medium',
    'Cinema History',
  ],
  [
    'Which director made In the Mood for Love?',
    'Wong Kar-wai',
    'John Woo',
    'Ang Lee',
    'Zhang Yimou',
    'hard',
    'Cinema History',
  ],
  [
    'Which director made Crouching Tiger, Hidden Dragon and Life of Pi?',
    'Ang Lee',
    'Zhang Yimou',
    'John Woo',
    'Wong Kar-wai',
    'medium',
    'Cinema History',
  ],
  [
    'Which Chinese director made Hero and House of Flying Daggers?',
    'Zhang Yimou',
    'Ang Lee',
    'Chen Kaige',
    'Tsui Hark',
    'medium',
    'Cinema History',
  ],
  [
    'Which Hong Kong director made hard-boiled hits like The Killer and Face/Off?',
    'John Woo',
    'Tsui Hark',
    'Ringo Lam',
    'Corey Yuen',
    'medium',
    'Cinema History',
  ],
  [
    'Which 1954 Kurosawa epic inspired The Magnificent Seven?',
    'Seven Samurai',
    'Rashomon',
    'Yojimbo',
    'Ikiru',
    'medium',
    'Cinema History',
  ],
  [
    'Which Kurosawa film inspired A Fistful of Dollars?',
    'Yojimbo',
    'Seven Samurai',
    'Sanjuro',
    'Throne of Blood',
    'hard',
    'Cinema History',
  ],
  [
    'Which Kurosawa film gave its name to conflicting-testimony storytelling?',
    'Rashomon',
    'Seven Samurai',
    'Ikiru',
    'High and Low',
    'medium',
    'Cinema History',
  ],
  [
    'Which Swedish director made The Seventh Seal?',
    'Ingmar Bergman',
    'Federico Fellini',
    'Andrei Tarkovsky',
    'Luis Bunuel',
    'medium',
    'Cinema History',
  ],
  [
    'Which Italian director made 8½ and La Dolce Vita?',
    'Federico Fellini',
    'Vittorio De Sica',
    'Roberto Rossellini',
    'Antonioni',
    'medium',
    'Cinema History',
  ],
  [
    'Which movement did Bicycle Thieves define?',
    'Italian neorealism',
    'French New Wave',
    'German Expressionism',
    'Soviet montage',
    'medium',
    'Cinema History',
  ],
  [
    'Which French movement featured Godard and Truffaut?',
    'The French New Wave',
    'Italian neorealism',
    'Cinema du look',
    'Pure cinema',
    'medium',
    'Cinema History',
  ],
  [
    'Which 1960 Godard film starred Jean-Paul Belmondo as Michel?',
    'Breathless',
    'The 400 Blows',
    'Jules and Jim',
    'Pierrot le Fou',
    'expert',
    'Cinema History',
  ],
  [
    'Which Truffaut debut about a boy launched the New Wave?',
    'The 400 Blows',
    'Breathless',
    'Jules and Jim',
    'Shoot the Piano Player',
    'hard',
    'Cinema History',
  ],
  [
    'Which German director made Metropolis in 1927?',
    'Fritz Lang',
    'F.W. Murnau',
    'Robert Wiene',
    'Ernst Lubitsch',
    'medium',
    'Cinema History',
  ],
  [
    'Which 1920 German horror film features a sleepwalking somnambulist?',
    'The Cabinet of Dr. Caligari',
    'Nosferatu',
    'Metropolis',
    'The Golem',
    'hard',
    'Cinema History',
  ],
  [
    'Which 1922 unauthorized Dracula adaptation starred Max Schreck?',
    'Nosferatu',
    'Dracula 1931',
    'Vampyr',
    'The Phantom Carriage',
    'medium',
    'Cinema History',
  ],
  [
    'Which silent comedian made City Lights and Modern Times?',
    'Charlie Chaplin',
    'Buster Keaton',
    'Harold Lloyd',
    'Harry Langdon',
    'easy',
    'Cinema History',
  ],
  [
    'Which silent star was called The Great Stone Face for his deadpan stunts?',
    'Buster Keaton',
    'Charlie Chaplin',
    'Harold Lloyd',
    'Roscoe Arbuckle',
    'medium',
    'Cinema History',
  ],
  [
    'Which silent star dangled from a clock in Safety Last?',
    'Harold Lloyd',
    'Buster Keaton',
    'Charlie Chaplin',
    'Douglas Fairbanks',
    'hard',
    'Cinema History',
  ],
  [
    'Which studio produced the Looney Tunes shorts?',
    'Warner Bros.',
    'MGM',
    'Disney',
    'Fleischer Studios',
    'medium',
    'Cinema History',
  ],
  [
    'Which studio produced Tom and Jerry shorts?',
    'MGM',
    'Warner Bros.',
    'Disney',
    'Fleischer',
    'medium',
    'Cinema History',
  ],
  [
    'Which studio produced Popeye and Betty Boop cartoons?',
    'Fleischer Studios',
    'Warner Bros.',
    'MGM',
    'Hanna-Barbera',
    'hard',
    'Cinema History',
  ],
  [
    'Which TV animation house created Scooby-Doo and The Flintstones?',
    'Hanna-Barbera',
    'Filmation',
    'DePatie-Freleng',
    'Ruby-Spears',
    'medium',
    'Cinema History',
  ],
  [
    'Which dog and his pals solve mysteries in the Mystery Machine?',
    'Scooby-Doo and the gang',
    'Alvin and the Chipmunks',
    'Yogi and Boo-Boo',
    'Augie Doggie',
    'easy',
    'Cinema History',
  ],
  [
    'Which singing chipmunk trio debuted in 1958?',
    'Alvin and the Chipmunks',
    'Chip and Dale',
    'Yakky Doodle',
    'Huckleberry Hound',
    'medium',
    'Cinema History',
  ],
];

// [question, correct, d1, d2, d3, level, chapter]
const TOPUP = [
  [
    'Which film features John Wick avenging his dog?',
    'John Wick',
    'Taken',
    'Man on Fire',
    'The Equalizer',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film features Bryan Mills saying I will find you?',
    'Taken',
    'John Wick',
    'Man on Fire',
    'Safe',
    'easy',
    'Movie Facts',
  ],
  [
    'Which film franchise features Dom and family saying family a lot in memes?',
    'Fast and Furious',
    'The Expendables',
    'Ocean films',
    'Rush Hour',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 2014 film launched the current Planet of the Apes trilogy with Caesar?',
    'Dawn of the Planet of the Apes 2014 followed Rise 2011',
    'Rise of the Planet of the Apes in 2011',
    'War for the Planet of the Apes',
    'Kingdom of the Planet of the Apes',
    'expert',
    'Movie Facts',
  ],
  [
    'Which 2011 film rebooted Planet of the Apes with James Franco?',
    'Rise of the Planet of the Apes',
    'Dawn of the Planet of the Apes',
    'War for the Planet of the Apes',
    'Kingdom of the Planet of the Apes',
    'medium',
    'Movie Facts',
  ],
  [
    'Which animated hit features Miguel visiting the Land of the Dead?',
    'Coco',
    'The Book of Life',
    'Encanto',
    'Luca',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Pixar film is set on the Italian Riviera as sea monsters? Luca',
    'Luca',
    'Finding Nemo',
    'Onward',
    'Turning Red',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Pixar film turns a girl into a red panda?',
    'Turning Red',
    'Brave',
    'Luca',
    'Onward',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Pixar film features two elves seeking magic? Onward',
    'Onward',
    'Brave',
    'Wish',
    'Elemental',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 2023 Pixar film is set in a city of elements? Elemental',
    'Elemental',
    'Luca',
    'Soul',
    'Wish',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Disney film features the madrigal family and no gifts? Encanto uses a candle',
    'Encanto',
    'Coco',
    'Moana',
    'Raya and the Last Dragon',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Disney film features Raya and the last of its namesake dragon? Raya and the Last Dragon',
    'Raya and the Last Dragon',
    'Mulan animated',
    'Moana',
    'Frozen II',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Disney hit features sisters Elsa and Anna? Frozen',
    'Frozen',
    'Tangled',
    'Brave',
    'Moana',
    'easy',
    'Movie Facts',
  ],
  [
    'Which song from Frozen became a global anthem? Let It Go',
    'Let It Go',
    'Do You Want to Build a Snowman',
    'Into the Unknown from Frozen II',
    'For the First Time in Forever',
    'easy',
    'Movie Facts',
  ],
  [
    'Which Disney film pairs rapunzel-tangled Flynn Rider and Rapunzel? Tangled',
    'Tangled',
    'Enchanted',
    'Frozen',
    'Wish',
    'easy',
    'Movie Facts',
  ],
  [
    'Which animated film parodies fairy tales with Fiona and Donkey? Shrek',
    'Shrek',
    'Tangled',
    'Enchanted',
    'Hoodwinked',
    'easy',
    'Movie Facts',
  ],
  [
    'Which villain sing-talks Be Prepared in The Lion King? Scar',
    'Scar',
    'Hyenas together',
    'Zazu',
    'Mufasa',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Lion King meerkat sings Hakuna Matata with Timon? Timon is the meerkat',
    'Timon',
    'Pumbaa the warthog',
    'Rafiki',
    'Zazu',
    'easy',
    'Movie Facts',
  ],
  [
    'Which warthog pairs with Timon in The Lion King? Pumbaa',
    'Pumbaa',
    'Timon',
    'Rafiki',
    'Simba',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 1999 Matrix line asks for red or blue pills? The Matrix',
    'The Matrix',
    'Inception',
    'Total Recall 1990 variant',
    'eXistenZ',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 1990 Schwarzenegger film also had memory implants? Total Recall',
    'Total Recall',
    'The Running Man',
    'Predator',
    'Commando',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1987 film featured the Predator hunting Arnold? Predator',
    'Predator',
    'Commando',
    'The Terminator',
    'Aliens',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 1986 sequel expanded the Aliens saga with Cameron directing? Aliens',
    'Aliens',
    'Alien',
    'Alien 3',
    'Alien Resurrection',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1979 chestburster scene shocked audiences? Alien',
    'Alien',
    'The Thing 1982',
    'Invasion of the Body Snatchers',
    'Life',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1982 Kurt Russell horror features a shape-shifting thing? The Thing',
    'The Thing',
    'The Fog',
    'Christine',
    'Prince of Darkness',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 1980 horror film follows Jack Torrance at the Overlook Hotel? The Shining',
    'The Shining',
    'Misery',
    'Psycho',
    'Hotel Inferno',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 1978 slasher follows Michael Myers on Halloween night? Halloween',
    'Halloween',
    'Friday the 13th at a camp',
    'Black Christmas 1974 earlier',
    'Scream 1996',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 1980 slasher is set at Camp Crystal Lake? Friday the 13th',
    'Friday the 13th',
    'Halloween',
    'A Nightmare on Elm Street',
    'Sleepaway Camp',
    'easy',
    'Movie Facts',
  ],
  [
    'Which slasher villain stalks dreams with a glove of blades? Freddy Krueger',
    'Freddy Krueger',
    'Jason Voorhees',
    'Michael Myers',
    'Leatherface',
    'easy',
    'Movie Facts',
  ],
  [
    'Which slasher villain wields a chainsaw in Texas? Leatherface',
    'Leatherface',
    'Jason Voorhees',
    'Michael Myers',
    'Pinhead',
    'medium',
    'Movie Facts',
  ],
  [
    'Which horror villain leads Cenobites saying we have such sights to show you? Pinhead',
    'Pinhead',
    'Pennywise',
    'Candyman',
    'Jigsaw',
    'medium',
    'Movie Facts',
  ],
  [
    'Which horror villain appears when saying his name five times in a mirror? Candyman',
    'Candyman',
    'Beetlejuice three times comedy',
    'Bloody Mary folklore',
    'Samara',
    'medium',
    'Movie Facts',
  ],
  [
    'Which cursed videotape kills viewers in seven days? The Ring',
    'The Ring',
    'The Grudge',
    'Ringu Japanese original same story',
    'Sinister',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Japanese horror inspired The Ring as Ringu? Ringu',
    'Ringu',
    'Ju-On',
    'Audition',
    'Dark Water',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Japanese horror follows a cursed house with Kayako? Ju-On: The Grudge',
    'Ju-On: The Grudge',
    'Ringu',
    'Audition',
    'Kwaidan',
    'hard',
    'Movie Facts',
  ],
  [
    'Which found-footage horror terrified 1999 audiences with the Blair Witch? The Blair Witch Project',
    'The Blair Witch Project',
    'Paranormal Activity 2007 later',
    'Cannibal Holocaust controversial 1980',
    'The Last Broadcast',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 2007 found-footage series features Katie and Micah? Paranormal Activity',
    'Paranormal Activity',
    'Blair Witch',
    'REC Spanish',
    'Cloverfield monster',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 2008 monster film by J.J. Abrams is called Cloverfield? Cloverfield',
    'Cloverfield',
    'Super 8 nostalgic 2011',
    '10 Cloverfield Lane 2016',
    'Godzilla 2014',
    'medium',
    'Movie Facts',
  ],
  [
    'Which M. Night film features an unbreakable hero? Unbreakable',
    'Unbreakable',
    'The Sixth Sense',
    'Split sequel',
    'Signs',
    'medium',
    'Movie Facts',
  ],
  [
    'Which M. Night film features James McAvoy with 24 personalities? Split',
    'Split',
    'Glass',
    'Unbreakable',
    'The Visit',
    'medium',
    'Movie Facts',
  ],
  [
    'Which M. Night film features crop circles and Mel Gibson? Signs',
    'Signs',
    'The Village',
    'The Happening',
    'Old',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Indian blockbuster series is Baahubali? Baahubali two-part epic',
    'Baahubali',
    'RRR',
    'KGF',
    'Pushpa',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 2022 Indian epic featured Naatu Naatu and SS Rajamouli? RRR',
    'RRR',
    'Baahubali',
    'KGF Chapter 2',
    'Vikram',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Nigerian-American actor played Okoye in Black Panther? Danai Gurira',
    'Danai Gurira',
    'Lupita Nyongo as Nakia',
    'Angela Bassett as Ramonda',
    'Letitia Wright as Shuri',
    'hard',
    'Movie Facts',
  ],
  [
    'Which Black Panther actress plays Shuri? Letitia Wright',
    'Letitia Wright',
    'Lupita Nyongo',
    'Danai Gurira',
    'Angela Bassett',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Oscar winner plays Ramonda in Black Panther? Angela Bassett',
    'Angela Bassett',
    'Lupita Nyongo',
    'Viola Davis',
    'Danai Gurira',
    'medium',
    'Movie Facts',
  ],
  [
    'Which Black Panther villain name means vengeance in the film? Killmonger is Erik, not translated',
    'Erik Killmonger',
    'M Baku',
    'W Kabi',
    'Zuri',
    'expert',
    'Movie Facts',
  ],
  [
    'Which 2018 film featured A Star is Born remake with Lady Gaga? A Star is Born 2018',
    'A Star is Born',
    'La La Land',
    'Rocketman 2019',
    'Judy 2019',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 2019 musical biopic followed Elton John? Rocketman',
    'Rocketman',
    'Bohemian Rhapsody 2018 Queen',
    'Judy 2019 Garland',
    'Respect 2021 Franklin',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 2018 biopic dramatized Queen and Freddie Mercury? Bohemian Rhapsody',
    'Bohemian Rhapsody',
    'Rocketman',
    'Judy',
    'Love and Mercy 2014 Beach Boys',
    'easy',
    'Movie Facts',
  ],
  [
    'Which 2019 film honored Judy Garland with Renee Zellweger? Judy',
    'Judy',
    'Bohemian Rhapsody',
    'Rocketman',
    'Respect',
    'medium',
    'Movie Facts',
  ],
  [
    'Which 2021 biopic starred Aretha Franklin story with Jennifer Hudson? Respect',
    'Respect',
    'Judy',
    'House of Gucci',
    'The United States vs. Billie Holiday',
    'hard',
    'Movie Facts',
  ],
  [
    'Which 2018 Queen hit title song bohemian rhapsody became a film title? Bohemian Rhapsody the song',
    'The song Bohemian Rhapsody',
    'We Will Rock You',
    'Dont Stop Me Now',
    'Somebody to Love',
    'easy',
    'Movie Facts',
  ],
];

function generate(rng) {
  const rows = [];

  const yearPool = FILMS.map((f) => String(f[1]));
  const dirPool = FILMS.map((f) => f[2]);
  const starPool = FILMS.map((f) => f[3]);
  const titlePool = FILMS.map((f) => f[0]);

  for (const [title, year, director, star] of FILMS) {
    rows.push({
      q: `In which year was ${title} released?`,
      correct: String(year),
      ds: distract(yearPool, String(year), 3),
      level: 'medium',
      chapter: 'Movies',
    });
    rows.push({
      q: `Who directed ${title}?`,
      correct: director,
      ds: distract(dirPool, director, 3),
      level: 'medium',
      chapter: 'Directors & Cast',
    });
    rows.push({
      q: `Which actor or actress starred in ${title}?`,
      correct: star,
      ds: distract(starPool, star, 3),
      level: 'hard',
      chapter: 'Directors & Cast',
    });
  }

  const showFacts = TV_SHOWS.map((t) => t[1]);
  const networks = TV_SHOWS.map((t) => t[2]);
  for (const [show, fact, network, d1, d2, d3, level] of TV_SHOWS) {
    rows.push({
      q: `What is ${show} about?`,
      correct: fact,
      ds: distract(showFacts, fact, 3),
      level: 'medium',
      chapter: 'TV Shows',
    });
    rows.push({
      q: `On which network or platform did ${show} air?`,
      correct: network,
      ds: [d1, d2, d3],
      level,
      chapter: 'TV Shows',
    });
  }

  const studioPool = ANIMATION.map((a) => a[1]);
  const animYearPool = ANIMATION.map((a) => String(a[2]));
  for (const [film, studio, year] of ANIMATION) {
    rows.push({
      q: `Which studio made the animated film ${film}?`,
      correct: studio,
      ds: distract(studioPool, studio, 3),
      level: 'easy',
      chapter: 'Animation',
    });
    rows.push({
      q: `In which year was the animated film ${film} released?`,
      correct: String(year),
      ds: distract(animYearPool, String(year), 3),
      level: 'medium',
      chapter: 'Animation',
    });
  }

  const rolePool = ACTORS.map((a) => a[1]);
  const namePool = ACTORS.map((a) => a[0]);
  for (const [actor, role] of ACTORS) {
    rows.push({
      q: `Which iconic role is ${actor} known for?`,
      correct: role,
      ds: distract(rolePool, role, 3),
      level: 'medium',
      chapter: 'Actors & Roles',
    });
    rows.push({
      q: `Who played ${role}?`,
      correct: actor,
      ds: distract(namePool, actor, 3),
      level: 'medium',
      chapter: 'Actors & Roles',
    });
  }

  const BANKS = [
    QUOTES,
    OSCARS,
    MOVIE_FACTS,
    TV_FACTS,
    SUPERHERO,
    CLASSIC_TV,
    KIDS_ANIME,
    CINEMA_HISTORY,
    TOPUP,
  ];
  for (const bank of BANKS) {
    for (const f of bank)
      rows.push({ q: f[0], correct: f[1], ds: [f[2], f[3], f[4]], level: f[5], chapter: f[6] });
  }

  return rows;
}

function distract(pool, correct, n) {
  const out = [];
  const seen = new Set([String(correct).toLowerCase()]);
  for (const cand of pool) {
    const key = String(cand).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(cand);
    if (out.length === n) break;
  }
  const fallback = ['None of these', 'Cannot recall'];
  let fi = 0;
  while (out.length < n && fi < fallback.length) {
    if (!seen.has(fallback[fi].toLowerCase())) {
      out.push(fallback[fi]);
      seen.add(fallback[fi].toLowerCase());
    }
    fi++;
  }
  return out;
}

module.exports = { subject: 'Movies & TV', generate };
