'use strict';

const rows = [
  [
    'Who sang Blinding Lights? The Weeknd',
    'The Weeknd',
    'Drake',
    'Post Malone',
    'Bruno Mars',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which Weeknd album has Blinding Lights? After Hours',
    'After Hours',
    'Starboy',
    'Dawn FM',
    'Beauty Behind the Madness',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang As It Was? Harry Styles',
    'Harry Styles',
    'The Weeknd',
    'Conan Gray',
    'Steve Lacy',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Levitating? Dua Lipa',
    'Dua Lipa',
    'Ariana Grande',
    'Bebe Rexha',
    'Rita Ora',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Stay with The Kid LAROI? Justin Bieber',
    'Justin Bieber with Kid LAROI',
    'The Kid LAROI solo',
    'Shawn Mendes',
    'Charlie Puth',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Stay? The Kid LAROI and Justin Bieber',
    'The Kid LAROI and Bieber',
    'Post and Swae Lee Sunflower different',
    'Drake and Rihanna different',
    'Wiz and Charlie Puth different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Sunflower? Post Malone and Swae Lee',
    'Post Malone and Swae Lee from Spider-Verse',
    'Wiz Khalifa and Charlie Puth See You Again',
    'Bruno and Mark Uptown Funk',
    'Justin and Danja different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang See You Again? Wiz Khalifa featuring Charlie Puth',
    'Wiz Khalifa and Charlie Puth Furious 7',
    'Post and Swae Sunflower',
    'Eminem and Nate Dogg Till I Collapse',
    'Drake and Wiz different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Uptown Funk? Mark Ronson featuring Bruno Mars',
    'Mark Ronson with Bruno Mars',
    'Pharrell with Daft Punk Get Lucky',
    'Bruno solo Locked out',
    'Justin Timberlake Suit Tie',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Get Lucky? Daft Punk featuring Pharrell',
    'Daft Punk with Pharrell and Rodgers',
    'Mark Ronson with Bruno',
    'Calvin with Rihanna',
    'Avicii with Souleye none',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Happy? Pharrell Williams',
    'Pharrell Williams',
    'Bruno Mars',
    'Justin Timberlake',
    'Will.i.am',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Counting Stars? OneRepublic',
    'OneRepublic',
    'Imagine Dragons',
    'The Script',
    'Coldplay',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Believer? Imagine Dragons',
    'Imagine Dragons',
    'OneRepublic',
    'X Ambassadors',
    'Mumford and Sons',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Pompeii? Bastille',
    'Bastille',
    'Imagine Dragons',
    'Foster the People',
    'Alt-J',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Pumped Up Kicks? Foster the People',
    'Foster the People',
    'Bastille',
    'MGMT',
    'Phoenix',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Electric Feel? MGMT',
    'MGMT',
    'Phoenix',
    'Vampire Weekend',
    'Foster the People',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang 1901? Phoenix',
    'Phoenix',
    'MGMT',
    'Vampire Weekend',
    'Two Door Cinema Club',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang A-Punk? Vampire Weekend',
    'Vampire Weekend',
    'Phoenix',
    'MGMT',
    'Beach Fossils',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Tongue Tied? Grouplove',
    'Grouplove',
    'Foster the People',
    'Walk the Moon',
    'Magic Man',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Shut Up and Dance? Walk the Moon',
    'Walk the Moon',
    'Grouplove',
    'Saint Motel',
    'Bleachers',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang My Type? Saint Motel',
    'Saint Motel',
    'Walk the Moon',
    'Bleachers',
    'The 1975',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Chocolate? The 1975',
    'The 1975',
    'Saint Motel',
    'Bleachers',
    'Vampire Weekend',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Somebody Else? The 1975',
    'The 1975',
    'LANY',
    'The Neighbourhood',
    'Arctic Monkeys',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Sweater Weather? The Neighbourhood',
    'The Neighbourhood',
    'The 1975',
    'Arctic Monkeys',
    'Cigarettes After Sex',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Do I Wanna Know? Arctic Monkeys',
    'Arctic Monkeys',
    'The Neighbourhood',
    'Catfish and the Bottlemen',
    'Bicycle Thieves none',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang R U Mine? Arctic Monkeys',
    'Arctic Monkeys',
    'Royal Blood duo bass drums',
    'QOTSA Homme featured',
    'Muse stadium rock different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Uprising? Muse',
    'Muse',
    'Royal Blood',
    'QOTSA',
    'Kasabian',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Fire? Kasabian',
    'Kasabian',
    'Muse',
    'Kings of Leon',
    'The Killers',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Use Somebody? Kings of Leon',
    'Kings of Leon',
    'Muse',
    'Kasabian',
    'The Fray',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Sex on Fire? Kings of Leon',
    'Kings of Leon',
    'The Killers',
    'Franz Ferdinand',
    'Jet',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Are You Gonna Be My Girl? Jet',
    'Jet',
    'Kings of Leon',
    'The Vines',
    'Wolfmother',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Mind Eraser No Chaser? skip real: Who sang Joker and the Thief? Wolfmother',
    'Wolfmother',
    'Jet',
    'The Vines',
    'Airbourne',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Feels Like We Only Go Backwards? Tame Impala',
    'Tame Impala',
    'MGMT',
    'Pond fellow psych',
    'Melodys Echo Chamber dreamier',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Tame Impala? Kevin Parkers psych project',
    'Kevin Parkers recording project',
    'A four-piece Aussie band literally',
    'Pond members only',
    'GUM solo side',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang The Less I Know the Better? Tame Impala',
    'Tame Impala',
    'Pond',
    'Khruangbin instrumental lean',
    'Parcels talkbox funk',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Borderline Tame feature? Tame with Daft Punk nod none',
    'None; Borderline is Tame Impala own',
    'Mac DeMarco jizz jazz',
    'Beach Fossils dream pop',
    'Alvvays dreamy',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who sang Dreams by Fleetwood covered by Who? The Corrs covered Dreams',
    'The Corrs covered Dreams',
    'The Cranberries original Zombie different',
    'Dixie Chicks covered Landslide',
    'Smashing Pumpkins covered Landslide too',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who covered Landslide by Fleetwood? Dixie Chicks covered it',
    'The Dixie Chicks covered Landslide',
    'Smashing Pumpkins covered it live',
    'Gwyneth sang it in Glee',
    'Miley covered it later',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who sang Landslide originally? Fleetwood Mac with Stevie Nicks',
    'Stevie Nicks wrote and sang it',
    'Dixie Chicks covered it',
    'Gwyneth Paltrow Glee cover',
    'Miley Cyrus later cover',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Dreams by The Cranberries different song? Zombie is the famous one',
    'Zombie is the famous Cranberries hit',
    'Dreams is their other hit yes',
    'Linger third famous',
    'All three are Cranberries hits',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Dreams remixed by Gabrielle? Gabrielle sampled it in Dreams',
    'Gabrielle built Dreams on it',
    'Emeli Sande sampled later',
    'Estelle sampled differently',
    'Duffy no sampling',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who sang Sweet Nothing? Calvin Harris with Florence Welch',
    'Calvin Harris with Florence Welch',
    'David Guetta with Sia',
    'Avicii with Audra',
    'Zedd with Hayley',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Spectrum? Florence and the Machine with Calvin production',
    'Florence with Calvin Harris producing',
    'Sia with Stargate producing',
    'Rihanna with Calvin producing',
    'Ellie with Calvin producing',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who sang Shake It Out? Florence and the Machine',
    'Florence and the Machine',
    'Adele',
    'Sia',
    'Emeli Sande',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Dog Days Are Over? Florence and the Machine',
    'Florence and the Machine',
    'Mumford and Sons similar energy',
    'Of Monsters and Men similar vibe',
    'Vampire Weekend different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Little Talks? Of Monsters and Men',
    'Of Monsters and Men',
    'The Lumineers similar',
    'Mumford and Sons similar',
    'Novo Amor softer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Ho Hey? The Lumineers',
    'The Lumineers',
    'Of Monsters and Men',
    'Mumford and Sons',
    'Vance Joy similar ukulele',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Riptide? Vance Joy',
    'Vance Joy',
    'George Ezra similar deep voice',
    'James Bay hat guitarist',
    'Hozier Take Me to Church',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Budapest? George Ezra',
    'George Ezra',
    'Vance Joy',
    'Hozier',
    'James Bay',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Shotgun? George Ezra',
    'George Ezra',
    'Vance Joy',
    'James Arthur',
    'Tom Grennan',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Take Me to Church? Hozier',
    'Hozier',
    'George Ezra',
    'James Bay',
    'Ben Howard',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Let It Go not Frozen? James Bay sang Let It Go',
    'James Bay sang the song Let It Go',
    'Idina Menzel Frozen version',
    'Demi Lovato Frozen single version',
    'Ella Henderson similar title ghost',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Hold Back the River? James Bay',
    'James Bay',
    'Ben Howard',
    'Tom Odell',
    'Passenger',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Let Her Go? Passenger',
    'Passenger',
    'James Bay',
    'Ed Sheeran',
    'Ben Howard',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang I See Fire? Ed Sheeran for The Hobbit',
    'Ed Sheeran for The Desolation of Smaug',
    'Passenger folk friend',
    'Ben Howard different film',
    'Hozier different year',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Perfect duet with Beyonce? Ed Sheeran Perfect Duet version',
    'Ed Sheeran with Beyonce',
    'Calvin with Dua',
    'Shawn with Camila Senorita',
    'Zayn with Taylor I Dont Wanna Live Forever',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Senorita? Shawn Mendes and Camila Cabello',
    'Shawn Mendes and Camila Cabello',
    'Ed and Beyonce Perfect Duet',
    'Zayn and Taylor IDWLF',
    'Charlie and Selena We Dont Talk Anymore',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang We Dont Talk Anymore? Charlie Puth with Selena Gomez',
    'Charlie Puth featuring Selena Gomez',
    'Shawn with Camila Senorita',
    'James Arthur withAnne-Marie Rewrite the Stars different',
    'Zayn with Sia Dusk Till Dawn',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Dusk Till Dawn? Zayn with Sia',
    'Zayn with Sia',
    'Charlie with Selena',
    'Shawn with Camila',
    'Louis with Bebe Rexha Back to You',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Back to You? Louis Tomlinson with Bebe Rexha',
    'Louis Tomlinson with Bebe Rexha',
    'Zayn with Sia Dusk',
    'Niall with Maren Morris Seeing Blind',
    'Harry solo Sign of Times',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Slow Hands solo from One Direction? Niall Horan',
    'Niall Horan solo',
    'Harry Styles solo Sign',
    'Louis solo Just Hold On with Steve Aoki',
    'Liam solo Strip That Down with Quavo',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Strip That Down? Liam Payne with Quavo',
    'Liam Payne featuring Quavo',
    'Niall with Maren',
    'Zayn solo Pillowtalk',
    'Harry solo Kiwi',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Pillowtalk? Zayn Malik',
    'Zayn Malik debut solo',
    'Harry solo Sign of Times',
    'Liam with Quavo',
    'Louis with Bebe',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who sang Sign of the Times asked again? Harry Styles',
    'Harry Styles again',
    'Zayn Pillowtalk different',
    'Niall Slow Hands different',
    'Louis Just Hold On different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is Lewis Capaldi partnering memes with? His humor on TikTok famous',
    'Self-deprecating TikTok humor',
    'Britney collab false',
    'Adele duet false',
    'Sam Smith feud false',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Before You Go follow-up hit? Lewis Capaldi',
    'Lewis Capaldi again',
    'James Arthur again',
    'Dean Lewis different artist',
    'Tom Walker different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Bruises? Lewis Capaldi debut single',
    'Lewis Capaldi debut',
    'James Arthur Say You Wont Let Go different',
    'Dean Lewis Be Alright different',
    'Tom Walker Leave a Light On different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who sang Say You Wont Let Go? James Arthur',
    'James Arthur',
    'Lewis Capaldi Bruises',
    'Dean Lewis Be Alright',
    'Tom Walker Leave Light',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Be Alright? Dean Lewis',
    'Dean Lewis',
    'James Arthur',
    'Lewis Capaldi',
    'Jonas Blue different dance',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Leave a Light On? Tom Walker',
    'Tom Walker',
    'Dean Lewis',
    'James Bay Let It Go',
    'Lewis Capaldi',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who sang Someone You Loved final answer? Lewis Capaldi',
    'Lewis Capaldi definitively',
    'James Arthur second guess',
    'Tom Walker third guess',
    'Dean Lewis fourth guess',
    'easy',
    'Celebrity Facts',
  ],
];

module.exports = { rows };
