'use strict';

// Extra banks for Pop Culture & Celebrities. Format: [q, correct, d1, d2, d3, level, chapter]

const HALFTIME = [
  [
    'Who headlined the 2023 Super Bowl halftime show?',
    'Rihanna',
    'The Weeknd',
    'Dr. Dre and friends',
    'Lady Gaga',
    'easy',
    'Awards & Events',
  ],
  [
    'Who headlined the 2024 Super Bowl halftime show?',
    'Usher',
    'Rihanna',
    'The Weeknd',
    'Katy Perry',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2022 Super Bowl halftime show?',
    'Dr. Dre, Snoop Dogg, Eminem, Mary J. Blige, and Kendrick Lamar',
    'The Weeknd',
    'Coldplay',
    'Lady Gaga',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2021 Super Bowl halftime show?',
    'The Weeknd',
    'Rihanna',
    'Shakira and Jennifer Lopez',
    'Justin Timberlake',
    'medium',
    'Awards & Events',
  ],
  [
    'Who co-headlined the 2020 Super Bowl halftime show?',
    'Shakira and Jennifer Lopez',
    'Lady Gaga',
    'Beyonce and Coldplay',
    'Maroon 5',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2018 Super Bowl halftime show?',
    'Justin Timberlake',
    'Lady Gaga',
    'Katy Perry',
    'Bruno Mars',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2017 Super Bowl halftime show?',
    'Lady Gaga',
    'Beyonce',
    'Coldplay',
    'Katy Perry',
    'medium',
    'Awards & Events',
  ],
  [
    'Who joined Coldplay in the 2016 halftime show?',
    'Beyonce and Bruno Mars',
    'Rihanna and Eminem',
    'Katy Perry and Lenny Kravitz',
    'Missy Elliott only',
    'hard',
    'Awards & Events',
  ],
  [
    'Who headlined the 2015 Super Bowl halftime show?',
    'Katy Perry with Left Shark fame',
    'Bruno Mars',
    'Lady Gaga',
    'Beyonce',
    'medium',
    'Awards & Events',
  ],
  [
    'Which dancing shark became a 2015 halftime meme?',
    'Left Shark',
    'Right Shark',
    'Dancing Baby',
    'KMart ship your pants shark',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2014 Super Bowl halftime show?',
    'Bruno Mars with Red Hot Chili Peppers',
    'Beyonce',
    'Madonna',
    'The Weeknd',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2013 Super Bowl halftime show causing a power outage?',
    'Beyonce',
    'Madonna',
    'Bruno Mars',
    'Katy Perry',
    'medium',
    'Awards & Events',
  ],
  [
    'Who headlined the 2012 Super Bowl halftime show?',
    'Madonna',
    'Beyonce',
    'The Black Eyed Peas',
    'The Who',
    'medium',
    'Awards & Events',
  ],
  [
    'Which artist performed in the 2007 rain-soaked halftime show? Prince',
    'Prince',
    'Tom Petty',
    'Rolling Stones',
    'Paul McCartney',
    'expert',
    'Awards & Events',
  ],
  [
    'Which halftime show incident involved Janet Jackson in 2004? The wardrobe malfunction with Justin Timberlake',
    'The Janet Jackson wardrobe moment',
    'Nipplegate censorship debate',
    'Both phrasings of the same moment',
    'A power outage',
    'expert',
    'Awards & Events',
  ],
];

const BIG_AWARDS = [
  [
    'Which film won Best Picture at the 2020 Oscars? Parasite',
    'Parasite',
    '1917',
    'Joker',
    'Ford v Ferrari',
    'medium',
    'Awards & Events',
  ],
  [
    'Which film won Best Picture at the 2021 Oscars? Nomadland',
    'Nomadland',
    'The Trial of the Chicago 7',
    'Promising Young Woman',
    'Mank',
    'medium',
    'Awards & Events',
  ],
  [
    'Which film won Best Picture at the 2022 Oscars? CODA',
    'CODA',
    'The Power of the Dog',
    'Dune',
    'Belfast',
    'medium',
    'Awards & Events',
  ],
  [
    'Which film won Best Picture at the 2023 Oscars? Everything Everywhere All at Once',
    'Everything Everywhere All at Once',
    'The Banshees of Inisherin',
    'Top Gun: Maverick',
    'The Whale',
    'medium',
    'Awards & Events',
  ],
  [
    'Which film won Best Picture at the 2024 Oscars? Oppenheimer',
    'Oppenheimer',
    'Barbie',
    'Killers of the Flower Moon',
    'Poor Things',
    'medium',
    'Awards & Events',
  ],
  [
    'Which album won Album of the Year at the 2020 Grammys? Billie Eilishs When We All Fall Asleep',
    'When We All Fall Asleep, Where Do We Go?',
    'Norman F Rockwell',
    'I Used to Know Her',
    'Cuz I Love You',
    'hard',
    'Awards & Events',
  ],
  [
    'Which album won the 2021 Album of the Year Grammy? Folklore by Taylor Swift',
    'Folklore',
    'Future Nostalgia',
    'After Hours',
    'Women in Music Pt. III',
    'medium',
    'Awards & Events',
  ],
  [
    'Which album won the 2022 Album of the Year Grammy? We Are by Jon Batiste',
    'We Are',
    'Sour',
    'Back of My Mind',
    'Planet Her',
    'hard',
    'Awards & Events',
  ],
  [
    'Which album won the 2023 Album of the Year Grammy? Harrys House',
    'Harrys House',
    'Renaissance',
    'Bad Bunni Un Verano Sin Ti',
    'Big Ideas',
    'medium',
    'Awards & Events',
  ],
  [
    'Which album won the 2024 Album of the Year Grammy? Midnights by Taylor Swift',
    'Midnights',
    'SOS by SZA',
    'Guts by Olivia Rodrigo',
    'World Music Radio Jon Batiste',
    'medium',
    'Awards & Events',
  ],
  [
    'Which drama won the Outstanding Drama Emmy repeatedly in the 2020s? Succession',
    'Succession',
    'The Crown',
    'Better Call Saul',
    'Severance',
    'medium',
    'Awards & Events',
  ],
  [
    'Which series won the 2021 Emmy for drama? The Crown',
    'The Crown',
    'The Mandalorian',
    'The Boys',
    'This Is Us',
    'hard',
    'Awards & Events',
  ],
  [
    'Which comedy won Emmys repeatedly in the late 2010s? The Marvelous Mrs. Maisel',
    'The Marvelous Mrs. Maisel',
    'Barry',
    'Ted Lasso later',
    'Schitts Creek later sweep',
    'expert',
    'Awards & Events',
  ],
  [
    'Which sitcom swept the 2020 Emmys comedy categories? Schitts Creek',
    'Schitts Creek',
    'The Marvelous Mrs. Maisel',
    'Ted Lasso first season',
    'Modern Family past',
    'medium',
    'Awards & Events',
  ],
  [
    'Which sports comedy won the 2021 comedy Emmy? Ted Lasso',
    'Ted Lasso',
    'Hacks',
    'The Kominsky Method',
    'What We Do in the Shadows',
    'medium',
    'Awards & Events',
  ],
  [
    'What is the Met Gala? An annual fashion fundraiser at the Met Museum',
    'The Costume Institute benefit gala',
    'A movie awards show',
    'A music chart event',
    'A modeling contest',
    'medium',
    'Awards & Events',
  ],
  [
    'Who runs the Met Gala guest list famously? Anna Wintour of Vogue',
    'Anna Wintour',
    'Karlie Kloss',
    'Diana Vreeland historically',
    'Tom Ford',
    'hard',
    'Awards & Events',
  ],
  [
    'What is the Hollywood Walk of Fame? Sidewalk stars honoring entertainers',
    'The terrazzo star sidewalk honors',
    'An awards ceremony',
    'A studio tour',
    'A museum hall',
    'easy',
    'Awards & Events',
  ],
  [
    'What are the Razzies? Awards mocking the worst films',
    'The anti-Oscar worst film awards',
    'A kids choice event',
    'A critics circle prize',
    'A stunt award',
    'medium',
    'Awards & Events',
  ],
  [
    'What gets dumped on hosts at Kids Choice Awards? Green slime',
    'Green slime',
    'Confetti only',
    'Water balloons',
    'Paint',
    'easy',
    'Awards & Events',
  ],
  [
    'What is the MTV VMAs statue called? The Moon Person (Moonman)',
    'The Moon Person astronaut',
    'The Golden Popcorn',
    'The Video Vanguard trophy only',
    'The VMA Globe',
    'medium',
    'Awards & Events',
  ],
  [
    'What is the Video Vanguard Award? An MTV lifetime-style video award',
    'The career video artistry honor',
    'Best new artist prize',
    'A chart trophy',
    'A critics nod',
    'hard',
    'Awards & Events',
  ],
  [
    'What is the Time 100? An annual influential people list',
    'The yearly most influential list',
    'A box office ranking',
    'A sports power list',
    'A wealth ranking',
    'medium',
    'Awards & Events',
  ],
  [
    'What is the Forbes Celebrity 100? A celebrity earnings power list',
    'The highest-paid celebrities ranking',
    'An acting honor',
    'A social award',
    'A film festival prize',
    'medium',
    'Awards & Events',
  ],
  [
    'What is People magazine Sexiest Man Alive? An annual title issue',
    'The yearly cover title honor',
    'A beauty pageant',
    'A dating show prize',
    'A fitness list',
    'medium',
    'Awards & Events',
  ],
  [
    'What is the Kennedy Center Honors? Annual American performing arts honors',
    'The lifetime arts honors ceremony',
    'A music chart show',
    'A film festival award',
    'A theater Tony event',
    'hard',
    'Awards & Events',
  ],
  [
    'What are the Tonys? Awards for Broadway theater',
    'The Broadway theater awards',
    'The film awards',
    'The TV awards',
    'The music awards',
    'easy',
    'Awards & Events',
  ],
  [
    'What are the BAFTAs? British film and TV awards',
    'The British Academy awards',
    'The US critics awards',
    'The European song awards',
    'The fashion awards',
    'easy',
    'Awards & Events',
  ],
  [
    'What is Cannes Palme dOr? The top prize at Cannes Film Festival',
    'The Cannes festival top prize',
    'The Venice Golden Lion',
    'The Berlin Golden Bear',
    'The Sundance Grand Jury',
    'medium',
    'Awards & Events',
  ],
  [
    'What is the Venice Golden Lion? The Venice film festival top prize',
    'The Venice Biennale film award',
    'Cannes top prize',
    'Berlin top prize',
    'Toronto People Choice',
    'hard',
    'Awards & Events',
  ],
];

const REALITY_TV = [
  [
    'Which franchise follows the Kardashians originally? Keeping Up with the Kardashians',
    'Keeping Up with the Kardashians',
    'The Real Housewives of Beverly Hills',
    'Selling Sunset',
    'The Simple Life',
    'easy',
    'Reality TV',
  ],
  [
    'Which Real Housewives city features Kyle Richards? Beverly Hills',
    'Beverly Hills',
    'New York City',
    'New Jersey',
    'Atlanta',
    'medium',
    'Reality TV',
  ],
  [
    'Which Real Housewives city features Teresa Giudice? New Jersey',
    'New Jersey',
    'Beverly Hills',
    'Miami',
    'Potomac',
    'medium',
    'Reality TV',
  ],
  [
    'Which Real Housewives city features Nene Leakes? Atlanta',
    'Atlanta',
    'New York',
    'Beverly Hills',
    'Dallas',
    'medium',
    'Reality TV',
  ],
  [
    'Which show follows Oppenheim Group realtors? Selling Sunset',
    'Selling Sunset',
    'Million Dollar Listing',
    'Below Deck',
    'Vanderpump Rules',
    'easy',
    'Reality TV',
  ],
  [
    'Which show follows crew on charter yachts? Below Deck',
    'Below Deck',
    'Selling Sunset',
    'The Apprentice',
    'Survivor',
    'medium',
    'Reality TV',
  ],
  [
    'Which restaurant spinoff followed Lisa Vanderpump staff? Vanderpump Rules',
    'Vanderpump Rules',
    'Selling Sunset',
    'Below Deck Mediterranean',
    'Million Dollar Listing NY',
    'medium',
    'Reality TV',
  ],
  [
    'Which show strands singles on an island to couple up? Love Island',
    'Love Island',
    'Too Hot to Handle no kissing rule',
    'Bachelor in Paradise beach',
    'Temptation Island test',
    'easy',
    'Reality TV',
  ],
  [
    'Which show bans kissing for a cash prize? Too Hot to Handle',
    'Too Hot to Handle',
    'Love Island',
    'Bachelor in Paradise',
    'Married at First Sight',
    'medium',
    'Reality TV',
  ],
  [
    'Which show marries strangers at the altar? Married at First Sight',
    'Married at First Sight',
    'Love is Blind pods proposal',
    '90 Day Fiance visa couples',
    'The Ultimatum ultimatum couples',
    'medium',
    'Reality TV',
  ],
  [
    'Which show has pods where couples get engaged unseen? Love is Blind',
    'Love is Blind',
    'Married at First Sight',
    'Too Hot to Handle',
    'Perfect Match mixer',
    'easy',
    'Reality TV',
  ],
  [
    'Which show follows 90-day visa couples? 90 Day Fiance',
    '90 Day Fiance',
    'Love is Blind',
    'The Bachelor',
    'Married at First Sight',
    'easy',
    'Reality TV',
  ],
  [
    'Which US long-running survivor competition is Survivor? Survivor hosted by Jeff Probst',
    'Survivor with Jeff Probst',
    'Big Brother with Julie Chen',
    'The Amazing Race with Phil',
    'Mt Everests alone show is Alone',
    'medium',
    'Reality TV',
  ],
  [
    'Which show locks housemates with live feeds? Big Brother',
    'Big Brother',
    'Survivor',
    'The Traitors castle game',
    'RuPauls Drag Race runway',
    'easy',
    'Reality TV',
  ],
  [
    'Which show races around the world in pairs? The Amazing Race',
    'The Amazing Race',
    'Survivor expeditions',
    'Naked and Afraid survival',
    'The Challenge competitive island',
    'medium',
    'Reality TV',
  ],
  [
    'Which cooking competition awards a Top Chef title? Top Chef',
    'Top Chef',
    'MasterChef amateur home cooks',
    'Hell Kitchen Ramsay',
    'Chopped basket rounds',
    'medium',
    'Reality TV',
  ],
  [
    'Which Gordon Ramsay show yells in a kitchen? Hells Kitchen',
    'Hells Kitchen',
    'Kitchen Nightmares rescues',
    'MasterChef Junior kids',
    'The F Word food travels',
    'easy',
    'Reality TV',
  ],
  [
    'Which show rescues failing restaurants? Kitchen Nightmares',
    'Kitchen Nightmares',
    'Hells Kitchen competition',
    'Bar Rescue drinks version',
    'Restaurant Startup pitch',
    'medium',
    'Reality TV',
  ],
  [
    'Which show tests bars with Jon Taffer? Bar Rescue',
    'Bar Rescue',
    'Kitchen Nightmares',
    'Restaurant Stakeout',
    'Best Bars in America tour',
    'medium',
    'Reality TV',
  ],
  [
    'Which design competition is Project Runway? Project Runway fashion design',
    'The fashion designer competition',
    'Ink Master tattoo artists',
    'Face Off makeup artists',
    'Top Chef chefs',
    'medium',
    'Reality TV',
  ],
  [
    'Which tattoo competition show is Ink Master? Ink Master',
    'Ink Master',
    'Project Runway',
    'Face Off creature makeup',
    'Skin Wars body paint',
    'medium',
    'Reality TV',
  ],
  [
    'Which singing show turned chairs around? The Voice',
    'The Voice',
    'American Idol auditions',
    'The X Factor groups',
    'Songland writers',
    'easy',
    'Reality TV',
  ],
  [
    'Which show formed One Direction? The X Factor UK',
    'The X Factor UK',
    'American Idol US',
    'The Voice UK',
    'Britains Got Talent variety',
    'medium',
    'Reality TV',
  ],
  [
    'Which show launched Kelly Clarkson? American Idol season one',
    'American Idol',
    'The Voice',
    'The X Factor',
    'Star Search classic',
    'medium',
    'Reality TV',
  ],
  [
    'Which drag competition is RuPauls Drag Race? RuPauls Drag Race',
    'RuPauls Drag Race',
    'Legendary ballroom vogue',
    'Drag Heals documentary',
    'We Are the queens doc',
    'easy',
    'Reality TV',
  ],
  [
    'Which apprentice show fired candidates weekly? The Apprentice',
    'The Apprentice',
    'Shark Tank investor pitches',
    'Dragons Den UK pitches',
    'The Profit Marcus deals',
    'medium',
    'Reality TV',
  ],
  [
    'Which show pitches to Shark Tank investors? Shark Tank',
    'Shark Tank',
    'The Apprentice hiring',
    'Dragons Den UK version',
    'Billion Dollar Buyer sourcing',
    'easy',
    'Reality TV',
  ],
  [
    'Which show follows renovating flippers Tarek and Christina early? Flip or Flop',
    'Flip or Flop',
    'Property Brothers twins',
    'Fixer Upper Chip Joanna',
    'Love It or List It decision',
    'medium',
    'Reality TV',
  ],
  [
    'Which show twins renovate with Jonathan and Drew? Property Brothers',
    'Property Brothers',
    'Flip or Flop exes',
    'Fixer Upper farmhouse',
    'HGTVs Unfinished Business',
    'easy',
    'Reality TV',
  ],
  [
    'Which Waco couple renovated farmhouses? Chip and Joanna Gaines Fixer Upper',
    'Fixer Upper couple',
    'Property Brothers twins',
    'Flip or Flop duo',
    'The Nanny Fran',
    'medium',
    'Reality TV',
  ],
];

const STREAMERS = [
  [
    'Who is Kai Cenat? A top Twitch streamer and AMP member',
    'A leading Twitch variety streamer',
    'A YouTube-only prankster',
    'A TikTok dancer',
    'A Kick executive',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is IShowSpeed? An energetic streamer known for viral outbursts',
    'The Speed soccer-streaming creator',
    'A Minecraft builder',
    'A chess streamer',
    'A cooking streamer',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is xQc? A Canadian variety streamer ex-Overwatch pro',
    'Felix Lengyel the Quebec streamer',
    'Kai Cenat AMP',
    'Ninja Fortnite pioneer',
    'Pokimane variety queen',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Pokimane? A Moroccan-Canadian variety streamer',
    'Imane Anys on Twitch',
    'Valkyrae YouTube Gaming',
    'Amouranth business streamer',
    'Emiru cosplayer streamer',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Ninja? Richard Tyler Blevins of Fortnite fame',
    'The Fortnite superstar streamer',
    'Dr Disrespect two-time block',
    'Shroud CS aim god',
    'Tfue Fortnite rival era',
    'easy',
    'Creators & Streamers',
  ],
  [
    'Who is Dr Disrespect? The two-time character of Herschel Guy Beahm',
    'The mustache wig 90s boxer persona',
    'Ninja Fortnite',
    'xQc Quebec',
    'Tim the Tatman dad streamer',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Valkyrae? A top female YouTube Gaming streamer co-owner of 100 Thieves',
    'Rachell Hofstetter at YouTube',
    'Pokimane Twitch counterpart',
    'Amouranth krew founder',
    'QT Cinderella streamer plus',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Ludwig? Ludwig Ahgren the subathon record streamer',
    'The 31-day subathon creator',
    'Kai Cenat AMP subathon rival',
    'MoistCr1TiKaL penguin owner',
    'Hasanabi political streamer',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Who is MoistCr1TiKaL? Charlie the penguin-owning monotone creator',
    'Charlie White aka penguinz0',
    'Ludwig Ahgren subathon',
    'Hasan Piker politics',
    'Jynxzi Rainbow Six Siege king newer',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Who is jacksepticeye? The Irish loud YouTube gamer Sean McLoughlin',
    'Seán McLoughlin of Ireland',
    'Markiplier Bob wakes up friend',
    'DanTDM diamond minecart',
    'PewDiePie floor gang neighbor era',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Markiplier? Mark Fischbach horror game YouTuber',
    "The Five Nights at Freddy's era creator",
    'Jacksepticeye Irish rival friend',
    'DanTDM family friendly',
    'Game Grumps duo member',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is DanTDM? Daniel Middleton family Minecraft creator',
    'The Diamond Minecart creator',
    'Dream Minecraft manhunt maker',
    'TommyInnit loud teen',
    'Technoblade potato war legend late',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Dream? The masked Minecraft manhunt creator',
    'The smiley-mask Minecraft creator',
    'Technoblade never dies legend',
    'TommyInnit Brit loud',
    'Sapleep side character memes',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who was Technoblade? The beloved Minecraft creator who passed in 2022',
    'The potato warTechnoblade legend',
    'Dream manhunt rival friend',
    'Skeppy Troll',
    'BadBoyHalo language',
    'expert',
    'Creators & Streamers',
  ],
  [
    'Who is TommyInnit? The loud British Minecraft streamer Thomas Simons',
    'Thomas Simons of the Dream SMP',
    'Wilbur Soot songwriter creator',
    'Philza hardcode veteran dad',
    'Tubbo bee streamer',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Philza? The hardcore Minecraft five-year run creator',
    'Phil Watson hardcore king',
    'Technoblade potato king',
    'Dream mask maker',
    'Sapnap Texas flame',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Who is HasanAbi? Hasan Piker the political Twitch streamer',
    'The left politics commentary streamer',
    'xQc variety gaming',
    'Adin Ross controversies',
    'Trainwreckstv gambling shows',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is SSSniperwolf? Lia a reaction and gaming YouTuber',
    'The reaction content creator Lia',
    'Pokimane Twitch',
    'Jenna Marbles retired icon',
    'Colleen Ballinger Miranda',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who was Jenna Marbles? A pioneering retired YouTube creator',
    'The early YouTube queen who retired',
    'Lilly Singh superwoman late night',
    'Michelle Phan beauty pioneer',
    'Zoella UK beauty',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Michelle Phan? A beauty YouTube pioneer',
    'The original makeup tutorial star',
    'Zoella UK vlogger',
    'Huda Kattan brand founder',
    'Jeffree Star cosmetics drama',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Who is Jeffree Star? A cosmetics founder and former musician',
    'The pink makeup mogul YouTuber',
    'James Charles cover boy',
    'Manny MUA male guru',
    'NikkieTutorials Dutch star',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is James Charles? A makeup artist CoverBoy first male',
    'The first male CoverGirl face',
    'Manny MUA male peer',
    'Nikkie coming out story',
    'Tati Westbrook fallout 2019',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is NikkieTutorials? Nikkie de Jager Dutch beauty creator',
    'The Dutch power of makeup star',
    'James Charles peer',
    'Jeffree Star mogul',
    'Huda Kattan Dubai brand',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Huda Kattan? A Dubai-based beauty founder',
    'The Huda Beauty founder',
    'Fenty Rihanna rival brand',
    'Kylie Cosmetics lip kits',
    'Morphe brushes partner store',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Emma Chamberlain? A lifestyle YouTuber turned coffee founder',
    'The Chamberlain Coffee creator',
    'Addison Rae dancer',
    'Dixie DAmelio singer sister',
    'Bretman Rock beauty humor',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Bretman Rock? A Filipino-American beauty creator',
    'The funny Hawaii-based creator',
    'James Charles makeup',
    'Manny MUA peer',
    'Nikkie Dutch tutorials',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is MrBeast collaborator Kris Tyson? A longtime MrBeast channel co-star',
    'The longtime Beast crew member',
    'Chandler Hallow crew always loses',
    'Karl Jacobs newer crew',
    'Nolan Hansen crew',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Which MrBeast crew member famously lost constantly? Chandler Hallow',
    'Chandler Hallow the unlucky one',
    'Karl Jacobs the rising one',
    'Jimmy Donaldson boss',
    'Jake the Viking early',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Who is Karl Jacobs? A MrBeast crew member turned creator',
    'The Beast crew producer turned star',
    'Chandler the loser arc',
    'Chris Tyson co-star',
    'Tareq crew member',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who is Roommate Markiplier collaborator Bob? Muyskerm Bob Muyskerm',
    'Bob Muyskerm friend co-host',
    'Wade LordMinion777 friend',
    'Ethan Nestor Crankgameils',
    'Tyler Scheid friend',
    'expert',
    'Creators & Streamers',
  ],
];

const FACTS = [
  [
    'Who created Keeping Up with the Kardashians with Ryan Seacrest? The Kardashian-Jenner family',
    'The family with Ryan Seacrest producing',
    'Andy Cohen Watch What Happens',
    'Kris Jenner alone',
    'E network alone',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Kardashian momager? Kris Jenner',
    'Kris Jenner the manager mom',
    'Caitlyn Jenner formerly Bruce',
    'Kim Kardashian eldest-ish',
    'Corey Gamble partner',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which Jenner founded 818 Tequila? Kendall Jenner',
    'Kendall Jenner',
    'Kylie Jenner cosmetics',
    'Khloe Good American',
    'Kourtney Poosh',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Kardashian founded SKIMS? Kim Kardashian',
    'Kim Kardashian shapewear brand',
    'Khloe Good American denim',
    'Kylie Skims competitor claim no',
    'Kourtney Poosh lifestyle',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which Kardashian founded Good American? Khloe Kardashian',
    'Khloe with Emma Grede',
    'Kim SKIMS',
    'Kylie Cosmetics',
    'Kendall 818',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Kardashian founded Poosh? Kourtney Kardashian',
    'Kourtney lifestyle site',
    'Kim SKIMS',
    'Khloe Good American',
    'Kris production',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Kylie product launched her fortune? Lip Kits',
    'The Kylie Lip Kits',
    'Eyeshadow palettes first',
    'Skin care later',
    'Fragrance later',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the youngest Jenner sibling? Kylie Jenner',
    'Kylie the youngest',
    'Kendall older sister',
    'Rob the only brother Kardashian',
    'Brandon Jenner half-brother',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the only Kardashian brother? Rob Kardashian',
    'Rob Kardashian',
    'Kendall Jenner model sister',
    'Brandon half-brother',
    'Brody Jenner Hills star half-brother',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which Hills star is a Jenner half-brother? Brody Jenner',
    'Brody Jenner of The Hills',
    'Brandon Jenner musician',
    'Rob Kardashian only brother',
    'Scott Disick ex',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which show followed Scott Disick? Keeping Up with the Kardashians mainstay',
    'The KUWTK mainstay lord Disick',
    'Selling Sunset realtor no',
    'VanderpumpSUR no',
    'Flip it like Disick his own show yes',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Kardashian married Travis Barker? Kourtney Kardashian',
    'Kourtney with the Blink-182 drummer',
    'Kim with Pete Davidson briefly',
    'Khloe with Tristan on-off',
    'Kylie with Travis Scott daughter Stormi',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which drummer is Travis Barker? The Blink-182 drummer',
    'The Blink-182 drummer',
    'Green Day Tre Cool',
    'Metallica Lars Ulrich',
    'Foo Fighters Taylor Hawkins late',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the mother of Kylie Jenners daughter Stormi? Kylie with Travis Scott',
    'Kylie with rapper Travis Scott',
    'Kendall with Devin Booker era',
    'Khloe with Tristan daughter True',
    'Kim with Kanye four kids',
    'medium',
    'Celebrity Facts',
  ],
  [
    'How many kids do Kim and Kanye have? Four children',
    'Four children together',
    'Three',
    'Two',
    'Five',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which basketball player co-parents with Khloe? Tristan Thompson',
    'Tristan Thompson NBA player',
    'Lamar Odom ex-husband earlier',
    'James Harden brief',
    'French Montana fling',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which NBA player was Khloe married to? Lamar Odom',
    'Lamar Odom ex-husband',
    'Tristan Thompson on-off',
    'James Harden teammate era',
    'Rick Fox actor athlete',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Kendall Jenners NBA ex? Devin Booker',
    'Devin Booker Suns guard',
    'Ben Simmons 76ers era',
    'Jordan Clarkson earlier',
    'Blake Griffin brief',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Taylor Swift album is about reputation era? Reputation',
    'Reputation',
    '1989',
    'Lover',
    'Evermore',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Taylor Swift re-recordings fight masters? Taylor versions project',
    'The Taylors Version re-recordings',
    'Lover remixes project',
    'Folklore sister albums',
    'Midnights vault tracks',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Travis Kelce? The Chiefs tight end dating Taylor Swift per 2023 rumors confirmed',
    'The Chiefs tight end Swift partner',
    '49ers tight end George Kittle',
    'Rob Gronkowski retired',
    'Tony Gonzalez legend',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Swift song references Scottsdale? none actually skip',
    'None of these',
    'Wildest Dreams',
    'Shake It Off',
    'Blank Space',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which actress played Glinda in Wicked 2024? Ariana Grande',
    'Ariana Grande',
    'Cynthia Erivo played Elphaba',
    'Zendaya rumored never',
    'Sabrina Carpenter shorter blonde',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Elphaba opposite Ariana? Cynthia Erivo',
    'Cynthia Erivo',
    'Ariana Grande Glinda',
    'Amber Riley Mercedes Glee',
    'Jennifer Hudson Dreamgirls Effie',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Selena Gomez founder of Rare Beauty? Selena Gomez herself',
    'Selena Gomez founded Rare Beauty',
    'Kylie Cosmetics rival brand claim',
    'Fenty Rihanna separate',
    'Haus Labs Lady Gaga brand',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Haus Labs founder is Lady Gaga? Haus Labs by Lady Gaga',
    'Lady Gaga founded Haus Labs',
    'Rihanna Fenty Beauty',
    'Kylie Cosmetics',
    'Rare Beauty Selena',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the highest paid YouTuber often cited? MrBeast in recent years',
    'MrBeast recent lists',
    'Jake Paul boxing years',
    'PewDiePie earlier years',
    'Ryan Kaji toys kid earlier',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which kid YouTuber topped earnings lists? Ryan Kaji of Ryan ToysReview',
    'Ryan Kaji toy reviews kid',
    'EvanTubeHD fellow kid',
    'Kids Diana Show rival',
    'Like Nastya newer',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which YouTuber moved to Japan and retired? Jenna Marbles did not move; choose real: Who retired YouTube in 2019? Jenna Marbles retired',
    'Jenna Marbles retired in 2019',
    'Shane Dawson scaled back drama',
    'Colleen Ballinger ukulele persona',
    'Lilly Singh moved to late night',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Shane Dawson? A veteran drama-documentary YouTuber',
    'The conspiracy docu-series creator',
    'Jeffree Star business partner feud',
    'Tana Mongeau storytime star',
    'David Dobrik vlog squad leader',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who leads the Vlog Squad? David Dobrik led it',
    'David Dobrik led the Vlog Squad',
    'Jake Paul Team 10 leader',
    'Logan Paul Maverick',
    'FaZe Banks FaZe clan',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who founded Team 10? Jake Paul founded it',
    'Jake Paul founded Team 10',
    'Logan Paul Maverick club',
    'FaZe Banks FaZe',
    'RiceGum collab member',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Paul brother boxed Tyron Woodley? Jake Paul fought Woodley twice',
    'Jake Paul versus Woodley',
    'Logan Paul versus KSI twice',
    'Logan versus Floyd exhibition Dubai',
    'Jake versus Ben Askren trunks',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Paul brother fought KSI twice? Logan Paul fought KSI',
    'Logan Paul versus KSI pair',
    'Jake Paul versus AnEsonGib undercard KSI',
    'Both brothers same night false',
    'Neither false',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is KSI? A British YouTuber boxer musician',
    'The British YouTube boxer',
    'W2S friend channel',
    'Miniminter Sidemen wife Talia',
    'Vikkstar123 Minecraft Sidemen',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which British YouTube group is the Sidemen? The Sidemen group with KSI',
    'The Sidemen with KSI',
    'FaZe Clan esports',
    'Team 10 Jake',
    'Dude Perfect trick shots',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which trick shot group is Dude Perfect? Dude Perfect five guys',
    'The five-guy trick shot crew',
    'Sidemen British group',
    'Team 10 Jake group',
    'Yes Theory yes travelers',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which yes-saying adventure channel is Yes Theory? Yes Theory seek discomfort',
    'The Seek Discomfort travelers',
    'Dude Perfect sports',
    'Mark Rober engineering glitter bomb',
    'MrBeast challenges',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which engineer built Glitter Bomb traps? Mark Rober package thief device',
    'Mark Rovers glitter bomb creator',
    'William Osman chaotic builds',
    'Michael Reeves laser robots',
    'Allen Pan inventions',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which YouTuber builds chaotic robots with lasers? Michael Reeves by LilyPichu partner',
    'Michael Reeves the chaos engineer',
    'Mark Rober NASA glitter',
    'William Osman cow skin table',
    'Allen Pan SugRU devices',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which twitch star is LilyPichu? Lily Ki voice actress streamer OfflineTV',
    'Lily Ki of OfflineTV and Richard',
    'Pokimane OfflineTV cofounder',
    'Scarra coach OfflineTV',
    'Yvonne manager wife of Scarra',
    'hard',
    'Creators & Streamers',
  ],
  [
    'What is OfflineTV? A content house collective with Pokimane',
    'The creator house with Pokimane and Scarra',
    'FaZe gaming house',
    'Hype House TikTok house',
    'Clout House Jake Paul house',
    'medium',
    'Creators & Streamers',
  ],
  [
    'What is FaZe Clan? A gaming esports organization',
    'The famous esports org from trickshots',
    'OfflineTV content house',
    '100 Thieves Ninja-owned part',
    'G2 Esports European org',
    'medium',
    'Creators & Streamers',
  ],
  [
    'What is 100 Thieves? An esports and apparel brand with Valkyrae',
    'The Nadeshot brand with Rae',
    'FaZe Clan rival org',
    'Clout House creators',
    'OpTic Texas org',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Who founded 100 Thieves? Matthew Nadeshot Haag',
    'Nadeshot the former COD pro',
    'Hiko CS veteran',
    'CouRage YT co-owner',
    'Valkyrae co-owner',
    'hard',
    'Creators & Streamers',
  ],
  [
    'Who is Matthew Nadeshot Haag? The 100 Thieves founder ex-COD pro',
    'The founder former competitive Call of Duty',
    'Dr Disrespect persona real rival',
    'Shroud CS legend',
    'Swagg streamer FaZe',
    'expert',
    'Creators & Streamers',
  ],
  [
    'What is Clout House? Jake Pauls creator house',
    'The Jake Paul team house',
    'Hype House TikTok',
    'OfflineTV Pokimane',
    'Team 10 earlier house',
    'medium',
    'Creators & Streamers',
  ],
  [
    'What is the Hype House? A TikTok collective house',
    'The TikTok creator house of 2019',
    'Clout House YouTube',
    'OfflineTV Twitch',
    'FaZe Clan esports',
    'easy',
    'Creators & Streamers',
  ],
  [
    'Who was in the original Hype House with Charli? Addison Rae and Dixie among others',
    'Addison Rae and fellow TikTokers',
    'MrBeast crew',
    'FaZe members',
    'OfflineTV members',
    'medium',
    'Creators & Streamers',
  ],
  [
    'What is Dixie DAmelio known for? Singing and being Charlis sister',
    'Charlis sister with music career',
    'TikTok dancing only',
    'Makeup brand founder',
    'Reality chef show',
    'medium',
    'Creators & Streamers',
  ],
  [
    'What is the DAmelio family show? The DAmelio Show on Hulu',
    'The DAmelio Show reality series',
    'KUWTK older',
    'The Simple Life Paris older',
    'Newlyweds Jessica Nick older',
    'medium',
    'Creators & Streamers',
  ],
  [
    'Which App hit show followed Paris Hilton and Nicole? The Simple Life',
    'The Simple Life farm adventures',
    'Newlyweds Jessica Nick',
    'House of Wax film Paris',
    'My New BFF Paris contest',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Newlyweds couple starred Jessica Simpson and Nick Lachey? Jessica and Nick Lachey',
    'Jessica Simpson and Nick Lachey',
    'Carmen Electra Dave Navarro',
    'Trista Ryan Bachelorette first',
    'Britney Kevin chaotic',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which MTV show followed Lauren Conrad in Laguna? Laguna Beach then The Hills',
    'Laguna Beach and The Hills',
    'The City spinoff Whitney',
    'Newport Harbor precursor series',
    'Real World original reality',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Hills star moved to The City? Whitney Port',
    'Whitney Port in New York',
    'Lauren Conrad LA remained',
    'Audrina Patridge stayed',
    'Heidi MontagSpeidi',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which couple was Speidi? Heidi Montag and Spencer Pratt',
    'Heidi and Spencer Pratt',
    'Lauren and Jason Wahler',
    'Audrina and Justin Bobby',
    'Whitney and Jay Lyon',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which MTV original reality house was The Real World? The Real World pioneered reality TV',
    'The Real World pioneered the genre',
    'Road Rules sibling spinoff',
    'The Challenge competition spinoff',
    'Jersey Shore later phenomenon',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Jersey Shore member calls himself the Situation? Mike Sorrentino',
    'Mike The Situation Sorrentino',
    'Snooki Nicole Polizzi',
    'Pauly D DJ DelVecchio',
    'JWoww Jenni Farley',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which Jersey Shore DJ is Pauly D? DJ Pauly D DelVecchio',
    'Pauly D the DJ',
    'The Situation gym tan laundry',
    'Snooki meatball',
    'Vinny Guadagnino keto guido',
    'easy',
    'Celebrity Facts',
  ],
  [
    'What is GTL in Jersey Shore? Gym, tan, laundry',
    'Gym tan laundry routine',
    'Grab the lemonade',
    'Go to Longport',
    'Good times love',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Which Shore spinoff pairs Snooki and JWoww? Snooki and JWoww series',
    'The Snooki and JWoww spinoff',
    'Jersey Shore Family Vacation reunion',
    'The Pauly D Project DJ spinoff',
    'The Situation family show',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Real Housewives tagline festival Watch What Happens Live host? Andy Cohen hosts it',
    'Andy Cohen hosts Watch What Happens',
    'Bravo exec Frances Berwick',
    'Teresa Giudice table flip',
    'NeNe Leakes close your legs',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Housewife flipped a table? Teresa Giudice',
    'Teresa flipped the table',
    'Nene shade said close your legs',
    'Ramona renewal sunglasses',
    'Bethenny skinnygirl',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Housewife founded Skinnygirl? Bethenny Frankel',
    'Bethenny Frankel Skinnygirl brand',
    'Teresa table flip',
    'Ramona renew',
    'Sonja tipsy toaster',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Housewife says renewal skin? Ramona Singer',
    'Ramona Singer renewal',
    'Bethenny skinny',
    'Sonja toaster oven',
    'Dorinda nice clean',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Housewife is tipsy toaster? Sonja Morgan',
    'Sonja and her toaster oven',
    'Dorinda nice clean all',
    'Luann countess money cant buy class',
    'Ramona eyes closed renewal',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Countess sang Money Cant Buy You Class? Luann de Lesseps',
    'Luann de Lesseps the Countess',
    'Ramona renewal',
    'Sonja toaster',
    'Dorinda cleaning',
    'hard',
    'Celebrity Facts',
  ],
];

module.exports = { banks: [HALFTIME, BIG_AWARDS, REALITY_TV, STREAMERS, FACTS] };
