'use strict';

const rows = [
  [
    'Who played Harley Quinn in Suicide Squad? Margot Robbie',
    'Margot Robbie',
    'Gal Gadot',
    'Jennifer Lawrence',
    'Emma Stone',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Poison Ivy in Batman and Robin 1997? Uma Thurman',
    'Uma Thurman',
    'Michelle Pfeiffer Catwoman 1992',
    'Halle Berry Catwoman 2004',
    'Anne Hathaway Catwoman 2012',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Catwoman 2004? Halle Berry',
    'Halle Berry',
    'Michelle Pfeiffer',
    'Anne Hathaway',
    'Zoe Kravitz newer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Catwoman 2022? Zoe Kravitz',
    'Zoe Kravitz',
    'Anne Hathaway',
    'Halle Berry',
    'Eartha Kitt classic TV',
    'medium',
    'Games',
  ],
  [
    'Who played the Joker 2019? Joaquin Phoenix',
    'Joaquin Phoenix',
    'Heath Ledger 2008',
    'Jared Leto Suicide Squad',
    'Jack Nicholson 1989',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played the Joker 1989? Jack Nicholson',
    'Jack Nicholson',
    'Cesar Romero TV classic',
    'Mark Hamill voice',
    'Cameron Monaghan Gotham TV',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who voiced the Joker in animated series? Mark Hamill',
    'Mark Hamill',
    'Kevin Conroy was Batman voice',
    'Tara Strong Harley voice later',
    'John DiMaggio newer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who voiced Batman with Hamill? Kevin Conroy',
    'Kevin Conroy',
    'Mark Hamill Joker',
    'Will Arnett LEGO Batman comedic',
    'Christian Bale live action',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Superman on TV Supergirl? Tyler Hoechlin',
    'Tyler Hoechlin',
    'Henry Cavill films',
    'Brandon Routh film 2006 and legends',
    'Dean Cain Lois and Clark 90s',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Superman 1978? Christopher Reeve',
    'Christopher Reeve',
    'George Reeves 1950s TV',
    'Dean Cain 1990s',
    'Tom Welling Smallville teen',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Batman on 1960s TV? Adam West',
    'Adam West',
    'Michael Keaton 1989',
    'Christian Bale 2005',
    'Robert Pattinson 2022',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Batman 2022? Robert Pattinson',
    'Robert Pattinson',
    'Ben Affleck DCEU',
    'Christian Bale trilogy',
    'Michael Keaton return multiverse',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Aquaman in the 2010s show Smallville? Alan Ritchson aquaman smallville',
    'Alan Ritchson early Smallville',
    'Jason Momoa films',
    'Vincent Chase fictional Entourage playing Aquaman',
    'Patrick Wilson Orm villain',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Which Entourage character played Aquaman fictitiously? Vincent Chase',
    'Vincent Chase in the show plot',
    'Johnny Drama his brother',
    'Eric Murphy manager E',
    'Turtle driver sidekick',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Thor Ragnarok director cameo? Taika Waititi as Korg',
    'Taika Waititi voiced Korg',
    'Matt Damon Loki actor cameo',
    'Sam Neill Odin actor cameo',
    'Chris Hemsworth real Thor',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who cameoed as Loki actor in Ragnarok play? Matt Damon',
    'Matt Damon played actor Loki',
    'Luke Hemsworth actor Thor',
    'Sam Neill actor Odin',
    'Cate Blanchett Hela real villain',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Hela in Thor Ragnarok? Cate Blanchett',
    'Cate Blanchett',
    'Tessa Thompson Valkyrie',
    'Rachel House grandma voice',
    'Natalie Portman Jane Mighty Thor later',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Valkyrie in Thor Ragnarok? Tessa Thompson',
    'Tessa Thompson',
    'Cate Blanchett Hela',
    'Zoe Saldana Gamora',
    'Lupita Nyongo Nakia',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Jane Foster Mighty Thor? Natalie Portman',
    'Natalie Portman',
    'Tessa Thompson Valkyrie',
    'Kat Dennings Darcy',
    'Jamie Alexander Sif',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Sif in early Thor? Jaimie Alexander',
    'Jaimie Alexander',
    'Natalie Portman Jane',
    'Kat Dennings Darcy',
    'Rene Russo Frigga',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Frigga Thor mother? Rene Russo',
    'Rene Russo',
    'Jaimie Alexander Sif',
    'Idris Elba Heimdall',
    'Anthony Hopkins Odin',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Odin in Thor? Anthony Hopkins',
    'Anthony Hopkins',
    'Idris Elba Heimdall gatekeeper',
    'Tom Hiddleston Loki',
    'Zachary Levi Fandral recast',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Heimdall in Thor? Idris Elba',
    'Idris Elba',
    'Anthony Hopkins Odin',
    'Karl Urban Skurge executioner',
    'Tadanobu Asano Hogun',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Skurge in Thor Ragnarok? Karl Urban',
    'Karl Urban',
    'Idris Elba Heimdall prior',
    'Jeff Goldblum Grandmaster',
    'Dirk Benedict original inspirations',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played the Grandmaster in Thor Ragnarok? Jeff Goldblum',
    'Jeff Goldblum',
    'Karl Urban Skurge',
    'Chris Hemsworth Thor',
    'Russell Crowe Zeus later',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Zeus in Love and Thunder? Russell Crowe',
    'Russell Crowe',
    'Jeff Goldblum Grandmaster prior',
    'Christian Bale Gorr villain',
    'Matt Damon actor Loki again',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Gorr the God Butcher? Christian Bale',
    'Christian Bale',
    'Russell Crowe Zeus',
    'Cate Blanchett Hela prior',
    'Mads Mikkelsen Kaecilius Doctor Strange',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Kaecilius in Doctor Strange? Mads Mikkelsen',
    'Mads Mikkelsen',
    'Christian Bale Gorr later',
    'Chiwetel Ejiofor Mordo ally turned',
    'Benedict Wong Wong',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Mordo in Doctor Strange? Chiwetel Ejiofor',
    'Chiwetel Ejiofor',
    'Mads Mikkelsen Kaecilius',
    'Benedict Wong Wong loyal',
    'Rachel McAdams Christine',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Wong in Doctor Strange? Benedict Wong',
    'Benedict Wong',
    'Chiwetel Ejiofor Mordo',
    'Benedict Cumberbatch title hero',
    'Tilda Swinton Ancient One casting debated',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played the Ancient One? Tilda Swinton',
    'Tilda Swinton',
    'Rachel McAdams Christine',
    'Elizabeth Olsen Wanda separate',
    'Eva Green rumored once',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Christine Palmer in Doctor Strange? Rachel McAdams',
    'Rachel McAdams',
    'Tilda Swinton Ancient One',
    'Linda Cardellini Hawkeye wife Laura',
    'Marisa Tomei Aunt May',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Aunt May in the MCU? Marisa Tomei',
    'Marisa Tomei',
    'Sally Field Amazing Spider-Man films',
    'Rosemary Harris original trilogy',
    'Zendaya MJ different character',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Aunt May in the original trilogy? Rosemary Harris',
    'Rosemary Harris',
    'Marisa Tomei MCU',
    'Sally Field reboot films',
    'Elizabeth Banks Betty Brant cameos',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Aunt May in Amazing Spider-Man? Sally Field',
    'Sally Field',
    'Rosemary Harris trilogy',
    'Marisa Tomei MCU',
    'Emma Stone Gwen Stacy different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Gwen Stacy in Amazing Spider-Man? Emma Stone',
    'Emma Stone',
    'Bryce Dallas Howard Spider-Man 3',
    'Kirsten Dunst MJ',
    'Zendaya MJ MCU',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played MJ in the original trilogy? Kirsten Dunst',
    'Kirsten Dunst',
    'Emma Stone Gwen',
    'Zendaya MJ MCU',
    'Shailene Woodley cut Gwen cameo',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Harry Osborn in Spider-Man 3? James Franco',
    'James Franco',
    'Dane DeHaan Amazing 2',
    'Willem Dafoe Norman Goblin',
    'Chris Cooper Norman Amazing 2',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Harry Osborn in Amazing Spider-Man 2? Dane DeHaan',
    'Dane DeHaan',
    'James Franco trilogy',
    'Chris Cooper Norman',
    'Campbell Scott Richard Parker',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Norman Osborn 2002? Willem Dafoe',
    'Willem Dafoe',
    'James Franco Harry son',
    'Chris Cooper Amazing reboot',
    'Michael Massee相关的 none skip',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Doctor Octopus 2004? Alfred Molina',
    'Alfred Molina',
    'Willem Dafoe Green Goblin',
    'Thomas Haden Church Sandman',
    'Topher Grace Venom Eddie',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Sandman in Spider-Man 3? Thomas Haden Church',
    'Thomas Haden Church',
    'Alfred Molina Doc Ock prior',
    'Topher Grace Venom',
    'James Franco Harry new goblin',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Venom in Spider-Man 3? Topher Grace',
    'Topher Grace',
    'Tom Hardy Venom solo films',
    'James Franco Harry',
    'J.K. Simmons Jameson editor',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played J. Jonah Jameson? J.K. Simmons',
    'J.K. Simmons',
    'Willem Dafoe Goblin',
    'Zen范畴 none skip',
    'J.K. Simmons returned in MCU too',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Betty Brant 2002 cameos? Elizabeth Banks',
    'Elizabeth Banks cameo',
    'Rosemary Harris May',
    'James Franco Harry',
    'Bill Nunn Robbie Robertson editor',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Robbie Robertson Spider-Man? Bill Nunn',
    'Bill Nunn the editor colleague',
    'Elizabeth Banks Betty',
    'J.K. Simmons Jameson',
    'Cliff Robertson Uncle Ben',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Uncle Ben 2002? Cliff Robertson',
    'Cliff Robertson',
    'Martin Sheen Amazing reboot Uncle',
    'Marisa Tomei May MCU',
    'Willem Dafoe Norman',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Uncle Ben in Amazing Spider-Man? Martin Sheen',
    'Martin Sheen',
    'Cliff Robertson original',
    'Marisa Tomei MCU May',
    'Sally Field May reboot',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played the Lizard in Amazing Spider-Man? Rhys Ifans',
    'Rhys Ifans',
    'Alfred Molina Doc Ock original',
    'Dane DeHaan Green Goblin reboot',
    'Jamie Foxx Electro reboot',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Electro in Amazing Spider-Man 2? Jamie Foxx',
    'Jamie Foxx',
    'Rhys Ifans Lizard',
    'Paul Giamatti Rhino',
    'Dane DeHaan Goblin',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Rhino in Amazing Spider-Man 2? Paul Giamatti',
    'Paul Giamatti',
    'Jamie Foxx Electro',
    'Dane DeHaan Goblin',
    'Chris Cooper Norman',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Vulture in Spider-Man Homecoming? Michael Keaton',
    'Michael Keaton',
    'Jake Gyllenhaal Mysterio Far From Home',
    'Willem Dafoe Goblin',
    'Jamie Foxx Electro return',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Mysterio in Far From Home? Jake Gyllenhaal',
    'Jake Gyllenhaal',
    'Michael Keaton Vulture first',
    'Tom Hardy Venom separate',
    'Willem Dafoe return No Way Home',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played the Green Goblin in No Way Home? Willem Dafoe returning',
    'Willem Dafoe returned',
    'Alfred Molina Doc Ock returned too',
    'Jamie Foxx Electro returned',
    'Thomas Haden Church Sandman returned',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who returned as Doc Ock in No Way Home? Alfred Molina',
    'Alfred Molina returned',
    'Willem Dafoe Goblin returned',
    'Jamie Foxx Electro returned',
    'Rhys Ifans Lizard returned',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who returned as Electro in No Way Home? Jamie Foxx',
    'Jamie Foxx returned',
    'Alfred Molina returned',
    'Rhys Ifans returned',
    'Thomas Haden Church returned',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Lizard in No Way Home? Rhys Ifans returned',
    'Rhys Ifans returned',
    'Jamie Foxx returned',
    'Alfred Molina returned',
    'Thomas Haden Church partially',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Sandman in No Way Home? Thomas Haden Church returned voice heavy',
    'Thomas Haden Church returned',
    'Rhys Ifans returned',
    'Jamie Foxx returned',
    'Charlie Cox Daredevil lawyer cameo',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who cameoed as Matt Murdock in No Way Home? Charlie Cox',
    'Charlie Cox as Daredevil lawyer',
    'Jon Bernthal Punisher cameo rumored cut',
    'Vincent DOnofrio Kingpin echo later',
    'Tom Hardy Venom post scene',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Kingpin in Daredevil Netflix? Vincent DOnofrio',
    'Vincent DOnofrio',
    'Charlie Cox title hero',
    'Jon Bernthal Punisher spinoff',
    'Elodie Yung Elektra',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Elektra in Daredevil Netflix? Elodie Yung',
    'Elodie Yung',
    'Jennifer Garner film Elektra 2005',
    'Deborah Ann Woll Karen page',
    'Ayelet Zurer Vanessa',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Elektra in the 2005 film? Jennifer Garner',
    'Jennifer Garner',
    'Elodie Yung Netflix later',
    'Carla Gugino Elektra dream only',
    'Anne Hathaway rumored never',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Karen Page in Daredevil? Deborah Ann Woll',
    'Deborah Ann Woll',
    'Elodie Yung Elektra',
    'Elden Henson Foggy lawyer friend',
    'Rosario Dawson Night Nurse Claire',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Foggy Nelson? Elden Henson',
    'Elden Henson',
    'Deborah Ann Woll Karen',
    'Charlie Cox Matt',
    'Jon Bernthal Frank',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Claire Temple across Netflix Marvel? Rosario Dawson',
    'Rosario Dawson the night nurse',
    'Deborah Ann Woll Karen',
    'Krysten Ritter Jessica Jones',
    'Simone Missick Misty Knight',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Jessica Jones? Krysten Ritter',
    'Krysten Ritter',
    'Rosario Dawson Claire',
    'Rachael Taylor Trish',
    'Carrie-Anne Moss Jeri',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Luke Cage? Mike Colter',
    'Mike Colter',
    'Krysten Ritter Jessica wife plot',
    'Finn Jones Danny Iron Fist',
    'Theo Rossi Shades villain',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Danny Rand Iron Fist? Finn Jones',
    'Finn Jones',
    'Mike Colter Luke partner',
    'Jessica Henwick Colleen wing',
    'David Wenham Harold meachum',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Colleen Wing? Jessica Henwick',
    'Jessica Henwick',
    'Simone Missick Misty',
    'Elodie Yung Elektra',
    'Wai Chinh Hoop Gao villain',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Misty Knight? Simone Missick',
    'Simone Missick',
    'Jessica Henwick Colleen',
    'Rosario Dawson Claire',
    'Alfre Woodard Mariah Dillard villain',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Mariah Dillard in Luke Cage? Alfre Woodard',
    'Alfre Woodard',
    'Simone Missick Misty hero',
    'Mustafa Shakir Bushmaster villain season two',
    'Gabriel Dennis Diamondback villain one',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Punisher Netflix? Jon Bernthal',
    'Jon Bernthal',
    'Mike Colter Luke ally teamup',
    'Ben Barnes Russo villain betray',
    'Amber Rose Revah Dinah agent',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Billy Russo in Punisher? Ben Barnes',
    'Ben Barnes',
    'Jon Bernthal title hero',
    'Amber Rose Revah Dinah',
    'Floriana Lima Krista therapist',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Yondu in Guardians? Michael Rooker',
    'Michael Rooker',
    'James Gunn brother actor frequent',
    'Sean Gunn Kraglin on-set stand',
    'Sylvester Stallone Stakar cameo',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Kraglin in Guardians? Sean Gunn',
    'Sean Gunn',
    'Michael Rooker Yondu boss',
    'Nathan Fillion cameo prisoner',
    'Rob Zombie voice creation',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who voiced Rocket in Guardians? Bradley Cooper',
    'Bradley Cooper',
    'Vin Diesel voiced Groot',
    'Sean Gunn on set stand-in',
    'Pom Klementieff Mantis live',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who voiced Groot? Vin Diesel',
    'Vin Diesel one line many languages',
    'Bradley Cooper Rocket voice',
    'James Gunn director',
    'Karen Gillan Nebula blue',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Nebula? Karen Gillan',
    'Karen Gillan',
    'Zoe Saldana Gamora sister',
    'Pom Klementieff Mantis sister',
    'Ariana Greenblatt young Gamora cameo',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Mantis? Pom Klementieff',
    'Pom Klementieff',
    'Karen Gillan Nebula blue',
    'Elizabeth Debicki Ayesha gold',
    'Laura Haddock Star-Lords mother two films',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Ayesha in Guardians 2? Elizabeth Debicki',
    'Elizabeth Debicki',
    'Pom Klementieff Mantis empath',
    'Karen Gillan Nebula',
    'Millya Susan? skip',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Ego in Guardians 2? Kurt Russell',
    'Kurt Russell',
    'Sylvester Stallone Stakar cameo',
    'David Hasselhoff cameo hallucination',
    'Michael Rooker Yondu blue',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Stakar Ogord cameo? Sylvester Stallone',
    'Sylvester Stallone cameo',
    'Kurt Russell Ego planet',
    'Michael Rooker Yondu arrow',
    'Ving Rhames Krugarr sorcerer cut',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Agent 13 Sharon Carter? Emily VanCamp',
    'Emily VanCamp',
    'Hayley Atwell Peggy Carter founder agent',
    'Linda Cardellini Sharon different Hawkeye wife',
    'Gugu Mbatha-Raw Ravonna Loki TVA judge',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Peggy Carter? Hayley Atwell',
    'Hayley Atwell',
    'Emily VanCamp Sharon niece',
    'Dominic Cooper young Howard Stark',
    'John Slattery older Howard',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Howard Stark young in Captain America first? Dominic Cooper',
    'Dominic Cooper young Howard',
    'John Slattery older Howard scenes',
    'Gerard Sanders photo only',
    'Matthew Stern transition none',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played older Howard Stark? John Slattery',
    'John Slattery Mad Men star',
    'Dominic Cooper young version',
    'Michael Douglas Hank Pym different',
    'Jeff Bridges Obadiah Iron Man villain',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Hank Pym in Ant-Man? Michael Douglas',
    'Michael Douglas',
    'Paul Rudd Scott Lang title hero',
    'Corey Stoll Darren Cross Yellowjacket villain',
    'Evangeline Lilly Hope Wasp',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Scott Lang? Paul Rudd',
    'Paul Rudd',
    'Michael Douglas Hank mentor',
    'Corey Stoll villain first film',
    'Jonathan Majors Kang later villain',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Hope van Dyne? Evangeline Lilly',
    'Evangeline Lilly',
    'Michelle Pfeiffer Janet mother Wasp',
    'Kathryn Newton Cassie recast later',
    'Emma Fuhrmann young Cassie first',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Janet van Dyne original Wasp? Michelle Pfeiffer',
    'Michelle Pfeiffer',
    'Evangeline Lilly Hope daughter Wasp',
    'Hayley Atwell Peggy different',
    'Maribel Verdu auntAdded cameo No',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Darren Cross in Ant-Man? Corey Stoll',
    'Corey Stoll',
    'Michael Douglas Hank mentor opposite',
    'Paul Rudd hero opposite',
    'Bobby Cannavale Paxton cop',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Paxton in Ant-Man? Bobby Cannavale',
    'Bobby Cannavale',
    'Corey Stoll villain',
    'Michael Pena Luis comic relief',
    'T.I. Dave crew',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Luis in Ant-Man? Michael Pena',
    'Michael Pena storyteller Luis',
    'T.I. crew Dave',
    'David Dastmalchian Kurt crew',
    'Judy Greer Maggie ex-wife',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Kurt in Ant-Man? David Dastmalchian',
    'David Dastmalchian crew hacker',
    'Michael Pena Luis stories',
    'T.I. Dave watcher',
    'Randall Park Jimmy Woo agent later',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Jimmy Woo in Ant-Man and WandaVision? Randall Park',
    'Randall Park',
    'David Dastmalchian Kurt separate',
    'Teaming Kat Dennings Darcy return',
    'Asif Ali norm comedian WandaVision',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Darcy Lewis in Thor and WandaVision? Kat Dennings',
    'Kat Dennings',
    'Randall Park Jimmy Woo partner WandaVision',
    'Stellan Skarsgard Selvig scientist',
    'Idra none skip',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Erik Selvig in Thor? Stellan Skarsgard',
    'Stellan Skarsgard',
    'Kat Dennings Darcy assistant',
    'Idris Elba Heimdall separate',
    'Rene Russo Frigga separate',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Heimdall again confirm? Idris Elba',
    'Idris Elba',
    'Stellan Skarsgard Selvig',
    'Anthony Hopkins Odin',
    'Taika Waititi Korg voice',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who directed Thor Ragnarok? Taika Waititi',
    'Taika Waititi',
    'Kenneth Branagh first Thor',
    'Alan Taylor Dark World',
    'Destin Daniel Cretton Shang-Chi',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed the first Thor? Kenneth Branagh',
    'Kenneth Branagh',
    'Taika Waititi Ragnarok later',
    'Alan Taylor Dark World',
    'Joe Russo Winter Soldier later',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Thor Dark World? Alan Taylor',
    'Alan Taylor',
    'Kenneth Branagh first',
    'Taika Waititi Ragnarok',
    'Patty Jenkins left project early',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who directed Captain America Winter Soldier? The Russo brothers',
    'Anthony and Joe Russo',
    'Joe Johnston first film',
    'Joss Whedon Avengers films',
    'Peyton Reed Ant-Man instead',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Captain America first? Joe Johnston',
    'Joe Johnston',
    'The Russo brothers Winter Soldier',
    'Joss Whedon Avengers',
    'Kenneth Branagh Thor same year different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who directed the Avengers 1 and 2? Joss Whedon',
    'Joss Whedon',
    'The Russo brothers later ones',
    'James Gunn Guardians',
    'Jon Favreau Iron Man first two',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Iron Man 1 and 2? Jon Favreau',
    'Jon Favreau',
    'Shane Black Iron Man 3',
    'Joss Whedon Avengers',
    'Kenneth Branagh Thor',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Iron Man 3? Shane Black',
    'Shane Black',
    'Jon Favreau first two',
    'The Russo brothers Winter Soldier',
    'Alan Taylor Thor Dark World',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Guardians of the Galaxy 1 and 2? James Gunn',
    'James Gunn',
    'Joss Whedon Avengers crossovers',
    'Taika Waititi Ragnarok same era',
    'Peyton Reed Ant-Man different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Doctor Strange? Scott Derrickson',
    'Scott Derrickson',
    'James Gunn Guardians',
    'Sam Raimi Multiverse of Madness sequel',
    'Jon Watts Spider-Man trilogy',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Multiverse of Madness? Sam Raimi',
    'Sam Raimi',
    'Scott Derrickson first Strange',
    'Jon Watts Spider-Man trilogy MCU',
    'Chloe Zhao Eternals',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Eternals? Chloe Zhao',
    'Chloe Zhao',
    'Sam Raimi Multiverse',
    'Destin Cretton Shang-Chi',
    'Nia DaCosta the Marvels',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who directed Shang-Chi? Destin Daniel Cretton',
    'Destin Daniel Cretton',
    'Chloe Zhao Eternals',
    'Daniel Kwan Daniels Everything',
    'Simu Liu title actor not director',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who plays Shang-Chi? Simu Liu',
    'Simu Liu',
    'Tony Leung Wenwu villain father',
    'Awkwafina Katy friend',
    'Michelle Yeoh different MCU aunt',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Wenwu in Shang-Chi? Tony Leung',
    'Tony Leung Chiu-wai',
    'Simu Liu title hero son',
    'Awkwafina comic friend Katy',
    'Fala Chen Ying Li mother',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Katy in Shang-Chi? Awkwafina',
    'Awkwafina',
    "Meng'er Zhang Xialing sister",
    'Michelle Yeoh Ying Nan aunt',
    'Fala Chen mother flashback',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Xialing in Shang-Chi? Menger Zhang',
    'Menger Zhang',
    'Awkwafina Katy friend',
    'Michelle Yeoh aunt Ying Nan',
    'Stephanie Hsu Joy different Everything',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who directed Everything Everywhere All at Once? The Daniels',
    'Daniel Kwan and Daniel Scheinert',
    'Destin Cretton Shang-Chi same year',
    'Chloe Zhao Eternals same year',
    'Rian Johnson Knives Out different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Waymond in Everything Everywhere? Ke Huy Quan',
    'Ke Huy Quan Oscar winning return',
    'Michelle Yeoh Evelyn lead',
    'Stephanie Hsu Joy daughter villain',
    'James Hong Gong Gong dad',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Evelyn in Everything Everywhere? Michelle Yeoh',
    'Michelle Yeoh',
    'Ke Huy Quan husband Waymond',
    'Stephanie Hsu daughter Joy',
    'Jamie Lee Curtis IRS Deirdre',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Deirdre in Everything Everywhere? Jamie Lee Curtis',
    'Jamie Lee Curtis IRS auditor',
    'Michelle Yeoh lead laundromat',
    'Stephanie Hsu bagel daughter',
    'Jenny Slate dog mom Baker',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Gong Gong in Everything Everywhere? James Hong',
    'James Hong veteran actor',
    'Ke Huy Quan husband role',
    'Harry Shum Jr quick cameo',
    'Odessa Young none skip',
    'hard',
    'Celebrity Facts',
  ],
];

module.exports = { rows };
