'use strict';

const rows = [
  [
    'Which designer made the iconic red soles? Christian Louboutin',
    'Christian Louboutin',
    'Jimmy Choo',
    'Manolo Blahnik',
    'Stuart Weitzman',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Which designer is famous for Manolo Blahnik shoes? The Sex and the City favorite',
    'The SATC name-drop shoe brand',
    'Louboutin red soles different',
    'Jimmy Choo different',
    'Stuart Weitzman different',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Which supermodel is the face of the 90s Heroin chic? Kate Moss',
    'Kate Moss',
    'Naomi Campbell different era icon',
    'Cindy Crawford all-American',
    'Claudia Schiffer German blonde',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Which supermodel is called Queen Naomi? Naomi Campbell',
    'Naomi Campbell',
    'Tyra Banks America model host',
    'Iman David Bowie widow',
    'Beverly Johnson first Black Vogue cover',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Which supermodel married David Bowie? Iman',
    'Iman the Somali-American model',
    'Zayn Malik Gigi Hadid couple different',
    'Naomi Campbell never married widely',
    'Iman Abdulmajid full name same person',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who created the Versace safety-pin dress moment? Gianni Versace for Elizabeth Hurley',
    'The 1994 Hurley dress by Gianni Versace',
    'Donatella later designer sister',
    'Atelier Versace line label',
    'JLo Grammys green Versace different',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Who wore the green Versace Grammys dress? Jennifer Lopez in 2000',
    'JLo at the 2000 Grammys',
    'Liz Hurley safety pin 1994 different',
    'Beyonce Met Gala different',
    'Rihanna yellow 2015 different',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who founded Off-White and directed Louis Vuitton mens? Virgil Abloh late designer',
    'Virgil Abloh 1980-2021',
    'Kanye West Yeezy separate',
    'Pharrell newer LV mens director',
    'Kim Jones Dior mens then LV after',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Who is the LV mens designer after Virgil? Pharrell Williams',
    'Pharrell Williams appointed 2023',
    'Virgil Abloh late predecessor',
    'Kim Jones earlier mens director',
    'Stefano Pilati unrelated',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who is Telfar known for? The shopping bag everyone wanted',
    'The not-for-everyone-everyone bag brand',
    'Cult Gaia bamboo bag brand',
    'Staud french branding',
    'Jacquemus mini bags brand',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Which designer is famous for the wrap dress? Diane von Furstenberg',
    'DVF wrap dress',
    'Stella McCartney vegetarian designer',
    'Victoria Beckham VB brand',
    'Oscar de la Renta gowns',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Which designer dresses Meghan Markle frequently? Givenchy Clare Waight Keller wedding',
    'Clare Waight Keller made the wedding dress',
    'Stella McCartney second dress evening',
    'Carolyn Bessette slip wedding 90s different',
    'Vera Wang bridal famous general',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Who made Kates wedding dress? Sarah Burton for Alexander McQueen',
    'Sarah Burton McQueen lace gown',
    'Clare Waight Keller Meghan different',
    'Vera Wang American bridal',
    'Jenny Packham Kate favorite evening',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Who made Pippas bridesmaid dress? Alexander McQueen Sarah Burton too',
    'Sarah Burton McQueen again',
    'Jenny Packham different designer',
    'Temperley Kate night out brand',
    'Reiss white dress Kate clone sold',
    'expert',
    'Fashion & Brands',
  ],
  [
    'Which Reiss dress did Kate wear for the engagement photo? The Nanette white dress',
    'The Reiss Nanette white dress',
    'Whistles blue zigzag different photo',
    'Zara blue dress different event',
    'Issa blue engagement dress actually',
    'expert',
    'Fashion & Brands',
  ],
  [
    'Which blue dress did Kate wear for the engagement? An Issa wrap dress',
    'The Issa blue wrap dress',
    'Reiss white dress official portrait',
    'Whistles blue zigzag later',
    'Temperley navy evening',
    'expert',
    'Fashion & Brands',
  ],
  [
    'Which fashion weeks are the big four? New York, London, Milan, and Paris',
    'NY, London, Milan, Paris',
    'Berlin, Madrid, Tokyo, Seoul',
    'Paris, Milan, Shanghai, Dubai',
    'NY, LA, Paris, Tokyo',
    'easy',
    'Fashion & Brands',
  ],
  [
    'Which magazine is Anna Wintour editor? Vogue',
    'Vogue',
    'Elle',
    'Harper’s Bazaar',
    'W Magazine',
    'easy',
    'Fashion & Brands',
  ],
  [
    'Who is Edward Enninful? Former British Vogue editor',
    'The British Vogue editor turned advisor',
    'Samira Nasr Harper’s Bazaar first Black EIC',
    'Chioma Blair cupids different',
    'Tracee Ellis Ross actor different',
    'hard',
    'Fashion & Brands',
  ],
  [
    'What is the Victoria Secret Fashion Show status? Ended run 2019 then reimagined',
    'Paused then rebooted differently',
    'Annual continuous event',
    'Moved to Paris permanently',
    'Became swimsuit only',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who is a famous Victoria Secret Angel alum? Tyra Banks among others',
    'Tyra Banks early angel',
    'Gisele Bundchen angel alum',
    'Heidi Klum angel alum',
    'All three were angels',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who is the Brazilian angel famous for walking? Gisele Bundchen and Adriana Lima',
    'Gisele and Adriana Brazilians',
    'Candice South African angel',
    'Karlie American angel',
    'Behati Namibian angel',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who is Kendall Jenners modeling agency mother manager? Kris Jenner manages her',
    'Kris manages Kendall too',
    'IMG Models agency signs her',
    'The Society Management NY agency',
    'Storm Models UK agency',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Which agency signs Gigi and Bella? IMG Models',
    'IMG Models for both sisters',
    'The Society Management',
    'Storm Models UK',
    'Elite Model Management historic',
    'medium',
    'Fashion & Brands',
  ],
  [
    'What is the CFDA? The Council of Fashion Designers of America',
    'The American fashion council',
    'The Paris fashion union',
    'A British council',
    'An Italian chamber',
    'medium',
    'Fashion & Brands',
  ],
  [
    'What is the Met Gallag theme 2023? Karl Lagerfeld tribute',
    'Honoring Karl Lagerfeld work',
    'Camp notes on fashion 2019 prior',
    'Heavenly bodies religion 2018',
    'Gilded glamour 2022 prior',
    'medium',
    'Fashion & Brands',
  ],
  [
    'What was the Met Gala 2019 theme? Camp Notes on Fashion',
    'Camp: Notes on Fashion',
    'Heavenly Bodies religion',
    'Manus x Machina tech',
    'Rei Kawakubo Comme des Garcons',
    'medium',
    'Games',
  ],
  [
    'What was the Met Gala 2018 theme? Heavenly Bodies fashion and Catholic imagination',
    'Religion-inspired couture theme',
    'Camp humor theme later',
    'Tech Manus x Machina earlier',
    'Kawakubo Comme des Garcons 2017 earlier',
    'medium',
    'Games',
  ],
  [
    'Which designer founded Comme des Garcons? Rei Kawakubo',
    'Rei Kawakubo',
    'Yohji Yamamoto peer designer',
    'Issey Miyake pleats designer',
    'Junya Watanabe protege designer',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Which designer is famous for pleats? Issey Miyake',
    'Issey Miyake pleats please',
    'Rei Kawakubo Comme',
    'Yohji Yamamoto black draped',
    'Junya Watanabe protege lines',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Which Brit designer is famous for draped black? Yohji Yamamoto is Japanese not British',
    'Yohji Yamamoto Japanese avant-garde',
    'Vivienne Westwood British punk dame',
    'Alexander McQueen British provocateur',
    'John Galliano British maverick',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who is the British punk fashion dame? Vivienne Westwood',
    'Vivienne Westwood Dame punk',
    'Alexander McQueen British but male',
    'Stella McCartney Beatles daughter',
    'Betty Jackson lesser known',
    'easy',
    'Fashion & Brands',
  ],
  [
    'Who founded McQueen brand? Alexander McQueen',
    'Lee Alexander McQueen',
    'Sarah Burton successor creative',
    'Stella McCartney Beatles daughter separate',
    'Tom Ford Gucci era separate',
    'easy',
    'Fashion & Brands',
  ],
  [
    'Who is Stella McCartneys father? Paul McCartney',
    'Beatle Paul McCartney',
    'George Harrison fellow Beatle',
    'John Lennon fellow Beatle',
    'Ringo Starr fellow Beatle',
    'easy',
    'Fashion & Brands',
  ],
  [
    'Which Beatles daughter is a fashion designer? Stella McCartney',
    'Stella the designer daughter',
    'Yoko Ono artist widow',
    'Linda McCartney photographer food brand mother',
    'Mary McCartney photographer daughter',
    'medium',
    'Fashion & Brands',
  ],
  [
    'Who is Sean Lennon? John and Yokos son musician',
    'The son of John Lennon and Yoko Ono',
    'Julian Lennon John first son different mother',
    'James McCartney Pauls musician son',
    'DHANI Harrison Georges son musician',
    'hard',
    'Fashion & Brands',
  ],
  [
    'Who is Dhani Harrison? Georges musician son',
    'George Harrisons son musician',
    'Sean Lennon Johns son',
    'James McCartney Pauls son',
    'Zak Starkey Ringos drummer son',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Zak Starkey? Ringos drummer son',
    'The Who and Oasis drummer son of Ringo',
    'Dhani Harrison guitar son',
    'James McCartney piano son',
    'Sean Lennon singer son',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is James McCartney? Pauls musician son',
    'The Only One singer son of Paul',
    'Zak drummer son of Ringo',
    'Dhani son of George',
    'Sean son of John',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Julian Lennon? Johns first son singer',
    'Hey Jude inspiration John first son',
    'Sean second son with Yoko',
    'James Pauls son',
    'Dhani Georges son',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Beatle song was written for Julian? Hey Jude',
    'Hey Jude by Paul for young Julian',
    'Let It Be for Mary McCartney birth',
    'Blackbird civil rights inspiration',
    'Dear Prudence Mia Farrow sister',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Beatles song referenced Prudence? Dear Prudence',
    'Dear Prudence about Mia Farrow sister',
    'Hey Jude for Julian',
    'Julia for Johns mother',
    'Martha My Dear for Pauls dog',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Beatles song is about a dog? Martha My Dear',
    'Pauls sheepdog Martha',
    'Polythene Pam character',
    'Mean Mr Mustard character',
    'Rocky Raccoon fictional raccoon',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Beatles song is about Johns mother? Julia',
    'Julia named for his mother',
    'Martha My Dear dog song',
    'Mother solo John song different',
    'Julian referred in Hey Jude not name',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Beyonce album is Lemonade? Lemonade visual album 2016',
    'The 2016 visual album',
    'Renaissance 2022 dance album',
    'Beyonce 2013 surprise album',
    '4 2011 earlier album',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Beyonce song is Formation? Lemonade opener hit',
    'Formation from Lemonade',
    'Single Ladies from I Am Sasha Fierce',
    'Crazy in Love debut solo',
    'Break My Soul from Renaissance',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Renaissance song broke my soul? Break My Soul',
    'Break My Soul house single',
    'Cuff It funky single',
    'Alien Superstar ballroom track',
    'Church Girl dance track',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Jay-Z album is 4:44? 4:44 confessional album',
    'The 2017 confessional album',
    'The Blueprint classic 2001',
    'The Black Album 2003',
    'Magnolia Carta joint with Beyonce',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which joint album did Jay-Z and Beyonce release? Everything Is Love',
    'Everything Is Love as The Carters',
    'Watch the Throne with Kanye',
    'Collision Course with Linkin Park for Jay',
    'Homecoming live album Beyonce solo',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Watch the Throne duo released it? Jay-Z and Kanye West',
    'The Jay-Z Kanye joint album',
    'The Carters Jay and Bey',
    'Eminem and Royce Bad Meets Evil',
    'Drake and Future mixtapes',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Drake label is OVO? October Very Own his brand',
    'His October Very Own label',
    'YMCMB Young Money parent historic',
    'Epic Records newer deal',
    'Republic Records distributor',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Young Money founder is Lil Wayne? Weezy founded the imprint',
    'Lil Wayne founded Young Money',
    'Birdman Cash Money parent label',
    'Drake signed artist from it',
    'Nicki signed artist from it',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Which Cash Money founders are Birdman and Slim? Ronald and Bryan Williams brothers',
    'The Williams brothers founded Cash Money',
    'Weezy founded Young Money under them',
    'Juvenile Hot Boys artist signed',
    'Mannie Fresh producer in-house',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which No Limit founder is Master P? Percy Miller founder',
    'Percy Master P Miller founded No Limit',
    'Birdman founded Cash Money rival',
    'J Prince Rap-A-Lot Houston founder',
    'Pimp C UGK Port Arthur co-founder',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Which Rap-A-Lot founder is J Prince? James Prince Houston label',
    'James Prince founded Rap-A-Lot',
    'Master P No Limit New Orleans',
    'Birdman Cash Money New Orleans also',
    'DJ Screw screwed music Houston legend different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is chopped and screwed? Houston slowed DJ style by DJ Screw',
    'DJ Screws slowed Houston style',
    'Atlanta trap music different',
    'Memphis phonk newer descendant',
    'Miami bass faster different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is trap music origin city? Atlanta scene mainstream',
    'Atlanta trap mainstream hub',
    'Houston chopped origin different',
    'Memphis underground roots earlier',
    'New York drill newer different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is drill music origin city? Chicago scene then UK NY',
    'Chicago drill then UK drill',
    'Atlanta trap different',
    'Detroit bubblegoth different',
    'LA hyphy different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is hyphy? A Bay Area hip hop movement',
    'The San Francisco Bay Area style',
    'LA jerk movement different',
    'Detroit jit dance different',
    'Miami bass different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is crunk origin? Memphis and Atlanta high energy',
    'Memphis-Atlanta crunk energy genre',
    'Bay hyphy different',
    'Jersey club different',
    'Baltimore club different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Jersey club? A Newark bounce dance music',
    'The Newark bounce club genre',
    'Philly club fast cousin different',
    'Baltimore club foundational cousin',
    'Chicago juke footwork cousin',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is footwork? Chicago fast foot dance music',
    'The 160bpm Chicago dance genre',
    'Jersey club bounce cousin',
    'Detroit juke related earlier',
    'Memphis jitterbug different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is gqom? A Durban raw house genre',
    'The South African Durban sound',
    'Amapiano log drum newer',
    'Kwaito older township',
    'Afrobeat Nigerian different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is amapiano? South African house with log drums',
    'The log drum piano house',
    'Gqom raw predecessor cousin',
    'Kwaito older roots',
    'Champeta Colombian different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is champeta? A Colombian Afro-Caribbean genre',
    'The Colombian Caribbean sound',
    'Cumbia folk different',
    'Vallenato accordion different',
    'Reggaeton Puerto Rican different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is dembow? The Dominican reggaeton rhythm',
    'The boom-ch-boom-chick rhythm pattern',
    'Cumbia rhythm different',
    'Salsa clave different',
    'Merengue quick rhythm different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is moombahton? Dave Nadas EDM reggaeton fusion',
    'The house-reggaeton fusion genre',
    'Dembow original Dominican',
    'Baile funk Brazilian different',
    'Tropical house Kygo style different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is baile funk? A Brazilian favela dance genre',
    'The Rio favela funk style',
    'Champeta Colombian different',
    'Reggaeton different',
    'Samba traditional different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Afrobeats vs Afrobeat difference? Beats plural is modern pop; beat singular is Felas genre',
    'Modern pop versus Felas founding sound',
    'They are identical terms',
    'One is South African only',
    'One is Ghanaian only',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is highlife? A Ghanaian guitar genre',
    'The Ghanaian horn-guitar genre',
    'Mbalax Senegalese different',
    'Soukous Congolese different',
    'Makossa Cameroonian different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is makossa? A Cameroonian dance genre',
    'The Cameroon popular sound',
    'Highlife Ghanaian different',
    'Juju Nigerian different',
    'Fuji Nigerian different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is juju? A Nigerian guitar genre by King Sunny Ade',
    'King Sunny Ades juju sound',
    'Fuji Muslim-rooted different',
    'Afrobeat Fela different',
    'Highlife Ghanaian different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is fuji? A Nigerian Islamic-rooted pop genre',
    'The Yoruba Islamic pop genre',
    'Juju Christian-rooted cousin',
    'Apala older genre different',
    'Sakara older genre different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'What is apala? An older Nigerian Yoruba genre',
    'The traditional Yoruba praise genre',
    'Fuji modernized descendant claim',
    'Juju Christian-rooted',
    'Highlife Ghanaian',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is King Sunny Ade? A juju music legend',
    'The Nigerian juju guitar king',
    'Fela Afrobeat king different',
    'Ebenezer Obey juju rival friendly',
    'Chief Commander Ebenezer Obey band name',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Ebenezer Obey? A juju rival legend',
    'The Chief Commander juju star',
    'Sunny Ade juju peer',
    'Fela Afrobeat critic of Obey',
    'Orlando Owoh older juju-adjacent',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Orlando Owoh? A Nigerian highlife-juju star',
    'The Kenery band highlife star',
    'Sunny Ade juju',
    'Obey juju',
    'Fela Afrobeat',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Osita Osadebe? A Nigerian highlife icon',
    'The highlife crooner icon',
    'Oliver De Coque highlife guitarist',
    'Sir Warrior Oriental Brothers',
    'Rex Lawson historic highlife',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Oliver De Coque? A Nigerian highlife guitarist',
    'The Ogene sound highlife master',
    'Osadebe highlife crooner',
    'Rex Lawson pioneer',
    'Cardinal Rex Jim Lawson same person clarified',
    'expert',
    'Celebrity Facts',
  ],
];

module.exports = { rows };
