'use strict';

const rows = [
  [
    'Who is the Prince of Wales? Prince William',
    'Prince William',
    'Prince Harry the Duke of Sussex',
    'King Charles was Prince of Wales before',
    'Prince George the next generation',
    'easy',
    'Royals',
  ],
  [
    'Who is the Princess of Wales? Kate Middleton',
    'Catherine Princess of Wales',
    'Meghan the Duchess of Sussex',
    'Camilla the Queen Consort',
    'Anne the Princess Royal',
    'easy',
    'Royals',
  ],
  [
    'Who is the Duke of Sussex? Prince Harry',
    'Prince Harry',
    'Prince William Wales',
    'Prince Andrew York',
    'Prince Edward Edinburgh newer',
    'easy',
    'Royals',
  ],
  [
    'Who is Meghan Markle married to? Prince Harry',
    'Prince Harry',
    'Prince William false',
    'False pairing rumors only',
    'Doria Ragland her mother is single',
    'easy',
    'Royals',
  ],
  [
    'Who are William and Harrys parents? Charles and Diana',
    'King Charles and Princess Diana',
    'Philip and Elizabeth grandparents',
    'Camilla stepmother',
    'Doria and Thomas Meghan parents',
    'easy',
    'Royals',
  ],
  [
    'Who is Prince Georges mother? Kate the Princess of Wales',
    'Kate Middleton his mother',
    'Meghan Markle uncle family',
    'Diana late grandmother',
    'Camilla step-grandmother',
    'easy',
    'Royals',
  ],
  [
    'Who is the Princess Royal? Princess Anne',
    'Princess Anne the Queens daughter',
    'Sophie Duchess of Edinburgh',
    'Kate Wales',
    'Beatrice York princess',
    'medium',
    'Royals',
  ],
  [
    'Who is the Duke of Edinburgh now? Prince Edward newer title',
    'Prince Edward received it in 2023',
    'Philip held it until 2021',
    'Andrew stripped',
    'Harry gave it up',
    'hard',
    'Royals',
  ],
  [
    'Who is the Duchess of Edinburgh? Sophie wife of Edward',
    'Sophie',
    'Anne the Princess Royal',
    'Camilla Queen Consort',
    'Katherine Duchess of Kent older',
    'hard',
    'Royals',
  ],
  [
    'Who are the York princesses? Beatrice and Eugenie',
    'Princesses Beatrice and Eugenie',
    'Lady Louise and Zara non-princess titles',
    'Charlotte and Lottie Wales',
    'Margaret and Elizabeth historic',
    'medium',
    'Royals',
  ],
  [
    'Who is Zara Tindall? The Queens granddaughter without a title',
    'Princess Anne daughter no HRH',
    'Beatrice sister cousin York',
    'Louise Wessex daughter',
    'Peter Phillips brother no title',
    'hard',
    'Royals',
  ],
  [
    'Who is Peter Phillips? The Queens eldest grandchild without a title',
    'Annes son no royal title',
    'Zara twin brother false they are siblings',
    'Williams cousin competing',
    'Harrys polo friend',
    'hard',
    'Royals',
  ],
  [
    'Who is Lady Louise Windsor? Edwards daughter',
    'The Wessex Edinburgh daughter',
    'Beatrice York sister false',
    'Zara cousin false',
    'Charlotte Wales sister false',
    'hard',
    'Royals',
  ],
  [
    'Who is the Duchess of York historic? Sarah Ferguson ex-wife of Andrew',
    'Sarah Ferguson formerly married Andrew',
    'Camilla now Queen Consort',
    'Diana late princess',
    'Sophie Edinburgh',
    'medium',
    'Royals',
  ],
  [
    'Who is Princess Beatrices husband? Edoardo Mapelli Mozzi',
    'Edoardo Mapelli Mozzi property man',
    'Jack Brooksbank Eugenie husband',
    'Mike Tindall Zara husband',
    'James Matthews Pippa husband',
    'hard',
    'Royals',
  ],
  [
    'Who is Princess Eugenies husband? Jack Brooksbank',
    'Jack Brooksbank',
    'Edoardo Beatrice husband',
    'Mike Tindall rugby Zara',
    'James Matthews hedge fund Pippa',
    'hard',
    'Royals',
  ],
  [
    'Who is Pippa Middletons husband? James Matthews',
    'James Matthews hedge fund manager',
    'Spencer Matthews reality TV brother',
    'James Middleton her brother',
    'Nico Jackson former boyfriend',
    'hard',
    'Royals',
  ],
  [
    'Who is Pippa Middleton? Kates sister',
    'The Princess of Wales younger sister',
    'Meghans friend via Netflix',
    'Eugenie school friend',
    'Rose Hanbury neighbor marchioness',
    'easy',
    'Royals',
  ],
  [
    'Who is Rose Hanbury? The Marchioness of Cholmondeley',
    'A Norfolk marchioness friend neighbor',
    'Kates stylist personal assistant false',
    'A royal biographer author false',
    'Meghans Canadian friend false',
    'expert',
    'Royals',
  ],
  [
    'Who is Mike Tindall married to? Zara Phillips Tindall',
    'Zara the princess cousin',
    'Eugenie false',
    'Beatrice false',
    'Louise false',
    'medium',
    'Royals',
  ],
  [
    'What sport did Mike Tindall play? Rugby union',
    'Rugby union World Cup winner',
    'Cricket county',
    'Polo professional',
    'Rowing Olympic',
    'medium',
    'Royals',
  ],
  [
    'Who is Camilla Tominey? A royal journalist commentator',
    'A royal correspondent media personality',
    'The Duchess of Cornwall past name confusion',
    'A palace press secretary',
    'A Tatler editor sister',
    'expert',
    'Royals',
  ],
  [
    'Who wrote royal books as a correspondent Omid Scobie? Finding Freedom co-author',
    'The Finding Freedom co-author',
    'Robert Lacey historical Majesty',
    'Tina Brown Palace Papers author',
    'Katie Nicholl royal correspondent',
    'hard',
    'Royals',
  ],
  [
    'What is the Oprah interview year with Harry and Meghan? March 2021',
    'March 2021 CBS interview',
    'January 2020 step-back announcement',
    'April 2022 Invictus visit',
    'September 2022 death month',
    'medium',
    'Royals',
  ],
  [
    'What is the Invictus Games? Harrys veteran sports event',
    'The wounded veterans games Harry founded',
    'Williams soccer charity match',
    'Charlon Earthshot prize different',
    'Sentebale charity Lesotho different',
    'medium',
    'Royals',
  ],
  [
    'What is Earthshot Prize? William environmental prize',
    'Williams five-year environment award',
    'Harrys veterans games different',
    'Charlottes school program none',
    'Anne equestrian award none',
    'medium',
    'Royals',
  ],
  [
    'What is Sentebale? Harrys Lesotho children charity',
    'His charity for Lesotho children',
    'Williams Earthshot different',
    'Kates early years survey different',
    'Meghans Archewell foundation different',
    'hard',
    'Royals',
  ],
  [
    'What is Archewell? Harry and Meghans foundation',
    'Their joint nonprofit and audio company',
    'William Earthshot different',
    'Kates Centre for Early Childhood different',
    'Charlon no such thing',
    'medium',
    'Royals',
  ],
  [
    'What is the Centre for Early Childhood? Kates initiative',
    'Kates early years project',
    'Meghans Archewell different',
    'Camilla reading room different',
    'Annes保存 none skip',
    'medium',
    'Royals',
  ],
  [
    "What is the Queen's Reading Room? Camillas book initiative",
    'Camillas literacy reading project',
    'Kates early years different',
    'Meghans podcast different',
    'Annes riding charity different',
    'hard',
    'Royals',
  ],
  [
    'What is Taylor Swifts partner Travis Kelce team? The Kansas City Chiefs',
    'The Kansas City Chiefs',
    'Philadelphia Eagles brother Jason team',
    'San Francisco 49ers Super Bowl rival',
    'Las Vegas Raiders unrelated',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Jason Kelce? Traviss brother an Eagles center',
    'The Eagles center brother podcast co-host',
    'The Chiefs tight end brother Travis',
    'A retired Packers quarterback false',
    'A Bengals kicker false',
    'medium',
    'Celebrity Couples',
  ],
  [
    'What podcast do the Kelce brothers host? New Heights',
    'The New Heights football podcast',
    'SmartLess actors podcast',
    'Call Her Daddy interview podcast',
    'Hot Ones spicy interview show',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is SmartLess host trio? Bateman, Hayes, and Arnett',
    'Jason Bateman, Sean Hayes, Will Arnett',
    'The Kelce brothers',
    'Joe Rogan solo',
    'Armchair Expert Dax',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who hosts Armchair Expert? Dax Shepard with Monica Padman',
    'Dax Shepard and Monica Padman',
    'SmartLess trio',
    'Marc Maron WTF solo',
    'Anna Faris Unqualified',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who hosts Hot Ones? Sean Evans eating spicy wings',
    'The First We Feast wing interviewer',
    'SmartLess trio',
    'Joe Rogan',
    'Dax Shepard',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Joe Rogan? A podcaster and UFC commentator',
    'The JRE podcast host and UFC voice',
    'Hot Ones host',
    'SNL anchor',
    'Netflix stand-up only',
    'easy',
    'Celebrity Couples',
  ],
  [
    'Who dated Kim Kardashian in 2022 briefly? Pete Davidson',
    'Pete Davidson comedian',
    'Travis Barker drummer married Kourtney',
    'Odell Beckham Jr rumors later',
    'Ray J tape ex past',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Ray J known for in Kardashian history? An early 2000s tape scandal',
    'The infamous early tape partner',
    'Kims first husband producer Damon Thomas',
    'Kris Humphries 72-day husband',
    'Kanye West 2014 husband',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who was Kims first husband? Damon Thomas producer',
    'Music producer Damon Thomas 2000-2004',
    'Kris Humphries 2011 brief',
    'Kanye West 2014-2022',
    'Pete Davidson 2022 fling',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who did Kim marry for 72 days? Kris Humphries',
    'NBA player Kris Humphries 2011',
    'Damon Thomas producer first',
    'Kanye West longer marriage',
    'Reggie Bush early boyfriend',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Blac Chyna connected to? Rob Kardashians ex and Dream mother',
    'Rob Kardashian ex with daughter Dream',
    'Tyga son King Cairo ex',
    'Kylie Tyga later relationship overlap drama',
    'Rapper Game rumors only',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who is Tyga? A rapper and Blac Chyna ex',
    'The rapper ex of Chyna father of King',
    'Kylie ex later relationship',
    'Travis Scott Astroworld false',
    'Drake feud mention only',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Kylie Jenners daughter father? Travis Scott',
    'Rapper Travis Scott daughter Stormi son Aire',
    'Tyga ex previous',
    'Drake rumors false',
    'Timothée false unrelated',
    'medium',
    'Celebrity Couples',
  ],
  [
    'What is Kylie sons name? Aire formerly Wolf',
    'Aire born Wolf changed',
    'Stormi is the daughter',
    'Ranger false',
    'River false',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who is Khloe daughter named? True Thompson',
    'True Thompson',
    'Stormi Kylie daughter',
    'Dream Robs daughter',
    'Chicago Kanye daughter',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Rob Kardashians daughter? Dream Kardashian',
    'Dream with Blac Chyna',
    'True Khloe daughter',
    'North Kim daughter',
    'Penelope Kourtney daughter',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Which Kourtney son is oldest? Mason Disick',
    'Mason the eldest',
    'Penelope middle daughter',
    'Reign youngest son',
    'Rocky new baby with Travis',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Kourtney and Traviss baby? Rocky Thirteen Barker',
    'Rocky Thirteen born 2023',
    'Reign older brother',
    'Mason eldest half-brother',
    'Alabama Traviss daughter step',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who is Travis Barkers stepdaughter? Alabama Barker',
    'Alabama his daughter with Shanna Moakler',
    'Atiana stepdaughter with Oscar De La Hoya',
    'Landon his son with Shanna',
    'Rocky newborn with Kourtney',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who is Atiana De La Hoya? Travis stepdaughter via Shanna',
    'Shannas daughter with boxer Oscar De La Hoya',
    'Travis and Shanna daughter Alabama',
    'Landon his son',
    'Kourtney stepdaughter none',
    'expert',
    'Celebrity Couples',
  ],
  [
    'Who is Shanna Moakler? Travis Barkers ex-wife model',
    'The model ex-wife and mother',
    'Kourtney rival commentary',
    'Oscar De La Hoya ex partner',
    'All true combined statements',
    'hard',
    'Celebrity Couples',
  ],
  [
    'Who is Oscar De La Hoya? The boxing champion',
    'The Golden Boy boxer champion',
    'A soccer legend false',
    'A music producer false',
    'A wrestling promoter false',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Gigi Hadid baby father? Zayn Malik daughter Khai',
    'Zayn Malik with daughter Khai',
    'Joe Jonas false Sophie Turner couple',
    'Zac Efron rumors false',
    'Leonardo party friend false',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Sophie Turner married to historically? Joe Jonas then divorce',
    'The Jonas Brother marriage 2019-2023',
    'Peregrine Pearson newer aristocrat',
    'Taron Egerton rumored false',
    'Kit Harington GoT co-star false',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Kit Haringtons wife? Rose Leslie Ygritte co-star',
    'Rose Leslie his GoT co-star',
    'Emilia Clarke Dany false',
    'Maisie Williams Arya friend',
    'Sophie Turner Sansa sister false',
    'medium',
    'Celebrity Couples',
  ],
  [
    'Who is Emilia Clarkes famous role? Daenerys Targaryen',
    'Daenerys the Mother of Dragons',
    'Sansa Stark Sophie',
    'Margaery Natalie Dormer',
    'Cersei Lena',
    'easy',
    'Celebrity Couples',
  ],
  [
    'Who played Margaery Tyrell? Natalie Dormer',
    'Natalie Dormer',
    'Emilia Clarke Daenerys',
    'Lena Headey Cersei',
    'Nathalie Emmanuel Missandei',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Missandei? Nathalie Emmanuel',
    'Nathalie Emmanuel',
    'Natalie Dormer Margaery',
    'Indira Varma Ellaria',
    'Sibel Kekilli Shae',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Shae in GoT? Sibel Kekilli',
    'Sibel Kekilli',
    'Nathalie Emmanuel Missandei',
    'Indira Varma Ellaria',
    'Keisha Castle-Hughes Obara sand snake',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Oberyn in GoT? Pedro Pascal',
    'Pedro Pascal the Red Viper',
    'Nikolaj Coster-Waldau Jaime',
    'Alfie Allen Theon',
    'Iwan Rheon Ramsay villain',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Ramsay Bolton? Iwan Rheon',
    'Iwan Rheon villain',
    'Pedro Pascal Oberyn',
    'Alfie Allen Theon victim',
    'Tom Wlaschiha Jaqen',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Jaqen Hghar? Tom Wlaschiha',
    'Tom Wlaschiha the Faceless Man',
    'Iwan Rheon Ramsay',
    'Miltos Yerolemou Syrio sword teacher',
    'Kristian Nairn Hodor hold door',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Hodor? Kristian Nairn',
    'Kristian Nairn hold the door',
    'Tom Wlaschiha Jaqen',
    'Rory McCann the Hound',
    'Jerome Flynn Bronn',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played the Hound? Rory McCann',
    'Rory McCann',
    'Jerome Flynn Bronn sellsword',
    'Kristian Nairn Hodor',
    'Ian McShane brief brother ray',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Bronn? Jerome Flynn',
    'Jerome Flynn the sellsword',
    'Rory McCann Hound',
    'Conleth Hill Varys spider',
    'Iain Glen Jorah bears',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Ser Jorah Mormont? Iain Glen',
    'Iain Glen',
    'Jerome Flynn Bronn',
    'Conleth Hill Varys',
    'Julian Glover Grand Maester Pycelle',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Varys? Conleth Hill',
    'Conleth Hill the Master of Whisperers',
    'Iain Glen Jorah',
    'Julian Glover Pycelle',
    'Ian Gelder Kevan Lannister',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Littlefinger? Aidan Gillen',
    'Aidan Gillen chaos ladder',
    'Conleth Hill Varys rival',
    'Charles Dance Tywin lion patriarch',
    'Jack Gleeson Joffrey boy king',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Joffrey? Jack Gleeson',
    'Jack Gleeson the boy king',
    'Aidan Gillen Littlefinger schemer',
    'Dean-Charles Chapman young Tommen brother',
    'Callum Wharry young Tommen first',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Tywin Lannister? Charles Dance',
    'Charles Dance the patriarch',
    'Aidan Gillen Littlefinger',
    'Nikolaj Jaime kingslayer',
    'Peter Dinklage Tyrion imp',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Robert Baratheon? Mark Addy',
    'Mark Addy the fat king',
    'Charles Dance Tywin',
    'Stephen Dillane Stannis brother',
    'Gethin Anthony Renly younger brother',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Stannis Baratheon? Stephen Dillane',
    'Stephen Dillane the rightful king claim',
    'Mark Addy Robert eldest',
    'Gethin Anthony Renly youngest',
    'Liam Cunningham Davos onion knight',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Davos Seaworth? Liam Cunningham',
    'Liam Cunningham the onion knight',
    'Stephen Dillane Stannis king he served',
    'Carice van Houten Melisandre priestess',
    'Kerry Ingram Shireen daughter',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Melisandre? Carice van Houten',
    'Carice van Houten the red woman',
    'Liam Cunningham Davos rival believer',
    'Kerry Ingram Shireen her sad case',
    'Charlotte Hope Mya? no she was Myrcella game',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Shireen Baratheon? Kerry Ingram',
    'Kerry Ingram the princess with greyscale cured',
    'Carice van Houten Melisandre cause of doom',
    'Nell Tiger Free Myrcella recast',
    'Aimee Richardson Myrcella original',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Myrcella recast? Nell Tiger Free',
    'Nell Tiger Free replaced Aimee Richardson',
    'Aimee Richardson original casting',
    'Kerry Ingram Shireen different role',
    'Isaac Hempstead Wright Bran different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Bran Stark? Isaac Hempstead Wright',
    'Isaac Hempstead Wright the Three-Eyed Raven king',
    'Rory McCann unrelated Hound',
    'Alfie Allen Theon ward',
    'Art Parkinson Rickon youngest brother',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Rickon Stark? Art Parkinson',
    'Art Parkinson the youngest brother',
    'Isaac Bran older brother',
    'Maisie Arya sister',
    'Sophie Sansa eldest sister',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Ygritte? Rose Leslie',
    'Rose Leslie you know nothing',
    'Natalie Dormer Margaery',
    'Emilia Clarke Daenerys',
    'Maisie Williams Arya no one',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Brienne of Tarth? Gwendoline Christie',
    'Gwendoline Christie the sworn shield',
    'Rose Leslie Ygritte wildling',
    'Natalia Tena Osha wildling',
    'Ellie Kendrick Meera Reed crannog',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Osha? Natalia Tena',
    'Natalia Tena the wildling nanny',
    'Ellie Kendrick Meera',
    'Gwendoline Christie Brienne',
    'Rose Leslie Ygritte',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who played Meera Reed? Ellie Kendrick',
    'Ellie Kendrick',
    'Natalia Tena Osha',
    'Kae Alexander Leaf child of forest',
    'Octavia Selman Alexandru none',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Jaqens fellow Faceless Waif? Faye Marsay the Waif',
    'Faye Marsay trained Arya harshly',
    'Ellie Kendrick Meera travel',
    'Natalia Tena Osha early',
    'Charlotte Hope Myrcella original',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Missandei again confirm? Nathalie Emmanuel',
    'Nathalie Emmanuel',
    'Faye Marsay Waif',
    'Indira Varma Ellaria',
    'Jessica Henwick Nymeria Sand actor separate',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who played Nymeria Sand? Jessica Henwick',
    'Jessica Henwick one of the Sand Snakes',
    'Rosabell Laurenti Sellers Tyene sand snake',
    'Keisha Castle-Hughes Obara sand snake',
    'Indira Varma Ellaria mother',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Ellaria Sand? Indira Varma',
    'Indira Varma Oberyns paramour',
    'Jessica Henwick daughter Nymeria',
    'Rosabell Sellers Tyene daughter',
    'Keisha Castle-Hughes Obara daughter',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Olenna Tyrell? Diana Rigg',
    'Diana Rigg the Queen of Thorns',
    'Natalie Dormer Margaery granddaughter',
    'Dame Maggie Smith different icon',
    'Fiona Shaw different actress',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Maester Pycelle? Julian Glover',
    'Julian Glover the old maester',
    'Conleth Hill Varys rival spymaster',
    'Ian McElhinney Barristan barristan the bold',
    'Ron Donachie Ser Rodrik winterfell master',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Barristan Selmy? Ian McElhinney',
    'Ian McElhinney the bold barristan',
    'Julian Glover Pycelle maester',
    'Ron Donachie Rodrik cassel',
    'James Cosmo Jeor mormont lord commander',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Jeor Mormont Lord Commander? James Cosmo',
    'James Cosmo the nights watch leader',
    'Ian McElhinney Barristan kings guard',
    'Ron Donachie Rodrik winterfell',
    'Ciaran Halm Qyburn necromancer',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Qyburn? Anton Lesser',
    'Anton Lesser the necromancer hand at end',
    'Julian Glover Pycelle poisoned',
    'Ciaran Hinds Mance king beyond wall',
    'Owen Teale Alliser thorne rival',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Mance Rayder? Ciaran Hinds',
    'Ciaran Hinds the king beyond the wall',
    'Anton Lesser Qyburn maester',
    'James Cosmo Mormont bear island',
    'Mackenzie Davis none skip',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who played Ygritte again? Rose Leslie',
    'Rose Leslie wildling archer wife',
    'Carice van Houten Melisandre fire',
    'Natalia Tena Osha spearwife',
    'Ellie Kendrick Meera crannog',
    'easy',
    'Celebrity Facts',
  ],
];

module.exports = { rows };
