'use strict';

const rows = [
  [
    'Who is Bad Bunny? A Puerto Rican reggaeton superstar',
    'The Puerto Rican streaming giant',
    'A Colombian reggaeton rival',
    'A Mexican banda star',
    'A Dominican dembow artist',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Karol G? A Colombian reggaeton star',
    'The Colombian Bichota singer',
    'A Puerto Rican star',
    'A Dominican star',
    'A Mexican pop star',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Rosalia? A Spanish flamenco-pop innovator',
    'The Catalan fusion star',
    'A Colombian star',
    'A Mexican star',
    'A Portuguese fado star',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Burna Boy? A Nigerian afrofusion star',
    'The Nigerian afrofusion headliner',
    'A Ghanaian star',
    'A South African star',
    'A Kenyan star',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Wizkid? A Nigerian afrobeats star',
    'The Starboy Nigerian hitmaker',
    'A Ghanaian star',
    'A Tanzanian bongo star',
    'A South African amapiano star',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Davido? A Nigerian afrobeats star',
    'The DMW Nigerian hitmaker',
    'A Ghanaian star',
    'A Cameroonian star',
    'An Ivorian star',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Tems? A Nigerian singer with global features',
    'The Nigerian alt-R&B voice',
    'A Ghanaian singer',
    'A South African singer',
    'A Kenyan singer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Rema? A Nigerian afrobeats young star',
    'The Calm Down Nigerian hitmaker',
    'A Ghanaian young star',
    'A Tanzanian young star',
    'A South African young star',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Calm Down by Rema remixed with? Selena Gomez',
    'A Selena Gomez remix smash',
    'A Camila remix',
    'A Dua remix',
    'A Tate remix',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Asake? A Nigerian amapiano-infused star',
    'The Yoruba amapiano hitmaker',
    'A Ghanaian star',
    'A Dominican star',
    'A Colombian star',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Ayra Starr? A Nigerian singer signed to Mavin',
    'The Mavin Records sunglasses singer',
    'A Ghanaian singer',
    'A Beninese singer',
    'A Togolese singer',
    'hard',
    'Celebrity Facts',
  ],
  [
    "What is Mavin Records? Don Jazzy's Nigerian label",
    "Don Jazzy's Nigerian record label",
    "YBNL Olamide's label",
    "Starboy Wizkid's label",
    "DMW Davido's label",
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Olamide? A Nigerian rap star label boss',
    'The YBNL street rap boss',
    'Davido DMW boss',
    'Don Jazzy Mavin boss',
    'Wizkid Starboy boss',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Fireboy DML? A Nigerian afrolife singer',
    'The Peru singer on YBNL',
    'A Mavin singer',
    'A Starboy singer',
    'A DMW singer',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Peru by Fireboy remixed with? Ed Sheeran',
    'An Ed Sheeran remix',
    'A Selena remix',
    'A Dua remix',
    'A Camila remix',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is CKay? A Nigerian singer of Love Nwantintin',
    'The Love Nwantintin viral singer',
    'A Ghanaian viral singer',
    'A Tanzanian viral singer',
    'A South African viral singer',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Joeboy? A Nigerian emPawa singer',
    'The emPawa Nigerian singer',
    'A Mavin singer',
    'A YBNL singer',
    'A Starboy singer',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Kizz Daniel? A Nigerian singer of Buga',
    'The Buga Nigerian hitmaker',
    'A Ghanaian hitmaker',
    'A Tanzanian hitmaker',
    'A Ugandan hitmaker',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Tekno? A Nigerian singer of Pana',
    'The Pana Nigerian singer',
    'A Ghanaian singer',
    'A Cameroonian singer',
    'An Ivorian singer',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is Yemi Alade? A Nigerian Mama Africa singer',
    'The Johnny singer Mama Africa',
    'A Ghanaian singer',
    'A Tanzanian singer',
    'A Congolese singer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Tiwa Savage? A Nigerian queen of afrobeats',
    'The female afrobeats queen',
    'A Ghanaian queen',
    'A South African queen',
    'A Kenyan queen',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Angelique Kidjo? A Beninese Grammy-winning singer',
    'The Beninese five-time Grammy winner',
    'A Nigerian Grammy winner',
    'A South African Grammy winner',
    'A Ghanaian Grammy winner',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Trevor Noah? A South African comedian and host',
    'The Daily Show South African host',
    'A Nigerian comedian host',
    'A Kenyan host',
    'A Ghanaian host',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is Lupita Nyongo? A Kenyan-Mexican Oscar winner',
    'The 12 Years a Slave Oscar winner',
    'A Nigerian Oscar winner',
    'A South African Oscar winner',
    'A Ghanaian Oscar winner',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Daniel Kaluuya? A British-Ugandan Oscar winner',
    'The Get Out Oscar-winning actor',
    'A Nigerian-British actor',
    'A Ghanaian-British actor',
    'A Kenyan-British actor',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is David Oyelowo? A British-Nigerian actor of Selma',
    'The Selma MLK portrayer',
    'A Get Out actor different',
    'A Moonlight actor different',
    'A Judas actor different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Chiwetel Ejiofor? A British-Nigerian actor of 12 Years',
    'The Solomon Northup actor',
    'The Selma MLK actor different',
    'The Get Out lead different',
    'The Judas lead different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is John Boyega? A British-Nigerian Star Wars actor',
    'The Finn actor in Star Wars',
    'The Get Out actor different',
    'The Black Panther villain different',
    'The Judas actor different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Letitia Wright? A Guyanese-British Black Panther actress',
    'The Shuri actress',
    'The Nakia actress different',
    'The Okoye actress different',
    'The Ramonda actress different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Danai Gurira? A Zimbabwean-American actress of Okoye',
    'The Okoye Dora Milaje general actress',
    'The Shuri actress different',
    'The Nakia actress different',
    'The Ramonda actress different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Sonequa Martin-Green? A Star Trek Discovery lead actress',
    'The Discovery captain Burnham actress',
    'The Okoye actress different',
    'The Mandalorian actress Gina Carano removed',
    'The Acolyte lead newer',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Gina Carano? A former MMA fighter actress removed from Star Wars',
    'The Cara Dune actress let go',
    'The Bo-Katan actress different',
    'The Fennec Shand actress different',
    'The Ahsoka actress Rosario',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Rosario Dawson in Star Wars? The Ahsoka actress',
    'The Ahsoka Tano live-action actress',
    'The Cara Dune actress different',
    'The Bo-Katan actress different',
    'The Fennec actress different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Katee Sackhoff in Star Wars? The Bo-Katan actress',
    'The Bo-Katan Mandalorian actress',
    'The Ahsoka actress different',
    'The Fennec actress different',
    'The Hera Syndulla voice actress',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Ming-Na Wen in Star Wars? The Fennec Shand actress',
    'The Fennec Shand bounty actress',
    'The Bo-Katan actress different',
    'The Ahsoka actress different',
    'The Sabine actress newer different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is Natasha Liu Bordizzo in Ahsoka? The Sabine Wren actress',
    'The Sabine Wren live-action actress',
    'The Hera actress different',
    'The Ahsoka lead different',
    'The Baylan actor different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who is the late Ray Stevenson in Ahsoka? The Baylan Skoll actor',
    'The Baylan Skoll actor passed after filming',
    'The Sabine actor different',
    'The Hera actress different',
    'The Thrawn actor Lars Mikkelsen different',
    'expert',
    'Celebrity Facts',
  ],
  [
    'Who played Thrawn in Ahsoka? Lars Mikkelsen',
    'The animated Thrawn voice actor live action',
    'Ray Stevenson Baylan different',
    'Ian McDiarmid Palpatine different',
    'Timothy Zahn Thrawn author different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who wrote the Thrawn novels? Timothy Zahn',
    'Timothy Zahn the author',
    'Lars Mikkelsen the actor',
    'Dave Filoni the producer',
    'Jon Favreau the producer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is Dave Filoni? A Star Wars producer director',
    'The Clone Wars Rebels Ahsoka producer',
    'The Thrawn novelist different',
    'The Mandalorian lead actor different',
    'The Lucasfilm president Kathleen Kennedy different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Lucasfilm president? Kathleen Kennedy',
    'Kathleen Kennedy the producer president',
    'Dave Filoni newer chief creative officer',
    'Jon Favreau producer-director',
    'Bob Iger Disney CEO different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Disney CEO? Bob Iger',
    'Bob Iger returned as CEO',
    'Bob Chapek replaced by Iger',
    'Kathleen Kennedy Lucasfilm only',
    'Reed Hastings Netflix different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Netflix co-CEO with Ted Sarandos? Greg Peters newer co-CEO',
    'Greg Peters with Sarandos',
    'Reed Hastings founder executive chairman',
    'Marc Randolph co-founder left early',
    'Bela Bajaria content chief newer',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who is the Netflix founder? Reed Hastings with Marc Randolph',
    'Reed Hastings and Marc Randolph founded',
    'Ted Sarandos joined later content',
    'Greg Peters newer co-CEO',
    'David Wells former CFO',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Amazon founder? Jeff Bezos',
    'Jeff Bezos founded Amazon',
    'Andy Jassy CEO now AWS then Amazon',
    'Marc Onetto operations none skip',
    'MacKenzie Scott ex-wife philanthropist',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the Amazon CEO? Andy Jassy',
    'Andy Jassy since 2021',
    'Jeff Bezos executive chair now',
    'Werner Vogels CTO',
    'Shirish sanskar none skip',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Microsoft CEO? Satya Nadella',
    'Satya Nadella since 2014',
    'Bill Gates founder chair history',
    'Steve Ballmer ex-CEO Clippers owner',
    'Paul Allen late co-founder',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the Apple CEO? Tim Cook',
    'Tim Cook since 2011',
    'Steve Jobs founder late 2011',
    'John Sculley 80s CEO history',
    'Jony Ive design chief departed',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the Meta CEO? Mark Zuckerberg',
    'Mark Zuckerberg founder CEO',
    'Sheryl Sandberg former COO departed',
    'Andrew Bosworth CTO',
    'Nick Clegg policy president',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the Tesla CEO? Elon Musk',
    'Elon Musk CEO since 2008',
    'Martin Eberhard original founder CEO',
    'JB Straubel former CTO',
    'Robyn Denholm board chair',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the Nvidia CEO? Jensen Huang',
    'Jensen Huang leather jacket CEO',
    'Lisa Su AMD CEO cousin relation',
    'Pat Gelsinger Intel CEO different',
    'Sundar Pichai Google CEO different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the AMD CEO? Lisa Su',
    'Lisa Su Jensen Huangs niece relation',
    'Jensen Huang Nvidia CEO cousin',
    'Pat Gelsinger Intel different',
    'Satya Nadella Microsoft different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Intel CEO? Pat Gelsinger',
    'Pat Gelsinger returned 2021',
    'Lisa Su AMD rival CEO',
    'Jensen Huang Nvidia CEO',
    'Bob Swan predecessor CEO',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Google CEO? Sundar Pichai',
    'Sundar Pichai CEO of Google and Alphabet',
    'Larry Page Alphabet co-founder stepped back',
    'Sergey Brin co-founder stepped back',
    'Ruth Porat CFO president',
    'easy',
    'Celebrity Facts',
  ],
  [
    'Who is the YouTube CEO listed 2023? Neal Mohan',
    'Neal Mohan took over from Wojcicki',
    'Susan Wojcicki stepped down 2023',
    'Sundar Pichai Google CEO over all',
    'Robert Kyncl WMG different industry',
    'hard',
    'Celebrity Facts',
  ],
  [
    'Who was the long-time YouTube CEO? Susan Wojcicki',
    'Susan Wojcicki led YouTube nearly a decade',
    'Neal Mohan successor 2023',
    'Sheryl Sandberg Facebook COO different',
    'Marissa Mayer Yahoo different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the OpenAI CEO? Sam Altman',
    'Sam Altman fired then reinstated 2023',
    'Greg Brockman president cofounder',
    'Mira Murati CTO interim moment',
    'Ilya Sutskever chief scientist departed later',
    'medium',
    'Celebrity Facts',
  ],
  [
    'Who is the Tesla robotics humanoid? Optimus by Tesla',
    'The Optimus humanoid robot',
    'Atlas by Boston Dynamics different',
    'ASIMO by Honda retired',
    'Pepper by SoftBank different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Boston Dynamics famous robot? Atlas the parkour humanoid',
    'The Atlas parkour robot',
    'Optimus Tesla different',
    'Pepper SoftBank retail different',
    'Spot the dog robot also theirs',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Spot? Boston Dynamics robot dog',
    'The quadruped Spot robot dog',
    'Atlas humanoid different',
    'BigDog earlier quadruped prototype',
    'Cheetah faster quadruped experiment',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Atlas by Boston Dynamics? A parkour humanoid robot',
    'The famous parkour humanoid',
    'A robot dog different Spot',
    'A drone fleet different',
    'A chess computer different',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Pepper by SoftBank? A retail service robot',
    'The friendly retail humanoid',
    'A robot dog different',
    'A humanoid Atlas different',
    'A chat app different',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is ASIMO? A retired Honda humanoid robot',
    'The retired Honda walking robot',
    'The Tesla humanoid Optimus',
    'The Boston Dynamics Atlas',
    'The Sony Aibo dog',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Aibo? A Sony robot dog',
    'The robotic pet dog from Sony',
    'The Honda humanoid ASIMO',
    'The Boston dog Spot',
    'The Parrot drone',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Parrot in drones? A French drone maker',
    'The French consumer drone maker',
    'The Chinese market leader DJI',
    'The US Skydio autonomy firm',
    'The Israeli military drone firm',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is Skydio known for? US autonomous drones',
    'The American autonomy drone firm',
    'The French drone maker Parrot',
    'The Chinese leader DJI',
    'The Israeli defense drones',
    'hard',
    'Celebrity Facts',
  ],
  [
    'What is DJI known for? Leading consumer drones',
    'The dominant Chinese drone maker',
    'The US autonomy firm Skydio',
    'The French maker Parrot',
    'The Korean maker none',
    'easy',
    'Celebrity Facts',
  ],
  [
    'What is GoPro known for? Action cameras',
    'The rugged action camera brand',
    'A drone maker different',
    'A phone brand different',
    'A headphone brand different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'What is Garmin known for? GPS watches and navigation',
    'The GPS watch navigation brand',
    'A camera brand different',
    'A drone brand different',
    'A laptop brand different',
    'easy',
    'Celebrity Facts',
  ],
  [
    'What is Fitbit owned by? Google',
    'Google acquired the tracker brand',
    'Apple',
    'Samsung',
    'Amazon',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Whoop? A screenless fitness tracker',
    'The subscription fitness band',
    'A smart scale',
    'A smart ring rival',
    'A bike computer',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is the Oura Ring? A smart health ring',
    'The sleep-tracking smart ring',
    'A fitness band wrist',
    'A smartwatch',
    'A hearing aid',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Peloton? An connected fitness bike company',
    'The interactive spin bike brand',
    'A treadmill only brand',
    'A gym chain',
    'A yoga app',
    'easy',
    'Celebrity Facts',
  ],
  [
    'What is Zwift? A virtual cycling app',
    'The indoor cycling game platform',
    'A running shoe brand',
    'A bike maker hardware',
    'A nutrition app',
    'medium',
    'Celebrity Facts',
  ],
  [
    'What is Strava club? Skip duplicate: What is duolingo owl name? Duo the owl mascot',
    'Duo the green owl mascot',
    'Ping the panda mascot',
    'Kiko the koala mascot',
    'Lila the lizard mascot',
    'medium',
    'Celebrity Facts',
  ],
];

module.exports = { rows };
