'use strict';

// Extra flat bank for Technology & Video Games.
const rows = [
  [
    'Which studio makes FIFA now EA Sports FC?',
    'EA Sports',
    'Konami',
    '2K Games',
    'Ubisoft',
    'easy',
    'Games',
  ],
  [
    'Which Konami series succeeded PES?',
    'eFootball',
    'Football Manager',
    'FIFA',
    'Pro Evo 2020',
    'medium',
    'Games',
  ],
  ['Which NBA series is 2K?', 'NBA 2K', 'NBA Live', 'NBA Jam', 'NBA Street', 'medium', 'Games'],
  [
    'Which skating series got a 1+2 remaster?',
    'Tony Hawks Pro Skater',
    'Skate',
    'SSX',
    'OlliWorld',
    'medium',
    'Games',
  ],
  [
    'Which farming game dominated early Facebook?',
    'FarmVille',
    'Words with Friends',
    'Mafia Wars',
    'Draw Something',
    'medium',
    'Games',
  ],
  [
    'Which word game by Zynga pairs friends?',
    'Words with Friends',
    'FarmVille',
    'Draw Something',
    'Scrabble GO',
    'medium',
    'Games',
  ],
  [
    'Which learning platform runs live quizzes?',
    'Kahoot',
    'Quizlet',
    'Anki',
    'Duolingo',
    'medium',
    'Games',
  ],
  [
    'Which flashcard platform is Quizlet?',
    'Quizlet',
    'Anki',
    'Kahoot',
    'Brainscape',
    'medium',
    'Games',
  ],
  [
    'Which spaced repetition app is Anki?',
    'Anki',
    'Quizlet',
    'Memrise',
    'SuperMemo',
    'hard',
    'Games',
  ],
  [
    'Which 2D sandbox has bosses and building?',
    'Terraria',
    'Minecraft',
    'Starbound',
    'Dont Starve',
    'easy',
    'Games',
  ],
  [
    'Which Klei gothic survival is Dont Starve?',
    'Dont Starve',
    'The Long Dark',
    'Grounded',
    'Subnautica',
    'medium',
    'Games',
  ],
  [
    'Which underwater survival game is Subnautica?',
    'Subnautica',
    'The Forest',
    'Raft',
    'Stranded Deep',
    'easy',
    'Games',
  ],
  [
    'Which cold Canadian survival is The Long Dark?',
    'The Long Dark',
    'Dont Starve',
    'Frostpunk',
    'This War of Mine',
    'medium',
    'Games',
  ],
  [
    'Which society survival city is Frostpunk?',
    'Frostpunk',
    'Cities Skylines',
    'Anno',
    'Tropico',
    'medium',
    'Games',
  ],
  [
    'Which civilian war survival is This War of Mine?',
    'This War of Mine',
    'Frostpunk',
    'Spec Ops the Line',
    'Valiant Hearts',
    'medium',
    'Games',
  ],
  [
    'Which modern city builder is Cities Skylines?',
    'Cities Skylines',
    'SimCity 2013',
    'Anno 1800',
    'Tropico 6',
    'easy',
    'Games',
  ],
  [
    'Which island dictator sim is Tropico?',
    'Tropico',
    'Cities Skylines',
    'Anno',
    'Rise of Nations',
    'medium',
    'Games',
  ],
  [
    'Which historical trade builder is Anno?',
    'Anno',
    'Tropico',
    'Civilization',
    'Total War',
    'hard',
    'Games',
  ],
  [
    'Which Creative Assembly strategy hybrid is Total War?',
    'Total War',
    'Age of Empires',
    'StarCraft',
    'Civilization',
    'medium',
    'Games',
  ],
  [
    'Which 4X turn-based is Civilization?',
    'Civilization',
    'Total War',
    'Age of Wonders',
    'Endless Legend',
    'medium',
    'Games',
  ],
  [
    'Which Paradox space grand strategy is Stellaris?',
    'Stellaris',
    'Endless Space',
    'Galactic Civilizations',
    'Distant Worlds',
    'easy',
    'Games',
  ],
  [
    'Which Paradox WWII strategy is Hearts of Iron?',
    'Hearts of Iron IV',
    'EU4',
    'CK3',
    'Victoria 3',
    'medium',
    'Games',
  ],
  [
    'Which Paradox medieval dynasty sim is Crusader Kings?',
    'Crusader Kings III',
    'HOI4',
    'EU4',
    'Victoria 3',
    'medium',
    'Games',
  ],
  [
    'Which Paradox early-modern game is EU4?',
    'Europa Universalis IV',
    'HOI4',
    'CK3',
    'Victoria 3',
    'medium',
    'Games',
  ],
  [
    'Which Rockstar western is Red Dead Redemption?',
    'Red Dead Redemption',
    'GTA',
    'Bully',
    'Max Payne',
    'easy',
    'Games',
  ],
  ['Which Rockstar school game is Bully?', 'Bully', 'GTA', 'RDR', 'LA Noire', 'medium', 'Games'],
  [
    'Which Team Bondi detective game did Rockstar publish?',
    'L.A. Noire',
    'Max Payne',
    'Red Dead Revolver',
    'The Warriors',
    'hard',
    'Games',
  ],
  [
    'Which Remedy noir bullet-time game is Max Payne?',
    'Max Payne',
    'Alan Wake',
    'Control',
    'Quantum Break',
    'medium',
    'Games',
  ],
  [
    'Which Remedy writer thriller is Alan Wake?',
    'Alan Wake',
    'Max Payne',
    'Control',
    'Quantum Break',
    'medium',
    'Games',
  ],
  [
    'Which Remedy Oldest House game is Control?',
    'Control',
    'Alan Wake',
    'CrossfireX',
    'Firebreak',
    'medium',
    'Games',
  ],
  [
    'Which Quantic Dream rain origami game is Heavy Rain?',
    'Heavy Rain',
    'Beyond Two Souls',
    'Detroit',
    'Fahrenheit',
    'medium',
    'Games',
  ],
  [
    'Which Quantic Dream android game is Detroit?',
    'Detroit Become Human',
    'Heavy Rain',
    'Beyond Two Souls',
    'Star Wars Eclipse',
    'medium',
    'Games',
  ],
  [
    'Which Telltale season won 2012 GOTY?',
    'The Walking Dead S1',
    'The Wolf Among Us',
    'Borderlands',
    'Batman',
    'medium',
    'Games',
  ],
  [
    'Which Telltale Fables noir is Wolf Among Us?',
    'The Wolf Among Us',
    'Walking Dead',
    'Borderlands',
    'Batman',
    'medium',
    'Games',
  ],
  [
    'Which Dontnod rewind game is Life is Strange?',
    'Life is Strange',
    'Vampyr',
    'Tell Me Why',
    'Jusant',
    'medium',
    'Games',
  ],
  [
    'Which Dontnod vampire RPG is Vampyr?',
    'Vampyr',
    'Life is Strange',
    'Tell Me Why',
    'Twin Mirror',
    'hard',
    'Games',
  ],
  [
    'Which Campo Santo tower game is Firewatch?',
    'Firewatch',
    'Valley of Gods',
    'Edith Finch',
    'Gone Home',
    'medium',
    'Games',
  ],
  [
    'Which Fullbright house story is Gone Home?',
    'Gone Home',
    'Firewatch',
    'Edith Finch',
    'Tacoma',
    'medium',
    'Games',
  ],
  [
    'Which Giant Sparrow finch game is Edith Finch?',
    'What Remains of Edith Finch',
    'Gone Home',
    'Firewatch',
    'Unfinished Swan',
    'hard',
    'Games',
  ],
  [
    'Which Fullbright space station game is Tacoma?',
    'Tacoma',
    'Gone Home',
    'Edith Finch',
    'Prey',
    'expert',
    'Games',
  ],
  [
    'Which Arkane station immersive sim is Prey?',
    'Prey 2017',
    'System Shock',
    'Bioshock',
    'Dead Space',
    'medium',
    'Games',
  ],
  [
    'Which Arkane vampire co-op is Redfall?',
    'Redfall',
    'Deathloop',
    'Dishonored',
    'Prey',
    'medium',
    'Games',
  ],
  [
    'Which Arkane time loop is Deathloop?',
    'Deathloop',
    'Prey',
    'Dishonored',
    'Redfall',
    'medium',
    'Games',
  ],
  [
    'Which Arkane whalepunk stealth is Dishonored?',
    'Dishonored',
    'Prey',
    'Deathloop',
    'Redfall',
    'easy',
    'Games',
  ],
  [
    'Which MachineGames reimagined Wolfenstein?',
    'The New Order',
    'Return to Castle Wolfenstein',
    'Wolfenstein 3D',
    'Youngblood',
    'medium',
    'Games',
  ],
  [
    'Which id classic defined FPS in 1993?',
    'Doom',
    'Wolfenstein 3D',
    'Quake',
    'Heretic',
    'easy',
    'Games',
  ],
  [
    'Which id 1996 game brought true 3D?',
    'Quake',
    'Doom',
    'Duke Nukem 3D',
    'Half-Life',
    'medium',
    'Games',
  ],
  [
    'Which Build engine hero said groovy?',
    'Duke Nukem 3D',
    'Doom',
    'Blood',
    'Shadow Warrior',
    'medium',
    'Games',
  ],
  [
    'Which Nightdive studio remasters System Shock?',
    'Nightdive Studios',
    'Bluepoint',
    'Virtuos',
    'Aspyr',
    'expert',
    'Games',
  ],
  [
    'Which Bluepoint remake is Demons Souls?',
    'The PS5 remake',
    'Shadow of the Colossus',
    'Uncharted Legacy',
    'Bloodborne none',
    'hard',
    'Games',
  ],
  [
    'Which FromSoftware game started soulslikes?',
    'Demons Souls',
    'Dark Souls',
    'Sekiro',
    'Elden Ring',
    'medium',
    'Games',
  ],
  [
    'Which Team Ninja soulslike is Nioh?',
    'Nioh',
    'Sekiro',
    'Stranger of Paradise',
    'Rise of Ronin',
    'medium',
    'Games',
  ],
  [
    'Which Team Ninja FF spinoff is Stranger of Paradise?',
    'Stranger of Paradise',
    'Nioh',
    'Wo Long',
    'Rise of Ronin',
    'hard',
    'Games',
  ],
  [
    'Which Team Ninja Three Kingdoms game is Wo Long?',
    'Wo Long Fallen Dynasty',
    'Nioh',
    'Stranger of Paradise',
    'Dynasty Warriors',
    'hard',
    'Games',
  ],
  [
    'Which Koei musou crowd series is Dynasty Warriors?',
    'Dynasty Warriors',
    'Samurai Warriors',
    'Hyrule Warriors',
    'Fire Emblem Warriors',
    'easy',
    'Games',
  ],
  [
    'Which Zelda musou crossover is Hyrule Warriors?',
    'Hyrule Warriors',
    'Dynasty Warriors',
    'Fire Emblem Warriors',
    'Persona Strikers',
    'easy',
    'Games',
  ],
  [
    'Which Persona musou is Strikers?',
    'Persona 5 Strikers',
    'Persona 4 Arena',
    'Persona Q',
    'P3 Reload',
    'medium',
    'Games',
  ],
  [
    'Which Atlus chibi dungeon crawler is Persona Q?',
    'Persona Q',
    'Strikers',
    'Dancing games',
    'P4 Golden',
    'expert',
    'Games',
  ],
  [
    'Which Atlus improved P4 port is Golden?',
    'Persona 4 Golden',
    'P3 Reload',
    'P5 Royal',
    'Persona 2',
    'medium',
    'Games',
  ],
  [
    'Which studio makes Cyberpunk 2077 sequel studio same? CD Projekt Red again',
    'CD Projekt Red',
    'Fool Theory supporting',
    'Techland Dying Light',
    'Bloober Silent Hill 2 remake',
    'easy',
    'Games',
  ],
  [
    'Which Bloober remake is Silent Hill 2? The Silent Hill 2 Remake 2024',
    'Silent Hill 2 Remake',
    'Resident Evil remakes Capcom',
    'Dead Space Motive',
    'Alan Wake Remastered',
    'medium',
    'Games',
  ],
  [
    'Which Motive remake is Dead Space? Dead Space Remake 2023',
    'Dead Space Remake',
    'Silent Hill 2 Bloober',
    'RE4 Capcom',
    'System Shock Nightdive',
    'medium',
    'Games',
  ],
  [
    'Which Capcom remake is RE4? Resident Evil 4 Remake 2023',
    'Resident Evil 4 Remake',
    'RE2 Remake 2019',
    'RE3 Remake 2020',
    'Code Veronica none yet',
    'medium',
    'Games',
  ],
  [
    'Which Capcom remake is RE2? Resident Evil 2 Remake 2019',
    'Resident Evil 2 Remake',
    'RE3 Remake',
    'RE4 Remake',
    'RE7 new era',
    'easy',
    'Games',
  ],
  [
    'Which sci-fi horror is Dead Space hero Isaac Clarke? Dead Space',
    'Dead Space with Isaac Clarke',
    'Prey Morgan Yu',
    'Bioshock Booker',
    'System Shock Hacker',
    'medium',
    'Games',
  ],
  [
    'Which Bioshock city is Rapture? Bioshock underwater',
    'Rapture underwater',
    'Columbia flying Infinite',
    'Talos I Prey station',
    'Dunwall Dishonored',
    'easy',
    'Games',
  ],
  [
    'Which Bioshock flying city is Columbia? Bioshock Infinite',
    'Columbia in Infinite',
    'Rapture original',
    'S-link separate',
    'Yharnam Bloodborne gothic',
    'medium',
    'Games',
  ],
  [
    'Which FromSoftware gothic city is Yharnam? Bloodborne',
    'Bloodborne Yharnam',
    'Dark Souls Lordran',
    'Elden Ring Lands Between',
    'Demons Souls Boletaria',
    'medium',
    'Games',
  ],
  [
    'Which FromSoftware land is the Lands Between? Elden Ring',
    'Elden Ring Lands Between',
    'Bloodborne Yharnam',
    'Dark Souls Lordran',
    'Demons Boletaria',
    'easy',
    'Games',
  ],
  [
    'Which FromSoftware kingdom is Lordran? Dark Souls',
    'Dark Souls Lordran',
    'Elden Ring Lands Between',
    'Bloodborne Yharnam',
    'Demons Boletaria',
    'medium',
    'Games',
  ],
  [
    'Which Taito shooter launched 1978 arcade boom? Space Invaders',
    'Space Invaders',
    'Pac-Man 1980 maze',
    'Asteroids Atari vector 1979',
    'Galaxian Namco 1979',
    'easy',
    'Games',
  ],
  [
    'Which Namco maze icon launched 1980? Pac-Man',
    'Pac-Man',
    'Space Invaders Taito',
    'Donkey Kong Nintendo 1981',
    'Galaga 1981',
    'easy',
    'Games',
  ],
  [
    'Which Nintendo arcade introduced Mario as Jumpman? Donkey Kong',
    'Donkey Kong',
    'Mario Bros 1983',
    'Super Mario Bros 1985',
    'Punch-Out arcade',
    'medium',
    'Games',
  ],
  [
    'Which vector Atari shooter 1979? Asteroids',
    'Asteroids',
    'Space Invaders Taito',
    'Battlezone tanks 1980',
    'Tempest 1981',
    'medium',
    'Games',
  ],
  [
    'Which Atari tank vector game 1980 used 3D wireframes? Battlezone',
    'Battlezone',
    'Asteroids rocks',
    'Tempest tunnels',
    'Star Wars cockpit game',
    'hard',
    'Games',
  ],
  [
    'Which Namco 1981 sequel to Galaxian? Galaga',
    'Galaga',
    'Galaxian predecessor',
    'Pac-Land platformer',
    'Dig Dug digging',
    'medium',
    'Games',
  ],
  [
    'Which Namco digging game features Pooka? Dig Dug',
    'Dig Dug',
    'Pac-Man dots',
    'Galaga bees',
    'Bosconian space',
    'hard',
    'Games',
  ],
  [
    'Which Konami rhythm dance series is Dance Dance Revolution? DDR',
    'Dance Dance Revolution',
    'Guitar Hero strumming',
    'Beatmania turntables',
    'Taiko no Tatsujin drums',
    'easy',
    'Games',
  ],
  [
    'Which Konami drum series is Taiko no Tatsujin? Taiko no Tatsujin',
    'Taiko no Tatsujin drums',
    'DDR dancing',
    'Beatmania keys',
    'Popn Music colorful',
    'medium',
    'Games',
  ],
  [
    'Which Konami DJ turntable series is Beatmania? Beatmania IIDX',
    'Beatmania IIDX',
    'DDR',
    'Taiko',
    'Sound Voltex newer knobs',
    'medium',
    'Games',
  ],
  [
    'Which Sega racer introduced sprite-scaling in 1986? OutRun',
    'OutRun',
    'Space Harrier rail shooter 1985',
    'After Burner 1987',
    'Hang-On 1985 motorbike',
    'hard',
    'Games',
  ],
  [
    'Which Sega rail shooter flew Harrier jets fantasy? Space Harrier',
    'Space Harrier',
    'After Burner fighter jet',
    'OutRun Ferrari driving',
    'Virtua Racing polygon later',
    'medium',
    'Games',
  ],
  [
    'Which Sega 1992 polygon fighter is Virtua Fighter as said? Virtua Racing polygon F1 1992',
    'Virtua Racing',
    'Virtua Fighter 1993',
    'Daytona USA 1994',
    'Sega Rally 1995',
    'expert',
    'Games',
  ],
  [
    'Which Sega NASCAR-style 1994 arcade racer? Daytona USA',
    'Daytona USA',
    'Virtua Racing F1',
    'Sega Rally WRC 1995',
    'Scud Race 1996',
    'medium',
    'Games',
  ],
  [
    'Which Sega 1995 rally arcade racer? Sega Rally Championship',
    'Sega Rally',
    'Daytona oval',
    'Virtua Racing',
    'Emergency Call Ambulance odd',
    'hard',
    'Games',
  ],
  [
    'Which Sega light-gun series is House of the Dead? House of the Dead',
    'House of the Dead',
    'Virtua Cop pioneered 3D light gun',
    'Time Crisis Namco pedal',
    'Point Blank Namco mini games',
    'medium',
    'Games',
  ],
  [
    'Which Namco light-gun series uses a foot pedal? Time Crisis',
    'Time Crisis pedal cover',
    'House of the Dead Sega',
    'Virtua Cop Sega again',
    'Silent Scope sniper scope',
    'medium',
    'Games',
  ],
  [
    'Which Konami sniper scope game is Silent Scope? Silent Scope',
    'Silent Scope',
    'Time Crisis pedal',
    'Point Blank wacky',
    'Lethal Enforcers colored guns',
    'hard',
    'Games',
  ],
  [
    'Which Konami light gun classic had colored guns? Lethal Enforcers',
    'Lethal Enforcers',
    'Silent Scope scope',
    'Time Crisis pedal',
    'Area 51 Atari rasterization',
    'expert',
    'Games',
  ],
  [
    'Which Atari 1991 light gun shooter filmed digitized actors? Area 51',
    'Area 51',
    'Lethal Enforcers sprite drawn',
    'Mad Dog McCree full motion video western',
    'Crime Patrol FMV similar',
    'expert',
    'Games',
  ],
  [
    'Which FMV western shooter is Mad Dog McCree? Mad Dog McCree',
    'Mad Dog McCree',
    'Area 51 aliens',
    'Crime Patrol police',
    'Who Shot Johnny Rock jazzy',
    'expert',
    'Games',
  ],
  [
    'Which Nintendo light gun classic had ducks? Duck Hunt',
    'Duck Hunt',
    'Wild Gunman cowboy earlier',
    'Hogan Alley training',
    'Barker Bill trick shooting',
    'medium',
    'Games',
  ],
  [
    'Which NES cowboy light gun sequel? Wild Gunman',
    'Wild Gunman',
    'Duck Hunt ducks',
    'Hogan Alley',
    'Duck Hunt dog laughing',
    'hard',
    'Games',
  ],
  [
    'Which NES fitness mat game used Power Pad? Track Meet style World Class Track Meet',
    'World Class Track Meet on Power Pad',
    'Duck Hunt zapper',
    'Ring Fit newer Switch',
    'Wii Fit balance board',
    'expert',
    'Games',
  ],
  [
    'Which Switch leg-strapped ring game is Ring Fit? Ring Fit Adventure',
    'Ring Fit Adventure',
    'Wii Fit balance board older',
    'Just Dance dancing mat free',
    'Fitness Boxing punching',
    'easy',
    'Games',
  ],
  [
    'Which Wii balance board series is Wii Fit? Wii Fit',
    'Wii Fit',
    'Ring Fit newer adventure',
    'Wii Sports simple sports',
    'Wii Play mini games bundle',
    'easy',
    'Games',
  ],
  [
    'Which Wii bundled sports compilation sold massively? Wii Sports',
    'Wii Sports bundled',
    'Wii Fit separate',
    'Wii Play with remote',
    'Wii Party board style',
    'easy',
    'Games',
  ],
  [
    'Which Wii mini-games bundle came with remote? Wii Play',
    'Wii Play',
    'Wii Sports separate',
    'Wii Party',
    'Wii Sports Resort with MotionPlus',
    'medium',
    'Games',
  ],
  [
    'Which 2009 Wii resort follow-up needed MotionPlus? Wii Sports Resort',
    'Wii Sports Resort',
    'Wii Sports original',
    'Wii Play motion bundle',
    'Wii Party U for Wii U',
    'medium',
    'Games',
  ],
  [
    'Which Wii U board-game style party game? Wii Party U',
    'Wii Party U',
    'Wii Party original',
    'Wii Play',
    'Nintendo Land theme park for Wii U',
    'hard',
    'Games',
  ],
  [
    'Which Wii U launch theme-park minigame collection? Nintendo Land',
    'Nintendo Land',
    'Wii Party U parties',
    'Nintendogs pets DS',
    'Tomodachi Life Mii life 3DS',
    'hard',
    'Games',
  ],
  [
    'Which DS pet dog game is Nintendogs? Nintendogs',
    'Nintendogs',
    'Animal Crossing villagers',
    'Tomodachi Life Mii apartment',
    'Pokemon Amie affection later',
    'medium',
    'Games',
  ],
  [
    'Which 3DS Mii apartment sim is Tomodachi Life? Tomodachi Life',
    'Tomodachi Life',
    'Nintendogs pets',
    'Miitopia RPG newer',
    'Street Pass Mii Plaza built-in',
    'hard',
    'Games',
  ],
  [
    'Which 3DS RPG puts Miis in classes? Miitopia',
    'Miitopia',
    'Tomodachi Life sim',
    'Street Pass Plaza minis',
    'Find Mii RPG in plaza actually',
    'expert',
    'Games',
  ],
  [
    'Which DS handheld Wi-Fi social plaza is StreetPass Mii Plaza? StreetPass Mii Plaza',
    'StreetPass Mii Plaza',
    'Tomodachi Life',
    'Miitopia',
    'Flipnote Studio animation',
    'hard',
    'Games',
  ],
  [
    'Which DS animation app is Flipnote Studio? Flipnote Studio',
    'Flipnote Studio',
    'Swapdoodle later messaging',
    'Pictochat DS built-in chat',
    'Notes 3DS',
    'expert',
    'Games',
  ],
  [
    'Which original DS built-in chat was PictoChat? PictoChat',
    'PictoChat',
    'Flipnote 3DS animation',
    'Swapnote 3DS messaging',
    'Chat later apps',
    'hard',
    'Games',
  ],
];

module.exports = { rows };
